@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_7ef4f4_26a8
	.thumb_func
	.type	 OvlFunc_7ef4f4_26a8,function
OvlFunc_7ef4f4_26a8:
	ldr	r3, .L3
	ldr	r3, [r3]
	mov	r2, #1
	add	r3, r3, #52
	strb	r2, [r3]
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	iwram_3001f30
.Lfe1:
	.size	 OvlFunc_7ef4f4_26a8,.Lfe1-OvlFunc_7ef4f4_26a8

	.text
	.align	2, 0
