@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_888_200a6f0
	.thumb_func
	.type	 OvlFunc_888_200a6f0,function
OvlFunc_888_200a6f0:
	push	{r5, r6, lr}
	mov	r6, sl
	mov	r5, r8
	push	{r5, r6}
	mov	r5, r0
	.code	16
	mov	r2, #100
	.code	16
	add	r2, r2, r5
	ldrh	r6, [r2]
	ldr	r1, [r5, #104]
	mov	r0, r6
	.code	16
	mov	r8, r2
	mov	sl, r1
	.code	16
	bl	__cos
	mov	r1, sl
	.code	16
	lsl	r2, r0, #3
	ldr	r3, [r1, #8]
	.code	16
	sub	r2, r2, r0
	lsl	r2, r2, #1
	add	r3, r3, r2
	str	r3, [r5, #8]
	mov	r0, r6
	.code	16
	bl	__sin
	mov	r1, sl
	.code	16
	lsl	r3, r0, #2
	ldr	r2, [r1, #16]
	.code	16
	add	r3, r3, r0
	lsl	r3, r3, #1
	add	r2, r2, r3
	.code	16
	ldr	r3, [r5, #8]
	str	r2, [r5, #16]
	str	r2, [r5, #64]
	str	r3, [r5, #56]
	mov	r2, r8
	.code	16
	add	r5, r5, #102
	.code	16
	ldrh	r3, [r2]
	.code	16
	ldrh	r2, [r5]
	.code	16
	mov	r1, r8
	.code	16
	add	r3, r3, r2
	strh	r3, [r1]
	pop	{r3, r5}
	mov	r8, r3
	mov	sl, r5
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_888_200a6f0,.Lfe1-OvlFunc_888_200a6f0

	.text
	.align	2, 0
