typedef unsigned short u16;

extern int __cos(int angle);
extern int __sin(int angle);

void OvlFunc_888_200a6f0(unsigned char *actor)
{
    register unsigned char *object asm("r5") = actor;
    register unsigned int offset asm("r2");
    register u16 *anglePtr asm("r2");
    register unsigned int phase asm("r6");
    register unsigned char *parentTmp asm("r1");
    register int cosArg asm("r0");
    register u16 *anglePtrSaved asm("r8");
    register unsigned char *parentSaved asm("r10");
    register int cosResult asm("r0");
    register unsigned char *parent asm("r1");
    register int t1 asm("r2");
    register int parentF8 asm("r3");
    register int x asm("r3");
    register int sinArg asm("r0");
    register int sinResult asm("r0");
    register int t2 asm("r3");
    register int parentF16 asm("r2");
    register int y asm("r2");
    register int xReload asm("r3");
    register u16 *anglePtrCopy asm("r2");
    register unsigned short oldPhase asm("r3");
    register unsigned short delta asm("r2");
    register u16 *anglePtrCopy2 asm("r1");
    register unsigned short newPhase asm("r3");

    asm volatile("" : "+r"(object));
    offset = 0x64;
    asm volatile("" : "+r"(offset), "+r"(object));
    anglePtr = (u16 *)(offset + (unsigned int)object);
    phase = *anglePtr;
    parentTmp = *(unsigned char **)(object + 0x68);
    cosArg = phase;
    asm volatile("" : "+r"(cosArg), "+r"(anglePtr), "+r"(parentTmp));
    anglePtrSaved = anglePtr;
    parentSaved = parentTmp;
    asm volatile("" : "+r"(cosArg), "+r"(anglePtrSaved), "+r"(parentSaved));
    cosResult = __cos(cosArg);
    parent = parentSaved;
    asm volatile("" : "+r"(cosResult), "+r"(parent));
    t1 = cosResult << 3;
    parentF8 = *(int *)(parent + 8);
    asm volatile("" : "+r"(t1), "+r"(cosResult), "+r"(parentF8));
    t1 = t1 - cosResult;
    t1 = t1 << 1;
    x = parentF8 + t1;
    *(int *)(object + 8) = x;
    sinArg = phase;
    asm volatile("" : "+r"(sinArg));
    sinResult = __sin(sinArg);
    parent = parentSaved;
    asm volatile("" : "+r"(sinResult), "+r"(parent));
    t2 = sinResult << 2;
    parentF16 = *(int *)(parent + 0x10);
    asm volatile("" : "+r"(t2), "+r"(sinResult), "+r"(parentF16));
    t2 = t2 + sinResult;
    t2 = t2 << 1;
    y = parentF16 + t2;
    asm volatile("" : "+r"(y));
    xReload = *(int *)(object + 8);
    *(int *)(object + 0x10) = y;
    *(int *)(object + 0x40) = y;
    *(int *)(object + 0x38) = xReload;
    anglePtrCopy = anglePtrSaved;
    asm volatile("" : "+r"(anglePtrCopy), "+r"(object));
    object = object + 0x66;
    asm volatile("" : "+r"(anglePtrCopy), "+r"(object));
    oldPhase = *anglePtrCopy;
    asm volatile("" : "+r"(oldPhase), "+r"(object));
    delta = *(u16 *)object;
    asm volatile("" : "+r"(oldPhase), "+r"(delta));
    anglePtrCopy2 = anglePtrSaved;
    asm volatile("" : "+r"(oldPhase), "+r"(delta), "+r"(anglePtrCopy2));
    newPhase = oldPhase + delta;
    *anglePtrCopy2 = newPhase;
}
