@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	Func_aa534
	.type	 Func_aa534,function
	.thumb_func
Func_aa534:
	mov	r0, #0x0
	bx	lr
.Lfe1:
	.size	 Func_aa534,.Lfe1-Func_aa534

	.text
	.align	2, 0
