@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	Func_a9e44
	.type	 Func_a9e44,function
	.thumb_func
Func_a9e44:
	bx	lr
.Lfe1:
	.size	 Func_a9e44,.Lfe1-Func_a9e44

	.text
	.align	2, 0
