@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80a5fe0
	.thumb_func
	.type	 Func_80a5fe0,function
Func_80a5fe0:
	push	{r5, lr}
	ldr	r3, .L5
	mov	r2, #188
	ldr	r3, [r3]
	lsl	r2, r2, #1
	add	r3, r3, r2
	ldrh	r3, [r3]
	ldr	r0, .L5+4
	and	r0, r0, r3
	bl	_GetMoveInfo
	mov	r5, r0
	ldrb	r0, [r5, #12]
	bl	_Func_808e96c
	cmp	r0, #0
	beq	.L3
	mov	r0, #0
	b	.L2
.L3:
	ldrb	r3, [r5, #8]
	mov	r0, #2
	cmp	r3, #255
	beq	.L2
	ldrb	r3, [r5]
	mov	r2, #2
	eor	r3, r3, r2
	neg	r0, r3
	orr	r0, r0, r3
	lsr	r0, r0, #31
	mov	r3, #1
	sub	r0, r3, r0
.L2:
	pop	{r5}
	pop	{r1}
	bx	r1
.L6:
	.align	2, 0
.L5:
	.word	iwram_3001f2c
	.word	16383
.Lfe1:
	.size	 Func_80a5fe0,.Lfe1-Func_80a5fe0

	.text
	.align	2, 0
