@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80a8b10
	.thumb_func
	.type	 Func_80a8b10,function
Func_80a8b10:
	push	{r5, r6, lr}
	mov	r5, r0
	mov	r0, r2
	mov	r6, r1
	bl	_GetUnit
	mov	r1, #0
	mov	r2, r0
	add r3, r5, #4
	mov r12, r5
	.code	16
.L6:
	strb	r1, [r3]
	sub	r3, r3, #1
	cmp	r3, ip
	bge	.L6
	mov	r1, #56
	ldrsh	r3, [r2, r1]
	mov	r0, #0
	cmp	r3, #0
	bne	.L7
	cmp	r6, #1
	bne	.L7
	strb	r6, [r5]
	mov	r0, #1
.L7:
	ldr	r1, .L13
	add	r3, r2, r1
	ldrb	r3, [r3, #0]
	lsl	r3, r3, #24
	asr	r3, r3, #24
	cmp	r3, #0
	beq	.L8
	cmp	r3, #1
	bne	.L9
	strb	r3, [r5, #1]
	b	.L10
.L9:
	mov	r3, #1
	strb	r3, [r5, #2]
.L10:
	add	r0, r0, #1
.L8:
	mov	r1, #152
	lsl	r1, r1, #1
	add	r3, r2, r1
	ldrb	r3, [r3, #0]
	lsl	r3, r3, #24
	asr	r3, r3, #24
	cmp	r3, #0
	beq	.L11
	mov	r3, #1
	strb	r3, [r5, #3]
	add	r0, r0, #1
.L11:
	mov r1, #0xa0
	lsl r1, #1
	add r3, r2, r1
	ldrb r3, [r3]
	.code	16
	cmp	r3, #0
	beq	.L12
	mov	r3, #1
	strb	r3, [r5, #4]
	add	r0, r0, #1
.L12:
	pop	{r5, r6}
	pop	{r1}
	bx	r1
.L14:
	.align	2, 0
.L13:
	.word	305
.Lfe1:
	.size	 Func_80a8b10,.Lfe1-Func_80a8b10

	.text
	.align	2, 0
