@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	LoadMoveRangeIcons
	.thumb_func
	.type	 LoadMoveRangeIcons,function
LoadMoveRangeIcons:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r8
	push	{r6, r7}
	ldr r2, =.Laf23c
	ldr r3, =Func_80008d8
	mov r7, #0
	mov r8, r2
	mov r10, r3
	.code	16
.L18:
	lsl r3, r7, #1
	add r3, r7
	ldr r2, =0x06005000
	lsl r3, #7
	mov r6, #0
	add r5, r3, r2
	.code	16
.L17:
	mov r0, r5
	mov r1, #0x40
	ldr r2, =0x44444444
	bl _call_via_r10
	.code	16
	mov	r4, #1
	.code	16
	add	r0, r5, #4
.L15:
	mov	r1, r6
	cmp	r7, #1
	bne	.L12
	cmp	r4, #1
	ble	.L11
.L12:
	cmp	r7, #0
	bne	.L13
	sub	r3, r4, #2
	cmp	r6, r3
	ble	.L13
	mov	r1, r3
	cmp	r1, #0
	bge	.L13
	mov r1, #0
	.code	16
.L13:
	lsl	r1, r1, #3
	mov r3, r8
	ldr r3, [r3, r1]
	ldr r2, [r0]
	.code	16
	eor	r2, r2, r3
	str	r2, [r0]
	add r1, #4
	mov r3, r8
	ldr r2, [r0, #0x20]
	ldr r1, [r3, r1]
	.code	16
	eor	r2, r2, r1
	str	r2, [r0, #32]
.L11:
	add	r4, r4, #1
	add	r0, r0, #4
	cmp	r4, #7
	ble	.L15
	add	r6, r6, #1
	add	r5, r5, #64
	cmp	r6, #5
	ble	.L17
	add	r7, r7, #1
	cmp	r7, #1
	ble	.L18
	pop	{r3, r5}
	mov	r8, r3
	mov	sl, r5
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 LoadMoveRangeIcons,.Lfe1-LoadMoveRangeIcons

	.text
	.align	2, 0
