@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80a2144
	.thumb_func
	.type	 Func_80a2144,function
Func_80a2144:
	push	{r5, lr}
	mov	r3, #160
	lsl	r0, r0, #5
	lsl	r3, r3, #19
	add	r5, r0, r3
	mov r1, r5
	ldr r3, 3f
	ldr r0, 4f
	ldr r2, 5f
	stmia r3!, {r0, r1, r2}
	sub r3, #0xc
	ldr r0, 4f
	ldr r2, 6f
	stmia r3!, {r0, r1, r2}
	sub r3, #0xc
	.code	16
	ldrh	r2, [r5, #8]
	lsl r3, r2, #16
	lsr r4, r3, #26
	lsr r1, r3, #21
	ldr r3, 1f
	mov r0, #0x1f
	add r4, #9
	and r1, r3
	and r0, r2
	.code	16
	cmp	r4, #31
	bls	.L9
	mov	r4, #31
.L9:
	add	r1, r1, #9
	cmp	r1, #31
	bls	.L10
	mov	r1, #31
.L10:
	add r0, #9
	cmp r0, #0x1f
	bls 2f
	mov r0, #0x1f
	b 2f
	.align 2, 0
1:
	.word 0x1f
3:
	.word 0x040000d4
4:
	.word 0x050001e0
5:
	.word 0x80000010
6:
	.word 0x84000008
2:
	lsl r3, r4, #10
	lsl r2, r1, #5
	orr r3, r2
	orr r3, r0
	strh r3, [r5, #8]
	.code	16
	pop	{r5}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Func_80a2144,.Lfe1-Func_80a2144

	.text
	.align	2, 0
