@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80a5614
	.thumb_func
	.type	 Func_80a5614,function
Func_80a5614:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r8
	push	{r6, r7}
	mov	r8, r2
	ldr	r3, .L9
	ldr	r2, [r2, #8]
	mov	r1, r8
	ldr	r7, [r3]
	lsl	r3, r2, #2
	add	r3, r3, r2
	ldr	r2, [r1, #16]
	add	r3, r3, r2
	str	r3, [r1, #24]
	ldr	r0, [r7, #44]
	sub	sp, sp, #8
	bl	_Func_8016498
	mov	r0, #1
	bl	WaitFrames
	mov r2, r8
	ldr r3, [r2, #0x18]
	mov r1, #0xe4
	lsl r3, #1
	lsl r1, #1
	add r3, r1
	ldrh r2, [r7, r3]
	mov r3, r2
	cmp r3, #0
	beq 1f
	ldr r0, =0x1ff
	ldr r3, =0x75
	and r0, r2
	add r0, r3
	ldr r1, [r7, #0x2c]
	mov r2, #0
	mov r3, #0
	bl _Func_801e7c0
	1:
	
	.code	16
	mov	r2, #1
	mov	r6, #0
	mov	sl, r2
	mov	r5, #1
.L8:
	mov	r1, r8
	ldr	r3, [r1, #16]
	cmp	r6, r3
	bne	.L6
	mov	r2, sl
	ldr	r0, [r7, #32]
	mov	r3, #14
	str	r2, [sp]
	mov	r1, #1
	mov	r2, r5
	str	r3, [sp, #4]
	bl	Func_80a2268
	b	.L7
.L6:
	mov	r3, sl
	ldr	r0, [r7, #32]
	str	r3, [sp]
	mov	r3, #15
	str	r3, [sp, #4]
	mov	r1, #1
	mov	r2, r5
	mov	r3, #14
	bl	Func_80a2268
.L7:
	add	r6, r6, #1
	add	r5, r5, #2
	cmp	r6, #4
	ble	.L8
	mov	r0, #1
	bl	WaitFrames
	mov	r0, #1
	add	sp, sp, #8
	pop	{r3, r5}
	mov	r8, r3
	mov	sl, r5
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L10:
	.align	2, 0
.L9:
	.word	iwram_3001f2c
.Lfe1:
	.size	 Func_80a5614,.Lfe1-Func_80a5614

	.text
	.align	2, 0
