@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_945_200beec
	.thumb_func
	.type	 OvlFunc_945_200beec,function
OvlFunc_945_200beec:
	push	{lr}
	bl	__CutsceneStart
	mov	r0, #0
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	bl	OvlFunc_945_200d004
	mov	r1, #150
	mov	r0, #18
	.code	16
	lsl	r1, r1, #16
	ldr	r2, .L3
	bl	__MapActor_SetPos
	mov	r0, #156
	mov	r1, #1
	mov	r2, #134
	ldr	r3, .L3+4
	lsl	r0, r0, #16
	neg	r1, r1
	lsl	r2, r2, #18
	bl	OvlFunc_945_200c8ac
	mov	r0, #8
	mov	r1, #0
	mov	r2, #0
	bl	OvlFunc_945_200c8e8
	mov	r0, #18
	ldr	r1, .L3+8
	.code	16
	ldr	r2, .L3+12
	bl	__MapActor_SetSpeed
	mov	r0, #18
	mov	r1, #168
	.code	16
	ldr	r2, .L3+16
	bl	__Func_80921c4
	mov	r0, #18
	mov	r1, #168
	.code	16
	ldr	r2, .L3+20
	bl	__Func_80921c4
	mov	r1, #128
	mov	r2, #20
	mov	r0, #18
	.code	16
	lsl	r1, r1, #8
	bl	__Func_8092adc
	mov	r1, #2
	mov	r0, #18
	bl	__Func_809259c
	ldr	r0, .L3+24
	bl	__MessageID
	mov	r0, #18
	mov	r1, #0
	mov	r2, #20
	bl	__Func_8093040
	mov	r0, #9
	mov	r1, #12
	mov	r2, #0
	bl	OvlFunc_945_200c8e8
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	38404096
	.word	16777217
	.word	52428
	.word	26214
	.word	578
	.word	554
	.word	7740
.Lfe1:
	.size	 OvlFunc_945_200beec,.Lfe1-OvlFunc_945_200beec

	.text
	.align	2, 0
