@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	OvlFunc_374
	.type	 OvlFunc_374,function
	.thumb_func
OvlFunc_374:
	mov	r0, #0x0
	bx	lr
.Lfe1:
	.size	 OvlFunc_374,.Lfe1-OvlFunc_374

	.text
	.align	2, 0
