@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_959_2009cf0
	.thumb_func
	.type	 OvlFunc_959_2009cf0,function
OvlFunc_959_2009cf0:
	push	{r5, r6, lr}
	ldr	r6, .L3
	mov	r5, r0
	mov	r0, r6
	bl	__MessageID
	mov	r0, r5
	mov	r1, #0
	bl	__ActorMessage
	mov	r0, #120
	bl	__CutsceneWait
	mov	r2, #60
	.code	16
	mov	r0, r5
	.code	16
	ldr	r1, .L3+4
	bl	__MapActor_Emote
	add	r0, r6, #1
	bl	__MessageID
	mov	r0, r5
	mov	r1, #0
	bl	__ActorMessage
	mov	r0, r5
	mov	r1, #1
	bl	__Func_80925cc
	add	r0, r6, #2
	bl	__MessageID
	mov	r0, r5
	mov	r1, #0
	bl	__ActorMessage
	add	r6, r6, #3
	mov	r0, r5
	mov	r1, #4
	bl	__MapActor_DoAnim
	mov	r0, r6
	bl	__MessageID
	mov	r0, r5
	mov	r1, #0
	bl	__ActorMessage
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	9252
	.word	257
.Lfe1:
	.size	 OvlFunc_959_2009cf0,.Lfe1-OvlFunc_959_2009cf0

	.text
	.align	2, 0
