@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_959_200a69c
	.thumb_func
	.type	 OvlFunc_959_200a69c,function
OvlFunc_959_200a69c:
	push	{lr}
	mov	r1, #1
	mov	r0, #11
	bl	__Func_8093500
	bl	__Func_8093530
	mov	r0, #60
	bl	__CutsceneWait
	ldr	r0, .L3
	bl	__MessageID
	mov	r0, #13
	mov	r1, #0
	bl	__ActorMessage
	mov	r1, #128
	mov	r2, #128
	.code	16
	mov	r0, #11
	.code	16
	lsl	r1, r1, #9
	.code	16
	lsl	r2, r2, #8
	.code	16
	bl	__MapActor_SetSpeed
	mov	r1, #128
	mov	r2, #128
	.code	16
	mov	r0, #15
	.code	16
	lsl	r1, r1, #9
	.code	16
	lsl	r2, r2, #8
	.code	16
	bl	__MapActor_SetSpeed
	mov	r1, #236
	.code	16
	mov	r0, #11
	.code	16
	lsl	r1, r1, #1
	.code	16
	mov	r2, #180
	.code	16
	bl	__Func_809218c
	mov	r1, #236
	.code	16
	mov	r2, #180
	.code	16
	mov	r0, #15
	.code	16
	lsl	r1, r1, #1
	.code	16
	bl	__Func_809218c
	mov	r1, #1
	mov	r0, #11
	bl	__SetCameraTarget
	mov	r0, #11
	bl	__MapActor_WaitMovement
	mov	r0, #11
	mov	r1, #4
	bl	__MapActor_SetAnim
	mov	r0, #30
	bl	__CutsceneWait
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	9340
.Lfe1:
	.size	 OvlFunc_959_200a69c,.Lfe1-OvlFunc_959_200a69c

	.text
	.align	2, 0
