@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_882_2009600
	.thumb_func
	.type	 OvlFunc_882_2009600,function
OvlFunc_882_2009600:
	push	{lr}
	ldr	r0, .L4
	bl	__GetFlag
	cmp	r0, #0
	bne	.L3
	ldr	r0, .L4+4
	bl	__GetFlag
	cmp	r0, #0
	bne	.L3
	bl	__CutsceneStart
	ldr	r0, .L4+8
	bl	__MessageID
	mov	r0, #22
	mov	r1, #0
	mov	r2, #20
	bl	__Func_8093040
	mov	r0, #0
	ldr	r1, .L4+12
	mov	r2, #40
	.code	16
	bl	__MapActor_Emote
	mov	r1, #191
	mov	r0, #0
	.code	16
	lsl	r1, r1, #1
	.code	16
	ldr	r2, .L4+16
	bl	__Func_80921c4
	mov	r2, #0
	mov	r0, #0
	mov	r1, #22
	.code	16
	bl	__Func_809280c
	mov	r1, #2
	mov	r0, #0
	bl	__Func_80925cc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #22
	mov	r1, #0
	bl	__ActorMessage
	ldr	r0, .L4
	bl	__SetFlag
	bl	__CutsceneEnd
.L3:
	pop	{r0}
	bx	r0
.L5:
	.align	2, 0
.L4:
	.word	2102
	.word	2103
	.word	3692
	.word	257
	.word	619
.Lfe1:
	.size	 OvlFunc_882_2009600,.Lfe1-OvlFunc_882_2009600

	.text
	.align	2, 0
