@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_939_2008314
	.thumb_func
	.type	 OvlFunc_939_2008314,function
OvlFunc_939_2008314:
	push	{lr}
	ldr	r3, .L7
	mov	r1, #224
	.code	16
	lsl	r1, r1, #1
	add	r3, r3, r1
	mov	r1, #0
	.code	16
	ldrsh	r2, [r3, r1]
	ldr	r3, .L7+4
	.code	16
	cmp	r2, r3
	beq	.L4
	ldr	r3, .L7+8
	.code	16
	cmp	r2, r3
	bne	.L4
	ldr	r0, .L7+12
	b	.L6
.L4:
	ldr	r0, .L7+16
.L6:
	.code	16
	pop	{r1}
	bx	r1
.L8:
	.align	2, 0
.L7:
	.word	gState
	.word	0x68
	.word	0x9f
	.word	gOvl_02009d3c
	.word	.L1bec
.Lfe1:
	.size	 OvlFunc_939_2008314,.Lfe1-OvlFunc_939_2008314

	.text
	.align	2, 0
