@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_314_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_7c460c_f9c
	.thumb_func
	.type	 OvlFunc_7c460c_f9c,function
OvlFunc_7c460c_f9c:
	bx	lr
.Lfe1:
	.size	 OvlFunc_7c460c_f9c,.Lfe1-OvlFunc_7c460c_f9c

	.text
	.align	2, 0
