@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	Func_b9b2c
	.type	 Func_b9b2c,function
	.thumb_func
Func_b9b2c:
	bx	lr
.Lfe1:
	.size	 Func_b9b2c,.Lfe1-Func_b9b2c

	.text
	.align	2, 0
