@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_948_2009308
	.thumb_func
	.type	 OvlFunc_948_2009308,function
OvlFunc_948_2009308:
	push	{r5, r6, r7, lr}
	mov	r0, #0
	bl	__MapActor_GetActor
	ldr	r3, [r0, #8]
	cmp	r3, #0
	bge	.L3
	ldr r1, =0xfffff
	.code	16
	add	r3, r3, r1
.L3:
	ldr	r0, [r0, #16]
	asr	r6, r3, #20
	cmp	r0, #0
	bge	.L4
	ldr r2, =0xfffff
	.code	16
	add	r0, r0, r2
.L4:
	asr	r5, r0, #20
	ldr r3, =iwram_3001ebc
	mov r0, #0x88
	lsl r0, #2
	ldr r7, [r3]
	.code	16
	bl	__GetFlag
	cmp	r0, #0
	bne	.L5
	ldr r2, =gState
	mov r1, #0x93
	lsl r1, #2
	add r3, r2, r1
	mov r1, #0
	ldrsh r3, [r3, r1]
	.code	16
	cmp	r3, #0
	bne	.L5
	ldr r1, =0x24a
	add r3, r2, r1
	mov r2, #0
	ldrsh r3, [r3, r2]
	.code	16
	cmp	r3, #8
	beq	.L5
	mov	r3, r6
	.code	16
	sub	r3, r3, #21
	cmp	r3, #2
	bhi	.L5
	cmp	r5, #9
	ble	.L5
	cmp	r5, #11
	bgt	.L5
	mov r0, #0x88
	lsl r0, #2
	.code	16
	bl	__SetFlag
	mov	r3, #193
	.code	16
	lsl	r3, r3, #1
	add	r2, r7, r3
	mov	r3, #91
	.code	16
	strh	r3, [r2]
.L5:
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_948_2009308,.Lfe1-OvlFunc_948_2009308

	.text
	.align	2, 0
