@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_948_200941c
	.thumb_func
	.type	 OvlFunc_948_200941c,function
OvlFunc_948_200941c:
	push	{r5, r6, r7, lr}
	mov	r0, #0
	bl	__MapActor_GetActor
	ldr	r3, [r0, #8]
	cmp	r3, #0
	bge	.L3
	ldr	r1, .L8
	add	r3, r3, r1
.L3:
	ldr	r0, [r0, #16]
	asr	r7, r3, #20
	cmp	r0, #0
	bge	.L4
	ldr	r2, .L8
	add	r0, r0, r2
.L4:
	asr	r5, r0, #20
	ldr	r3, .L8+4
	mov	r0, #136
	lsl	r0, r0, #2
	ldr	r6, [r3]
	bl	__GetFlag
	cmp	r0, #0
	bne	.L5
	ldr	r2, .L8+8
	.code	16
	mov	r1, #147
	lsl	r1, r1, #2
	add	r3, r2, r1
	mov	r1, #0
	ldrsh	r3, [r3, r1]
	cmp	r3, #0
	bne	.L5
	ldr r1, =0x24a
add r3, r2, r1
mov r2, #0
ldrsh r3, [r3, r2]
	.code	16
	cmp	r3, #9
	beq	.L5
	cmp	r7, #10
	bne	.L5
	mov	r3, r5
	sub	r3, r3, #16
	cmp	r3, #2
	bhi	.L5
	mov r0, #0x88
lsl r0, #2
	.code	16
	bl	__SetFlag
	mov r3, #0xc1
lsl r3, #1
add r2, r6, r3
	.code	16
	mov	r3, #92
	strh	r3, [r2]
.L5:
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L9:
	.align	2, 0
.L8:
	.word	1048575
	.word	iwram_3001ebc
	.word	gState
.Lfe1:
	.size	 OvlFunc_948_200941c,.Lfe1-OvlFunc_948_200941c

	.text
	.align	2, 0
