@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_948_200938c
	.thumb_func
	.type	 OvlFunc_948_200938c,function
OvlFunc_948_200938c:
	push	{lr}
	bl	__CutsceneStart
	mov r0, #0
	ldr r1, =0x1e666
	ldr r2, =0xf333
	.code	16
	bl	__MapActor_SetSpeed
	mov r0, #8
	ldr r1, =0x1e666
	ldr r2, =0xf333
	.code	16
	bl	__MapActor_SetSpeed
	mov	r0, #188
	bl	__PlaySound
	mov	r0, #0
	bl	__MapActor_GetActor
	cmp	r0, #0
	beq	.L3
	mov	r3, #10
	ldrsh	r1, [r0, r3]
	mov	r3, #18
	ldrsh	r2, [r0, r3]
	mov	r0, #8
	bl	__MapActor_TravelTo
.L3:
	mov	r0, #8
	bl	__MapActor_WaitMovement
	mov	r1, #0
	mov	r2, #24
	mov	r0, #0
	bl	__Func_809228c
	mov	r0, #4
	bl	__CutsceneWait
	mov	r0, #188
	bl	__PlaySound
	mov	r1, #0
	mov	r2, #16
	mov	r0, #8
	bl	__Func_809228c
	mov	r0, #0
	bl	__MapActor_WaitMovement
	mov	r1, #180
	lsl	r1, r1, #1
	mov	r2, #152
	mov	r0, #8
	bl	__MapActor_TravelTo
	mov	r0, #8
	bl	__MapActor_WaitMovement
	bl	__CutsceneEnd
	mov	r0, #136
	lsl	r0, r0, #2
	bl	__ClearFlag
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_948_200938c,.Lfe1-OvlFunc_948_200938c

	.text
	.align	2, 0
