@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_948_2008f40
	.thumb_func
	.type	 OvlFunc_948_2008f40,function
OvlFunc_948_2008f40:
	push	{r5, r6, lr}
	mov	r3, #255
	and	r3, r3, r0
	lsl	r3, r3, #2
	mov	r6, r3
	mov	r5, r3
	mov	r3, #128
	lsl	r3, r3, #1
	and	r3, r3, r0
	sub	sp, sp, #8
	add	r6, r6, #77
	add	r5, r5, #13
	cmp	r3, #0
	beq	.L3
	mov	r0, #157
	bl	__PlaySound
	mov r0, #0x80
	mov r1, #0x80
	mov r2, #0x80
	lsl r0, #10
	lsl r1, #10
	lsl r2, #9
	bl __Func_8012330
	mov r0, #1
	mov r1, #1
	neg r0, r0
	neg r1, r1
	ldr r2, =0xe666
	bl __Func_8012330
	.code	16
	mov	r3, #40
	str	r3, [sp, #4]
	mov	r0, #79
	mov	r1, #29
	mov	r2, #1
	mov	r3, #3
	str	r6, [sp]
	bl	__Func_80105d4
	mov	r0, #40
	bl	__WaitFrames
.L3:
	mov	r3, #40
	str	r3, [sp, #4]
	mov	r0, #80
	mov	r1, #29
	mov	r2, #1
	mov	r3, #3
	str	r6, [sp]
	bl	__Func_80105d4
	mov	r3, #41
	str	r3, [sp, #4]
	mov	r0, r5
	mov	r1, #40
	mov	r2, #1
	mov	r3, #1
	str	r5, [sp]
	bl	__Func_8010704
	mov	r3, #42
	str	r3, [sp, #4]
	mov	r0, r5
	mov	r1, #40
	mov	r2, #1
	mov	r3, #1
	str	r5, [sp]
	bl	__Func_8010704
	add	sp, sp, #8
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_948_2008f40,.Lfe1-OvlFunc_948_2008f40

	.text
	.align	2, 0
