@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_948_2008fdc
	.thumb_func
	.type	 OvlFunc_948_2008fdc,function
OvlFunc_948_2008fdc:
	push	{r5, lr}
	mov	r3, #128
	lsl	r3, r3, #1
	and	r0, r0, r3
	sub	sp, sp, #8
	cmp	r0, #0
	beq	.L3
	mov	r0, #157
	bl	__PlaySound
	mov r0, #0x80
	mov r1, #0x80
	mov r2, #0x80
	lsl r0, #10
	lsl r1, #10
	lsl r2, #9
	bl __Func_8012330
	mov r0, #1
	mov r1, #1
	neg r0, r0
	neg r1, r1
	ldr r2, =0xe666
	bl __Func_8012330
	mov r3, #0x46
	mov r2, #0x31
	str r3, [sp]
	str r2, [sp, #4]
	mov r0, #0x54
	mov r1, #0x1d
	mov r2, #1
	mov r3, #3
	bl __Func_80105d4
	.code	16
	mov	r0, #60
	bl	__WaitFrames
.L3:
	mov r3, #0x46
	mov r2, #0x31
	str r3, [sp]
	str r2, [sp, #4]
	mov r0, #0x55
	mov r1, #0x1d
	mov r2, #1
	mov r3, #3
	bl __Func_80105d4
	.code	16
	mov	r3, #50
	str	r3, [sp, #4]
	mov	r5, #6
	mov	r0, #6
	mov	r1, #49
	mov	r2, #1
	mov	r3, #1
	str	r5, [sp]
	bl	__Func_8010704
	mov	r3, #51
	str	r3, [sp, #4]
	mov	r0, #6
	mov	r1, #49
	mov	r2, #1
	mov	r3, #1
	str	r5, [sp]
	bl	__Func_8010704
	add	sp, sp, #8
	pop	{r5}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_948_2008fdc,.Lfe1-OvlFunc_948_2008fdc

	.text
	.align	2, 0
