@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_922_2009fac
	.thumb_func
	.type	 OvlFunc_922_2009fac,function
OvlFunc_922_2009fac:
	push	{lr}
	ldr	r3, .L4
	mov	r2, #225
	.code	16
	lsl	r2, r2, #1
	add	r3, r3, r2
	mov	r2, #0
	.code	16
	ldrsh	r3, [r3, r2]
	.code	16
	cmp	r3, #6
	bgt	.L2
	ldr	r3, .L4+4
	.code	16
	ldr	r2, [r3]
	.code	16
	mov	r0, #1
	.code	16
	sub	r3, r3, #100
	.code	16
	add	r2, r2, #52
	.code	16
	ldr	r1, [r3]
	.code	16
	strb	r0, [r2]
	ldr	r2, .L4+8
	.code	16
	mov	r4, #0
	.code	16
	add	r3, r1, r2
	sub	r2, r2, #2
	.code	16
	strb	r4, [r3]
	add	r3, r1, r2
	.code	16
	strb	r0, [r3]
	ldr	r3, .L4+12
	.code	16
	add	r1, r1, r3
	.code	16
	strb	r0, [r1]
	mov	r0, #0
	mov	r1, #1
	bl	__Func_8091220
	ldr	r0, .L4+16
	mov	r1, #1
	bl	__Func_8091200
	mov	r0, #16
	bl	__Func_8091254
	mov	r0, #16
	bl	__WaitFrames
.L2:
	pop	{r0}
	bx	r0
.L5:
	.align	2, 0
.L4:
	.word	gState
	.word	iwram_3001f30
	.word	1342
	.word	1341
	.word	2109704
.Lfe1:
	.size	 OvlFunc_922_2009fac,.Lfe1-OvlFunc_922_2009fac

	.text
	.align	2, 0
