@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_922_2009a34
	.thumb_func
	.type	 OvlFunc_922_2009a34,function
OvlFunc_922_2009a34:
	push	{r5, r6, lr}
	ldr r3, =iwram_3001ebc
	mov r1, #0xb6
	ldr r3, [r3]
	lsl r1, #1
	ldr r5, =gState
	add r3, r1
	add r1, #0x54
	mov r2, #0
	ldrsh r6, [r3, r2]
	add r3, r5, r1
	mov r1, #0
	ldrsh r2, [r3, r1]
	ldr r3, =0x3f
	.code	16
	cmp	r2, r3
	bne	.L3
	cmp	r6, #17
	bne	.L4
	mov	r1, #32
	neg	r1, r1
	mov	r0, #0
	bl	OvlFunc_922_2009ad0
	b	.L3
.L4:
	mov	r0, #32
	neg	r0, r0
	mov	r1, #0
	bl	OvlFunc_922_2009ad0
.L3:
	mov r2, #0xe0
	lsl r2, #1
	add r3, r5, r2
	mov r1, #0
	ldrsh r2, [r3, r1]
	ldr r3, =0x40
	.code	16
	cmp	r2, r3
	bne	.L6
	cmp	r6, #25
	bne	.L6
	ldr r0, =0x309
	.code	16
	bl	__GetFlag
	cmp	r0, #0
	beq	.L6
	mov	r0, #0
	mov	r1, #32
	bl	OvlFunc_922_2009ad0
.L6:
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_922_2009a34,.Lfe1-OvlFunc_922_2009a34

	.text
	.align	2, 0
