@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_f9ef8_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_fa260
	.thumb_func
	.type	 Func_fa260,function
Func_fa260:
	bx	lr
.Lfe1:
	.size	 Func_fa260,.Lfe1-Func_fa260

	.text
	.align	2, 0

	.text
	.align	2, 0
