@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_f9080_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_f94f8
	.thumb_func
	.type	 Func_f94f8,function
Func_f94f8:
	ldr	r3, .L3
	strh	r0, [r3]
	ldr	r3, .L3+4
	strh	r1, [r3]
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	ewram_3030
	.word	ewram_300c
.Lfe1:
	.size	 Func_f94f8,.Lfe1-Func_f94f8

	.text
	.align	2, 0

	.text
	.align	2, 0
