@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_20198_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_209cc
	.thumb_func
	.type	 Func_209cc,function
Func_209cc:
	mov	r0, #1
	bx	lr
.Lfe1:
	.size	 Func_209cc,.Lfe1-Func_209cc

	.text
	.align	2, 0

	.text
	.align	2, 0
