@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_19ebc_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_1a5a0
	.thumb_func
	.type	 Func_1a5a0,function
Func_1a5a0:
	bx	lr
.Lfe1:
	.size	 Func_1a5a0,.Lfe1-Func_1a5a0

	.text
	.align	2, 0

	.text
	.align	2, 0
