@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_23178_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_294d0
	.thumb_func
	.type	 Func_294d0,function
Func_294d0:
	bx	lr
.Lfe1:
	.size	 Func_294d0,.Lfe1-Func_294d0

	.text
	.align	2, 0

	.text
	.align	2, 0
