@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_801fd34
	.thumb_func
	.type	 Func_801fd34,function
Func_801fd34:
	push	{r5, r6, r7, lr}
	ldr	r7, .L6
	.code	16
	ldr	r6, .L6+4
	.code	16
	mov	r5, #0
	.code	16
.L3:
	ldr	r3, [r7]
	lsl	r2, r5, #3
	add	r3, r3, r2
	lsl	r0, r3, #1
	add	r0, r0, r3
	lsl	r0, r0, #8
	bl	sin
	cmp	r0, #0
	bge	.L4
	ldr	r3, .L6+8
	.code	16
	add	r0, r0, r3
.L4:
	asr	r3, r0, #14
	.code	16
	lsl	r1, r3, #1
	.code	16
	mov	r2, r3
	.code	16
	add	r1, r1, #22
	.code	16
	add	r2, r2, #16
	.code	16
	add	r3, r3, #20
	.code	16
	lsl	r3, r3, #10
	.code	16
	lsl	r2, r2, #5
	.code	16
	orr	r3, r3, r2
	.code	16
	orr	r3, r3, r1
	.code	16
	strh	r3, [r6]
	.code	16
	add	r6, r6, #2
	.code	16
	add	r5, r5, #1
	cmp	r5, #3
	ble	.L3
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L7:
	.align	2, 0
.L6:
	.word	iwram_3001800
	.word	83886544
	.word	16383
.Lfe1:
	.size	 Func_801fd34,.Lfe1-Func_801fd34

	.text
	.align	2, 0
