@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	LoadGS1CreditsBG
	.thumb_func
	.type	 LoadGS1CreditsBG,function
LoadGS1CreditsBG:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r8
	push	{r6, r7}
	mov	r5, r1
	cmp	r0, #0
	bne	.L3
	mov	r0, r5
	bl	Func_80f0254
	b	.L2
.L3:
	bl	GetFile
	mov	r6, r0
	cmp	r5, #0
	bne	.L4
	mov r3, #0xa0
	mov r2, #0
	mov r7, #0xc0
	lsl r3, r3, #19
	mov r8, r2
	lsl r7, r7, #19
	.code	16
	b	.L5
.L4:
	ldr r2, =0x80808080
	ldr r3, =0x5000100
	ldr r7, =0x6008000
	mov r8, r2
	.code	16
.L5:
	mov	sl, r3
	ldr r5, =0x230
	mov r0, #0x31
	mov r1, r5
	bl galloc_iwram
	mov r2, #0x84
	lsr r5, r5, #2
	lsl r2, r2, #24
	mov r1, r0
	ldr r3, =0x040000d4
	ldr r0, =Func_80f0024
	orr r2, r2, r5
	stmia r3!, {r0, r1, r2}
	sub r3, r3, #0xc
	ldr r3, =gPtrs
	mov r2, #0x80
	lsl r2, r2, #1
	add r3, r3, #0xc4
	mov r1, r7
	add r0, r6, r2
	ldr r3, [r3]
	mov r2, r8
	bl _call_via_r3
	mov r0, #0x31
	bl gfree
	ldr r1, =gDMATaskCount
	ldr r0, =0x04000208
	ldrh r3, [r0]
	mov r4, r3
	strh r0, [r0]
	ldrh r2, [r1]
	cmp r2, #0x1f
	bgt 1f
	lsl r3, r2, #1
	add r3, r3, r2
	lsl r3, r3, #2
	add r3, r3, r1
	add r3, r3, #4
	add r2, r2, #1
	stmia r3!, {r6}
	strh r2, [r1]
	mov r2, r10
	stmia r3!, {r2}
	ldr r2, =0x84000040
	str r2, [r3]
1:
	strh r4, [r0]
	.code	16
.L2:
	pop	{r3, r5}
	mov	r8, r3
	mov	sl, r5
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 LoadGS1CreditsBG,.Lfe1-LoadGS1CreditsBG

	.text
	.align	2, 0
