@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80f61e8
	.thumb_func
	.type	 Func_80f61e8,function
Func_80f61e8:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r8
	push	{r6, r7}
	mov r1, #0xa0
	lsl r1, r1, #19
	sub sp, sp, #0x80
	mov r8, r1
	bl GetFile
	ldr r3, =0x040000d4
	mov r1, sp
	ldr r2, =0x84000020
	stmia r3!, {r0, r1, r2}
	sub r3, r3, #0xc
	mov r2, #0
	mov r3, #0x1f
	ldr r7, 9f
	mov r14, r2
	mov r10, r3
	mov r12, sp
	mov r6, #0
	b 1f
	.align 2, 0
9:
	.word 0x1f
	.pool
1:
	mov r1, r8
	ldrh r3, [r1]
	mov r5, r10
	mov r1, r12
	and r5, r3
	lsl r3, r3, #16
	lsr r2, r3, #21
	lsr r0, r3, #26
	ldrh r3, [r6, r1]
	mov r1, r10
	and r1, r3
	lsl r3, r3, #16
	lsr r4, r3, #21
	lsr r3, r3, #26
	and r2, r7
	and r0, r7
	and r4, r7
	and r3, r7
	cmp r5, r1
	bge 2f
	add r5, r5, #1
	b 3f
2:
	cmp r5, r1
	ble 3f
	sub r5, r5, #1
3:
	cmp r2, r4
	bge 4f
	add r2, r2, #1
	b 5f
4:
	cmp r2, r4
	ble 5f
	sub r2, r2, #1
5:
	cmp r0, r3
	bge 6f
	add r0, r0, #1
	b 7f
6:
	cmp r0, r3
	ble 7f
	sub r0, r0, #1
7:
	lsl r2, r2, #5
	lsl r3, r0, #10
	orr r3, r2
	orr r3, r5
	mov r2, r12
	strh r3, [r6, r2]
	mov r3, #1
	add r14, r14, r3
	mov r1, #2
	mov r2, r14
	add r6, r6, #2
	add r8, r8, r1
	cmp r2, #0x40
	bne 1b
	mov r0, sp
	ldr r3, =0x040000d4
	add r0, r0, #2
	ldr r1, =0x5000002
	ldr r2, =0x8000003f
	stmia r3!, {r0, r1, r2}
	sub r3, r3, #0xc
	add sp, sp, #0x80
	
	.code	16
	pop	{r3, r5}
	mov	r8, r3
	mov	sl, r5
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Func_80f61e8,.Lfe1-Func_80f61e8

	.text
	.align	2, 0
