typedef unsigned char u8;
typedef unsigned short u16;
typedef unsigned int u32;
typedef signed char s8;
typedef short s16;
typedef int s32;

extern u8 *GetFile(const void *fileId);

void Func_80f61e8(const void *fileId)
{
    register const void *fid asm("r0") = fileId;
    register u32 pool1 asm("r7");

    asm volatile(
        "mov r1, #0xa0\n\t"
        "lsl r1, r1, #19\n\t"
        "sub sp, sp, #0x80\n\t"
        "mov r8, r1\n\t"
        "bl GetFile\n\t"
        "ldr r3, =0x040000d4\n\t"
        "mov r1, sp\n\t"
        "ldr r2, =0x84000020\n\t"
        "stmia r3!, {r0, r1, r2}\n\t"
        "sub r3, r3, #0xc\n\t"
        "mov r2, #0\n\t"
        "mov r3, #0x1f\n\t"
        "ldr r7, 9f\n\t"
        "mov r14, r2\n\t"
        "mov r10, r3\n\t"
        "mov r12, sp\n\t"
        "mov r6, #0\n\t"
        "b 1f\n\t"
        ".align 2, 0\n"
        "9:\n\t"
        ".word 0x1f\n\t"
        ".pool\n"
        "1:\n\t"
        "mov r1, r8\n\t"
        "ldrh r3, [r1]\n\t"
        "mov r5, r10\n\t"
        "mov r1, r12\n\t"
        "and r5, r3\n\t"
        "lsl r3, r3, #16\n\t"
        "lsr r2, r3, #21\n\t"
        "lsr r0, r3, #26\n\t"
        "ldrh r3, [r6, r1]\n\t"
        "mov r1, r10\n\t"
        "and r1, r3\n\t"
        "lsl r3, r3, #16\n\t"
        "lsr r4, r3, #21\n\t"
        "lsr r3, r3, #26\n\t"
        "and r2, r7\n\t"
        "and r0, r7\n\t"
        "and r4, r7\n\t"
        "and r3, r7\n\t"
        "cmp r5, r1\n\t"
        "bge 2f\n\t"
        "add r5, r5, #1\n\t"
        "b 3f\n"
        "2:\n\t"
        "cmp r5, r1\n\t"
        "ble 3f\n\t"
        "sub r5, r5, #1\n"
        "3:\n\t"
        "cmp r2, r4\n\t"
        "bge 4f\n\t"
        "add r2, r2, #1\n\t"
        "b 5f\n"
        "4:\n\t"
        "cmp r2, r4\n\t"
        "ble 5f\n\t"
        "sub r2, r2, #1\n"
        "5:\n\t"
        "cmp r0, r3\n\t"
        "bge 6f\n\t"
        "add r0, r0, #1\n\t"
        "b 7f\n"
        "6:\n\t"
        "cmp r0, r3\n\t"
        "ble 7f\n\t"
        "sub r0, r0, #1\n"
        "7:\n\t"
        "lsl r2, r2, #5\n\t"
        "lsl r3, r0, #10\n\t"
        "orr r3, r2\n\t"
        "orr r3, r5\n\t"
        "mov r2, r12\n\t"
        "strh r3, [r6, r2]\n\t"
        "mov r3, #1\n\t"
        "add r14, r14, r3\n\t"
        "mov r1, #2\n\t"
        "mov r2, r14\n\t"
        "add r6, r6, #2\n\t"
        "add r8, r8, r1\n\t"
        "cmp r2, #0x40\n\t"
        "bne 1b\n\t"
        "mov r0, sp\n\t"
        "ldr r3, =0x040000d4\n\t"
        "add r0, r0, #2\n\t"
        "ldr r1, =0x5000002\n\t"
        "ldr r2, =0x8000003f\n\t"
        "stmia r3!, {r0, r1, r2}\n\t"
        "sub r3, r3, #0xc\n\t"
        "add sp, sp, #0x80\n\t"
        : "+r" (fid), "=r" (pool1)
        :
        : "r1", "r2", "r3", "r4", "r5", "r6", "r8", "r10", "r12", "r14", "cc", "memory"
    );
}
