@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_909_2008150
	.thumb_func
	.type	 OvlFunc_909_2008150,function
OvlFunc_909_2008150:
	push	{lr}
	bl	__CutsceneStart
	mov	r1, #129
	.code	16
	mov	r2, #0
	.code	16
	mov	r0, #14
	.code	16
	lsl	r1, r1, #1
	.code	16
	bl	__MapActor_Emote
	mov	r1, #2
	.code	16
	mov	r0, #14
	.code	16
	bl	__Func_80925cc
	mov	r0, #40
	bl	__CutsceneWait
	ldr	r0, .L3
	bl	__MessageID
	mov	r0, #14
	.code	16
	mov	r1, #0
	.code	16
	mov	r2, #20
	.code	16
	bl	__Func_8093040
	mov	r1, #0
	.code	16
	mov	r2, #0
	.code	16
	mov	r0, #14
	.code	16
	bl	__Func_809280c
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #14
	.code	16
	mov	r1, #0
	.code	16
	mov	r2, #10
	.code	16
	bl	__Func_8093040
	mov	r1, #176
	.code	16
	mov	r0, #14
	.code	16
	lsl	r1, r1, #8
	.code	16
	mov	r2, #10
	.code	16
	bl	__Func_8092adc
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	5988
.Lfe1:
	.size	 OvlFunc_909_2008150,.Lfe1-OvlFunc_909_2008150
	.align	2, 0
	.global	OvlFunc_909_20081b4
	.thumb_func
	.type	 OvlFunc_909_20081b4,function
OvlFunc_909_20081b4:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L7
	.code	16
	bl	__MessageID
	ldr	r0, .L7+4
	.code	16
	bl	__GetFlag
	cmp	r0, #0
	beq	.L6
	ldr	r0, .L7+8
	.code	16
	bl	__MessageID
.L6:
	mov	r1, #0
	.code	16
	mov	r0, #15
	.code	16
	bl	__ActorMessage
	ldr	r0, .L7+4
	.code	16
	bl	__SetFlag
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L8:
	.align	2, 0
.L7:
	.word	5968
	.word	770
	.word	5992
.Lfe2:
	.size	 OvlFunc_909_20081b4,.Lfe2-OvlFunc_909_20081b4

	.text
	.align	2, 0
