@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_909_200809c
	.thumb_func
	.type	 OvlFunc_909_200809c,function
OvlFunc_909_200809c:
	push	{r5, lr}
	ldr	r3, .L5
	.code	16
	mov	r1, #224
	lsl	r1, r1, #1
	.code	16
	add	r3, r3, r1
	mov	r1, #0
	.code	16
	ldrsh	r2, [r3, r1]
	ldr	r3, .L5+4
	.code	16
	cmp	r2, r3
	bne	.L3
	ldr	r5, .L5+8
	.code	16
	mov	r0, r5
	bl	__Func_808b868
	ldr	r0, .L5+12
	bl	__GetFlag
	cmp	r0, #0
	beq	.L4
	mov	r1, r5
	.code	16
	mov	r3, #2
	.code	16
	add	r1, r1, #166
	.code	16
	strb	r3, [r1]
	mov	r3, r5
	.code	16
	mov	r2, #0
	.code	16
	add	r3, r3, #190
	.code	16
	strb	r2, [r3]
	mov	r2, r5
	.code	16
	add	r2, r2, #214
	.code	16
	mov	r3, #3
	.code	16
	strb	r3, [r2]
	add	r2, r2, #24
	.code	16
	mov	r3, #1
	.code	16
	strb	r3, [r2]
.L4:
	mov	r0, r5
	b	.L2
.L3:
	ldr	r0, .L5+16
.L2:
	pop	{r5}
	pop	{r1}
	bx	r1
.L6:
	.align	2, 0
.L5:
	.word	gState
	.word	0x21
	.word	.L29b4
	.word	2126
	.word	.L299c
.Lfe1:
	.size	 OvlFunc_909_200809c,.Lfe1-OvlFunc_909_200809c
	.align	2, 0
	.global	OvlFunc_909_2008100
	.thumb_func
	.type	 OvlFunc_909_2008100,function
OvlFunc_909_2008100:
	push	{lr}
	ldr	r3, .L9
	.code	16
	mov	r1, #224
	lsl	r1, r1, #1
	.code	16
	add	r3, r3, r1
	mov	r1, #0
	.code	16
	ldrsh	r2, [r3, r1]
	ldr	r3, .L9+4
	.code	16
	cmp	r2, r3
	bne	.L8
	ldr	r0, .L9+8
	b	.L7
.L8:
	ldr	r0, .L9+12
.L7:
	pop	{r1}
	bx	r1
.L10:
	.align	2, 0
.L9:
	.word	gState
	.word	0x21
	.word	.L2ca8
	.word	.L2c9c
.Lfe2:
	.size	 OvlFunc_909_2008100,.Lfe2-OvlFunc_909_2008100

	.text
	.align	2, 0
