#define ACTOR_DIALOGUE_FUNCTION OvlFunc_943_2008a48
#define ACTOR_DIALOGUE_ACTOR_ID 0x15
#define ACTOR_DIALOGUE_DONE_MESSAGE 0x1e08
#define ACTOR_DIALOGUE_PROGRESS_MESSAGE 0x1d6f
#define ACTOR_DIALOGUE_DEFAULT_MESSAGE 0x1d36

#include "../actor_dialogue_branch.inc"
