@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_943_200c218
	.thumb_func
	.type	 OvlFunc_943_200c218,function
OvlFunc_943_200c218:
	push	{lr}
	mov	r0, #232
	mov	r1, #1
	mov	r2, #169
	mov	r3, #0
	.code	16
	lsl	r0, r0, #16
	neg	r1, r1
	lsl	r2, r2, #18
	bl	__Func_80933f8
	bl	__Func_800fe9c
	mov	r1, #232
	mov	r2, #169
	.code	16
	lsl	r1, r1, #16
	lsl	r2, r2, #18
	mov	r0, #0
	.code	16
	bl	__MapActor_SetPos
	mov	r0, #0
	bl	__MapActor_GetActor
	mov	r3, #128
	.code	16
	lsl	r3, r3, #7
	strh	r3, [r0, #6]
	mov	r0, #1
	bl	__WaitFrames
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_943_200c218,.Lfe1-OvlFunc_943_200c218

	.text
	.align	2, 0
