#define ACTOR_DIALOGUE_FUNCTION OvlFunc_943_2008af0
#define ACTOR_DIALOGUE_ACTOR_ID 0x18
#define ACTOR_DIALOGUE_DONE_MESSAGE 0x1e09
#define ACTOR_DIALOGUE_PROGRESS_MESSAGE 0x1d70
#define ACTOR_DIALOGUE_DEFAULT_MESSAGE 0x1d37

#include "../actor_dialogue_branch.inc"
