#define ACTOR_DIRECTION_FUNCTION OvlFunc_967_200829c
#define ACTOR_DIRECTION_ACTION __Func_80b3284
#define ACTOR_DIRECTION_ACTION_ID 0x0b
#define ACTOR_DIRECTION_FLAG 0x9a7
#define ACTOR_DIRECTION_MESSAGE_SET 0x28f6
#define ACTOR_DIRECTION_MESSAGE_CLEAR 0x26eb
#include "../actor_direction_message.inc"
