#define ACTOR_DIRECTION_FUNCTION OvlFunc_967_200815c
#define ACTOR_DIRECTION_ACTION __Func_80b0278
#define ACTOR_DIRECTION_ACTION_ID 0x21
#define ACTOR_DIRECTION_FLAG 0x9a7
#define ACTOR_DIRECTION_MESSAGE_SET 0x28f2
#define ACTOR_DIRECTION_MESSAGE_CLEAR 0x26e7
#include "../actor_direction_message.inc"
