@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_2f84
	.thumb_func
	.type	 OvlFunc_2f84,function
OvlFunc_2f84:
	push	{lr}
	mov	r0, #2
	bl	__Func_77394
	mov	r3, #140
	lsl	r3, r3, #1
	add	r0, r0, r3
	ldrb	r0, [r0]
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 OvlFunc_2f84,.Lfe1-OvlFunc_2f84

	.text
	.align	2, 0
