@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_94
	.thumb_func
	.type	 OvlFunc_94,function
OvlFunc_94:
	mov	r0, #0
	bx	lr
.Lfe1:
	.size	 OvlFunc_94,.Lfe1-OvlFunc_94

	.text
	.align	2, 0
