@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	ActorCmd_Loop
	.thumb_func
	.type	 ActorCmd_Loop,function
ActorCmd_Loop:
	push	{r5, lr}
	mov	r5, r0
	.code	16
	mov	r3, #4
	ldrsh	r2, [r5, r3]
	ldr	r3, [r5]
	lsl	r2, r2, #2
	add	r3, r3, r2
	add	r3, r3, #4
	ldmia	r3!, {r4}
	ldr	r1, [r3]
	.code	16
	ldr	r3, .L8
	cmp	r4, r3
	beq	.L4
	mov	r0, r5
	.code	16
	add	r0, r0, #93
	.code	16
	ldrb	r2, [r0]
	.code	16
	add	r2, r2, #1
	.code	16
	strb	r2, [r0]
	lsl	r3, r4, #16
	.code	16
	lsl	r2, r2, #24
	.code	16
	lsr	r2, r2, #24
	.code	16
	asr	r3, r3, #16
	.code	16
	cmp	r2, r3
	bge	.L6
	mov	r0, r5
	.code	16
.L4:
	bl	Actor_FindScriptMarker
	strh	r0, [r5, #4]
	b	.L7
.L6:
	mov	r3, #0
	.code	16
	strb	r3, [r0]
	ldrh	r3, [r5, #4]
	.code	16
	add	r3, r3, #3
	.code	16
	strh	r3, [r5, #4]
.L7:
	mov	r0, #1
	pop	{r5}
	pop	{r1}
	bx	r1
.L9:
	.align	2, 0
.L8:
	.word	65535
.Lfe1:
	.size	 ActorCmd_Loop,.Lfe1-ActorCmd_Loop

	.text
	.align	2, 0
