@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	ActorCmd_GotoIfNZ
	.thumb_func
	.type	 ActorCmd_GotoIfNZ,function
ActorCmd_GotoIfNZ:
	push	{r5, lr}
	mov	r5, r0
	.code	16
	mov	r2, #4
	.code	16
	ldrsh	r3, [r5, r2]
	ldr	r2, [r5]
	lsl	r3, r3, #2
	add	r3, r3, r2
	ldr	r1, [r3, #4]
	mov	r3, r5
	add	r3, r3, #87
	ldrb	r3, [r3]
	ldrh	r0, [r5, #4]
	cmp	r3, #0
	beq	.L4
	mov	r0, r5
	bl	Actor_FindScriptMarker
	strh	r0, [r5, #4]
	b	.L5
.L4:
	add	r3, r0, #2
	strh	r3, [r5, #4]
.L5:
	mov	r0, #1
	pop	{r5}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 ActorCmd_GotoIfNZ,.Lfe1-ActorCmd_GotoIfNZ
	.align	2, 0
	.global	ActorCmd_GotoIfZ
	.thumb_func
	.type	 ActorCmd_GotoIfZ,function
ActorCmd_GotoIfZ:
	push	{r5, lr}
	mov	r5, r0
	.code	16
	mov	r2, #4
	.code	16
	ldrsh	r3, [r5, r2]
	ldr	r2, [r5]
	lsl	r3, r3, #2
	add	r3, r3, r2
	ldr	r1, [r3, #4]
	mov	r3, r5
	add	r3, r3, #87
	ldrb	r3, [r3]
	ldrh	r0, [r5, #4]
	cmp	r3, #0
	bne	.L8
	mov	r0, r5
	bl	Actor_FindScriptMarker
	strh	r0, [r5, #4]
	b	.L9
.L8:
	add	r3, r0, #2
	strh	r3, [r5, #4]
.L9:
	mov	r0, #1
	pop	{r5}
	pop	{r1}
	bx	r1
.Lfe2:
	.size	 ActorCmd_GotoIfZ,.Lfe2-ActorCmd_GotoIfZ

	.text
	.align	2, 0
