@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	OvlFunc_f34
	.type	 OvlFunc_f34,function
	.thumb_func
OvlFunc_f34:
	mov	r0, #0x0
	bx	lr
.Lfe1:
	.size	 OvlFunc_f34,.Lfe1-OvlFunc_f34

	.text
	.align	2, 0
