@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	GetLocationName
	.thumb_func
	.type	 GetLocationName,function
GetLocationName:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	mov r3, #0
	mov r6, r1
	ldr r5, =.L9ddd8
	mov r8, r3
	mov r7, r0
	.code	16
	bl	GetMapArea
	ldrh r4, [r5]
	mov r1, r4
	lsl r3, r1, #16
	mov r2, #1
	asr r3, #16
	neg r2, r2
	mov r12, r0
	.code	16
	cmp	r3, r2
	beq	.L3
	ldr r0, =0x7fff
	mov r14, r2
	.code	16
.L16:
	ldrb	r2, [r5, #3]
	mov r3, #0x80
	and r3, r2
	.code	16
	cmp	r3, #0
	beq	.L7
	lsl r3, r1, #16
	asr r3, #16
	.code	16
	cmp	r3, r7
	bne	.L10
	b	.L9
.L7:
	lsl r3, r4, #16
	asr r3, #16
	.code	16
	cmp	r3, ip
	bne	.L10
.L9:
	ldrh	r2, [r5, #2]
	mov r3, r0
	and r3, r2
	.code	16
	cmp	r3, r0
	beq	.L14
	lsl r3, r2, #17
	asr r3, #17
	.code	16
	cmp	r3, r6
	bne	.L10
.L14:
	ldr	r5, [r5, #4]
	mov	r8, r5
	b	.L3
.L10:
	add	r5, r5, #8
	ldrh r1, [r5]
	lsl r3, r1, #16
	asr r3, #16
	mov r4, r1
	.code	16
	cmp	r3, lr
	bne	.L16
.L3:
	mov	r0, r8
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 GetLocationName,.Lfe1-GetLocationName

	.text
	.align	2, 0
