@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_808d828
	.thumb_func
	.type	 Func_808d828,function
Func_808d828:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	mov	r6, r0
	mov	r1, r6
	mov	r0, #2
	bl	FindMapActorEvent
	ldr	r3, .L16
	ldr	r3, [r3]
	mov	r7, #1
	mov	r5, r0
	neg	r7, r7
	mov	r8, r3
	cmp	r5, #0
	beq	.L3
	ldr	r1, [r5, #8]
	cmp	r1, #0
	beq	.L3
	ldr	r3, [r5]
	mov	r2, #128
	lsl	r2, r2, #2
	and	r3, r3, r2
	cmp	r3, #0
	beq	.L4
	sub r2, #0x64
	add r2, r8
	mov r3, #0
	strh r3, [r2]
	ldr r1, [r5, #8]
	
	.code	16
.L4:
	mov	r3, #128
	lsl	r3, r3, #9
	cmp	r1, r3
	bge	.L5
	bl	CutsceneStart
	ldr	r0, [r5, #8]
	bl	MessageID
	mov	r0, r7
	mov	r1, #0
	bl	ActorMessage
	mov	r7, #0
	bl	CutsceneEnd
	b	.L7
.L5:
	mov	r0, r6
	bl	_call_via_r1
	b	.L15
.L3:
	mov	r0, #1
	mov	r1, r6
	bl	FindMapActorEvent
	mov	r5, r0
	cmp	r5, #0
	beq	.L7
	ldr	r2, [r5]
	mov	r3, #48
	and	r2, r2, r3
	cmp	r2, #48
	beq	.L12
	cmp	r2, #48
	bgt	.L9
	cmp	r2, #0
	beq	.L10
	cmp	r2, #32
	beq	.L11
	b	.L9
.L10:
	mov	r0, #123
	bl	_PlaySound
	b	.L9
.L11:
	mov	r0, #128
	bl	_PlaySound
	bl	Player_EnterStairsUp
	b	.L9
.L12:
	mov	r0, #129
	bl	_PlaySound
	bl	Player_EnterStairsDown
.L9:
	mov	r3, #184
	ldr	r2, [r5, #8]
	lsl	r3, r3, #1
	add	r3, r3, r8
	strh	r2, [r3]
.L15:
	mov	r7, #0
.L7:
	mov	r0, r7
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L17:
	.align	2, 0
.L16:
	.word	iwram_3001ebc
.Lfe1:
	.size	 Func_808d828,.Lfe1-Func_808d828

	.text
	.align	2, 0
