@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_809a7f4
	.thumb_func
	.type	 Func_809a7f4,function
Func_809a7f4:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	mov	r7, r0
	ldr r0, [r7, #0x68]
	ldrh r6, [r7, #6]
	mov r2, #0x80
	lsl r2, #12
	mov r9, r0
	mov r0, r6
	mov r10, r2
	.code	16
	bl	cos
	ldr r5, =Func_8000888
	mov r1, r0
	mov r0, r10
	mov r12, pc
	bx r5
	.code	16
	mov	r8, r0
	mov	r0, r6
	bl	sin
	mov r1, r0
	mov r0, r10
	mov r12, pc
	bx r5
	.code	16
	mov	r2, r9
	ldr	r3, [r2, #8]
	add	r3, r3, r8
	str	r3, [r7, #8]
	ldr	r3, [r2, #16]
	add	r3, r3, r0
	str	r3, [r7, #16]
	mov r0, #0x80
	ldrh r3, [r7, #6]
	lsl r0, #4
	add r3, r0
	strh r3, [r7, #6]
	mov r2, r7
	add r2, #0x64
	ldrh r3, [r2]
	mov r0, #0xf2
	add r3, #1
	strh r3, [r2]
	lsl r0, #15
	lsl r3, #16
	mov r1, #0
	.code	16
	cmp	r3, r0
	bne	.L3
	ldr r3, =Func_809a738
	str r3, [r7, #0x6c]
	mov r3, r7
	add r3, #0x66
	strh r1, [r2]
	strh r1, [r3]
	ldr r3, =0x1999
	str r3, [r7, #0x48]
	mov r3, #0xc0
	lsl r3, #10
	str r3, [r7, #0x28]
	.code	16
	bl	Random
	strh	r0, [r7, #6]
.L3:
	pop	{r3, r5, r6}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Func_809a7f4,.Lfe1-Func_809a7f4

	.text
	.align	2, 0
