@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80978c4
	.thumb_func
	.type	 Func_80978c4,function
Func_80978c4:
	push	{r5, r6, r7, lr}
	ldr r3, =iwram_3001ea8
	ldr r2, =654
	ldr r5, [r3]
	add r6, r5, r2
	ldrh r0, [r6]
	sub sp, sp, #12
	mov r7, #0
	lsl r0, r0, #16
	add r1, sp, #8
	add r2, sp, #4
	mov r3, sp
	str r7, [sp, #8]
	str r7, [sp, #4]
	str r7, [sp]
	.code	16
	bl	Func_8097948
	ldr r3, [sp, #8]
	ldr r2, =651
	.code	16
	asr	r3, r3, #18
	add	r4, r5, r2
	add	r3, r3, #4
	strb	r3, [r4]
	ldr r3, [sp, #4]
	.code	16
	add	r2, r2, #1
	asr	r3, r3, #18
	add	r0, r5, r2
	add	r3, r3, #4
	strb	r3, [r0]
	ldr r3, [sp]
	.code	16
	add	r2, r2, #1
	asr	r3, r3, #18
	add	r5, r5, r2
	add	r3, r3, #4
	strb	r3, [r5]
	ldrh	r3, [r6]
	add	r3, r3, #4
	strh	r3, [r6]
	mov	r2, #31
	ldrb	r1, [r4]
	mov	r3, r2
	and	r3, r3, r1
	strb	r3, [r4]
	ldrb	r1, [r0]
	mov	r3, r2
	and	r3, r3, r1
	strb	r3, [r0]
	ldrb	r3, [r5]
	and	r2, r2, r3
	strb	r2, [r5]
	mov	r2, #180
	ldrh	r3, [r6]
	lsl	r2, r2, #1
	cmp	r3, r2
	bcc	.L3
	strh	r7, [r6]
.L3:
	add sp, sp, #12
	.code	16
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Func_80978c4,.Lfe1-Func_80978c4

	.text
	.align	2, 0
