@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_808f0d8
	.thumb_func
	.type	 Func_808f0d8,function
Func_808f0d8:
	push	{r5, r6, lr}
	mov	r6, r0
	cmp	r6, #0
	beq	.L2
	ldr	r3, .L4
	mov	r2, #250
	lsl	r2, r2, #1
	add	r3, r3, r2
	ldr	r0, [r3]
	bl	GetFieldActor
	mov	r3, #128
	lsl	r3, r3, #9
	str	r3, [r6, #52]
	mov	r3, #128
	lsl	r3, r3, #10
	mov	r2, r6
	str	r3, [r6, #48]
	add	r2, r2, #85
	.code	16
	mov	r3, #0
	strb	r3, [r2]
	.code	16
	mov	r5, r0
	ldr	r2, [r5, #12]
	mov	r3, #144
	lsl	r3, r3, #14
	add	r2, r2, r3
	ldr	r1, [r5, #8]
	ldr	r3, [r5, #16]
	mov	r0, r6
	bl	_Actor_TravelTo
	mov	r0, #3
	bl	WaitFrames
	mov	r0, r5
	mov	r1, #28
	bl	_Actor_SetAnim
	ldr	r1, .L4+4
	mov	r0, r6
	bl	_Actor_SetScript
	mov	r3, #128
	lsl	r3, r3, #7
	strh	r3, [r5, #6]
.L2:
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L5:
	.align	2, 0
.L4:
	.word	gState
	.word	.L9e75c
.Lfe1:
	.size	 Func_808f0d8,.Lfe1-Func_808f0d8

	.text
	.align	2, 0
