extern void StopTask(void (*)(void));
extern void SetIntrHandler(int, int, int);
extern int divsi3_RAM(int, int);
extern void *iwram_3001ecc;

void Func_80903bc(void)
{
    register void *hud asm("r7");
    register void *base asm("r6");
    register void *valptr asm("r5");

    asm volatile(
        "ldr\tr3, 11f\n\t"
        "ldr\tr1, 12f\n\t"
        "ldr\tr6, [r3]\n\t"
        "add\tr4, r6, r1\n\t"
        "mov\tr2, #0\n\t"
        "ldrsb\tr2, [r4, r2]\n\t"
        "sub\tr3, #0x5c\n\t"
        "ldr\tr7, [r3]\n\t"
        "cmp\tr2, #0\n\t"
        "beq\t1f\n\t"
        "ldr\tr3, 13f\n\t"
        "add\tr1, r6, r3\n\t"
        "mov\tr3, #0\n\t"
        "ldrsb\tr3, [r1, r3]\n\t"
        "ldrb\tr0, [r1]\n\t"
        "cmp\tr3, r2\n\t"
        "blt\t2f\n\t"
        "mov\tr3, #0\n\t"
        "strb\tr3, [r4]\n\t"
        "ldr\tr0, 14f\n\t"
        "bl\tStopTask\n\t"
        "mov\tr0, #1\n\t"
        "mov\tr1, #0\n\t"
        "mov\tr2, #0\n\t"
        "bl\tSetIntrHandler\n\t"
        "b\t3f\n\t"
        "2:\n\t"
        "ldr\tr2, 15f\n\t"
        "add\tr3, r6, r2\n\t"
        "mov\tr2, #0\n\t"
        "ldrsb\tr2, [r3, r2]\n\t"
        "ldr\tr3, 16f\n\t"
        "add\tr5, r6, r3\n\t"
        "mov\tr3, #0\n\t"
        "ldrsb\tr3, [r5, r3]\n\t"
        "sub\tr2, r3\n\t"
        "add\tr3, r0, #1\n\t"
        "strb\tr3, [r1]\n\t"
        "lsl\tr3, r3, #24\n\t"
        "asr\tr3, r3, #24\n\t"
        "mov\tr0, r3\n\t"
        "mul\tr0, r2\n\t"
        "mov\tr1, #0\n\t"
        "ldrsb\tr1, [r4, r1]\n\t"
        "ldr\tr3, 17f\n\t"
        "bl\t_call_via_r3\n\t"
        "mov\tr3, #0\n\t"
        "ldrsb\tr3, [r5, r3]\n\t"
        "ldr\tr1, 18f\n\t"
        "add\tr3, r0\n\t"
        "add\tr2, r6, r1\n\t"
        "strh\tr3, [r2]\n\t"
        "1:\n\t"
        "ldr\tr2, 18f\n\t"
        "add\tr3, r6, r2\n\t"
        "ldrh\tr2, [r3]\n\t"
        "cmp\tr2, #0x4f\n\t"
        "bls\t4f\n\t"
        "mov\tr1, #0x80\n\t"
        "lsl\tr1, r1, #1\n\t"
        "add\tr3, r7, r1\n\t"
        "mov\tr2, #0xc8\n\t"
        "strh\tr2, [r3]\n\t"
        "mov\tr3, #0x81\n\t"
        "lsl\tr3, r3, #1\n\t"
        "add\tr2, r7, r3\n\t"
        "mov\tr3, #0xfa\n\t"
        "strh\tr3, [r2]\n\t"
        "b\t3f\n\t"
        "4:\n\t"
        "mov\tr1, #0x80\n\t"
        "lsl\tr1, r1, #1\n\t"
        "add\tr3, r7, r1\n\t"
        "strh\tr2, [r3]\n\t"
        "ldr\tr3, 10f\n\t"
        "sub\tr3, r2\n\t"
        "mov\tr2, #0x81\n\t"
        "lsl\tr2, r2, #1\n\t"
        "add\tr1, r7, r2\n\t"
        "strh\tr3, [r1]\n\t"
        "3:\n\t"
        : "=r"(hud), "=r"(base), "=r"(valptr)
        :
        : "r0", "r1", "r2", "r3", "r4", "lr", "cc", "memory");
    (void)hud;
    (void)base;
    (void)valptr;
}

asm(
    ".align 2, 0\n\t"
    "10:\n\t"
    ".word\t0x9f\n\t"
    "11:\n\t"
    ".word\tiwram_3001ecc\n\t"
    "12:\n\t"
    ".word\t0x53c\n\t"
    "13:\n\t"
    ".word\t0x53d\n\t"
    "14:\n\t"
    ".word\tFunc_80903bc\n\t"
    "15:\n\t"
    ".word\t0x53b\n\t"
    "16:\n\t"
    ".word\t0x53a\n\t"
    "17:\n\t"
    ".word\tdivsi3_RAM\n\t"
    "18:\n\t"
    ".word\t0x52a\n\t"
);
