@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_1440_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_14b8
	.thumb_func
	.type	 OvlFunc_14b8,function
OvlFunc_14b8:
	mov	r0, #0
	bx	lr
.Lfe1:
	.size	 OvlFunc_14b8,.Lfe1-OvlFunc_14b8

	.text
	.align	2, 0
