@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_921_200816c
	.thumb_func
	.type	 OvlFunc_921_200816c,function
OvlFunc_921_200816c:
	push	{r5, lr}
	ldr	r3, .L8
	mov	r1, #224
	.code	16
	lsl	r1, r1, #1
	add	r3, r3, r1
	mov	r1, #0
	.code	16
	ldrsh	r2, [r3, r1]
	ldr	r3, .L8+4
	.code	16
	cmp	r2, r3
	bne	.L3
	ldr	r5, .L8+8
	.code	16
	mov	r0, r5
	bl	__Func_808b868
	ldr	r0, .L8+12
	bl	__GetFlag
	cmp	r0, #0
	beq	.L4
	mov	r3, #131
	lsl	r3, r3, #1
	.code	16
	add	r2, r5, r3
	mov	r3, #0
	.code	16
	strb	r3, [r2]
	mov	r3, #182
	lsl	r3, r3, #16
	.code	16
	str	r3, [r5, #80]
	mov	r3, #141
	lsl	r3, r3, #18
	.code	16
	str	r3, [r5, #88]
	mov	r3, #2
	.code	16
	str	r3, [r5, #76]
.L4:
	mov	r0, r5
	b	.L5
.L3:
	ldr	r0, .L8+12
	bl	__GetFlag
	cmp	r0, #0
	beq	.L6
	ldr	r0, .L8+16
	b	.L5
.L6:
	ldr	r0, .L8+20
.L5:
	.code	16
	pop	{r5}
	pop	{r1}
	bx	r1
.L9:
	.align	2, 0
.L8:
	.word	gState
	.word	0x33
	.word	.L2ad0
	.word	2177
	.word	gOvl_0200aa58
	.word	.L29e0
.Lfe1:
	.size	 OvlFunc_921_200816c,.Lfe1-OvlFunc_921_200816c

	.text
	.align	2, 0
