@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_150
	.thumb_func
	.type	 OvlFunc_150,function
OvlFunc_150:
	ldr	r3, .L3
	ldr	r3, [r3]
	mov	r2, #1
	add	r3, r3, #53
	strb	r2, [r3]
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	iwram_1f30
.Lfe1:
	.size	 OvlFunc_150,.Lfe1-OvlFunc_150

	.text
	.align	2, 0
