@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_968_200af30
	.thumb_func
	.type	 OvlFunc_968_200af30,function
OvlFunc_968_200af30:
	push	{lr}
	bl	__CutsceneStart
	mov	r1, #128
	mov	r2, #128
	.code	16
	mov	r0, #0
	.code	16
	lsl	r1, r1, #8
	.code	16
	lsl	r2, r2, #7
	.code	16
	bl	__MapActor_SetSpeed
	mov	r1, #130
	mov	r2, #178
	.code	16
	mov	r0, #0
	.code	16
	lsl	r1, r1, #2
	.code	16
	lsl	r2, r2, #2
	.code	16
	bl	__Func_80921c4
	mov	r1, #128
	mov	r0, #0
	.code	16
	lsl	r1, r1, #7
	.code	16
	mov	r2, #10
	.code	16
	bl	__Func_8092adc
	mov	r0, #130
	mov	r2, #196
	mov	r3, #223
	.code	16
	lsl	r2, r2, #18
	.code	16
	mov	r1, #0
	.code	16
	lsl	r0, r0, #18
	.code	16
	bl	OvlFunc_968_2008058
	mov	r1, #6
	mov	r2, #0
	mov	r0, #0
	.code	16
	bl	__Func_8092708
	mov	r0, #60
	bl	__CutsceneWait
	mov	r0, #20
	bl	__Func_8091e9c
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_968_200af30,.Lfe1-OvlFunc_968_200af30

	.text
	.align	2, 0
