@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_946_200a3c4
	.thumb_func
	.type	 OvlFunc_946_200a3c4,function
OvlFunc_946_200a3c4:
	push	{r5, r6, lr}
	mov	r0, #17
	sub	sp, sp, #8
	bl	__MapActor_GetActor
	ldr	r3, [r0, #8]
	mov	r0, #17
	asr r5, r3, #20
	.code	16
	bl	__MapActor_GetActor
	ldr	r3, [r0, #16]
	mov	r0, #19
	asr r6, r3, #20
	.code	16
	bl	__MapActor_GetActor
	ldr	r3, [r0, #8]
	asr	r3, r3, #20
	cmp	r6, #19
	bne	.L3
	sub	r3, r3, #3
	cmp	r3, #2
	bhi	.L4
	
	.code	16
	mov	r2, #16
	b	.L6
.L4:
	
	.code	16
	mov	r2, #64
	b	.L6
.L3:
	cmp	r6, #18
	bne	.L8
	sub	r3, r3, #3
	cmp	r3, #2
	bls	.L2
	mov	r2, #48
.L6:
	neg	r2, r2
	mov	r0, #17
	mov	r1, #0
	bl	OvlFunc_946_2009774
	b	.L10
.L8:
	cmp	r6, #15
	beq	.L2
.L10:
	mov	r0, #2
	bl	__WaitFrames
	mov	r0, #17
	bl	__MapActor_GetActor
	ldr	r3, [r0, #16]
	sub	r5, r5, #1
	asr	r3, r3, #20
	str	r3, [sp, #4]
	mov	r0, r5
	mov	r1, r6
	mov	r2, #3
	mov	r3, #1
	str	r5, [sp]
	bl	__Func_8010704
	mov	r0, #0
	mov	r1, #0
	mov	r2, #3
	mov	r3, #1
	str	r5, [sp]
	str	r6, [sp, #4]
	bl	__Func_8010704
.L2:
	add	sp, sp, #8
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_946_200a3c4,.Lfe1-OvlFunc_946_200a3c4

	.text
	.align	2, 0
