@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_924_200b5b8
	.thumb_func
	.type	 OvlFunc_924_200b5b8,function
OvlFunc_924_200b5b8:
	push	{lr}
	bl	__CutsceneStart
	mov	r0, #0
	mov	r1, #1
	bl	__MapActor_SetAnim
	ldr	r0, .L3
	mov	r1, #1
	bl	__Func_801776c
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	5494
.Lfe1:
	.size	 OvlFunc_924_200b5b8,.Lfe1-OvlFunc_924_200b5b8
	.align	2, 0
	.global	OvlFunc_924_200b5dc
	.thumb_func
	.type	 OvlFunc_924_200b5dc,function
OvlFunc_924_200b5dc:
	push	{lr}
	bl	__CutsceneStart
	mov	r0, #0
	mov	r1, #1
	bl	__MapActor_SetAnim
	ldr	r0, .L6
	mov	r1, #1
	bl	__Func_801776c
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L7:
	.align	2, 0
.L6:
	.word	2387
.Lfe2:
	.size	 OvlFunc_924_200b5dc,.Lfe2-OvlFunc_924_200b5dc
	.align	2, 0
	.global	OvlFunc_924_200b600
	.thumb_func
	.type	 OvlFunc_924_200b600,function
OvlFunc_924_200b600:
	push	{lr}
	bl	__CutsceneStart
	mov	r0, #0
	mov	r1, #1
	bl	__MapActor_SetAnim
	ldr	r0, .L12
	bl	__GetFlag
	cmp	r0, #0
	bne	.L9
	ldr	r0, .L12+4
	mov	r1, #1
	bl	__Func_801776c
	b	.L10
.L9:
	ldr	r0, .L12+8
	mov	r1, #1
	bl	__Func_801776c
.L10:
	mov	r0, #185
	bl	__CheckPartyItem
	mov	r1, #1
	.code	16
	neg	r1, r1
	.code	16
	cmp	r0, r1
	beq	.L11
	ldr	r3, .L12+12
	.code	16
	mov	r1, #185
	.code	16
	ldr	r3, [r3]
	lsl	r1, r1, #1
	.code	16
	add	r2, r3, r1
	mov	r3, #1
	.code	16
	strh	r3, [r2]
.L11:
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L13:
	.align	2, 0
.L12:
	.word	2177
	.word	5686
	.word	5685
	.word	iwram_3001ebc
.Lfe3:
	.size	 OvlFunc_924_200b600,.Lfe3-OvlFunc_924_200b600

	.text
	.align	2, 0
