@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_314_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_4a0
	.thumb_func
	.type	 OvlFunc_4a0,function
OvlFunc_4a0:
	mov	r0, #0
	bx	lr
.Lfe1:
	.size	 OvlFunc_4a0,.Lfe1-OvlFunc_4a0

	.text
	.align	2, 0
