@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_926_2008cd4
	.thumb_func
	.type	 OvlFunc_926_2008cd4,function
OvlFunc_926_2008cd4:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	mov	r0, #19
	sub	sp, sp, #16
	bl	__MapActor_GetActor
	mov	r6, #8
	mov	r7, r0
	.code	16
.L6:
	ldr	r3, [r7, #80]
	mov	r0, #12
	lsl	r5, r6, #12
	sub	r0, r0, r6
	strh	r5, [r3, #30]
	lsl	r0, r0, #1
	bl	__WaitFrames
	mov	r0, r5
	bl	__cos
	lsl	r2, r0, #1
	ldr	r3, [r7, #8]
	add	r2, r2, r0
	lsl	r2, r2, #1
	sub	r3, r3, r2
	str	r3, [r7, #8]
	mov	r0, r5
	bl	__sin
	lsl	r2, r0, #1
	ldr	r3, [r7, #16]
	add	r2, r2, r0
	lsl	r2, r2, #1
	sub	r3, r3, r2
	add	r6, r6, #1
	str	r3, [r7, #16]
	cmp	r6, #12
	bls	.L6
	mov	r3, #144
	lsl	r3, r3, #13
	str	r3, [r7, #12]
	str	r3, [r7, #60]
	ldr	r3, .L7
	mov	r0, #227
	str	r3, [r7, #24]
	bl	__PlaySound
	ldr	r0, [r7, #8]
	ldr	r3, .L7+4
	ldr	r2, [r7, #16]
	mov	r6, #128
	lsl	r6, r6, #12
	ldr	r4, .L7+8
	add	r0, r0, r3
	mov	r3, #128
	mov	r5, #0
	ldr	r1, [r7, #12]
	add	r2, r2, r6
	lsl	r3, r3, #9
	str	r4, [sp]
	str	r5, [sp, #4]
	str	r5, [sp, #8]
	str	r5, [sp, #12]
	mov	r8, r4
	bl	OvlFunc_common0_10c
	ldr	r2, [r7, #16]
	ldr	r4, .L7+12
	ldr	r0, [r7, #8]
	ldr	r1, [r7, #12]
	add	r2, r2, r6
	ldr	r3, .L7+16
	str	r4, [sp]
	str	r5, [sp, #4]
	str	r5, [sp, #8]
	str	r5, [sp, #12]
	bl	OvlFunc_common0_10c
	ldr	r0, [r7, #8]
	mov	r3, #160
	lsl	r3, r3, #12
	ldr	r2, [r7, #16]
	add	r0, r0, r3
	ldr	r3, .L7+20
	ldr	r1, [r7, #12]
	add	r2, r2, r6
	str	r3, [sp]
	mov	r3, r8
	str	r5, [sp, #4]
	str	r5, [sp, #8]
	str	r5, [sp, #12]
	bl	OvlFunc_common0_10c
	add	sp, sp, #16
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L8:
	.align	2, 0
.L7:
	.word	-52428
	.word	-786432
	.word	13107
	.word	19660
	.word	52428
	.word	26214
.Lfe1:
	.size	 OvlFunc_926_2008cd4,.Lfe1-OvlFunc_926_2008cd4

	.text
	.align	2, 0
