@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	MidiKeyToFreq
	.type	 MidiKeyToFreq,function
	.thumb_func
MidiKeyToFreq:
	push	{r4, r5, r6, r7, lr}
	mov	ip, r0
	lsl	r1, r1, #0x18
	lsr	r6, r1, #0x18
	lsl	r7, r2, #0x18
	cmp	r6, #0xb2
	bls	.L7	@cond_branch
	mov	r6, #0xb2
	mov	r7, #0xff
	lsl	r7, r7, #0x18
.L7:
	ldr	r3, .L8
	add	r0, r6, r3
	ldrb	r5, [r0]
	ldr	r4, .L8+0x4
	mov	r2, #0xf
	add	r0, r5, #0
	and	r0, r0, r2
	lsl	r0, r0, #0x2
	add	r0, r0, r4
	lsr	r1, r5, #0x4
	ldr	r5, [r0]
	lsr	r5, r5, r1
	add	r0, r6, #0x1
	add	r0, r0, r3
	ldrb	r1, [r0]
	add	r0, r1, #0
	and	r0, r0, r2
	lsl	r0, r0, #0x2
	add	r0, r0, r4
	lsr	r1, r1, #0x4
	ldr	r0, [r0]
	lsr	r0, r0, r1
	mov	r1, ip
	ldr	r4, [r1, #0x4]
	sub	r0, r0, r5
	add	r1, r7, #0
	bl	umul3232H32
	add	r1, r0, #0
	add	r1, r5, r1
	add	r0, r4, #0
	bl	umul3232H32
	pop	{r4, r5, r6, r7}
	pop	{r1}
	bx	r1
.L9:
	.align	2, 0
.L8:
	.word	gScaleTable
	.word	gFreqTable
.Lfe1:
	.size	 MidiKeyToFreq,.Lfe1-MidiKeyToFreq
	.align	2, 0
	.type	 UnusedFunc,function
	.thumb_func
UnusedFunc:
	bx	lr
.Lfe2:
	.size	 UnusedFunc,.Lfe2-UnusedFunc
	.align	2, 0
	.globl	MPlayContinue
	.type	 MPlayContinue,function
	.thumb_func
MPlayContinue:
	add	r2, r0, #0
	ldr	r3, [r2, #0x34]
	ldr	r0, .L13
	cmp	r3, r0
	bne	.L12	@cond_branch
	ldr	r0, [r2, #0x4]
	ldr	r1, .L13+0x4
	and	r0, r0, r1
	str	r0, [r2, #0x4]
.L12:
	bx	lr
.L14:
	.align	2, 0
.L13:
	.word	0x68736d53
	.word	0x7fffffff
.Lfe3:
	.size	 MPlayContinue,.Lfe3-MPlayContinue
	.align	2, 0
	.globl	MPlayFadeOut
	.type	 MPlayFadeOut,function
	.thumb_func
MPlayFadeOut:
	add	r2, r0, #0
	lsl	r1, r1, #0x10
	lsr	r1, r1, #0x10
	ldr	r3, [r2, #0x34]
	ldr	r0, .L17
	cmp	r3, r0
	bne	.L16	@cond_branch
	strh	r1, [r2, #0x26]
	strh	r1, [r2, #0x24]
	mov	r0, #0x80
	lsl	r0, r0, #0x1
	strh	r0, [r2, #0x28]
.L16:
	bx	lr
.L18:
	.align	2, 0
.L17:
	.word	0x68736d53
.Lfe4:
	.size	 MPlayFadeOut,.Lfe4-MPlayFadeOut
	.align	2, 0
	.globl	m4aSoundInit
	.type	 m4aSoundInit,function
	.thumb_func
m4aSoundInit:
	push	{r4, r5, r6, lr}
	ldr	r0, .L25
	mov	r1, #0x2
	neg	r1, r1
	and	r0, r0, r1
	ldr	r1, .L25+0x4
	ldr	r2, .L25+0x8
	bl	CpuSet
	ldr	r0, .L25+0xc
	bl	SoundInit
	ldr	r0, .L25+0x10
	bl	MPlayExtender
	ldr	r0, .L25+0x14
	bl	m4aSoundMode
	ldr	r0, .L25+0x18
	lsl	r0, r0, #0x10
	lsr	r0, r0, #0x10
	cmp	r0, #0
	beq	.L21	@cond_branch
	ldr	r5, .L25+0x1c
	add	r6, r0, #0
.L23:
	ldr	r4, [r5]
	ldr	r1, [r5, #0x4]
	ldrb	r2, [r5, #0x8]
	add	r0, r4, #0
	bl	MPlayOpen
	ldrh	r0, [r5, #0xa]
	strb	r0, [r4, #0xb]
	ldr	r0, .L25+0x20
	str	r0, [r4, #0x18]
	add	r5, r5, #0xc
	sub	r6, r6, #0x1
	cmp	r6, #0
	bne	.L23	@cond_branch
.L21:
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
.L26:
	.align	2, 0
.L25:
	.word	SoundMainRAM
	.word	SoundMainRAM_Buffer
	.word	0x4000100
	.word	gSoundInfo
	.word	gCgbChans
	.word	0x97f800
	.word	gNumMusicPlayers
	.word	gMPlayTable
	.word	gMPlayMemAccArea
.Lfe5:
	.size	 m4aSoundInit,.Lfe5-m4aSoundInit
	.align	2, 0
	.globl	m4aSoundMain
	.type	 m4aSoundMain,function
	.thumb_func
m4aSoundMain:
	push	{lr}
	bl	SoundMain
	pop	{r0}
	bx	r0
.Lfe6:
	.size	 m4aSoundMain,.Lfe6-m4aSoundMain
	.align	2, 0
	.globl	m4aSongNumStart
	.type	 m4aSongNumStart,function
	.thumb_func
m4aSongNumStart:
	push	{lr}
	lsl	r0, r0, #0x10
	ldr	r2, .L29
	ldr	r1, .L29+0x4
	lsr	r0, r0, #0xd
	add	r0, r0, r1
	ldrh	r3, [r0, #0x4]
	lsl	r1, r3, #0x1
	add	r1, r1, r3
	lsl	r1, r1, #0x2
	add	r1, r1, r2
	ldr	r2, [r1]
	ldr	r1, [r0]
	add	r0, r2, #0
	bl	MPlayStart
	pop	{r0}
	bx	r0
.L30:
	.align	2, 0
.L29:
	.word	gMPlayTable
	.word	gSongTable
.Lfe7:
	.size	 m4aSongNumStart,.Lfe7-m4aSongNumStart
	.align	2, 0
	.globl	m4aSongNumStartOrChange
	.type	 m4aSongNumStartOrChange,function
	.thumb_func
m4aSongNumStartOrChange:
	push	{lr}
	lsl	r0, r0, #0x10
	ldr	r2, .L36
	ldr	r1, .L36+0x4
	lsr	r0, r0, #0xd
	add	r0, r0, r1
	ldrh	r3, [r0, #0x4]
	lsl	r1, r3, #0x1
	add	r1, r1, r3
	lsl	r1, r1, #0x2
	add	r1, r1, r2
	ldr	r1, [r1]
	ldr	r3, [r1]
	ldr	r2, [r0]
	cmp	r3, r2
	beq	.L32	@cond_branch
	add	r0, r1, #0
	add	r1, r2, #0
	bl	MPlayStart
	b	.L33
.L37:
	.align	2, 0
.L36:
	.word	gMPlayTable
	.word	gSongTable
.L32:
	ldr	r2, [r1, #0x4]
	ldrh	r0, [r1, #0x4]
	cmp	r0, #0
	beq	.L35	@cond_branch
	cmp	r2, #0
	bge	.L33	@cond_branch
.L35:
	add	r0, r1, #0
	add	r1, r3, #0
	bl	MPlayStart
.L33:
	pop	{r0}
	bx	r0
.Lfe8:
	.size	 m4aSongNumStartOrChange,.Lfe8-m4aSongNumStartOrChange
	.align	2, 0
	.globl	m4aSongNumStartOrContinue
	.type	 m4aSongNumStartOrContinue,function
	.thumb_func
m4aSongNumStartOrContinue:
	push	{lr}
	lsl	r0, r0, #0x10
	ldr	r2, .L44
	ldr	r1, .L44+0x4
	lsr	r0, r0, #0xd
	add	r0, r0, r1
	ldrh	r3, [r0, #0x4]
	lsl	r1, r3, #0x1
	add	r1, r1, r3
	lsl	r1, r1, #0x2
	add	r1, r1, r2
	ldr	r1, [r1]
	ldr	r3, [r1]
	ldr	r2, [r0]
	cmp	r3, r2
	beq	.L39	@cond_branch
	add	r0, r1, #0
	add	r1, r2, #0
	bl	MPlayStart
	b	.L40
.L45:
	.align	2, 0
.L44:
	.word	gMPlayTable
	.word	gSongTable
.L39:
	ldr	r2, [r1, #0x4]
	ldrh	r0, [r1, #0x4]
	cmp	r0, #0
	bne	.L41	@cond_branch
	add	r0, r1, #0
	add	r1, r3, #0
	bl	MPlayStart
	b	.L40
.L41:
	cmp	r2, #0
	bge	.L40	@cond_branch
	add	r0, r1, #0
	bl	MPlayContinue
.L40:
	pop	{r0}
	bx	r0
.Lfe9:
	.size	 m4aSongNumStartOrContinue,.Lfe9-m4aSongNumStartOrContinue
	.align	2, 0
	.globl	m4aSongNumStop
	.type	 m4aSongNumStop,function
	.thumb_func
m4aSongNumStop:
	push	{lr}
	lsl	r0, r0, #0x10
	ldr	r2, .L48
	ldr	r1, .L48+0x4
	lsr	r0, r0, #0xd
	add	r0, r0, r1
	ldrh	r3, [r0, #0x4]
	lsl	r1, r3, #0x1
	add	r1, r1, r3
	lsl	r1, r1, #0x2
	add	r1, r1, r2
	ldr	r2, [r1]
	ldr	r1, [r2]
	ldr	r0, [r0]
	cmp	r1, r0
	bne	.L47	@cond_branch
	add	r0, r2, #0
	bl	MPlayStop
.L47:
	pop	{r0}
	bx	r0
.L49:
	.align	2, 0
.L48:
	.word	gMPlayTable
	.word	gSongTable
.Lfe10:
	.size	 m4aSongNumStop,.Lfe10-m4aSongNumStop
	.align	2, 0
	.globl	m4aSongNumContinue
	.type	 m4aSongNumContinue,function
	.thumb_func
m4aSongNumContinue:
	push	{lr}
	lsl	r0, r0, #0x10
	ldr	r2, .L52
	ldr	r1, .L52+0x4
	lsr	r0, r0, #0xd
	add	r0, r0, r1
	ldrh	r3, [r0, #0x4]
	lsl	r1, r3, #0x1
	add	r1, r1, r3
	lsl	r1, r1, #0x2
	add	r1, r1, r2
	ldr	r2, [r1]
	ldr	r1, [r2]
	ldr	r0, [r0]
	cmp	r1, r0
	bne	.L51	@cond_branch
	add	r0, r2, #0
	bl	MPlayContinue
.L51:
	pop	{r0}
	bx	r0
.L53:
	.align	2, 0
.L52:
	.word	gMPlayTable
	.word	gSongTable
.Lfe11:
	.size	 m4aSongNumContinue,.Lfe11-m4aSongNumContinue
	.align	2, 0
	.globl	m4aMPlayAllStop
	.type	 m4aMPlayAllStop,function
	.thumb_func
m4aMPlayAllStop:
	push	{r4, r5, lr}
	ldr	r0, .L60
	lsl	r0, r0, #0x10
	lsr	r0, r0, #0x10
	cmp	r0, #0
	beq	.L56	@cond_branch
	ldr	r5, .L60+0x4
	add	r4, r0, #0
.L58:
	ldr	r0, [r5]
	bl	MPlayStop
	add	r5, r5, #0xc
	sub	r4, r4, #0x1
	cmp	r4, #0
	bne	.L58	@cond_branch
.L56:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
.L61:
	.align	2, 0
.L60:
	.word	gNumMusicPlayers
	.word	gMPlayTable
.Lfe12:
	.size	 m4aMPlayAllStop,.Lfe12-m4aMPlayAllStop
	.align	2, 0
	.globl	m4aMPlayContinue
	.type	 m4aMPlayContinue,function
	.thumb_func
m4aMPlayContinue:
	push	{lr}
	bl	MPlayContinue
	pop	{r0}
	bx	r0
.Lfe13:
	.size	 m4aMPlayContinue,.Lfe13-m4aMPlayContinue
	.align	2, 0
	.globl	m4aMPlayAllContinue
	.type	 m4aMPlayAllContinue,function
	.thumb_func
m4aMPlayAllContinue:
	push	{r4, r5, lr}
	ldr	r0, .L69
	lsl	r0, r0, #0x10
	lsr	r0, r0, #0x10
	cmp	r0, #0
	beq	.L65	@cond_branch
	ldr	r5, .L69+0x4
	add	r4, r0, #0
.L67:
	ldr	r0, [r5]
	bl	MPlayContinue
	add	r5, r5, #0xc
	sub	r4, r4, #0x1
	cmp	r4, #0
	bne	.L67	@cond_branch
.L65:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
.L70:
	.align	2, 0
.L69:
	.word	gNumMusicPlayers
	.word	gMPlayTable
.Lfe14:
	.size	 m4aMPlayAllContinue,.Lfe14-m4aMPlayAllContinue
	.align	2, 0
	.globl	m4aMPlayFadeOut
	.type	 m4aMPlayFadeOut,function
	.thumb_func
m4aMPlayFadeOut:
	push	{lr}
	lsl	r1, r1, #0x10
	lsr	r1, r1, #0x10
	bl	MPlayFadeOut
	pop	{r0}
	bx	r0
.Lfe15:
	.size	 m4aMPlayFadeOut,.Lfe15-m4aMPlayFadeOut
	.align	2, 0
	.globl	m4aMPlayFadeOutTemporarily
	.type	 m4aMPlayFadeOutTemporarily,function
	.thumb_func
m4aMPlayFadeOutTemporarily:
	add	r2, r0, #0
	lsl	r1, r1, #0x10
	lsr	r1, r1, #0x10
	ldr	r3, [r2, #0x34]
	ldr	r0, .L74
	cmp	r3, r0
	bne	.L73	@cond_branch
	strh	r1, [r2, #0x26]
	strh	r1, [r2, #0x24]
	ldr	r0, .L74+0x4
	strh	r0, [r2, #0x28]
.L73:
	bx	lr
.L75:
	.align	2, 0
.L74:
	.word	0x68736d53
	.word	0x101
.Lfe16:
	.size	 m4aMPlayFadeOutTemporarily,.Lfe16-m4aMPlayFadeOutTemporarily
	.align	2, 0
	.globl	m4aMPlayFadeIn
	.type	 m4aMPlayFadeIn,function
	.thumb_func
m4aMPlayFadeIn:
	add	r2, r0, #0
	lsl	r1, r1, #0x10
	lsr	r1, r1, #0x10
	ldr	r3, [r2, #0x34]
	ldr	r0, .L78
	cmp	r3, r0
	bne	.L77	@cond_branch
	strh	r1, [r2, #0x26]
	strh	r1, [r2, #0x24]
	mov	r0, #0x2
	strh	r0, [r2, #0x28]
	ldr	r0, [r2, #0x4]
	ldr	r1, .L78+0x4
	and	r0, r0, r1
	str	r0, [r2, #0x4]
.L77:
	bx	lr
.L79:
	.align	2, 0
.L78:
	.word	0x68736d53
	.word	0x7fffffff
.Lfe17:
	.size	 m4aMPlayFadeIn,.Lfe17-m4aMPlayFadeIn
	.align	2, 0
	.globl	m4aMPlayImmInit
	.type	 m4aMPlayImmInit,function
	.thumb_func
m4aMPlayImmInit:
	push	{r4, r5, r6, r7, lr}
	ldrb	r5, [r0, #0x8]
	ldr	r4, [r0, #0x2c]
	cmp	r5, #0
	ble	.L82	@cond_branch
	mov	r7, #0x80
.L83:
	ldrb	r1, [r4]
	add	r0, r7, #0
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L84	@cond_branch
	mov	r6, #0x40
	add	r0, r6, #0
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L84	@cond_branch
	add	r0, r4, #0
	bl	Clear64byte
	strb	r7, [r4]
	mov	r0, #0x2
	strb	r0, [r4, #0xf]
	strb	r6, [r4, #0x13]
	mov	r0, #0x16
	strb	r0, [r4, #0x19]
	add	r1, r4, #0
	add	r1, r1, #0x24
	mov	r0, #0x1
	strb	r0, [r1]
.L84:
	sub	r5, r5, #0x1
	add	r4, r4, #0x50
	cmp	r5, #0
	bgt	.L83	@cond_branch
.L82:
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe18:
	.size	 m4aMPlayImmInit,.Lfe18-m4aMPlayImmInit
	.align	2, 0
	.globl	MPlayExtender
	.type	 MPlayExtender,function
	.thumb_func
MPlayExtender:
	push	{r4, r5, r6, lr}
	add	sp, sp, #-0x4
	add	r5, r0, #0
	ldr	r1, .L89
	mov	r0, #0x8f
	strh	r0, [r1]
	ldr	r3, .L89+0x4
	mov	r2, #0x0
	strh	r2, [r3]
	ldr	r0, .L89+0x8
	mov	r1, #0x8
	strb	r1, [r0]
	add	r0, r0, #0x6
	strb	r1, [r0]
	add	r0, r0, #0x10
	strb	r1, [r0]
	sub	r0, r0, #0x14
	mov	r1, #0x80
	strb	r1, [r0]
	add	r0, r0, #0x8
	strb	r1, [r0]
	add	r0, r0, #0x10
	strb	r1, [r0]
	sub	r0, r0, #0xd
	strb	r2, [r0]
	mov	r0, #0x77
	strb	r0, [r3]
	ldr	r0, .L89+0xc
	ldr	r4, [r0]
	ldr	r6, [r4]
	ldr	r0, .L89+0x10
	cmp	r6, r0
	bne	.L87	@cond_branch
	add	r0, r6, #0x1
	str	r0, [r4]
	ldr	r1, .L89+0x14
	ldr	r0, .L89+0x18
	str	r0, [r1, #0x20]
	ldr	r0, .L89+0x1c
	str	r0, [r1, #0x44]
	ldr	r0, .L89+0x20
	str	r0, [r1, #0x4c]
	ldr	r0, .L89+0x24
	str	r0, [r1, #0x70]
	ldr	r0, .L89+0x28
	str	r0, [r1, #0x74]
	ldr	r0, .L89+0x2c
	str	r0, [r1, #0x78]
	ldr	r0, .L89+0x30
	str	r0, [r1, #0x7c]
	add	r2, r1, #0
	add	r2, r2, #0x80
	ldr	r0, .L89+0x34
	str	r0, [r2]
	add	r1, r1, #0x84
	ldr	r0, .L89+0x38
	str	r0, [r1]
	str	r5, [r4, #0x1c]
	ldr	r0, .L89+0x3c
	str	r0, [r4, #0x28]
	ldr	r0, .L89+0x40
	str	r0, [r4, #0x2c]
	ldr	r0, .L89+0x44
	str	r0, [r4, #0x30]
	ldr	r0, .L89+0x48
	mov	r1, #0x0
	strb	r0, [r4, #0xc]
	str	r1, [sp]
	ldr	r2, .L89+0x4c
	mov	r0, sp
	add	r1, r5, #0
	bl	CpuSet
	mov	r0, #0x1
	strb	r0, [r5, #0x1]
	mov	r0, #0x11
	strb	r0, [r5, #0x1c]
	add	r1, r5, #0
	add	r1, r1, #0x41
	mov	r0, #0x2
	strb	r0, [r1]
	add	r1, r1, #0x1b
	mov	r0, #0x22
	strb	r0, [r1]
	add	r1, r1, #0x25
	mov	r0, #0x3
	strb	r0, [r1]
	add	r1, r1, #0x1b
	mov	r0, #0x44
	strb	r0, [r1]
	add	r1, r1, #0x24
	mov	r0, #0x4
	strb	r0, [r1, #0x1]
	mov	r0, #0x88
	strb	r0, [r1, #0x1c]
	str	r6, [r4]
.L87:
	add	sp, sp, #0x4
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
.L90:
	.align	2, 0
.L89:
	.word	0x4000084
	.word	0x4000080
	.word	0x4000063
	.word	0x3007ff0
	.word	0x68736d53
	.word	gMPlayJumpTable
	.word	MP2K_event_memacc
	.word	MP2K_event_lfos
	.word	MP2K_event_mod
	.word	MP2K_event_xcmd
	.word	MP2K_event_endtie
	.word	SampleFreqSet
	.word	TrackStop
	.word	FadeOutBody
	.word	TrkVolPitSet
	.word	CgbSound
	.word	CgbOscOff
	.word	MidiKeyToCgbFreq
	.word	gMaxLines
	.word	0x5000040
.Lfe19:
	.size	 MPlayExtender,.Lfe19-MPlayExtender
	.align	2, 0
	.globl	MusicPlayerJumpTableCopy
	.type	 MusicPlayerJumpTableCopy,function
	.thumb_func
MusicPlayerJumpTableCopy:
	swi 0x2A
	.code	16
	bx	lr
.Lfe20:
	.size	 MusicPlayerJumpTableCopy,.Lfe20-MusicPlayerJumpTableCopy
	.align	2, 0
	.globl	ClearChain
	.type	 ClearChain,function
	.thumb_func
ClearChain:
	push	{lr}
	ldr	r1, .L93
	ldr	r1, [r1]
	bl	_call_via_r1
	pop	{r0}
	bx	r0
.L94:
	.align	2, 0
.L93:
	.word	gMPlayJumpTable+0x88
.Lfe21:
	.size	 ClearChain,.Lfe21-ClearChain
	.align	2, 0
	.globl	Clear64byte
	.type	 Clear64byte,function
	.thumb_func
Clear64byte:
	push	{lr}
	ldr	r1, .L96
	ldr	r1, [r1]
	bl	_call_via_r1
	pop	{r0}
	bx	r0
.L97:
	.align	2, 0
.L96:
	.word	gMPlayJumpTable+0x8c
.Lfe22:
	.size	 Clear64byte,.Lfe22-Clear64byte
	.align	2, 0
	.globl	SoundInit
	.type	 SoundInit,function
	.thumb_func
SoundInit:
	push	{r4, r5, lr}
	add	sp, sp, #-0x4
	add	r5, r0, #0
	mov	r3, #0x0
	str	r3, [r5]
	ldr	r1, .L101
	ldr	r0, [r1]
	mov	r2, #0x80
	lsl	r2, r2, #0x12
	and	r0, r0, r2
	cmp	r0, #0
	beq	.L99	@cond_branch
	ldr	r0, .L101+0x4
	str	r0, [r1]
.L99:
	ldr	r1, .L101+0x8
	ldr	r0, [r1]
	and	r0, r0, r2
	cmp	r0, #0
	beq	.L100	@cond_branch
	ldr	r0, .L101+0x4
	str	r0, [r1]
.L100:
	ldr	r0, .L101+0xc
	mov	r2, #0x80
	lsl	r2, r2, #0x3
	add	r1, r2, #0
	strh	r1, [r0]
	add	r0, r0, #0xc
	strh	r1, [r0]
	ldr	r1, .L101+0x10
	mov	r0, #0x8f
	strh	r0, [r1]
	sub	r1, r1, #0x2
	ldr	r2, .L101+0x14
	add	r0, r2, #0
	strh	r0, [r1]
	ldr	r2, .L101+0x18
	ldrb	r1, [r2]
	mov	r0, #0x3f
	and	r0, r0, r1
	mov	r1, #0x40
	orr	r0, r0, r1
	strb	r0, [r2]
	ldr	r1, .L101+0x1c
	mov	r2, #0xd4
	lsl	r2, r2, #0x2
	add	r0, r5, r2
	str	r0, [r1]
	add	r1, r1, #0x4
	ldr	r0, .L101+0x20
	str	r0, [r1]
	add	r1, r1, #0x8
	mov	r2, #0x98
	lsl	r2, r2, #0x4
	add	r0, r5, r2
	str	r0, [r1]
	add	r1, r1, #0x4
	ldr	r0, .L101+0x24
	str	r0, [r1]
	ldr	r0, .L101+0x28
	str	r5, [r0]
	str	r3, [sp]
	ldr	r2, .L101+0x2c
	mov	r0, sp
	add	r1, r5, #0
	bl	CpuSet
	mov	r0, #0x8
	strb	r0, [r5, #0x6]
	mov	r0, #0xf
	strb	r0, [r5, #0x7]
	ldr	r0, .L101+0x30
	str	r0, [r5, #0x38]
	ldr	r0, .L101+0x34
	str	r0, [r5, #0x28]
	str	r0, [r5, #0x2c]
	str	r0, [r5, #0x30]
	str	r0, [r5, #0x3c]
	ldr	r4, .L101+0x38
	add	r0, r4, #0
	bl	MPlayJumpTableCopy
	str	r4, [r5, #0x34]
	mov	r0, #0x80
	lsl	r0, r0, #0xb
	bl	SampleFreqSet
	ldr	r0, .L101+0x3c
	str	r0, [r5]
	add	sp, sp, #0x4
	pop	{r4, r5}
	pop	{r0}
	bx	r0
.L102:
	.align	2, 0
.L101:
	.word	0x40000c4
	.word	-0x7bbffffc
	.word	0x40000d0
	.word	0x40000c6
	.word	0x4000084
	.word	0xa90e
	.word	0x4000089
	.word	0x40000bc
	.word	0x40000a0
	.word	0x40000a4
	.word	0x3007ff0
	.word	0x50003ec
	.word	MP2K_event_nxx
	.word	MP2K_event_null
	.word	gMPlayJumpTable
	.word	0x68736d53
.Lfe23:
	.size	 SoundInit,.Lfe23-SoundInit
	.align	2, 0
	.globl	SampleFreqSet
	.type	 SampleFreqSet,function
	.thumb_func
SampleFreqSet:
	push	{r4, r5, r6, lr}
	add	r2, r0, #0
	ldr	r0, .L112
	ldr	r4, [r0]
	mov	r0, #0xf0
	lsl	r0, r0, #0xc
	and	r0, r0, r2
	lsr	r2, r0, #0x10
	mov	r6, #0x0
	strb	r2, [r4, #0x8]
	ldr	r1, .L112+0x4
	sub	r0, r2, #0x1
	lsl	r0, r0, #0x1
	add	r0, r0, r1
	ldrh	r5, [r0]
	str	r5, [r4, #0x10]
	mov	r0, #0xc6
	lsl	r0, r0, #0x3
	add	r1, r5, #0
	bl	__divsi3
	strb	r0, [r4, #0xb]
	ldr	r0, .L112+0x8
	mul	r0, r0, r5
	ldr	r1, .L112+0xc
	add	r0, r0, r1
	ldr	r1, .L112+0x10
	bl	__divsi3
	add	r1, r0, #0
	str	r1, [r4, #0x14]
	mov	r0, #0x80
	lsl	r0, r0, #0x11
	bl	__divsi3
	add	r0, r0, #0x1
	asr	r0, r0, #0x1
	str	r0, [r4, #0x18]
	ldr	r0, .L112+0x14
	strh	r6, [r0]
	ldr	r4, .L112+0x18
	ldr	r0, .L112+0x1c
	add	r1, r5, #0
	bl	__divsi3
	neg	r0, r0
	strh	r0, [r4]
	bl	m4aSoundVSyncOn
	ldr	r1, .L112+0x20
.L104:
	ldrb	r0, [r1]
	cmp	r0, #0x9f
	beq	.L104	@cond_branch
	ldr	r1, .L112+0x20
.L108:
	ldrb	r0, [r1]
	cmp	r0, #0x9f
	bne	.L108	@cond_branch
	ldr	r1, .L112+0x14
	mov	r0, #0x80
	strh	r0, [r1]
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
.L113:
	.align	2, 0
.L112:
	.word	0x3007ff0
	.word	gPcmSamplesPerVBlankTable
	.word	0x91d1b
	.word	0x1388
	.word	0x2710
	.word	0x4000102
	.word	0x4000100
	.word	0x44940
	.word	0x4000006
.Lfe24:
	.size	 SampleFreqSet,.Lfe24-SampleFreqSet
	.align	2, 0
	.globl	m4aSoundMode
	.type	 m4aSoundMode,function
	.thumb_func
m4aSoundMode:
	push	{r4, r5, lr}
	add	r3, r0, #0
	ldr	r0, .L125
	ldr	r5, [r0]
	ldr	r1, [r5]
	ldr	r0, .L125+0x4
	cmp	r1, r0
	bne	.L114	@cond_branch
	add	r0, r1, #0x1
	str	r0, [r5]
	mov	r4, #0xff
	and	r4, r4, r3
	cmp	r4, #0
	beq	.L116	@cond_branch
	mov	r0, #0x7f
	and	r4, r4, r0
	strb	r4, [r5, #0x5]
.L116:
	mov	r4, #0xf0
	lsl	r4, r4, #0x4
	and	r4, r4, r3
	cmp	r4, #0
	beq	.L117	@cond_branch
	lsr	r0, r4, #0x8
	strb	r0, [r5, #0x6]
	mov	r4, #0xc
	add	r0, r5, #0
	add	r0, r0, #0x50
	mov	r1, #0x0
.L120:
	strb	r1, [r0]
	sub	r4, r4, #0x1
	add	r0, r0, #0x40
	cmp	r4, #0
	bne	.L120	@cond_branch
.L117:
	mov	r4, #0xf0
	lsl	r4, r4, #0x8
	and	r4, r4, r3
	cmp	r4, #0
	beq	.L122	@cond_branch
	lsr	r0, r4, #0xc
	strb	r0, [r5, #0x7]
.L122:
	mov	r4, #0xb0
	lsl	r4, r4, #0x10
	and	r4, r4, r3
	cmp	r4, #0
	beq	.L123	@cond_branch
	mov	r0, #0xc0
	lsl	r0, r0, #0xe
	and	r0, r0, r4
	lsr	r4, r0, #0xe
	ldr	r2, .L125+0x8
	ldrb	r1, [r2]
	mov	r0, #0x3f
	and	r0, r0, r1
	orr	r0, r0, r4
	strb	r0, [r2]
.L123:
	mov	r4, #0xf0
	lsl	r4, r4, #0xc
	and	r4, r4, r3
	cmp	r4, #0
	beq	.L124	@cond_branch
	bl	m4aSoundVSyncOff
	add	r0, r4, #0
	bl	SampleFreqSet
.L124:
	ldr	r0, .L125+0x4
	str	r0, [r5]
.L114:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
.L126:
	.align	2, 0
.L125:
	.word	0x3007ff0
	.word	0x68736d53
	.word	0x4000089
.Lfe25:
	.size	 m4aSoundMode,.Lfe25-m4aSoundMode
	.align	2, 0
	.globl	SoundClear
	.type	 SoundClear,function
	.thumb_func
SoundClear:
	push	{r4, r5, r6, r7, lr}
	ldr	r0, .L138
	ldr	r6, [r0]
	ldr	r1, [r6]
	ldr	r0, .L138+0x4
	cmp	r1, r0
	bne	.L127	@cond_branch
	add	r0, r1, #0x1
	str	r0, [r6]
	mov	r5, #0xc
	add	r4, r6, #0
	add	r4, r4, #0x50
	mov	r0, #0x0
.L131:
	strb	r0, [r4]
	sub	r5, r5, #0x1
	add	r4, r4, #0x40
	cmp	r5, #0
	bgt	.L131	@cond_branch
	ldr	r4, [r6, #0x1c]
	cmp	r4, #0
	beq	.L133	@cond_branch
	mov	r5, #0x1
	mov	r7, #0x0
.L136:
	lsl	r0, r5, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, [r6, #0x2c]
	bl	_call_via_r1
	strb	r7, [r4]
	add	r5, r5, #0x1
	add	r4, r4, #0x40
	cmp	r5, #0x4
	ble	.L136	@cond_branch
.L133:
	ldr	r0, .L138+0x4
	str	r0, [r6]
.L127:
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.L139:
	.align	2, 0
.L138:
	.word	0x3007ff0
	.word	0x68736d53
.Lfe26:
	.size	 SoundClear,.Lfe26-SoundClear
	.align	2, 0
	.globl	m4aSoundVSyncOff
	.type	 m4aSoundVSyncOff,function
	.thumb_func
m4aSoundVSyncOff:
	push	{lr}
	add	sp, sp, #-0x4
	ldr	r0, .L144
	ldr	r2, [r0]
	ldr	r1, [r2]
	ldr	r3, .L144+0x4
	add	r0, r1, r3
	cmp	r0, #0x1
	bhi	.L141	@cond_branch
	add	r0, r1, #0
	add	r0, r0, #0xa
	str	r0, [r2]
	ldr	r1, .L144+0x8
	ldr	r0, [r1]
	mov	r3, #0x80
	lsl	r3, r3, #0x12
	and	r0, r0, r3
	cmp	r0, #0
	beq	.L142	@cond_branch
	ldr	r0, .L144+0xc
	str	r0, [r1]
.L142:
	ldr	r1, .L144+0x10
	ldr	r0, [r1]
	and	r0, r0, r3
	cmp	r0, #0
	beq	.L143	@cond_branch
	ldr	r0, .L144+0xc
	str	r0, [r1]
.L143:
	ldr	r0, .L144+0x14
	mov	r3, #0x80
	lsl	r3, r3, #0x3
	add	r1, r3, #0
	strh	r1, [r0]
	add	r0, r0, #0xc
	strh	r1, [r0]
	mov	r0, #0x0
	str	r0, [sp]
	mov	r0, #0xd4
	lsl	r0, r0, #0x2
	add	r1, r2, r0
	ldr	r2, .L144+0x18
	mov	r0, sp
	bl	CpuSet
.L141:
	add	sp, sp, #0x4
	pop	{r0}
	bx	r0
.L145:
	.align	2, 0
.L144:
	.word	0x3007ff0
	.word	-0x68736d53
	.word	0x40000c4
	.word	-0x7bbffffc
	.word	0x40000d0
	.word	0x40000c6
	.word	0x5000318
.Lfe27:
	.size	 m4aSoundVSyncOff,.Lfe27-m4aSoundVSyncOff
	.align	2, 0
	.globl	m4aSoundVSyncOn
	.type	 m4aSoundVSyncOn,function
	.thumb_func
m4aSoundVSyncOn:
	push	{r4, lr}
	ldr	r0, .L148
	ldr	r2, [r0]
	ldr	r3, [r2]
	ldr	r0, .L148+0x4
	cmp	r3, r0
	beq	.L146	@cond_branch
	ldr	r0, .L148+0x8
	mov	r4, #0xb6
	lsl	r4, r4, #0x8
	add	r1, r4, #0
	strh	r1, [r0]
	add	r0, r0, #0xc
	strh	r1, [r0]
	ldrb	r0, [r2, #0x4]
	mov	r0, #0x0
	strb	r0, [r2, #0x4]
	add	r0, r3, #0
	sub	r0, r0, #0xa
	str	r0, [r2]
.L146:
	pop	{r4}
	pop	{r0}
	bx	r0
.L149:
	.align	2, 0
.L148:
	.word	0x3007ff0
	.word	0x68736d53
	.word	0x40000c6
.Lfe28:
	.size	 m4aSoundVSyncOn,.Lfe28-m4aSoundVSyncOn
	.align	2, 0
	.globl	MPlayOpen
	.type	 MPlayOpen,function
	.thumb_func
MPlayOpen:
	push	{r4, r5, r6, r7, lr}
	add	r7, r0, #0
	add	r6, r1, #0
	lsl	r2, r2, #0x18
	lsr	r4, r2, #0x18
	cmp	r4, #0
	beq	.L150	@cond_branch
	cmp	r4, #0x10
	bls	.L152	@cond_branch
	mov	r4, #0x10
.L152:
	ldr	r0, .L159
	ldr	r5, [r0]
	ldr	r1, [r5]
	ldr	r0, .L159+0x4
	cmp	r1, r0
	bne	.L150	@cond_branch
	add	r0, r1, #0x1
	str	r0, [r5]
	add	r0, r7, #0
	bl	Clear64byte
	str	r6, [r7, #0x2c]
	strb	r4, [r7, #0x8]
	mov	r0, #0x80
	lsl	r0, r0, #0x18
	str	r0, [r7, #0x4]
	cmp	r4, #0
	beq	.L155	@cond_branch
	mov	r1, #0x0
.L156:
	strb	r1, [r6]
	sub	r0, r4, #0x1
	lsl	r0, r0, #0x18
	lsr	r4, r0, #0x18
	add	r6, r6, #0x50
	cmp	r4, #0
	bne	.L156	@cond_branch
.L155:
	ldr	r0, [r5, #0x20]
	cmp	r0, #0
	beq	.L158	@cond_branch
	str	r0, [r7, #0x38]
	ldr	r0, [r5, #0x24]
	str	r0, [r7, #0x3c]
	mov	r0, #0x0
	str	r0, [r5, #0x20]
.L158:
	str	r7, [r5, #0x24]
	ldr	r0, .L159+0x8
	str	r0, [r5, #0x20]
	ldr	r0, .L159+0x4
	str	r0, [r5]
	str	r0, [r7, #0x34]
.L150:
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.L160:
	.align	2, 0
.L159:
	.word	0x3007ff0
	.word	0x68736d53
	.word	MP2KPlayerMain
.Lfe29:
	.size	 MPlayOpen,.Lfe29-MPlayOpen
	.align	2, 0
	.globl	MPlayStart
	.type	 MPlayStart,function
	.thumb_func
MPlayStart:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	add	r5, r0, #0
	add	r7, r1, #0
	ldr	r1, [r5, #0x34]
	ldr	r0, .L178
	cmp	r1, r0
	bne	.L161	@cond_branch
	ldrb	r0, [r5, #0xb]
	ldrb	r2, [r7, #0x2]
	cmp	r0, #0
	beq	.L164	@cond_branch
	ldr	r0, [r5]
	cmp	r0, #0
	beq	.L166	@cond_branch
	ldr	r1, [r5, #0x2c]
	mov	r0, #0x40
	ldrb	r1, [r1]
	and	r0, r0, r1
	cmp	r0, #0
	bne	.L165	@cond_branch
.L166:
	ldr	r1, [r5, #0x4]
	ldrh	r0, [r5, #0x4]
	cmp	r0, #0
	beq	.L164	@cond_branch
	cmp	r1, #0
	blt	.L164	@cond_branch
.L165:
	ldrb	r0, [r7, #0x2]
	add	r2, r0, #0
	ldrb	r0, [r5, #0x9]
	cmp	r0, r2
	bhi	.L161	@cond_branch
.L164:
	ldr	r0, [r5, #0x34]
	add	r0, r0, #0x1
	str	r0, [r5, #0x34]
	mov	r1, #0x0
	str	r1, [r5, #0x4]
	str	r7, [r5]
	ldr	r0, [r7, #0x4]
	str	r0, [r5, #0x30]
	strb	r2, [r5, #0x9]
	str	r1, [r5, #0xc]
	mov	r0, #0x96
	strh	r0, [r5, #0x1c]
	strh	r0, [r5, #0x20]
	add	r0, r0, #0x6a
	strh	r0, [r5, #0x1e]
	strh	r1, [r5, #0x22]
	strh	r1, [r5, #0x24]
	mov	r6, #0x0
	ldr	r4, [r5, #0x2c]
	ldrb	r1, [r7]
	cmp	r6, r1
	bge	.L168	@cond_branch
	ldrb	r0, [r5, #0x8]
	cmp	r6, r0
	bge	.L177	@cond_branch
	mov	r8, r6
.L169:
	add	r0, r5, #0
	add	r1, r4, #0
	bl	TrackStop
	mov	r0, #0xc0
	strb	r0, [r4]
	mov	r1, r8
	str	r1, [r4, #0x20]
	lsl	r1, r6, #0x2
	add	r0, r7, #0
	add	r0, r0, #0x8
	add	r0, r0, r1
	ldr	r0, [r0]
	str	r0, [r4, #0x40]
	add	r6, r6, #0x1
	add	r4, r4, #0x50
	ldrb	r0, [r7]
	cmp	r6, r0
	bge	.L168	@cond_branch
	ldrb	r1, [r5, #0x8]
	cmp	r6, r1
	blt	.L169	@cond_branch
.L168:
	ldrb	r0, [r5, #0x8]
	cmp	r6, r0
	bge	.L177	@cond_branch
	mov	r1, #0x0
	mov	r8, r1
.L174:
	add	r0, r5, #0
	add	r1, r4, #0
	bl	TrackStop
	mov	r0, r8
	strb	r0, [r4]
	add	r6, r6, #0x1
	add	r4, r4, #0x50
	ldrb	r1, [r5, #0x8]
	cmp	r6, r1
	blt	.L174	@cond_branch
.L177:
	mov	r0, #0x80
	ldrb	r1, [r7, #0x3]
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L176	@cond_branch
	ldrb	r0, [r7, #0x3]
	bl	m4aSoundMode
.L176:
	ldr	r0, .L178
	str	r0, [r5, #0x34]
.L161:
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.L179:
	.align	2, 0
.L178:
	.word	0x68736d53
.Lfe30:
	.size	 MPlayStart,.Lfe30-MPlayStart
	.align	2, 0
	.globl	MPlayStop
	.type	 MPlayStop,function
	.thumb_func
MPlayStop:
	push	{r4, r5, r6, lr}
	add	r6, r0, #0
	ldr	r1, [r6, #0x34]
	ldr	r0, .L186
	cmp	r1, r0
	bne	.L180	@cond_branch
	add	r0, r1, #0x1
	str	r0, [r6, #0x34]
	ldr	r0, [r6, #0x4]
	mov	r1, #0x80
	lsl	r1, r1, #0x18
	orr	r0, r0, r1
	str	r0, [r6, #0x4]
	ldrb	r4, [r6, #0x8]
	ldr	r5, [r6, #0x2c]
	cmp	r4, #0
	ble	.L183	@cond_branch
.L184:
	add	r0, r6, #0
	add	r1, r5, #0
	bl	TrackStop
	sub	r4, r4, #0x1
	add	r5, r5, #0x50
	cmp	r4, #0
	bgt	.L184	@cond_branch
.L183:
	ldr	r0, .L186
	str	r0, [r6, #0x34]
.L180:
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
.L187:
	.align	2, 0
.L186:
	.word	0x68736d53
.Lfe31:
	.size	 MPlayStop,.Lfe31-MPlayStop
	.align	2, 0
	.globl	FadeOutBody
	.type	 FadeOutBody,function
	.thumb_func
FadeOutBody:
	push	{r4, r5, r6, r7, lr}
	add	r6, r0, #0
	ldrh	r1, [r6, #0x24]
	cmp	r1, #0
	beq	.L188	@cond_branch
	ldrh	r0, [r6, #0x26]
	sub	r0, r0, #0x1
	strh	r0, [r6, #0x26]
	ldr	r3, .L208
	add	r2, r3, #0
	lsl	r0, r0, #0x10
	lsr	r3, r0, #0x10
	cmp	r3, #0
	bne	.L188	@cond_branch
	strh	r1, [r6, #0x26]
	ldrh	r1, [r6, #0x28]
	mov	r0, #0x2
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L191	@cond_branch
	add	r0, r1, #0
	add	r0, r0, #0x10
	strh	r0, [r6, #0x28]
	and	r0, r0, r2
	cmp	r0, #0xff
	bls	.L193	@cond_branch
	mov	r0, #0x80
	lsl	r0, r0, #0x1
	strh	r0, [r6, #0x28]
	strh	r3, [r6, #0x24]
	b	.L193
.L209:
	.align	2, 0
.L208:
	.word	0xffff
.L191:
	add	r0, r1, #0
	sub	r0, r0, #0x10
	strh	r0, [r6, #0x28]
	and	r0, r0, r2
	lsl	r0, r0, #0x10
	cmp	r0, #0
	bgt	.L193	@cond_branch
	ldrb	r5, [r6, #0x8]
	ldr	r4, [r6, #0x2c]
	cmp	r5, #0
	ble	.L196	@cond_branch
.L197:
	add	r0, r6, #0
	add	r1, r4, #0
	bl	TrackStop
	mov	r0, #0x1
	ldrh	r7, [r6, #0x28]
	and	r0, r0, r7
	cmp	r0, #0
	bne	.L198	@cond_branch
	strb	r0, [r4]
.L198:
	sub	r5, r5, #0x1
	add	r4, r4, #0x50
	cmp	r5, #0
	bgt	.L197	@cond_branch
.L196:
	mov	r0, #0x1
	ldrh	r1, [r6, #0x28]
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L200	@cond_branch
	ldr	r0, [r6, #0x4]
	mov	r1, #0x80
	lsl	r1, r1, #0x18
	orr	r0, r0, r1
	b	.L207
.L200:
	mov	r0, #0x80
	lsl	r0, r0, #0x18
.L207:
	str	r0, [r6, #0x4]
	mov	r0, #0x0
	strh	r0, [r6, #0x24]
	b	.L188
.L193:
	ldrb	r5, [r6, #0x8]
	ldr	r4, [r6, #0x2c]
	cmp	r5, #0
	ble	.L188	@cond_branch
	mov	r3, #0x80
	mov	r7, #0x0
	mov	r2, #0x3
.L204:
	ldrb	r1, [r4]
	add	r0, r3, #0
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L205	@cond_branch
	ldrh	r7, [r6, #0x28]
	lsr	r0, r7, #0x2
	strb	r0, [r4, #0x13]
	add	r0, r1, #0
	orr	r0, r0, r2
	strb	r0, [r4]
.L205:
	sub	r5, r5, #0x1
	add	r4, r4, #0x50
	cmp	r5, #0
	bgt	.L204	@cond_branch
.L188:
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe32:
	.size	 FadeOutBody,.Lfe32-FadeOutBody
	.align	2, 0
	.globl	TrkVolPitSet
	.type	 TrkVolPitSet,function
	.thumb_func
TrkVolPitSet:
	push	{r4, lr}
	add	r2, r1, #0
	mov	r0, #0x1
	ldrb	r1, [r2]
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L211	@cond_branch
	ldrb	r3, [r2, #0x13]
	ldrb	r1, [r2, #0x12]
	mov	r0, r3
	mul	r0, r0, r1
	lsr	r3, r0, #0x5
	ldrb	r4, [r2, #0x18]
	cmp	r4, #0x1
	bne	.L212	@cond_branch
	mov	r0, #0x16
	ldrsb	r0, [r2, r0]
	add	r0, r0, #0x80
	mul	r0, r0, r3
	lsr	r3, r0, #0x7
.L212:
	mov	r0, #0x14
	ldrsb	r0, [r2, r0]
	lsl	r0, r0, #0x1
	mov	r1, #0x15
	ldrsb	r1, [r2, r1]
	add	r1, r0, r1
	cmp	r4, #0x2
	bne	.L213	@cond_branch
	mov	r0, #0x16
	ldrsb	r0, [r2, r0]
	add	r1, r1, r0
.L213:
	mov	r0, #0x80
	neg	r0, r0
	cmp	r1, r0
	bge	.L214	@cond_branch
	add	r1, r0, #0
	b	.L215
.L214:
	cmp	r1, #0x7f
	ble	.L215	@cond_branch
	mov	r1, #0x7f
.L215:
	add	r0, r1, #0
	add	r0, r0, #0x80
	mul	r0, r0, r3
	lsr	r0, r0, #0x8
	strb	r0, [r2, #0x10]
	mov	r0, #0x7f
	sub	r0, r0, r1
	mul	r0, r0, r3
	lsr	r0, r0, #0x8
	strb	r0, [r2, #0x11]
.L211:
	ldrb	r1, [r2]
	mov	r0, #0x4
	and	r0, r0, r1
	add	r3, r1, #0
	cmp	r0, #0
	beq	.L217	@cond_branch
	mov	r0, #0xe
	ldrsb	r0, [r2, r0]
	ldrb	r1, [r2, #0xf]
	mul	r0, r0, r1
	mov	r1, #0xc
	ldrsb	r1, [r2, r1]
	add	r1, r1, r0
	lsl	r1, r1, #0x2
	mov	r0, #0xa
	ldrsb	r0, [r2, r0]
	lsl	r0, r0, #0x8
	add	r1, r1, r0
	mov	r0, #0xb
	ldrsb	r0, [r2, r0]
	lsl	r0, r0, #0x8
	add	r1, r1, r0
	ldrb	r0, [r2, #0xd]
	add	r1, r0, r1
	ldrb	r0, [r2, #0x18]
	cmp	r0, #0
	bne	.L218	@cond_branch
	mov	r0, #0x16
	ldrsb	r0, [r2, r0]
	lsl	r0, r0, #0x4
	add	r1, r1, r0
.L218:
	asr	r0, r1, #0x8
	strb	r0, [r2, #0x8]
	strb	r1, [r2, #0x9]
.L217:
	mov	r0, #0xfa
	and	r0, r0, r3
	strb	r0, [r2]
	pop	{r4}
	pop	{r0}
	bx	r0
.Lfe33:
	.size	 TrkVolPitSet,.Lfe33-TrkVolPitSet
	.align	2, 0
	.globl	MidiKeyToCgbFreq
	.type	 MidiKeyToCgbFreq,function
	.thumb_func
MidiKeyToCgbFreq:
	push	{r4, r5, r6, r7, lr}
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	lsl	r1, r1, #0x18
	lsr	r5, r1, #0x18
	lsl	r2, r2, #0x18
	lsr	r2, r2, #0x18
	mov	ip, r2
	cmp	r0, #0x4
	bne	.L220	@cond_branch
	cmp	r5, #0x14
	bhi	.L221	@cond_branch
	mov	r5, #0x0
	b	.L222
.L221:
	add	r0, r5, #0
	sub	r0, r0, #0x15
	lsl	r0, r0, #0x18
	lsr	r5, r0, #0x18
	cmp	r5, #0x3b
	bls	.L222	@cond_branch
	mov	r5, #0x3b
.L222:
	ldr	r0, .L230
	add	r0, r5, r0
	ldrb	r0, [r0]
	b	.L229
.L231:
	.align	2, 0
.L230:
	.word	gNoiseTable
.L220:
	cmp	r5, #0x23
	bhi	.L225	@cond_branch
	mov	r0, #0x0
	mov	ip, r0
	mov	r5, #0x0
	b	.L226
.L225:
	add	r0, r5, #0
	sub	r0, r0, #0x24
	lsl	r0, r0, #0x18
	lsr	r5, r0, #0x18
	cmp	r5, #0x82
	bls	.L226	@cond_branch
	mov	r5, #0x82
	mov	r1, #0xff
	mov	ip, r1
.L226:
	ldr	r3, .L232
	add	r0, r5, r3
	ldrb	r6, [r0]
	ldr	r4, .L232+0x4
	mov	r2, #0xf
	add	r0, r6, #0
	and	r0, r0, r2
	lsl	r0, r0, #0x1
	add	r0, r0, r4
	mov	r7, #0x0
	ldrsh	r1, [r0, r7]
	asr	r0, r6, #0x4
	add	r6, r1, #0
	asr	r6, r6, r0
	add	r0, r5, #0x1
	add	r0, r0, r3
	ldrb	r1, [r0]
	add	r0, r1, #0
	and	r0, r0, r2
	lsl	r0, r0, #0x1
	add	r0, r0, r4
	mov	r2, #0x0
	ldrsh	r0, [r0, r2]
	asr	r1, r1, #0x4
	asr	r0, r0, r1
	sub	r0, r0, r6
	mov	r7, ip
	mul	r7, r7, r0
	add	r0, r7, #0
	asr	r0, r0, #0x8
	add	r0, r6, r0
	mov	r1, #0x80
	lsl	r1, r1, #0x4
	add	r0, r0, r1
.L229:
	pop	{r4, r5, r6, r7}
	pop	{r1}
	bx	r1
.L233:
	.align	2, 0
.L232:
	.word	gCgbScaleTable
	.word	gCgbFreqTable
.Lfe34:
	.size	 MidiKeyToCgbFreq,.Lfe34-MidiKeyToCgbFreq
	.align	2, 0
	.globl	CgbOscOff
	.type	 CgbOscOff,function
	.thumb_func
CgbOscOff:
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	add	r1, r0, #0
	cmp	r0, #0x2
	beq	.L237	@cond_branch
	cmp	r0, #0x2
	bgt	.L241	@cond_branch
	cmp	r0, #0x1
	beq	.L236	@cond_branch
	b	.L239
.L241:
	cmp	r1, #0x3
	beq	.L238	@cond_branch
	b	.L239
.L236:
	ldr	r1, .L245
	mov	r0, #0x8
	strb	r0, [r1]
	add	r1, r1, #0x2
	b	.L242
.L246:
	.align	2, 0
.L245:
	.word	0x4000063
.L237:
	ldr	r1, .L247
	b	.L243
.L248:
	.align	2, 0
.L247:
	.word	0x4000069
.L238:
	ldr	r1, .L249
	mov	r0, #0x0
	b	.L244
.L250:
	.align	2, 0
.L249:
	.word	0x4000070
.L239:
	ldr	r1, .L251
.L243:
	mov	r0, #0x8
	strb	r0, [r1]
	add	r1, r1, #0x4
.L242:
	mov	r0, #0x80
.L244:
	strb	r0, [r1]
	bx	lr
.L252:
	.align	2, 0
.L251:
	.word	0x4000079
.Lfe35:
	.size	 CgbOscOff,.Lfe35-CgbOscOff
	.align	2, 0
	.globl	CgbModVol
	.type	 CgbModVol,function
	.thumb_func
CgbModVol:
	push	{r4, lr}
	add	r1, r0, #0
	ldrb	r0, [r1, #0x2]
	lsl	r2, r0, #0x18
	lsr	r4, r2, #0x18
	ldrb	r3, [r1, #0x3]
	lsl	r0, r3, #0x18
	lsr	r3, r0, #0x18
	cmp	r4, r3
	bcc	.L260	@cond_branch
	lsr	r0, r2, #0x19
	cmp	r0, r3
	bcc	.L263	@cond_branch
	mov	r0, #0xf
	strb	r0, [r1, #0x1b]
	b	.L259
.L260:
	lsr	r0, r0, #0x19
	cmp	r0, r4
	bcc	.L263	@cond_branch
	mov	r0, #0xf0
	strb	r0, [r1, #0x1b]
	b	.L259
.L263:
	mov	r0, #0xff
	strb	r0, [r1, #0x1b]
	ldrb	r2, [r1, #0x3]
	ldrb	r3, [r1, #0x2]
	add	r0, r2, r3
	lsr	r0, r0, #0x4
	b	.L267
.L259:
	ldrb	r2, [r1, #0x3]
	ldrb	r3, [r1, #0x2]
	add	r0, r2, r3
	lsr	r0, r0, #0x4
	strb	r0, [r1, #0xa]
	cmp	r0, #0xf
	bls	.L265	@cond_branch
	mov	r0, #0xf
.L267:
	strb	r0, [r1, #0xa]
.L265:
	ldrb	r2, [r1, #0x6]
	ldrb	r3, [r1, #0xa]
	mov	r0, r2
	mul	r0, r0, r3
	add	r0, r0, #0xf
	asr	r0, r0, #0x4
	strb	r0, [r1, #0x19]
	ldrb	r0, [r1, #0x1c]
	ldrb	r2, [r1, #0x1b]
	and	r0, r0, r2
	strb	r0, [r1, #0x1b]
	pop	{r4}
	pop	{r0}
	bx	r0
.Lfe36:
	.size	 CgbModVol,.Lfe36-CgbModVol
	.align	2, 0
	.globl	CgbSound
	.type	 CgbSound,function
	.thumb_func
CgbSound:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	add	sp, sp, #-0x1c
	ldr	r0, .L360
	ldr	r0, [r0]
	str	r0, [sp, #0x4]
	ldrb	r0, [r0, #0xa]
	cmp	r0, #0
	beq	.L269	@cond_branch
	sub	r0, r0, #0x1
	ldr	r1, [sp, #0x4]
	strb	r0, [r1, #0xa]
	b	.L270
.L361:
	.align	2, 0
.L360:
	.word	0x3007ff0
.L269:
	mov	r0, #0xe
	ldr	r2, [sp, #0x4]
	strb	r0, [r2, #0xa]
.L270:
	mov	r6, #0x1
	ldr	r0, [sp, #0x4]
	ldr	r4, [r0, #0x1c]
.L274:
	ldrb	r1, [r4]
	mov	r0, #0xc7
	and	r0, r0, r1
	add	r2, r6, #0x1
	mov	sl, r2
	mov	r2, #0x40
	add	r2, r2, r4
	mov	r9, r2
	cmp	r0, #0
	bne	.LCB2314
	b	.L273	@long jump
.LCB2314:
	cmp	r6, #0x2
	beq	.L278	@cond_branch
	cmp	r6, #0x2
	bgt	.L282	@cond_branch
	cmp	r6, #0x1
	beq	.L277	@cond_branch
	b	.L280
.L282:
	cmp	r6, #0x3
	beq	.L279	@cond_branch
	b	.L280
.L277:
	ldr	r0, .L362
	str	r0, [sp, #0x8]
	ldr	r7, .L362+0x4
	ldr	r2, .L362+0x8
	str	r2, [sp, #0xc]
	add	r0, r0, #0x4
	str	r0, [sp, #0x10]
	add	r2, r2, #0x2
	b	.L356
.L363:
	.align	2, 0
.L362:
	.word	0x4000060
	.word	0x4000062
	.word	0x4000063
.L278:
	ldr	r0, .L364
	str	r0, [sp, #0x8]
	ldr	r7, .L364+0x4
	ldr	r2, .L364+0x8
	b	.L357
.L365:
	.align	2, 0
.L364:
	.word	0x4000061
	.word	0x4000068
	.word	0x4000069
.L279:
	ldr	r0, .L366
	str	r0, [sp, #0x8]
	ldr	r7, .L366+0x4
	ldr	r2, .L366+0x8
	str	r2, [sp, #0xc]
	add	r0, r0, #0x4
	str	r0, [sp, #0x10]
	add	r2, r2, #0x2
	b	.L356
.L367:
	.align	2, 0
.L366:
	.word	0x4000070
	.word	0x4000072
	.word	0x4000073
.L280:
	ldr	r0, .L368
	str	r0, [sp, #0x8]
	ldr	r7, .L368+0x4
	ldr	r2, .L368+0x8
.L357:
	str	r2, [sp, #0xc]
	add	r0, r0, #0xb
	str	r0, [sp, #0x10]
	add	r2, r2, #0x4
.L356:
	str	r2, [sp, #0x14]
	ldr	r0, [sp, #0x4]
	ldrb	r0, [r0, #0xa]
	str	r0, [sp]
	ldr	r2, [sp, #0xc]
	ldrb	r0, [r2]
	mov	r8, r0
	add	r2, r1, #0
	mov	r0, #0x80
	and	r0, r0, r2
	cmp	r0, #0
	beq	.L283	@cond_branch
	mov	r3, #0x40
	add	r0, r3, #0
	and	r0, r0, r2
	lsl	r0, r0, #0x18
	lsr	r5, r0, #0x18
	add	r0, r6, #0x1
	mov	sl, r0
	mov	r1, #0x40
	add	r1, r1, r4
	mov	r9, r1
	cmp	r5, #0
	bne	.L303	@cond_branch
	mov	r0, #0x3
	strb	r0, [r4]
	strb	r0, [r4, #0x1d]
	add	r0, r4, #0
	str	r3, [sp, #0x18]
	bl	CgbModVol
	ldr	r3, [sp, #0x18]
	cmp	r6, #0x2
	beq	.L287	@cond_branch
	cmp	r6, #0x2
	bgt	.L297	@cond_branch
	cmp	r6, #0x1
	beq	.L286	@cond_branch
	b	.L293
.L369:
	.align	2, 0
.L368:
	.word	0x4000071
	.word	0x4000078
	.word	0x4000079
.L297:
	cmp	r6, #0x3
	beq	.L289	@cond_branch
	b	.L293
.L286:
	ldrb	r0, [r4, #0x1f]
	ldr	r2, [sp, #0x8]
	strb	r0, [r2]
.L287:
	ldr	r0, [r4, #0x24]
	lsl	r0, r0, #0x6
	ldrb	r1, [r4, #0x1e]
	add	r0, r1, r0
	strb	r0, [r7]
	b	.L288
.L289:
	ldr	r1, [r4, #0x24]
	ldr	r0, [r4, #0x28]
	cmp	r1, r0
	beq	.L290	@cond_branch
	ldr	r2, [sp, #0x8]
	strb	r3, [r2]
	ldr	r1, .L370
	ldr	r2, [r4, #0x24]
	ldr	r0, [r2]
	str	r0, [r1]
	add	r1, r1, #0x4
	ldr	r0, [r2, #0x4]
	str	r0, [r1]
	add	r1, r1, #0x4
	ldr	r0, [r2, #0x8]
	str	r0, [r1]
	add	r1, r1, #0x4
	ldr	r0, [r2, #0xc]
	str	r0, [r1]
	str	r2, [r4, #0x28]
.L290:
	ldr	r0, [sp, #0x8]
	strb	r5, [r0]
	ldrb	r0, [r4, #0x1e]
	strb	r0, [r7]
	ldrb	r0, [r4, #0x1e]
	cmp	r0, #0
	beq	.L291	@cond_branch
	mov	r0, #0xc0
	b	.L294
.L371:
	.align	2, 0
.L370:
	.word	0x4000090
.L291:
	mov	r1, #0x80
	neg	r1, r1
	strb	r1, [r4, #0x1a]
	b	.L285
.L293:
	ldrb	r0, [r4, #0x1e]
	strb	r0, [r7]
	ldr	r0, [r4, #0x24]
	lsl	r0, r0, #0x3
	ldr	r2, [sp, #0x10]
	strb	r0, [r2]
.L288:
	ldrb	r0, [r4, #0x4]
	add	r0, r0, #0x8
	mov	r8, r0
	ldrb	r0, [r4, #0x1e]
	cmp	r0, #0
	beq	.L294	@cond_branch
	mov	r0, #0x40
.L294:
	strb	r0, [r4, #0x1a]
.L285:
	ldrb	r1, [r4, #0x4]
	mov	r2, #0x0
	strb	r1, [r4, #0xb]
	mov	r0, #0xff
	and	r0, r0, r1
	add	r1, r6, #0x1
	mov	sl, r1
	mov	r1, #0x40
	add	r1, r1, r4
	mov	r9, r1
	cmp	r0, #0
	bne	.LCB2550
	b	.L301	@long jump
.LCB2550:
	strb	r2, [r4, #0x9]
	b	.L299
.L283:
	mov	r0, #0x4
	and	r0, r0, r2
	cmp	r0, #0
	beq	.L305	@cond_branch
	ldrb	r0, [r4, #0xd]
	sub	r0, r0, #0x1
	strb	r0, [r4, #0xd]
	mov	r2, #0xff
	and	r0, r0, r2
	lsl	r0, r0, #0x18
	add	r1, r6, #0x1
	mov	sl, r1
	mov	r2, #0x40
	add	r2, r2, r4
	mov	r9, r2
	cmp	r0, #0
	ble	.LCB2581
	b	.L308	@long jump
.LCB2581:
.L303:
	lsl	r0, r6, #0x18
	lsr	r0, r0, #0x18
	bl	CgbOscOff
	mov	r0, #0x0
	strb	r0, [r4]
	b	.L307
.L305:
	mov	r0, #0x40
	and	r0, r0, r1
	add	r2, r6, #0x1
	mov	sl, r2
	mov	r2, #0x40
	add	r2, r2, r4
	mov	r9, r2
	cmp	r0, #0
	beq	.L316	@cond_branch
	mov	r0, #0x3
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L316	@cond_branch
	mov	r0, #0xfc
	and	r0, r0, r1
	mov	r2, #0x0
	strb	r0, [r4]
	ldrb	r1, [r4, #0x7]
	strb	r1, [r4, #0xb]
	mov	r0, #0xff
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L314	@cond_branch
	mov	r0, #0x1
	ldrb	r1, [r4, #0x1d]
	orr	r0, r0, r1
	strb	r0, [r4, #0x1d]
	cmp	r6, #0x3
	beq	.L299	@cond_branch
	ldrb	r2, [r4, #0x7]
	mov	r8, r2
	b	.L299
.L316:
	ldrb	r0, [r4, #0xb]
	cmp	r0, #0
	bne	.L299	@cond_branch
	cmp	r6, #0x3
	bne	.L318	@cond_branch
	mov	r0, #0x1
	ldrb	r1, [r4, #0x1d]
	orr	r0, r0, r1
	strb	r0, [r4, #0x1d]
.L318:
	add	r0, r4, #0
	bl	CgbModVol
	mov	r0, #0x3
	ldrb	r2, [r4]
	and	r0, r0, r2
	cmp	r0, #0
	bne	.L319	@cond_branch
	ldrb	r0, [r4, #0x9]
	sub	r0, r0, #0x1
	strb	r0, [r4, #0x9]
	mov	r1, #0xff
	and	r0, r0, r1
	lsl	r0, r0, #0x18
	cmp	r0, #0
	bgt	.L320	@cond_branch
.L314:
	ldrb	r2, [r4, #0xc]
	ldrb	r1, [r4, #0xa]
	mov	r0, r2
	mul	r0, r0, r1
	add	r0, r0, #0xff
	asr	r0, r0, #0x8
	mov	r1, #0x0
	strb	r0, [r4, #0x9]
	lsl	r0, r0, #0x18
	cmp	r0, #0
	beq	.L303	@cond_branch
	mov	r0, #0x4
	ldrb	r2, [r4]
	orr	r0, r0, r2
	strb	r0, [r4]
	mov	r0, #0x1
	ldrb	r1, [r4, #0x1d]
	orr	r0, r0, r1
	strb	r0, [r4, #0x1d]
	cmp	r6, #0x3
	beq	.L308	@cond_branch
	mov	r2, #0x8
	mov	r8, r2
	b	.L308
.L320:
	ldrb	r0, [r4, #0x7]
	b	.L358
.L319:
	cmp	r0, #0x1
	bne	.L326	@cond_branch
.L327:
	ldrb	r0, [r4, #0x19]
	strb	r0, [r4, #0x9]
	mov	r0, #0x7
	b	.L358
.L326:
	cmp	r0, #0x2
	bne	.L329	@cond_branch
	ldrb	r0, [r4, #0x9]
	sub	r0, r0, #0x1
	strb	r0, [r4, #0x9]
	mov	r1, #0xff
	and	r0, r0, r1
	lsl	r0, r0, #0x18
	ldrb	r2, [r4, #0x19]
	lsl	r1, r2, #0x18
	cmp	r0, r1
	bgt	.L330	@cond_branch
.L331:
	ldrb	r0, [r4, #0x6]
	cmp	r0, #0
	bne	.L332	@cond_branch
	mov	r0, #0xfc
	ldrb	r1, [r4]
	and	r0, r0, r1
	strb	r0, [r4]
	b	.L314
.L332:
	ldrb	r0, [r4]
	sub	r0, r0, #0x1
	strb	r0, [r4]
	mov	r0, #0x1
	ldrb	r2, [r4, #0x1d]
	orr	r0, r0, r2
	strb	r0, [r4, #0x1d]
	cmp	r6, #0x3
	beq	.L327	@cond_branch
	mov	r0, #0x8
	mov	r8, r0
	b	.L327
.L330:
	ldrb	r0, [r4, #0x5]
	b	.L358
.L329:
	ldrb	r0, [r4, #0x9]
	add	r0, r0, #0x1
	strb	r0, [r4, #0x9]
	mov	r1, #0xff
	and	r0, r0, r1
	ldrb	r2, [r4, #0xa]
	cmp	r0, r2
	bcc	.L337	@cond_branch
.L301:
	ldrb	r0, [r4]
	sub	r0, r0, #0x1
	mov	r2, #0x0
	strb	r0, [r4]
	ldrb	r1, [r4, #0x5]
	strb	r1, [r4, #0xb]
	mov	r0, #0xff
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L331	@cond_branch
	mov	r0, #0x1
	ldrb	r1, [r4, #0x1d]
	orr	r0, r0, r1
	strb	r0, [r4, #0x1d]
	ldrb	r0, [r4, #0xa]
	strb	r0, [r4, #0x9]
	cmp	r6, #0x3
	beq	.L299	@cond_branch
	ldrb	r2, [r4, #0x5]
	mov	r8, r2
	b	.L299
.L337:
	ldrb	r0, [r4, #0x4]
.L358:
	strb	r0, [r4, #0xb]
.L299:
	ldrb	r0, [r4, #0xb]
	sub	r0, r0, #0x1
	strb	r0, [r4, #0xb]
	ldr	r0, [sp]
	cmp	r0, #0
	bne	.L308	@cond_branch
	sub	r0, r0, #0x1
	str	r0, [sp]
	b	.L316
.L308:
	mov	r0, #0x2
	ldrb	r1, [r4, #0x1d]
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L343	@cond_branch
	cmp	r6, #0x3
	bgt	.L344	@cond_branch
	mov	r0, #0x8
	ldrb	r2, [r4, #0x1]
	and	r0, r0, r2
	cmp	r0, #0
	beq	.L344	@cond_branch
	ldr	r0, .L372
	ldrb	r0, [r0]
	cmp	r0, #0x3f
	bgt	.L345	@cond_branch
	ldr	r0, [r4, #0x20]
	add	r0, r0, #0x2
	ldr	r1, .L372+0x4
	b	.L359
.L373:
	.align	2, 0
.L372:
	.word	0x4000089
	.word	0x7fc
.L345:
	cmp	r0, #0x7f
	bgt	.L344	@cond_branch
	ldr	r0, [r4, #0x20]
	add	r0, r0, #0x1
	ldr	r1, .L374
.L359:
	and	r0, r0, r1
	str	r0, [r4, #0x20]
.L344:
	cmp	r6, #0x4
	beq	.L348	@cond_branch
	ldr	r0, [r4, #0x20]
	ldr	r1, [sp, #0x10]
	strb	r0, [r1]
	b	.L349
.L375:
	.align	2, 0
.L374:
	.word	0x7fe
.L348:
	ldr	r2, [sp, #0x10]
	ldrb	r0, [r2]
	mov	r1, #0x8
	and	r1, r1, r0
	ldr	r0, [r4, #0x20]
	orr	r0, r0, r1
	strb	r0, [r2]
.L349:
	mov	r0, #0xc0
	ldrb	r1, [r4, #0x1a]
	and	r0, r0, r1
	add	r1, r4, #0
	add	r1, r1, #0x21
	ldrb	r1, [r1]
	add	r0, r1, r0
	strb	r0, [r4, #0x1a]
	mov	r2, #0xff
	and	r0, r0, r2
	ldr	r1, [sp, #0x14]
	strb	r0, [r1]
.L343:
	mov	r0, #0x1
	ldrb	r2, [r4, #0x1d]
	and	r0, r0, r2
	cmp	r0, #0
	beq	.L307	@cond_branch
	ldr	r1, .L376
	ldrb	r0, [r1]
	ldrb	r2, [r4, #0x1c]
	bic	r0, r0, r2
	ldrb	r2, [r4, #0x1b]
	orr	r0, r0, r2
	strb	r0, [r1]
	cmp	r6, #0x3
	bne	.L351	@cond_branch
	ldr	r0, .L376+0x4
	ldrb	r1, [r4, #0x9]
	add	r0, r1, r0
	ldrb	r0, [r0]
	ldr	r2, [sp, #0xc]
	strb	r0, [r2]
	mov	r1, #0x80
	add	r0, r1, #0
	ldrb	r2, [r4, #0x1a]
	and	r0, r0, r2
	cmp	r0, #0
	beq	.L307	@cond_branch
	ldr	r0, [sp, #0x8]
	strb	r1, [r0]
	ldrb	r0, [r4, #0x1a]
	ldr	r1, [sp, #0x14]
	strb	r0, [r1]
	mov	r0, #0x7f
	ldrb	r2, [r4, #0x1a]
	and	r0, r0, r2
	strb	r0, [r4, #0x1a]
	b	.L307
.L377:
	.align	2, 0
.L376:
	.word	0x4000081
	.word	gCgb3Vol
.L351:
	mov	r0, #0xf
	mov	r1, r8
	and	r1, r1, r0
	mov	r8, r1
	ldrb	r2, [r4, #0x9]
	lsl	r0, r2, #0x4
	add	r0, r0, r8
	ldr	r1, [sp, #0xc]
	strb	r0, [r1]
	mov	r2, #0x80
	ldrb	r0, [r4, #0x1a]
	orr	r0, r0, r2
	ldr	r1, [sp, #0x14]
	strb	r0, [r1]
	cmp	r6, #0x1
	bne	.L307	@cond_branch
	ldr	r0, [sp, #0x8]
	ldrb	r1, [r0]
	mov	r0, #0x8
	and	r0, r0, r1
	cmp	r0, #0
	bne	.L307	@cond_branch
	ldrb	r0, [r4, #0x1a]
	orr	r0, r0, r2
	ldr	r1, [sp, #0x14]
	strb	r0, [r1]
.L307:
	mov	r0, #0x0
	strb	r0, [r4, #0x1d]
.L273:
	mov	r6, sl
	mov	r4, r9
	cmp	r6, #0x4
	bgt	.LCB3047
	b	.L274	@long jump
.LCB3047:
	add	sp, sp, #0x1c
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe37:
	.size	 CgbSound,.Lfe37-CgbSound
	.align	2, 0
	.globl	m4aMPlayTempoControl
	.type	 m4aMPlayTempoControl,function
	.thumb_func
m4aMPlayTempoControl:
	push	{r4, lr}
	add	r2, r0, #0
	lsl	r1, r1, #0x10
	lsr	r1, r1, #0x10
	ldr	r3, [r2, #0x34]
	ldr	r0, .L380
	cmp	r3, r0
	bne	.L379	@cond_branch
	strh	r1, [r2, #0x1e]
	ldrh	r4, [r2, #0x1c]
	mov	r0, r1
	mul	r0, r0, r4
	asr	r0, r0, #0x8
	strh	r0, [r2, #0x20]
.L379:
	pop	{r4}
	pop	{r0}
	bx	r0
.L381:
	.align	2, 0
.L380:
	.word	0x68736d53
.Lfe38:
	.size	 m4aMPlayTempoControl,.Lfe38-m4aMPlayTempoControl
	.align	2, 0
	.globl	m4aMPlayVolumeControl
	.type	 m4aMPlayVolumeControl,function
	.thumb_func
m4aMPlayVolumeControl:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r9
	mov	r6, r8
	push	{r6, r7}
	add	r4, r0, #0
	lsl	r1, r1, #0x10
	lsr	r7, r1, #0x10
	lsl	r6, r2, #0x10
	ldr	r3, [r4, #0x34]
	ldr	r0, .L390
	cmp	r3, r0
	bne	.L382	@cond_branch
	add	r0, r3, #0x1
	str	r0, [r4, #0x34]
	ldrb	r2, [r4, #0x8]
	ldr	r1, [r4, #0x2c]
	mov	r5, #0x1
	cmp	r2, #0
	ble	.L385	@cond_branch
	mov	r0, #0x80
	mov	r8, r0
	lsr	r6, r6, #0x12
	mov	r0, #0x3
	mov	ip, r0
.L386:
	add	r0, r7, #0
	and	r0, r0, r5
	cmp	r0, #0
	beq	.L387	@cond_branch
	ldrb	r3, [r1]
	mov	r0, r8
	and	r0, r0, r3
	cmp	r0, #0
	beq	.L387	@cond_branch
	strb	r6, [r1, #0x13]
	mov	r0, ip
	orr	r0, r0, r3
	strb	r0, [r1]
.L387:
	sub	r2, r2, #0x1
	add	r1, r1, #0x50
	lsl	r5, r5, #0x1
	cmp	r2, #0
	bgt	.L386	@cond_branch
.L385:
	ldr	r0, .L390
	str	r0, [r4, #0x34]
.L382:
	pop	{r3, r4}
	mov	r8, r3
	mov	r9, r4
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.L391:
	.align	2, 0
.L390:
	.word	0x68736d53
.Lfe39:
	.size	 m4aMPlayVolumeControl,.Lfe39-m4aMPlayVolumeControl
	.align	2, 0
	.globl	m4aMPlayPitchControl
	.type	 m4aMPlayPitchControl,function
	.thumb_func
m4aMPlayPitchControl:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	add	r4, r0, #0
	lsl	r1, r1, #0x10
	lsr	r1, r1, #0x10
	mov	ip, r1
	lsl	r2, r2, #0x10
	lsr	r6, r2, #0x10
	ldr	r3, [r4, #0x34]
	ldr	r0, .L400
	cmp	r3, r0
	bne	.L392	@cond_branch
	add	r0, r3, #0x1
	str	r0, [r4, #0x34]
	ldrb	r2, [r4, #0x8]
	ldr	r3, [r4, #0x2c]
	mov	r5, #0x1
	cmp	r2, #0
	ble	.L395	@cond_branch
	mov	r0, #0x80
	mov	r9, r0
	lsl	r0, r6, #0x10
	asr	r7, r0, #0x18
	mov	r0, #0xc
	mov	r8, r0
.L396:
	mov	r0, ip
	and	r0, r0, r5
	cmp	r0, #0
	beq	.L397	@cond_branch
	ldrb	r1, [r3]
	mov	r0, r9
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L397	@cond_branch
	strb	r7, [r3, #0xb]
	strb	r6, [r3, #0xd]
	mov	r0, r8
	orr	r0, r0, r1
	strb	r0, [r3]
.L397:
	sub	r2, r2, #0x1
	add	r3, r3, #0x50
	lsl	r5, r5, #0x1
	cmp	r2, #0
	bgt	.L396	@cond_branch
.L395:
	ldr	r0, .L400
	str	r0, [r4, #0x34]
.L392:
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.L401:
	.align	2, 0
.L400:
	.word	0x68736d53
.Lfe40:
	.size	 m4aMPlayPitchControl,.Lfe40-m4aMPlayPitchControl
	.align	2, 0
	.globl	m4aMPlayPanpotControl
	.type	 m4aMPlayPanpotControl,function
	.thumb_func
m4aMPlayPanpotControl:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r9
	mov	r6, r8
	push	{r6, r7}
	add	r4, r0, #0
	lsl	r1, r1, #0x10
	lsr	r7, r1, #0x10
	lsl	r2, r2, #0x18
	lsr	r6, r2, #0x18
	ldr	r3, [r4, #0x34]
	ldr	r0, .L410
	cmp	r3, r0
	bne	.L402	@cond_branch
	add	r0, r3, #0x1
	str	r0, [r4, #0x34]
	ldrb	r2, [r4, #0x8]
	ldr	r1, [r4, #0x2c]
	mov	r5, #0x1
	cmp	r2, #0
	ble	.L405	@cond_branch
	mov	r0, #0x80
	mov	r8, r0
	mov	r0, #0x3
	mov	ip, r0
.L406:
	add	r0, r7, #0
	and	r0, r0, r5
	cmp	r0, #0
	beq	.L407	@cond_branch
	ldrb	r3, [r1]
	mov	r0, r8
	and	r0, r0, r3
	cmp	r0, #0
	beq	.L407	@cond_branch
	strb	r6, [r1, #0x15]
	mov	r0, ip
	orr	r0, r0, r3
	strb	r0, [r1]
.L407:
	sub	r2, r2, #0x1
	add	r1, r1, #0x50
	lsl	r5, r5, #0x1
	cmp	r2, #0
	bgt	.L406	@cond_branch
.L405:
	ldr	r0, .L410
	str	r0, [r4, #0x34]
.L402:
	pop	{r3, r4}
	mov	r8, r3
	mov	r9, r4
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.L411:
	.align	2, 0
.L410:
	.word	0x68736d53
.Lfe41:
	.size	 m4aMPlayPanpotControl,.Lfe41-m4aMPlayPanpotControl
	.align	2, 0
	.globl	ClearModM
	.type	 ClearModM,function
	.thumb_func
ClearModM:
	add	r1, r0, #0
	mov	r2, #0x0
	mov	r0, #0x0
	strb	r0, [r1, #0x1a]
	strb	r0, [r1, #0x16]
	ldrb	r0, [r1, #0x18]
	cmp	r0, #0
	bne	.L413	@cond_branch
	mov	r0, #0xc
	b	.L415
.L413:
	mov	r0, #0x3
.L415:
	ldrb	r2, [r1]
	orr	r0, r0, r2
	strb	r0, [r1]
	bx	lr
.Lfe42:
	.size	 ClearModM,.Lfe42-ClearModM
	.align	2, 0
	.globl	m4aMPlayModDepthSet
	.type	 m4aMPlayModDepthSet,function
	.thumb_func
m4aMPlayModDepthSet:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	add	r6, r0, #0
	lsl	r1, r1, #0x10
	lsr	r1, r1, #0x10
	mov	sl, r1
	lsl	r2, r2, #0x18
	lsr	r2, r2, #0x18
	mov	r8, r2
	ldr	r1, [r6, #0x34]
	ldr	r0, .L425
	cmp	r1, r0
	bne	.L416	@cond_branch
	add	r0, r1, #0x1
	str	r0, [r6, #0x34]
	ldrb	r5, [r6, #0x8]
	ldr	r4, [r6, #0x2c]
	mov	r7, #0x1
	cmp	r5, #0
	ble	.L419	@cond_branch
	mov	r9, r8
.L420:
	mov	r0, sl
	and	r0, r0, r7
	cmp	r0, #0
	beq	.L421	@cond_branch
	mov	r0, #0x80
	ldrb	r1, [r4]
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L421	@cond_branch
	mov	r0, r8
	strb	r0, [r4, #0x17]
	mov	r1, r9
	cmp	r1, #0
	bne	.L421	@cond_branch
	add	r0, r4, #0
	bl	ClearModM
.L421:
	sub	r5, r5, #0x1
	add	r4, r4, #0x50
	lsl	r7, r7, #0x1
	cmp	r5, #0
	bgt	.L420	@cond_branch
.L419:
	ldr	r0, .L425
	str	r0, [r6, #0x34]
.L416:
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.L426:
	.align	2, 0
.L425:
	.word	0x68736d53
.Lfe43:
	.size	 m4aMPlayModDepthSet,.Lfe43-m4aMPlayModDepthSet
	.align	2, 0
	.globl	m4aMPlayLFOSpeedSet
	.type	 m4aMPlayLFOSpeedSet,function
	.thumb_func
m4aMPlayLFOSpeedSet:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	add	r6, r0, #0
	lsl	r1, r1, #0x10
	lsr	r1, r1, #0x10
	mov	sl, r1
	lsl	r2, r2, #0x18
	lsr	r2, r2, #0x18
	mov	r8, r2
	ldr	r1, [r6, #0x34]
	ldr	r0, .L436
	cmp	r1, r0
	bne	.L427	@cond_branch
	add	r0, r1, #0x1
	str	r0, [r6, #0x34]
	ldrb	r5, [r6, #0x8]
	ldr	r4, [r6, #0x2c]
	mov	r7, #0x1
	cmp	r5, #0
	ble	.L430	@cond_branch
	mov	r9, r8
.L431:
	mov	r0, sl
	and	r0, r0, r7
	cmp	r0, #0
	beq	.L432	@cond_branch
	mov	r0, #0x80
	ldrb	r1, [r4]
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L432	@cond_branch
	mov	r0, r8
	strb	r0, [r4, #0x19]
	mov	r1, r9
	cmp	r1, #0
	bne	.L432	@cond_branch
	add	r0, r4, #0
	bl	ClearModM
.L432:
	sub	r5, r5, #0x1
	add	r4, r4, #0x50
	lsl	r7, r7, #0x1
	cmp	r5, #0
	bgt	.L431	@cond_branch
.L430:
	ldr	r0, .L436
	str	r0, [r6, #0x34]
.L427:
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.L437:
	.align	2, 0
.L436:
	.word	0x68736d53
.Lfe44:
	.size	 m4aMPlayLFOSpeedSet,.Lfe44-m4aMPlayLFOSpeedSet
	.align	2, 0
	.globl	MP2K_event_memacc
	.type	 MP2K_event_memacc,function
	.thumb_func
MP2K_event_memacc:
	push	{r4, r5, r6, lr}
	add	r4, r0, #0
	add	r6, r1, #0
	ldr	r1, [r6, #0x40]
	ldrb	r5, [r1]
	add	r2, r1, #0x1
	str	r2, [r6, #0x40]
	ldr	r0, [r4, #0x18]
	ldrb	r1, [r1, #0x1]
	add	r3, r1, r0
	add	r0, r2, #0x1
	str	r0, [r6, #0x40]
	ldrb	r2, [r2, #0x1]
	add	r0, r0, #0x1
	str	r0, [r6, #0x40]
	cmp	r5, #0x11
	bls	.LCB3528
	b	.L438	@long jump
.LCB3528:
	lsl	r0, r5, #0x2
	ldr	r1, .L486
	add	r0, r0, r1
	ldr	r0, [r0]
	mov	pc, r0
.L487:
	.align	2, 0
.L486:
	.word	.L485
	.align	2, 0
	.align	2, 0
.L485:
	.word	.L440
	.word	.L441
	.word	.L442
	.word	.L443
	.word	.L444
	.word	.L445
	.word	.L446
	.word	.L451
	.word	.L454
	.word	.L457
	.word	.L460
	.word	.L463
	.word	.L466
	.word	.L469
	.word	.L472
	.word	.L475
	.word	.L478
	.word	.L481
.L440:
	strb	r2, [r3]
	b	.L438
.L441:
	ldrb	r1, [r3]
	add	r0, r1, r2
	strb	r0, [r3]
	b	.L438
.L442:
	ldrb	r1, [r3]
	sub	r0, r1, r2
	strb	r0, [r3]
	b	.L438
.L443:
	ldr	r0, [r4, #0x18]
	add	r0, r0, r2
	ldrb	r0, [r0]
	strb	r0, [r3]
	b	.L438
.L444:
	ldr	r0, [r4, #0x18]
	add	r0, r0, r2
	ldrb	r1, [r3]
	ldrb	r0, [r0]
	add	r0, r1, r0
	strb	r0, [r3]
	b	.L438
.L445:
	ldr	r0, [r4, #0x18]
	add	r0, r0, r2
	ldrb	r1, [r3]
	ldrb	r0, [r0]
	sub	r0, r1, r0
	strb	r0, [r3]
	b	.L438
.L446:
	ldrb	r3, [r3]
	cmp	r3, r2
	beq	.L448	@cond_branch
	b	.L450
.L451:
	ldrb	r3, [r3]
	cmp	r3, r2
	bne	.L448	@cond_branch
	b	.L450
.L454:
	ldrb	r3, [r3]
	cmp	r3, r2
	bhi	.L448	@cond_branch
	b	.L450
.L457:
	ldrb	r3, [r3]
	cmp	r3, r2
	bcs	.L448	@cond_branch
	b	.L450
.L460:
	ldrb	r3, [r3]
	cmp	r3, r2
	bls	.L448	@cond_branch
	b	.L450
.L463:
	ldrb	r3, [r3]
	cmp	r3, r2
	bcc	.L448	@cond_branch
	b	.L450
.L466:
	ldr	r0, [r4, #0x18]
	add	r0, r0, r2
	ldrb	r3, [r3]
	ldrb	r0, [r0]
	cmp	r3, r0
	beq	.L448	@cond_branch
	b	.L450
.L469:
	ldr	r0, [r4, #0x18]
	add	r0, r0, r2
	ldrb	r3, [r3]
	ldrb	r0, [r0]
	cmp	r3, r0
	bne	.L448	@cond_branch
	b	.L450
.L472:
	ldr	r0, [r4, #0x18]
	add	r0, r0, r2
	ldrb	r3, [r3]
	ldrb	r0, [r0]
	cmp	r3, r0
	bhi	.L448	@cond_branch
	b	.L450
.L475:
	ldr	r0, [r4, #0x18]
	add	r0, r0, r2
	ldrb	r3, [r3]
	ldrb	r0, [r0]
	cmp	r3, r0
	bcs	.L448	@cond_branch
	b	.L450
.L478:
	ldr	r0, [r4, #0x18]
	add	r0, r0, r2
	ldrb	r3, [r3]
	ldrb	r0, [r0]
	cmp	r3, r0
	bls	.L448	@cond_branch
	b	.L450
.L481:
	ldr	r0, [r4, #0x18]
	add	r0, r0, r2
	ldrb	r3, [r3]
	ldrb	r0, [r0]
	cmp	r3, r0
	bcs	.L450	@cond_branch
.L448:
	ldr	r0, .L488
	ldr	r2, [r0]
	add	r0, r4, #0
	add	r1, r6, #0
	bl	_call_via_r2
	b	.L438
.L489:
	.align	2, 0
.L488:
	.word	gMPlayJumpTable+0x4
.L450:
	ldr	r0, [r6, #0x40]
	add	r0, r0, #0x4
	str	r0, [r6, #0x40]
.L438:
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
.Lfe45:
	.size	 MP2K_event_memacc,.Lfe45-MP2K_event_memacc
	.align	2, 0
	.globl	MP2K_event_xcmd
	.type	 MP2K_event_xcmd,function
	.thumb_func
MP2K_event_xcmd:
	push	{lr}
	ldr	r2, [r1, #0x40]
	ldrb	r3, [r2]
	add	r2, r2, #0x1
	str	r2, [r1, #0x40]
	ldr	r2, .L491
	lsl	r3, r3, #0x2
	add	r3, r3, r2
	ldr	r2, [r3]
	bl	_call_via_r2
	pop	{r0}
	bx	r0
.L492:
	.align	2, 0
.L491:
	.word	gXcmdTable
.Lfe46:
	.size	 MP2K_event_xcmd,.Lfe46-MP2K_event_xcmd
	.align	2, 0
	.globl	MP2K_event_xxx
	.type	 MP2K_event_xxx,function
	.thumb_func
MP2K_event_xxx:
	push	{lr}
	ldr	r2, .L494
	ldr	r2, [r2]
	bl	_call_via_r2
	pop	{r0}
	bx	r0
.L495:
	.align	2, 0
.L494:
	.word	gMPlayJumpTable
.Lfe47:
	.size	 MP2K_event_xxx,.Lfe47-MP2K_event_xxx
	.align	2, 0
	.globl	MP2K_event_xwave
	.type	 MP2K_event_xwave,function
	.thumb_func
MP2K_event_xwave:
	push	{r4, lr}
	ldr	r2, [r1, #0x40]
	ldr	r0, .L497
	and	r4, r4, r0
	ldrb	r0, [r2]
	orr	r4, r4, r0
	ldrb	r0, [r2, #0x1]
	lsl	r3, r0, #0x8
	ldr	r0, .L497+0x4
	and	r4, r4, r0
	orr	r4, r4, r3
	ldrb	r0, [r2, #0x2]
	lsl	r3, r0, #0x10
	ldr	r0, .L497+0x8
	and	r4, r4, r0
	orr	r4, r4, r3
	ldrb	r0, [r2, #0x3]
	lsl	r3, r0, #0x18
	ldr	r0, .L497+0xc
	and	r4, r4, r0
	orr	r4, r4, r3
	str	r4, [r1, #0x28]
	add	r2, r2, #0x4
	str	r2, [r1, #0x40]
	pop	{r4}
	pop	{r0}
	bx	r0
.L498:
	.align	2, 0
.L497:
	.word	-0x100
	.word	-0xff01
	.word	-0xff0001
	.word	0xffffff
.Lfe48:
	.size	 MP2K_event_xwave,.Lfe48-MP2K_event_xwave
	.align	2, 0
	.globl	MP2K_event_xtype
	.type	 MP2K_event_xtype,function
	.thumb_func
MP2K_event_xtype:
	ldr	r0, [r1, #0x40]
	ldrb	r2, [r0]
	add	r0, r1, #0
	add	r0, r0, #0x24
	strb	r2, [r0]
	ldr	r0, [r1, #0x40]
	add	r0, r0, #0x1
	str	r0, [r1, #0x40]
	bx	lr
.Lfe49:
	.size	 MP2K_event_xtype,.Lfe49-MP2K_event_xtype
	.align	2, 0
	.globl	MP2K_event_xatta
	.type	 MP2K_event_xatta,function
	.thumb_func
MP2K_event_xatta:
	ldr	r0, [r1, #0x40]
	ldrb	r2, [r0]
	add	r0, r1, #0
	add	r0, r0, #0x2c
	strb	r2, [r0]
	ldr	r0, [r1, #0x40]
	add	r0, r0, #0x1
	str	r0, [r1, #0x40]
	bx	lr
.Lfe50:
	.size	 MP2K_event_xatta,.Lfe50-MP2K_event_xatta
	.align	2, 0
	.globl	MP2K_event_xdeca
	.type	 MP2K_event_xdeca,function
	.thumb_func
MP2K_event_xdeca:
	ldr	r0, [r1, #0x40]
	ldrb	r0, [r0]
	add	r2, r1, #0
	add	r2, r2, #0x2d
	strb	r0, [r2]
	ldr	r0, [r1, #0x40]
	add	r0, r0, #0x1
	str	r0, [r1, #0x40]
	bx	lr
.Lfe51:
	.size	 MP2K_event_xdeca,.Lfe51-MP2K_event_xdeca
	.align	2, 0
	.globl	MP2K_event_xsust
	.type	 MP2K_event_xsust,function
	.thumb_func
MP2K_event_xsust:
	ldr	r0, [r1, #0x40]
	ldrb	r0, [r0]
	add	r2, r1, #0
	add	r2, r2, #0x2e
	strb	r0, [r2]
	ldr	r0, [r1, #0x40]
	add	r0, r0, #0x1
	str	r0, [r1, #0x40]
	bx	lr
.Lfe52:
	.size	 MP2K_event_xsust,.Lfe52-MP2K_event_xsust
	.align	2, 0
	.globl	MP2K_event_xrele
	.type	 MP2K_event_xrele,function
	.thumb_func
MP2K_event_xrele:
	ldr	r0, [r1, #0x40]
	ldrb	r0, [r0]
	add	r2, r1, #0
	add	r2, r2, #0x2f
	strb	r0, [r2]
	ldr	r0, [r1, #0x40]
	add	r0, r0, #0x1
	str	r0, [r1, #0x40]
	bx	lr
.Lfe53:
	.size	 MP2K_event_xrele,.Lfe53-MP2K_event_xrele
	.align	2, 0
	.globl	MP2K_event_xiecv
	.type	 MP2K_event_xiecv,function
	.thumb_func
MP2K_event_xiecv:
	ldr	r0, [r1, #0x40]
	ldrb	r2, [r0]
	strb	r2, [r1, #0x1e]
	add	r0, r0, #0x1
	str	r0, [r1, #0x40]
	bx	lr
.Lfe54:
	.size	 MP2K_event_xiecv,.Lfe54-MP2K_event_xiecv
	.align	2, 0
	.globl	MP2K_event_xiecl
	.type	 MP2K_event_xiecl,function
	.thumb_func
MP2K_event_xiecl:
	ldr	r0, [r1, #0x40]
	ldrb	r2, [r0]
	strb	r2, [r1, #0x1f]
	add	r0, r0, #0x1
	str	r0, [r1, #0x40]
	bx	lr
.Lfe55:
	.size	 MP2K_event_xiecl,.Lfe55-MP2K_event_xiecl
	.align	2, 0
	.globl	MP2K_event_xleng
	.type	 MP2K_event_xleng,function
	.thumb_func
MP2K_event_xleng:
	ldr	r0, [r1, #0x40]
	ldrb	r0, [r0]
	add	r2, r1, #0
	add	r2, r2, #0x26
	strb	r0, [r2]
	ldr	r0, [r1, #0x40]
	add	r0, r0, #0x1
	str	r0, [r1, #0x40]
	bx	lr
.Lfe56:
	.size	 MP2K_event_xleng,.Lfe56-MP2K_event_xleng
	.align	2, 0
	.globl	MP2K_event_xswee
	.type	 MP2K_event_xswee,function
	.thumb_func
MP2K_event_xswee:
	ldr	r0, [r1, #0x40]
	ldrb	r0, [r0]
	add	r2, r1, #0
	add	r2, r2, #0x27
	strb	r0, [r2]
	ldr	r0, [r1, #0x40]
	add	r0, r0, #0x1
	str	r0, [r1, #0x40]
	bx	lr
.Lfe57:
	.size	 MP2K_event_xswee,.Lfe57-MP2K_event_xswee
	.align	2, 0
	.type	 MP2K_event_null,function
	.thumb_func
MP2K_event_null:
	bx	lr
.Lfe58:
	.size	 MP2K_event_null,.Lfe58-MP2K_event_null

	.text
	.align	2, 0
