@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_911_2008114
	.thumb_func
	.type	 OvlFunc_911_2008114,function
OvlFunc_911_2008114:
	push	{r5, lr}
	mov	r5, r0
	ldr	r1, [r5, #104]
	cmp	r1, #0
	beq	.L3
	add	r0, r0, #90
	.code	16
	ldrb	r2, [r0]
	.code	16
	mov	r3, #254
	and	r3, r3, r2
	strb	r3, [r0]
	ldr	r0, [r1, #16]
	.code	16
	ldr	r3, [r5, #16]
	.code	16
	ldr	r1, [r1, #8]
	.code	16
	sub	r0, r0, r3
	ldr	r3, [r5, #8]
	sub	r1, r1, r3
	bl	__atan2
	ldrh	r3, [r5, #6]
	.code	16
	lsl	r0, r0, #16
	.code	16
	lsr	r0, r0, #16
	.code	16
	sub	r0, r0, r3
	.code	16
	lsl	r0, r0, #16
	.code	16
	asr	r0, r0, #16
	.code	16
	cmp	r0, #0
	beq	.L3
	mov	r2, #128
	lsl	r2, r2, #5
	cmp	r0, r2
	ble	.L5
	mov	r0, r2
.L5:
	ldr	r2, .L7
	cmp	r0, r2
	bge	.L6
	mov	r0, r2
.L6:
	add	r3, r3, r0
	strh	r3, [r5, #6]
.L3:
	mov	r0, #1
	pop	{r5}
	pop	{r1}
	bx	r1
.L8:
	.align	2, 0
.L7:
	.word	-4096
.Lfe1:
	.size	 OvlFunc_911_2008114,.Lfe1-OvlFunc_911_2008114
	.align	2, 0
	.global	OvlFunc_911_200816c
	.thumb_func
	.type	 OvlFunc_911_200816c,function
OvlFunc_911_200816c:
	push	{lr}
	ldr	r3, .L12
	.code	16
	mov	r1, #224
	lsl	r1, r1, #1
	.code	16
	add	r3, r3, r1
	mov	r1, #0
	.code	16
	ldrsh	r2, [r3, r1]
	ldr	r3, .L12+4
	.code	16
	cmp	r2, r3
	bne	.L10
	ldr	r0, .L12+8
	b	.L9
.L10:
	ldr	r3, .L12+12
	.code	16
	cmp	r2, r3
	bne	.L11
	ldr	r0, .L12+16
	b	.L9
.L11:
	ldr	r0, .L12+20
.L9:
	pop	{r1}
	bx	r1
.L13:
	.align	2, 0
.L12:
	.word	gState
	.word	0x27
	.word	.L2f80
	.word	0x26
	.word	gScript_913__0200afc8
	.word	.L2e60
.Lfe2:
	.size	 OvlFunc_911_200816c,.Lfe2-OvlFunc_911_200816c
	.align	2, 0
	.global	OvlFunc_911_20081ac
	.thumb_func
	.type	 OvlFunc_911_20081ac,function
OvlFunc_911_20081ac:
	push	{lr}
	ldr	r3, .L16
	.code	16
	mov	r1, #224
	.code	16
	lsl	r1, r1, #1
	add	r3, r3, r1
	.code	16
	mov	r1, #0
	.code	16
	ldrsh	r2, [r3, r1]
	.code	16
	ldr	r3, .L16+4
	.code	16
	mov	r0, #0
	.code	16
	cmp	r2, r3
	bne	.L15
	ldr	r0, .L16+8
.L15:
	pop	{r1}
	bx	r1
.L17:
	.align	2, 0
.L16:
	.word	gState
	.word	0x26
	.word	.L3010
.Lfe3:
	.size	 OvlFunc_911_20081ac,.Lfe3-OvlFunc_911_20081ac

	.text
	.align	2, 0
