@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_916_2008054
	.thumb_func
	.type	 OvlFunc_916_2008054,function
OvlFunc_916_2008054:
	push	{r5, lr}
	ldr	r5, .L3
	ldr	r0, [r5]
	sub	sp, sp, #8
	bl	OvlFunc_916_2008c2c
	mov	r3, #0
	.code	16
	str	r3, [sp]
	str	r3, [sp, #4]
	.code	16
	mov	r2, #32
	mov	r3, #32
	.code	16
	mov	r0, #0
	mov	r1, #64
	.code	16
	bl	__Func_8010704
	mov	r1, #255
	ldr	r0, [r5]
	.code	16
	bl	OvlFunc_916_2008b3c
	bl	OvlFunc_916_2008150
	add	sp, sp, #8
	pop	{r5}
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	.L12c0
.Lfe1:
	.size	 OvlFunc_916_2008054,.Lfe1-OvlFunc_916_2008054

	.text
	.align	2, 0
