@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_922_20080f8
	.thumb_func
	.type	 OvlFunc_922_20080f8,function
OvlFunc_922_20080f8:
	push	{lr}
	ldr	r3, .L10
	mov	r1, #224
	.code	16
	lsl	r1, r1, #1
	add	r3, r3, r1
	mov	r1, #0
	.code	16
	ldrsh	r2, [r3, r1]
	ldr	r3, .L10+4
	.code	16
	cmp	r2, r3
	bne	.L3
	ldr	r0, .L10+8
	b	.L4
.L3:
	ldr	r3, .L10+12
	.code	16
	cmp	r2, r3
	bne	.L5
	ldr	r0, .L10+16
	b	.L4
.L5:
	ldr	r3, .L10+20
	.code	16
	cmp	r2, r3
	bne	.L6
	ldr	r0, .L10+24
	b	.L4
.L6:
	ldr	r3, .L10+28
	.code	16
	cmp	r2, r3
	bne	.L7
	ldr	r0, .L10+32
	b	.L4
.L7:
	ldr	r3, .L10+36
	.code	16
	cmp	r2, r3
	bne	.L8
	ldr	r0, .L10+40
	b	.L4
.L8:
	ldr	r3, .L10+44
	.code	16
	cmp	r2, r3
	bne	.L9
	ldr	r0, .L10+48
	b	.L4
.L9:
	ldr	r0, .L10+52
.L4:
	.code	16
	pop	{r1}
	bx	r1
.L11:
	.align	2, 0
.L10:
	.word	gState
	.word	0x34
	.word	.L29bc
	.word	0x3e
	.word	.L29ec
	.word	0x3f
	.word	.L2a4c
	.word	0x40
	.word	.L2ac4
	.word	0x41
	.word	.L2b3c
	.word	0x43
	.word	.L2b9c
	.word	.L29a4
.Lfe1:
	.size	 OvlFunc_922_20080f8,.Lfe1-OvlFunc_922_20080f8

	.text
	.align	2, 0
