@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_955_200862c
	.thumb_func
	.type	 OvlFunc_955_200862c,function
OvlFunc_955_200862c:
	push	{r5, lr}
	sub	sp, sp, #8
	mov r3, #14
	str r3, [sp]
	mov r5, #11
	mov r1, #11
	mov r2, #12
	mov r3, #4
	mov r0, #100
	str r5, [sp, #4]
	.code	16
	bl	__Func_8010704
	mov	r0, #15
	bl	__MapActor_GetActor
	ldr	r3, [r0, #8]
	.code	16
	asr	r2, r3, #20
	.code	16
	str	r2, [sp]
	mov	r1, #28
	mov	r2, #1
	mov	r3, #4
	mov	r0, #13
	str	r5, [sp, #4]
	bl	__Func_8010704
	mov	r0, #16
	bl	__MapActor_GetActor
	ldr	r3, [r0, #8]
	.code	16
	asr	r2, r3, #20
	.code	16
	str	r2, [sp]
	mov	r1, #28
	mov	r2, #1
	mov	r3, #4
	mov	r0, #13
	str	r5, [sp, #4]
	bl	__Func_8010704
	mov	r0, #17
	bl	__MapActor_GetActor
	ldr	r3, [r0, #16]
	.code	16
	asr	r2, r3, #20
	.code	16
	mov	r3, #18
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #13
	mov	r1, #28
	mov	r2, #4
	mov	r3, #1
	bl	__Func_8010704
	add	sp, sp, #8
	pop	{r5}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_955_200862c,.Lfe1-OvlFunc_955_200862c

	.text
	.align	2, 0
