@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80c23a0
	.thumb_func
	.type	 Func_80c23a0,function
Func_80c23a0:
	push	{lr}
	cmp	r0, #171
	bls	.L3
	ldr	r3, .L5
	ldrh	r0, [r3]
	b	.L4
.L3:
	ldr	r3, .L5
	.code	16
	lsl	r2, r0, #3
	.code	16
	add	r2, r2, r3
	.code	16
	ldrb	r0, [r2, #3]
	lsl	r0, r0, #27
	lsr	r0, r0, #28
.L4:
	pop	{r1}
	bx	r1
.L6:
	.align	2, 0
.L5:
	.word	.Lc7420
.Lfe1:
	.size	 Func_80c23a0,.Lfe1-Func_80c23a0
	.align	2, 0
	.global	Func_80c23c0
	.thumb_func
	.type	 Func_80c23c0,function
Func_80c23c0:
	push	{lr}
	cmp	r0, #171
	bls	.L8
	mov	r0, #0
	.code	16
	b	.L9
.L8:
	ldr	r3, .L11
	.code	16
	lsl	r2, r0, #3
	.code	16
	add	r2, r2, r3
	.code	16
	ldrb	r3, [r2, #2]
	lsl	r3, r3, #31
	.code	16
	mov	r1, #0
	.code	16
	cmp	r3, #0
	beq	.L10
	mov	r1, #1
.L10:
	mov	r0, r1
.L9:
	.code	16
	pop	{r1}
	bx	r1
.L12:
	.align	2, 0
.L11:
	.word	.Lc7420
.Lfe2:
	.size	 Func_80c23c0,.Lfe2-Func_80c23c0
	.align	2, 0
	.global	Func_80c23e8
	.thumb_func
	.type	 Func_80c23e8,function
Func_80c23e8:
	push	{lr}
	cmp	r0, #171
	bls	.L14
	mov	r0, #1
	.code	16
	b	.L15
.L14:
	ldr	r3, .L17
	.code	16
	lsl	r2, r0, #3
	.code	16
	add	r2, r2, r3
	.code	16
	ldrb	r3, [r2, #2]
	lsl	r3, r3, #27
	lsr	r3, r3, #28
	mov	r0, r3
	.code	16
	cmp	r3, #0
	bne	.L15
	mov	r0, #1
.L15:
	.code	16
	pop	{r1}
	bx	r1
.L18:
	.align	2, 0
.L17:
	.word	.Lc7420
.Lfe3:
	.size	 Func_80c23e8,.Lfe3-Func_80c23e8
	.align	2, 0
	.global	GetEnemyAttackAnimParam
	.thumb_func
	.type	 GetEnemyAttackAnimParam,function
GetEnemyAttackAnimParam:
	push	{lr}
	cmp	r0, #171
	bls	.L20
	mov	r0, #0
	.code	16
	b	.L21
.L20:
	ldr	r3, .L23
	.code	16
	lsl	r2, r0, #3
	.code	16
	add	r2, r2, r3
	.code	16
	ldrb	r3, [r2, #2]
	lsr	r3, r3, #5
	mov	r0, r3
	.code	16
	cmp	r3, #0
	bne	.L21
	mov	r0, #0
.L21:
	.code	16
	pop	{r1}
	bx	r1
.L24:
	.align	2, 0
.L23:
	.word	.Lc7420
.Lfe4:
	.size	 GetEnemyAttackAnimParam,.Lfe4-GetEnemyAttackAnimParam

	.text
	.align	2, 0
