@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_911_200a910
	.thumb_func
	.type	 OvlFunc_911_200a910,function
OvlFunc_911_200a910:
	push	{lr}
	ldr	r0, .L6
	sub sp, #8
	.code	16
	bl	__GetFlag
	cmp	r0, #0
	bne	.L3
	mov	r0, #8
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	mov r3, #9
	mov r2, #0x12
	str r3, [sp]
	str r2, [sp, #4]
	.code	16
	mov	r0, #9
	mov	r1, #17
	mov	r2, #5
	mov	r3, #1
	bl	__Func_8010704
	bl	__Func_800fe9c
	mov	r0, #1
	bl	__WaitFrames
	b	.L4
.L3:
	mov	r0, #9
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
.L4:
	ldr	r0, .L6+4
	bl	__GetFlag
	cmp	r0, #0
	beq	.L5
	mov r3, #5
	mov r2, #7
	str r3, [sp]
	str r2, [sp, #4]
	.code	16
	mov	r0, #91
	mov	r1, #19
	mov	r2, #72
	mov	r3, #9
	bl	__CopyMapTiles
	mov r3, #8
	mov r2, #0xb
	str r3, [sp]
	str r2, [sp, #4]
	.code	16
	mov	r0, #23
	mov	r1, #11
	mov	r2, #5
	mov	r3, #7
	bl	__Func_8010704
	bl	__Func_800fe9c
	mov	r0, #1
	bl	__WaitFrames
.L5:
	add sp, #8
	.code	16
	pop	{r0}
	bx	r0
.L7:
	.align	2, 0
.L6:
	.word	2117
	.word	2119
.Lfe1:
	.size	 OvlFunc_911_200a910,.Lfe1-OvlFunc_911_200a910

	.text
	.align	2, 0
