#define ACTOR_SPAWN_EFFECT_FUNCTION OvlFunc_911_200a7ac
#define ACTOR_SPAWN_EFFECT_X_SYMBOL ".L368c"
#define ACTOR_SPAWN_EFFECT_RANGE_SYMBOL ".L3690"
#define ACTOR_SPAWN_EFFECT_MODE_SYMBOL ".L3694"
#define ACTOR_SPAWN_EFFECT_SCRIPT gScript_911__0200b610
#include "../actor_spawn_effect.inc"
