@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	OvlFunc_5a4
	.type	 OvlFunc_5a4,function
	.thumb_func
OvlFunc_5a4:
	mov	r0, #0x0
	bx	lr
.Lfe1:
	.size	 OvlFunc_5a4,.Lfe1-OvlFunc_5a4

	.text
	.align	2, 0
