@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_949_2008ca8
	.thumb_func
	.type	 OvlFunc_949_2008ca8,function
OvlFunc_949_2008ca8:
	push	{r5, lr}
	mov	r0, #9
	sub	sp, sp, #8
	bl	__MapActor_GetActor
	mov	r5, r0
	cmp	r5, #0
	beq	.L3
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r1, r5
	mov	r2, #2
	.code	16
	add	r1, r1, #35
	strb	r2, [r1]
	mov	r2, r5
	.code	16
	mov	r3, #0
	.code	16
	add	r2, r2, #85
	strb	r3, [r2]
.L3:
	mov	r0, #9
	mov	r1, #5
	bl	__MapActor_SetAnim
	mov	r3, #34
	mov	r2, #16
	.code	16
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r1, #16
	mov	r2, #1
	mov	r3, #1
	mov	r0, #36
	.code	16
	bl	__Func_8010704
	ldr	r0, .L4
	bl	__SetFlag
	add	sp, sp, #8
	pop	{r5}
	pop	{r0}
	bx	r0
.L5:
	.align	2, 0
.L4:
	.word	513
.Lfe1:
	.size	 OvlFunc_949_2008ca8,.Lfe1-OvlFunc_949_2008ca8

	.text
	.align	2, 0
