@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_953_20091c4
	.thumb_func
	.type	 OvlFunc_953_20091c4,function
OvlFunc_953_20091c4:
	push	{r5, lr}
	bl	__CutsceneStart
	ldr	r0, 11f
	bl	__GetFlag
	mov	r5, r0
	cmp	r5, #0
	beq	1f
	mov	r1, #0
	mov	r2, #0x28
	mov	r0, #0x11
	bl	__Func_8092848
	ldr	r0, 12f
	bl	__MessageID
	mov	r0, #0x11
	bl	OvlFunc_953_2009c48
	mov	r1, #0xc0
	mov	r0, #0x11
	lsl	r1, #6
	mov	r2, #0x14
	bl	__Func_8092adc
	b	2f
	1:
	mov	r1, #2
	mov	r0, #0x11
	bl	__Func_809259c
	ldr	r0, 13f
	bl	__MessageID
	mov	r1, #0
	mov	r0, #0x11
	bl	__ActorMessage
	bl	__Func_8093554
	add	r0, #0x55
	strb	r5, [r0]
	mov	r0, #1
	bl	__WaitFrames
	ldr	r0, 14f
	ldr	r1, 15f
	bl	__Func_80933d4
	mov	r0, #0x87
	mov	r1, #1
	mov	r2, #0xd0
	lsl	r0, #18
	neg	r1, r1
	lsl	r2, #16
	mov	r3, #1
	bl	__Func_80933f8
	bl	__Func_8093530
	ldr	r3, 16f
	ldr	r1, [r3]
	mov	r3, #0xe0
	lsl	r3, #1
	add	r2, r1, r3
	add	r3, #0x40
	str	r3, [r2]
	sub	r3, #0x38
	add	r2, r1, r3
	mov	r3, #0x20
	str	r3, [r2]
	bl	__MapTransitionOut
	bl	__WaitMapTransition
	ldr	r0, 17f
	bl	__GetFlag
	cmp	r0, #0
	beq	3f
	mov	r0, #0x46
	bl	__Func_8091e9c
	b	2f
	3:
	mov	r0, #7
	bl	__Func_8091e9c
	2:
	bl	__CutsceneEnd
	
	.code	16
	pop	{r5}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_953_20091c4,.Lfe1-OvlFunc_953_20091c4
	.align 2, 0
	11:
	.word	0x8a4
	12:
	.word	0x206f
	13:
	.word	0x206d
	14:
	.word	0x66666
	15:
	.word	0xcccc
	16:
	.word	iwram_3001ebc
	17:
	.word	0x8a3
	

	.text
	.align	2, 0
