@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_933_200841c
	.thumb_func
	.type	 OvlFunc_933_200841c,function
OvlFunc_933_200841c:
	push	{r5, lr}
	ldr	r5, .L8
	.code	16
	mov	r1, #224
	lsl	r1, r1, #1
	.code	16
	add	r3, r5, r1
	mov	r1, #0
	.code	16
	ldrsh	r2, [r3, r1]
	ldr	r3, .L8+4
	.code	16
	cmp	r2, r3
	bne	.L3
	mov	r2, #225
	lsl	r2, r2, #1
	.code	16
	add	r3, r5, r2
	mov	r1, #0
	.code	16
	ldrsh	r3, [r3, r1]
	cmp	r3, #5
	bne	.L3
	ldr	r0, .L8+8
	bl	__SetFlag
.L3:
	mov	r2, #224
	lsl	r2, r2, #1
	.code	16
	add	r3, r5, r2
	mov	r1, #0
	.code	16
	ldrsh	r2, [r3, r1]
	ldr	r3, .L8+12
	.code	16
	cmp	r2, r3
	bne	.L5
	ldr	r0, .L8+16
	b	.L2
.L5:
	ldr	r3, .L8+20
	.code	16
	cmp	r2, r3
	bne	.L6
	ldr	r0, .L8+24
	b	.L2
.L6:
	ldr	r3, .L8+4
	.code	16
	cmp	r2, r3
	bne	.L7
	ldr	r0, .L8+28
	b	.L2
.L7:
	ldr	r0, .L8+32
.L2:
	pop	{r5}
	pop	{r1}
	bx	r1
.L9:
	.align	2, 0
.L8:
	.word	gState
	.word	0x5b
	.word	2314
	.word	0x59
	.word	.L23c8
	.word	0x5a
	.word	.L2410
	.word	.L24b8
	.word	.L23b0
.Lfe1:
	.size	 OvlFunc_933_200841c,.Lfe1-OvlFunc_933_200841c
	.align	2, 0
	.global	OvlFunc_933_2008498
	.thumb_func
	.type	 OvlFunc_933_2008498,function
OvlFunc_933_2008498:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L13
	.code	16
	bl	__GetFlag
	cmp	r0, #0
	bne	.L11
	ldr	r0, .L13+4
	.code	16
	bl	__GetFlag
	cmp	r0, #0
	bne	.L11
	ldr	r0, .L13+4
	.code	16
	bl	__SetFlag
	ldr	r0, .L13
	.code	16
	bl	__SetFlag
.L11:
	mov	r0, #123
	bl	__PlaySound
	mov	r0, #3
	bl	__Func_8091e9c
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L14:
	.align	2, 0
.L13:
	.word	2226
	.word	2227
.Lfe2:
	.size	 OvlFunc_933_2008498,.Lfe2-OvlFunc_933_2008498

	.text
	.align	2, 0
