@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_886_20090c0
	.thumb_func
	.type	 OvlFunc_886_20090c0,function
OvlFunc_886_20090c0:
	push	{r5, r6, lr}
	ldr	r3, .L5
	mov	r1, #180
	ldr	r0, [r3]
	bl	_umodsi3_RAM
	mov r6, #0x17
	cmp r0, #0x14
	beq 1f
	cmp r0, #0x14
	bhi 2f
	cmp r0, #0xa
	beq 3f
	b .LOvl886_end
2:
	cmp r0, #0x1e
	beq 4f
	b .LOvl886_end
1:
	mov r6, #0x18
	b 3f
4:
	mov r6, #0x19
3:
	.code	16
	mov	r0, r6
	bl	__MapActor_GetActor
	mov	r5, r0
	cmp	r5, #0
	beq	.L2
	mov	r0, #8
	bl	__MapActor_GetActor
	cmp	r0, #0
	beq	.L4
	ldr	r1, [r0, #8]
	ldr	r2, [r0, #16]
	mov	r0, r6
	bl	__MapActor_SetPos
.L4:
	ldr r3, =0x6666
	mov r2, #0xc0
	str r3, [r5, #0x18]
	str r3, [r5, #0x1c]
	ldr r3, [r5, #0xc]
	lsl r2, #13
	add r3, r2
	mov r2, r5
	str r3, [r5, #0xc]
	str r3, [r5, #0x3c]
	add r2, #0x64
	mov r3, #0x19
	strh r3, [r2]
	add r2, #2
	mov r3, #0x80
	strh r3, [r2]
	ldr r1, =gScript_886__02009440
	mov r0, r6
	bl __MapActor_SetBehavior
	.LOvl886_end:
	.code	16
.L2:
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L6:
	.align	2, 0
.L5:
	.word	iwram_3001e40
.Lfe1:
	.size	 OvlFunc_886_20090c0,.Lfe1-OvlFunc_886_20090c0

	.text
	.align	2, 0
