@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	ply_patt
	.thumb_func
	.type	 ply_patt,function
ply_patt:
	ldrb	r2, [r1, #2]
	cmp r2, #3
	bcs .Lply_patt_full
	.code	16
	lsl	r2, r2, #2
	add	r3, r1, r2
	ldr	r2, [r1, #64]
	add	r2, r2, #4
	str	r2, [r3, #68]
	ldrb	r2, [r1, #2]
	add	r2, r2, #1
	strb	r2, [r1, #2]
	b ply_goto
.Lply_patt_full:
	b ply_fine
	.macro bx target
	.endm
	.code	16
	bx	lr
.Lfe1:
	.size	 ply_patt,.Lfe1-ply_patt

	.text
	.align	2, 0
