@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	ply_lfodl
	.thumb_func
	.type	 ply_lfodl,function
ply_lfodl:
	mov r12, lr
	bl Func_80f9ab4
	.code	16
	strb	r3, [r1, #27]
	.macro bx target
	.hword 0x4760
	.endm
	.code	16
	bx	lr
.Lfe1:
	.size	 ply_lfodl,.Lfe1-ply_lfodl

	.text
	.align	2, 0
