@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	ply_tempo
	.thumb_func
	.type	 ply_tempo,function
ply_tempo:
	mov r12, lr
	bl Func_80f9ab4
	.code	16
	lsl	r3, r3, #1
	strh	r3, [r0, #28]
	ldrh	r2, [r0, #30]
	mul	r3, r3, r2
	lsr	r3, r3, #8
	strh	r3, [r0, #32]
	.macro bx target
	.hword 0x4760
	.endm
	.code	16
	bx	lr
.Lfe1:
	.size	 ply_tempo,.Lfe1-ply_tempo

	.text
	.align	2, 0
