@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	umul3232H32
	.thumb_func
	.type	 umul3232H32,function
umul3232H32:
	adr r2, .Lumul3232H32_arm
	bx r2
	.align 2, 0
	.arm
.Lumul3232H32_arm:
	umull r2, r3, r0, r1
	add r0, r3, #0
	bx lr
	.thumb
	.macro bx target
	.endm
	.code	16
	bx	lr
.Lfe1:
	.size	 umul3232H32,.Lfe1-umul3232H32

	.text
	.align	2, 0
