@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	MPlayJumpTableCopy
	.thumb_func
	.type	 MPlayJumpTableCopy,function
MPlayJumpTableCopy:
	mov r12, lr
	mov r1, #0x24
	ldr r2, .LM4aJumpTableLiteral
.LMPlayJumpTableCopy_loop:
	.code	16
	ldr	r3, [r2]
	bl .LM4aValidatePointerLocal
	.code	16
	stmia	r0!, {r3}
	add	r2, r2, #4
	sub r1, #1
	bgt .LMPlayJumpTableCopy_loop
	.macro bx target
	.hword 0x4760
	.endm
	.code	16
	bx	lr
.Lfe1:
	.size	 MPlayJumpTableCopy,.Lfe1-MPlayJumpTableCopy
	.align	2, 0
	.global	Func_80f9a98
	.thumb_func
	.type	 Func_80f9a98,function
Func_80f9a98:
	.purgem bx
	.code	16
	ldrb	r3, [r2]
	.global M4aValidatePointer
M4aValidatePointer:
	.LM4aValidatePointerLocal:
	.hword 0xb401
	lsr r0, r2, #25
	bne .LM4aValidatePointer_end
	ldr r0, .LM4aJumpTableLiteral
	cmp r2, r0
	bcc .LM4aValidatePointer_invalid
	lsr r0, r2, #14
	beq .LM4aValidatePointer_end
.LM4aValidatePointer_invalid:
	.code	16
	mov	r3, #0
	.LM4aValidatePointer_end:
	.hword 0xbc01
	.macro bx target
	.hword 0x4770
	.align 2, 0
.LM4aJumpTableLiteral:
	.word M4aJumpTableSource
	.endm
	.code	16
	bx	lr
.Lfe2:
	.size	 Func_80f9a98,.Lfe2-Func_80f9a98

	.text
	.align	2, 0
