@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_884_2008030
	.thumb_func
	.type	 OvlFunc_884_2008030,function
OvlFunc_884_2008030:
	push	{r5, lr}
	mov	r5, r0
	.code	16
	ldr	r1, [r5, #104]
	.code	16
	cmp	r1, #0
	beq	.L3
	.code	16
	add	r0, r0, #90
	ldrb	r2, [r0]
	.code	16
	mov	r3, #254
	.code	16
	and	r3, r3, r2
	.code	16
	strb	r3, [r0]
	ldr	r0, [r1, #16]
	.code	16
	ldr	r3, [r5, #16]
	.code	16
	ldr	r1, [r1, #8]
	.code	16
	sub	r0, r0, r3
	.code	16
	ldr	r3, [r5, #8]
	.code	16
	sub	r1, r1, r3
	.code	16
	bl	__atan2
	ldrh	r3, [r5, #6]
	.code	16
	lsl	r0, r0, #16
	.code	16
	lsr	r0, r0, #16
	.code	16
	sub	r0, r0, r3
	.code	16
	lsl	r0, r0, #16
	.code	16
	asr	r0, r0, #16
	cmp	r0, #0
	beq	.L3
	mov	r2, #128
	lsl	r2, r2, #5
	cmp	r0, r2
	ble	.L5
	mov	r0, r2
.L5:
	ldr	r2, .L7
	cmp	r0, r2
	bge	.L6
	mov	r0, r2
.L6:
	add	r3, r3, r0
	strh	r3, [r5, #6]
.L3:
	mov	r0, #1
	pop	{r5}
	pop	{r1}
	bx	r1
.L8:
	.align	2, 0
.L7:
	.word	-4096
.Lfe1:
	.size	 OvlFunc_884_2008030,.Lfe1-OvlFunc_884_2008030

	.text
	.align	2, 0
