@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_48
	.thumb_func
	.type	 OvlFunc_48,function
OvlFunc_48:
	mov	r0, #0
	bx	lr
.Lfe1:
	.size	 OvlFunc_48,.Lfe1-OvlFunc_48

	.text
	.align	2, 0
