@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80c1a34
	.thumb_func
	.type	 Func_80c1a34,function
Func_80c1a34:
	push	{r5, r6, r7, lr}
	mov	r7, fp
	mov	r6, sl
	mov	r5, r9
	push	{r5, r6, r7}
	mov	r7, r8
	push	{r7}
	ldr	r3, .L20
	lsl	r0, r0, #4
	add	r0, r0, r3
	ldrb	r3, [r0, #6]
	mov r2, #0
	sub sp, #0x1c
	mov r9, r2
	mov r11, r2
	mov r10, r0
	mov r7, #0
	.code	16
	cmp	r3, #0
	bne	.L3
	mov	r2, sl
	add	r2, r2, #6
.L4:
	add	r7, r7, #1
	cmp	r7, #4
	bhi	.L3
	add	r2, r2, #1
	ldrb	r3, [r2]
	cmp	r3, #0
	beq	.L4
.L3:
	cmp	r7, #5
	bne	.L7
	mov r0, #1
	neg r0, r0
	.code	16
	b	.L8
.L7:
	mov r3, #0xb
	add r3, sl
	mov r7, #0
	.code	16
	mov	r8, r3
.L9:
	mov	r2, r8
	ldrb	r3, [r2]
	mov	r2, #1
	add	r8, r8, r2
	cmp	r3, #0
	beq	.L10
	mov	r3, sl
	add	r3, r3, #1
	ldrb	r6, [r3, r7]
	mov	r0, r6
	add	r0, r0, #8
	bl	_GetEnemyInfo
	mov	r5, r0
	cmp	r5, #0
	beq	.L10
	ldrb	r3, [r5, #15]
	cmp	r3, #3
	bls	.L13
	mov	r0, #186
	lsl	r0, r0, #1
	bl	_GetFlag
	cmp	r0, #0
	bne	.L13
	mov	r3, #193
	lsl	r3, r3, #3
	add	r0, r6, r3
	bl	_GetFlag
	cmp	r0, #0
	beq	.L16
.L13:
	ldrb	r3, [r5, #15]
	mov	r2, #1
	add	fp, fp, r3
	add	r9, r9, r2
.L10:
	add	r7, r7, #1
	cmp	r7, #4
	bls	.L9
	mov	r3, r9
	cmp	r3, #0
	bne	.L19
	mov r0, #3
	neg r0, r0
	.code	16
	b	.L8
.L16:
	mov r0, #2
	neg r0, r0
	.code	16
	b	.L8
.L19:
	mov	r0, fp
	mov	r1, r9
	bl	__divsi3
.L8:
	add sp, #0x1c
	.code	16
	pop	{r3, r5, r6, r7}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	mov	fp, r7
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L21:
	.align	2, 0
.L20:
	.word	.Lc5c38
.Lfe1:
	.size	 Func_80c1a34,.Lfe1-Func_80c1a34

	.text
	.align	2, 0
