@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80c1df4
	.thumb_func
	.type	 Func_80c1df4,function
Func_80c1df4:
	push	{r5, r6, r7, lr}
	ldr	r3, .L12
	ldr	r5, [r3]
	mov	r6, r5
	add	r6, r6, #64
	ldrb	r4, [r6]
	mov	r1, #0
	sub	sp, sp, #4
	cmp	r1, r4
	bge	.L3
	ldrh	r3, [r5, #16]
	cmp	r3, r0
	beq	.L3
	mov	r2, r5
	add	r2, r2, #16
.L8:
	add	r1, r1, #1
	cmp	r1, r4
	bge	.L3
	add	r2, r2, #2
	ldrh	r3, [r2]
	cmp	r3, r0
	bne	.L8
.L3:
	cmp	r1, r4
	beq	.L9
	mov	r6, r1
	add	r6, r6, #52
	ldrsb	r3, [r5, r6]
	mov	r4, #0
	cmp	r3, #0
	bge	.L10
	mov r3, #1
	strb r3, [r5, r6]
	lsl r3, r1, #2
	add r3, r3, #0x1c
	mov r2, #3
	str r2, [r5, r3]
	
	.code	16
	ldr	r0, .L12+4
	b	.L2
.L10:
	lsl	r7, r1, #2
	b 1f
	2:
	add r4, r4, #1
	1:
	cmp r4, #31
	bgt 3f
	ldrsb r0, [r5, r6]
	mov r1, #9
	add r0, r0, #1
	str r4, [sp]
	bl __modsi3
	mov r3, r7
	strb r0, [r5, r6]
	add r3, r3, #0x1c
	lsl r0, r0, #24
	asr r0, r0, #24
	mov r2, #1
	ldr r3, [r5, r3]
	lsl r2, r2, r0
	and r3, r3, r2
	ldr r4, [sp]
	cmp r3, #0
	bne 2b
	3:
	ldrsb r3, [r5, r6]
	mov r1, r7
	add r1, r1, #0x1c
	mov r2, #1
	lsl r2, r2, r3
	ldr r3, [r5, r1]
	orr r3, r3, r2
	str r3, [r5, r1]
	ldrsb r0, [r5, r6]
	
	.code	16
	b	.L2
.L9:
	cmp	r4, #4
	bgt	.L11
	mov	r1, #1
	mov	r2, r4
	neg	r1, r1
	add	r2, r2, #52
	add	r3, r1, #0
	strb	r3, [r5, r2]
	lsl	r3, r4, #1
	add	r3, r3, #16
	strh	r0, [r5, r3]
	lsl	r3, r4, #2
	add	r3, r3, #28
	mov	r2, #0
	str	r2, [r5, r3]
	add	r3, r4, #1
	strb	r3, [r6]
	mov	r0, #9
	b	.L2
.L11:
	mov	r0, #1
	neg	r0, r0
.L2:
	add	sp, sp, #4
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L13:
	.align	2, 0
.L12:
	.word	iwram_3001e74
	.word	32769
.Lfe1:
	.size	 Func_80c1df4,.Lfe1-Func_80c1df4

	.text
	.align	2, 0
