@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80bf250
	.thumb_func
	.type	 Func_80bf250,function
Func_80bf250:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	mov	r8, r0
	bl	_GetUnit
	mov	r2, #153
	.code	16
	lsl	r2, r2, #1
	.code	16
	mov	r1, r0
	add	r5, r1, r2
	ldrb	r2, [r5]
	.code	16
	mov	r3, r2
	.code	16
	cmp	r3, #0
	beq	.L3
	add	r3, r3, #255
	strb	r3, [r5]
	lsl	r3, r3, #24
	.code	16
	mov	r7, #0
	.code	16
	cmp	r3, #0
	bne	.L4
	ldr	r2, .L6
	.code	16
	add	r3, r1, r2
	.code	16
	strb	r7, [r3]
	mov	r0, #1
	b	.L2
.L4:
	ldr	r3, .L6
	add	r6, r1, r3
	mov	r3, #0
	ldrsb	r3, [r6, r3]
	cmp	r3, #0
	bge	.L3
	ldrb	r1, [r5]
	mov	r0, r8
	mov	r2, #30
	bl	Func_80bf208
	cmp	r0, #0
	beq	.L3
	strb	r7, [r6]
	mov	r0, #1
	strb	r7, [r5]
	b	.L2
.L3:
	mov	r0, #0
.L2:
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L7:
	.align	2, 0
.L6:
	.word	307
.Lfe1:
	.size	 Func_80bf250,.Lfe1-Func_80bf250

	.text
	.align	2, 0
