@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80c1084
	.thumb_func
	.type	 Func_80c1084,function
Func_80c1084:
	push	{lr}
	ldr	r3, .L5+8
	ldr	r0, [r3]
	cmp	r0, #0
	beq	.L3
	mov	r2, #202
	lsl	r2, r2, #3
	add	r3, r0, r2
	ldrh	r3, [r3]
	cmp	r3, #0
	beq	.L3
	ldr	r2, .L5+12
	ldrh	r3, .L5
	strh	r3, [r2]
	ldrh	r3, .L5+4
	add	r2, r2, #2
	strh	r3, [r2]
	ldr	r3, .L5+16
	add	r0, r0, r3
	ldr	r2, .L5+20
	ldrh	r3, [r0]
	ldr	r1, .L5+24
	ldrsb	r3, [r2, r3]
	strh	r3, [r1]
	ldrh	r2, [r0]
	mov	r3, #15
	add	r1, r2, #1
	and	r1, r1, r3
	cmp	r2, #14
	bls	.L4
	mov	r3, #16
	orr	r1, r1, r3
.L4:
	strh	r1, [r0]
	b	.L6
.L7:
	.align	2, 0
.L5:
	.word	16272
	.word	16
	.word	iwram_3001e74
	.word	67108944
	.word	1614
	.word	.Lc5c10
	.word	67108948
.L6:
.L3:
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Func_80c1084,.Lfe1-Func_80c1084

	.text
	.align	2, 0
