@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80b595c
	.thumb_func
	.type	 Func_80b595c,function
Func_80b595c:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r8
	push	{r6, r7}
	ldr	r3, .L29
	ldr	r3, [r3]
	sub	sp, sp, #16
	mov	r7, r0
	mov	sl, r3
	bl	_Func_80198dc
	mov	r6, sp
	mov	r0, r6
	bl	Func_80b6ae0
	.code	16
	mov	r5, #0
	cmp	r7, #0
	beq	.L3
	sub	r3, r7, #1
	mov	r8, r3
.L17:
	ldrh	r0, [r6]
	mov	r1, #1
	add	r6, r6, #2
	bl	_Func_8019908
	cmp	r5, r8
	bne	.L7
	ldr r0, =0x811
	.code	16
	bl	_Func_80175a0
	b	.L12
.L7:
	ldr r0, =0x810
	.code	16
	bl	_Func_80175a0
.L12:
	add	r5, r5, #1
	bl	WaitTextPrompt
	cmp	r5, r7
	bne	.L17
.L3:
	bl	_Func_80174d8
	mov	r3, sl
	add	r3, r3, #69
	ldrb	r3, [r3]
	cmp	r3, #1
	bne	.L18
	bl	_Func_80198dc
	mov	r0, #0
	mov	r1, #1
	bl	_Func_8019908
	ldr r0, =0x812
	.code	16
	bl	_Func_80175a0
	bl	WaitTextPrompt
	b	.L23
.L18:
	cmp	r3, #2
	bne	.L23
	bl	_Func_80198dc
	mov	r0, #0
	mov	r1, #1
	bl	_Func_8019908
	ldr r0, =0x813
	.code	16
	bl	_Func_80175a0
	bl	WaitTextPrompt
.L23:
	add	sp, sp, #16
	pop	{r3, r5}
	mov	r8, r3
	mov	sl, r5
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L30:
	.align	2, 0
.L29:
	.word	iwram_3001e74
.Lfe1:
	.size	 Func_80b595c,.Lfe1-Func_80b595c

	.text
	.align	2, 0
