@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80b7548
	.thumb_func
	.type	 Func_80b7548,function
Func_80b7548:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	ldr r3, =iwram_3001e74
	ldr r2, [r3]
	mov r3, #0x64
	add r2, #2
	ldrsh r3, [r2, r3]
	sub sp, #0x4c
	mov r6, #0
	mov r9, r2
	.code	16
	cmp	r3, #255
	beq	.L3
	add r0, sp, #0x30
	mov r5, r0
	mov r4, #0
	mov r2, #0x64
	mov r1, r9
	.code	16
.L9:
	ldrh r3, [r1, r2]
	add r6, #1
	strh r3, [r4, r5]
	add r2, #2
	add r4, #2
	.code	16
	cmp	r6, #5
	bgt	.L10
	ldrsh r3, [r1, r2]
	.code	16
	cmp	r3, #255
	bne	.L9
	b	.L10
.L3:
	add r0, sp, #0x30
	.code	16
.L10:
	add r1, sp, #0x18
	mov r10, r1
	mov r8, sp
	.code	16
	mov	r1, r6
	mov	r2, sl
	mov	r3, r8
	bl	Func_80b7424
	cmp	r6, #0
	ble	.L11
	mov	r5, #0
	mov	r7, #100
.L16:
	mov r2, r9
	ldrsh r0, [r2, r7]
	.code	16
	cmp	r0, #254
	beq	.L15
	bl	GetBattleActor
	mov r1, r10
	ldr r3, [r5, r1]
	lsl r3, #16
	str r3, [r0, #0xc]
	mov r2, r8
	ldr r3, [r5, r2]
	lsl r3, #16
	str r3, [r0, #0x10]
	.code	16
.L15:
	sub	r6, r6, #1
	add	r5, r5, #4
	add	r7, r7, #2
	cmp	r6, #0
	bne	.L16
.L11:
	add sp, #0x4c
	.code	16
	pop	{r3, r5, r6}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 Func_80b7548,.Lfe1-Func_80b7548

	.text
	.align	2, 0
