@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80b5864
	.thumb_func
	.type	 Func_80b5864,function
Func_80b5864:
	push	{r5, r6, r7, lr}
	ldr	r3, .L13
	mov	r2, r3
	ldr	r6, [r3]
	sub	r3, r3, #12
	ldr	r1, [r3]
	mov	r3, r1
	add	r3, r3, #68
	ldrb	r3, [r3]
	add	r2, r2, #128
	sub	sp, sp, #16
	ldr	r7, [r2]
	cmp	r3, #0
	beq	.L6
	ldr	r3, .L13+4
	ldrh	r2, [r3]
	mov	r3, #3
	and	r3, r3, r2
	cmp	r3, #3
	beq	.L4
	mov	r2, r1
	add	r2, r2, #81
	ldrb	r3, [r2]
	add	r3, r3, #1
	strb	r3, [r2]
	mov	r2, #192
	lsl	r3, r3, #24
	lsl	r2, r2, #21
	cmp	r3, r2
	bls	.L6
	mov	r2, r1
	add	r2, r2, #82
	mov	r3, #1
	b	.L7
.L4:
	ldr r3, =0x04000128
	mov r2, r1
	ldr r3, [r3]
	add r2, #0x50
	lsl r3, #26
	ldrb r2, [r2]
	lsr r3, #30
	.code	16
	cmp	r2, r3
	beq	.L8
	mov	r2, r1
	add	r2, r2, #82
	mov	r3, #1
	strb	r3, [r2]
.L8:
	mov	r2, r1
	add	r2, r2, #81
	mov	r3, #0
.L7:
	strb	r3, [r2]
.L6:
	ldr	r3, [r7, #4]
	cmp	r3, #0
	beq	.L9
	ldr	r3, [r7]
	ldrh	r1, [r6, #54]
	sub	r3, r3, r1
	lsl	r3, r3, #16
	asr	r3, r3, #16
	mov	r2, r3
	cmp	r3, #0
	bge	.L10
	add	r2, r2, #15
.L10:
	asr	r3, r2, #4
	add r3, r1, r3
	.code	16
	strh	r3, [r6, #54]
	ldr	r3, [r7, #4]
	sub	r3, r3, #1
	str	r3, [r7, #4]
.L9:
	ldr	r3, [r6, #28]
	mov	r5, r6
	add	r5, r5, #12
	cmp	r3, #0
	beq	.L11
	mov	r5, r3
.L11:
	bl	InitMatrixStack
	mov	r0, r5
	bl	MatrixTranslatev
	mov	r3, #54
	ldrsh	r0, [r6, r3]
	bl	MatrixYaw
	mov	r2, #52
	ldrsh	r0, [r6, r2]
	bl	MatrixPitch
	mov	r3, #0
	add	r0, sp, #4
	str	r3, [r0]
	str	r3, [r0, #4]
	ldr	r3, [r6, #32]
	mov	r1, r6
	str	r3, [r0, #8]
	ldr r3, =Func_80009c0
	.code	16
	bl	_call_via_r3
	ldr	r3, [r7, #20]
	cmp	r3, #0
	bne	.L12
	mov	r1, #240
	mov	r3, #128
	lsl	r3, r3, #9
	lsl	r1, r1, #15
	str	r3, [sp]
	mov	r0, r1
	mov	r2, #0
	mov	r3, #0
	bl	Func_80c0a24
.L12:
	add	sp, sp, #16
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L14:
	.align	2, 0
.L13:
	.word	iwram_3001e80
	.word	iwram_3001f64
.Lfe1:
	.size	 Func_80b5864,.Lfe1-Func_80b5864

	.text
	.align	2, 0
