@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80bad7c
	.thumb_func
	.type	 Func_80bad7c,function
Func_80bad7c:
	push	{r5, r6, r7, lr}
	ldr	r3, .L21+4
	sub	sp, sp, #16
	mov	r4, #0
	ldr	r1, [r3]
	cmp	r0, #0
	beq	.L3
	mov r3, #0x58
	ldrsh r3, [r1, r3]
	.code	16
	mov	r7, #0
	cmp	r3, #255
	beq	.L12
	mov	r5, r1
	add	r5, r5, #88
	add	r6, sp, #4
.L11:
	mov r1, #0
	ldrsh r0, [r5, r1]
	.code	16
	cmp	r0, #254
	beq	.L8
	str	r4, [sp]
	.code	16
	bl	_GetUnit
	.code	16
	mov	r2, #56
	ldrsh	r3, [r0, r2]
	ldr	r4, [sp]
	cmp	r3, #0
	beq	.L8
	ldrh	r2, .L21
	mov	r3, r7
	orr	r3, r3, r2
	strh	r3, [r6]
	add	r4, r4, #1
	add	r6, r6, #2
.L8:
	add	r5, r5, #2
	mov r0, #0
	ldrsh r3, [r5, r0]
	.code	16
	add	r7, r7, #1
	cmp	r3, #255
	bne	.L11
	b	.L12
.L22:
	.align	2, 0
.L21:
	.word	256
	.word	iwram_3001e74
.L3:
	mov r3, #0x64
	add r2, r1, #2
	ldrsh r3, [r2, r3]
	.code	16
	mov	r7, #0
	cmp	r3, #255
	beq	.L12
	mov r0, r1
	lsl r3, r4, #1
	add r1, sp, #0x10
	add r3, r1
	add r0, #0x66
	mov r1, r3
	ldr r5, =0x180
	mov r2, r0
	sub r1, #0xc
	.code	16
.L19:
	ldrh r3, [r2]
	mov r6, #0xfe
	lsl r3, r3, #16
	lsl r6, r6, #16
	.code	16
	add	r2, r2, #2
	cmp	r3, r6
	beq	.L17
	mov	r3, r7
	orr	r3, r3, r5
	strh	r3, [r1]
	add	r4, r4, #1
	add	r1, r1, #2
.L17:
	add r0, #2
	mov r6, #0
	ldrsh r3, [r0, r6]
	.code	16
	add	r7, r7, #1
	cmp	r3, #255
	bne	.L19
	b 1f
	.pool
1:
	.code	16
.L12:
	mov	r0, #0
	cmp	r4, #0
	beq	.L20
	add	r5, sp, #4
	str	r4, [sp]
	.code	16
	bl	Random
	.code	16
	ldr	r4, [sp]
	mov	r3, r4
	mul	r3, r3, r0
	lsr	r3, r3, #16
	lsl	r3, r3, #1
	ldrh r0, [r5, r3]
	.code	16
.L20:
	add	sp, sp, #16
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 Func_80bad7c,.Lfe1-Func_80bad7c

	.text
	.align	2, 0
