@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_935_2008554
	.thumb_func
	.type	 OvlFunc_935_2008554,function
OvlFunc_935_2008554:
	push	{r5, lr}
	mov	r0, #17
	sub	sp, sp, #8
	bl	__MapActor_GetActor
	mov	r3, #23
	mov	r2, #34
	mov	r5, r0
	.code	16
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #26
	mov	r1, #30
	mov	r2, #1
	mov	r3, #1
	bl	__Func_8010704
	cmp	r5, #0
	beq	.L3
	mov	r0, #17
	bl	__MapActor_GetActor
	mov	r3, #0
	.code	16
	add	r0, r0, #85
	mov	r2, r5
	.code	16
	strb	r3, [r0]
	add	r2, r2, #35
	mov	r3, #1
	strb	r3, [r2]
.L3:
	ldr	r0, .L4
	bl	__SetFlag
	add	sp, sp, #8
	pop	{r5}
	pop	{r0}
	bx	r0
.L5:
	.align	2, 0
.L4:
	.word	513
.Lfe1:
	.size	 OvlFunc_935_2008554,.Lfe1-OvlFunc_935_2008554
	.align	2, 0
	.global	OvlFunc_935_20085a0
	.thumb_func
	.type	 OvlFunc_935_20085a0,function
OvlFunc_935_20085a0:
	push	{r5, lr}
	mov	r0, #18
	sub	sp, sp, #8
	bl	__MapActor_GetActor
	mov	r3, #24
	mov	r2, #34
	mov	r5, r0
	.code	16
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #26
	mov	r1, #30
	mov	r2, #1
	mov	r3, #1
	bl	__Func_8010704
	cmp	r5, #0
	beq	.L7
	mov	r0, #18
	bl	__MapActor_GetActor
	mov	r3, #0
	.code	16
	add	r0, r0, #85
	mov	r2, r5
	.code	16
	strb	r3, [r0]
	add	r2, r2, #35
	mov	r3, #1
	strb	r3, [r2]
.L7:
	ldr	r0, .L8
	bl	__SetFlag
	add	sp, sp, #8
	pop	{r5}
	pop	{r0}
	bx	r0
.L9:
	.align	2, 0
.L8:
	.word	514
.Lfe2:
	.size	 OvlFunc_935_20085a0,.Lfe2-OvlFunc_935_20085a0

	.text
	.align	2, 0
