@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_2e0_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_7bf5a8_4cc
	.thumb_func
	.type	 OvlFunc_7bf5a8_4cc,function
OvlFunc_7bf5a8_4cc:
	bx	lr
.Lfe1:
	.size	 OvlFunc_7bf5a8_4cc,.Lfe1-OvlFunc_7bf5a8_4cc

	.text
	.align	2, 0
