@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_935_20080e0
	.thumb_func
	.type	 OvlFunc_935_20080e0,function
OvlFunc_935_20080e0:
	push	{lr}
	ldr	r3, .L7
	mov	r1, #224
	.code	16
	lsl	r1, r1, #1
	add	r3, r3, r1
	mov	r1, #0
	.code	16
	ldrsh	r2, [r3, r1]
	ldr	r3, .L7+4
	.code	16
	cmp	r2, r3
	bne	.L3
	ldr	r0, .L7+8
	b	.L4
.L3:
	ldr	r3, .L7+12
	.code	16
	cmp	r2, r3
	bne	.L5
	ldr	r0, .L7+16
	b	.L4
.L5:
	ldr	r3, .L7+20
	.code	16
	cmp	r2, r3
	bne	.L6
	ldr	r0, .L7+24
	b	.L4
.L6:
	ldr	r0, .L7+28
.L4:
	.code	16
	pop	{r1}
	bx	r1
.L8:
	.align	2, 0
.L7:
	.word	gState
	.word	0x60
	.word	.L1d34
	.word	0x61
	.word	.L1d4c
	.word	0x62
	.word	gScript_887__02009ecc
	.word	.L1d1c
.Lfe1:
	.size	 OvlFunc_935_20080e0,.Lfe1-OvlFunc_935_20080e0

	.text
	.align	2, 0
