@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_7a0010_64
	.thumb_func
	.type	 OvlFunc_7a0010_64,function
OvlFunc_7a0010_64:
	mov	r0, #0
	bx	lr
.Lfe1:
	.size	 OvlFunc_7a0010_64,.Lfe1-OvlFunc_7a0010_64

	.text
	.align	2, 0
