@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80f4100
	.thumb_func
	.type	 Func_80f4100,function
Func_80f4100:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	mov	r7, r0
	.code	16
	mov	r6, r1
	.code	16
	mov	r5, r2
	.code	16
	cmp	r3, #0
	ble	.L3
	mov	r1, #31
	.code	16
	mov	r8, r1
	.code	16
	mov	r2, #248
	.code	16
	mov	r1, #248
	.code	16
	lsl	r2, r2, #2
	.code	16
	lsl	r1, r1, #7
	.code	16
	mov	lr, r2
	.code	16
	mov	ip, r1
	.code	16
	mov	r0, r3
	.code	16
.L7:
	ldrh	r4, [r7]
	.code	16
	mov	r2, r8
	.code	16
	mov	r3, r4
	.code	16
	and	r3, r3, r2
	.code	16
	mov	r1, lr
	.code	16
	mov	r2, r4
	.code	16
	and	r2, r2, r1
	.code	16
	mul	r3, r3, r5
	.code	16
	mov	r1, ip
	.code	16
	mul	r2, r2, r5
	.code	16
	and	r1, r1, r4
	.code	16
	mul	r1, r1, r5
	.code	16
	lsr	r4, r3, #16
	.code	16
	mov	r3, r8
	.code	16
	and	r4, r4, r3
	.code	16
	lsr	r2, r2, #16
	.code	16
	mov	r3, lr
	.code	16
	and	r2, r2, r3
	.code	16
	orr	r4, r4, r2
	.code	16
	lsr	r1, r1, #16
	.code	16
	mov	r2, ip
	.code	16
	and	r1, r1, r2
	.code	16
	orr	r4, r4, r1
	.code	16
	sub	r0, r0, #1
	.code	16
	strh	r4, [r6]
	add	r7, r7, #2
	.code	16
	add	r6, r6, #2
	.code	16
	cmp	r0, #0
	bne	.L7
.L3:
	mov	r0, #0
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 Func_80f4100,.Lfe1-Func_80f4100

	.text
	.align	2, 0
