@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"altin.c"
	.code	16
.gcc2_compiled.:
	.include "asm/maps/altin/exports.s"
	.text

	.include "asm/maps/altin/ovl_30_a.s"
	.text

	.code	16
.text
	.align	2, 0
	.global	Altin_GetSpecialExits
	.thumb_func
	.type	 Altin_GetSpecialExits,function
Altin_GetSpecialExits:
	mov	r0, #0
	bx	lr
.Lfe1:
	.size	 Altin_GetSpecialExits,.Lfe1-Altin_GetSpecialExits
	.align	2, 0
	.global	Altin_GetExits
	.thumb_func
	.type	 Altin_GetExits,function
Altin_GetExits:
	ldr	r0, .L4
	bx	lr
.L5:
	.align	2, 0
.L4:
	.word	gOvl_02009390
.Lfe2:
	.size	 Altin_GetExits,.Lfe2-Altin_GetExits
	.include "asm/maps/altin/ovl_30_c_c_a_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_931_200815c
	.thumb_func
	.type	 OvlFunc_931_200815c,function
OvlFunc_931_200815c:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L9
	bl	__MessageID
	mov	r1, #0
	mov	r0, #8
	bl	__ShowActorMessage_NoWait
	mov	r0, #0
	mov	r1, #0
	bl	__Func_8091c7c
	cmp	r0, #1
	bne	.L7
	mov	r0, #8
	mov	r1, #0
	bl	__ActorMessage
	b	.L8
.L7:
	ldr	r3, .L9+4
	ldr	r2, [r3]
	mov	r3, #236
	lsl	r3, r3, #1
	add	r2, r2, r3
	ldrh	r3, [r2]
	add	r3, r3, #1
	strh	r3, [r2]
	mov	r0, #8
	mov	r1, #0
	bl	__Func_8093054
.L8:
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L10:
	.align	2, 0
.L9:
	.word	6333
	.word	iwram_3001ebc
.Lfe3:
	.size	 OvlFunc_931_200815c,.Lfe3-OvlFunc_931_200815c
	.align	2, 0
	.global	OvlFunc_931_20081b0
	.thumb_func
	.type	 OvlFunc_931_20081b0,function
OvlFunc_931_20081b0:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L12
	bl	__MessageID
	mov	r1, #0
	mov	r0, #9
	bl	__Func_8093054
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L13:
	.align	2, 0
.L12:
	.word	6424
.Lfe4:
	.size	 OvlFunc_931_20081b0,.Lfe4-OvlFunc_931_20081b0
	.include "asm/maps/altin/ovl_30_c_c_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_931_2008298
	.thumb_func
	.type	 OvlFunc_931_2008298,function
OvlFunc_931_2008298:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L15
	bl	__MessageID
	mov	r1, #0
	mov	r0, #17
	bl	__Func_8093054
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L16:
	.align	2, 0
.L15:
	.word	6436
.Lfe5:
	.size	 OvlFunc_931_2008298,.Lfe5-OvlFunc_931_2008298
	.align	2, 0
	.global	OvlFunc_931_20082b8
	.thumb_func
	.type	 OvlFunc_931_20082b8,function
OvlFunc_931_20082b8:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L18
	bl	__MessageID
	mov	r1, #0
	mov	r0, #9
	bl	__Func_8093054
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L19:
	.align	2, 0
.L18:
	.word	6450
.Lfe6:
	.size	 OvlFunc_931_20082b8,.Lfe6-OvlFunc_931_20082b8
	.align	2, 0
	.global	OvlFunc_931_20082d8
	.thumb_func
	.type	 OvlFunc_931_20082d8,function
OvlFunc_931_20082d8:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L21
	bl	__MessageID
	mov	r1, #0
	mov	r0, #10
	bl	__Func_8093054
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L22:
	.align	2, 0
.L21:
	.word	6361
.Lfe7:
	.size	 OvlFunc_931_20082d8,.Lfe7-OvlFunc_931_20082d8
	.align	2, 0
	.global	OvlFunc_931_20082f8
	.thumb_func
	.type	 OvlFunc_931_20082f8,function
OvlFunc_931_20082f8:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L24
	bl	__MessageID
	mov	r1, #0
	mov	r0, #14
	bl	__Func_8093054
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L25:
	.align	2, 0
.L24:
	.word	6369
.Lfe8:
	.size	 OvlFunc_931_20082f8,.Lfe8-OvlFunc_931_20082f8
	.align	2, 0
	.global	OvlFunc_931_2008318
	.thumb_func
	.type	 OvlFunc_931_2008318,function
OvlFunc_931_2008318:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L27
	bl	__MessageID
	mov	r1, #0
	mov	r0, #21
	bl	__Func_8093054
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L28:
	.align	2, 0
.L27:
	.word	6474
.Lfe9:
	.size	 OvlFunc_931_2008318,.Lfe9-OvlFunc_931_2008318
	.align	2, 0
	.global	OvlFunc_931_2008338
	.thumb_func
	.type	 OvlFunc_931_2008338,function
OvlFunc_931_2008338:
	push	{lr}
	mov	r0, #0
	bl	__MapActor_GetActor
	ldr	r2, .L31
	ldrh	r3, [r0, #6]
	add	r3, r3, r2
	ldr	r2, .L31+4
	lsl	r3, r3, #16
	mov	r0, #1
	cmp	r3, r2
	bls	.L29
	mov	r0, #0
.L29:
	pop	{r1}
	bx	r1
.L32:
	.align	2, 0
.L31:
	.word	24575
	.word	1073610752
.Lfe10:
	.size	 OvlFunc_931_2008338,.Lfe10-OvlFunc_931_2008338
	.include "asm/maps/altin/ovl_30_c_c_c_c_c_c_c_c_c_a_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_931_20084bc
	.thumb_func
	.type	 OvlFunc_931_20084bc,function
OvlFunc_931_20084bc:
	push	{lr}
	mov	r0, #0
	bl	__MapActor_GetActor
	ldr	r2, .L38
	ldrh	r3, [r0, #6]
	add	r3, r3, r2
	ldr	r2, .L38+4
	lsl	r3, r3, #16
	cmp	r3, r2
	bhi	.L34
	mov	r0, #6
	mov	r1, #18
	bl	__Func_80b3284
	b	.L35
.L34:
	bl	__CutsceneStart
	ldr	r0, .L38+8
	bl	__GetFlag
	cmp	r0, #0
	beq	.L36
	ldr	r0, .L38+12
	bl	__MessageID
	mov	r0, #18
	mov	r1, #0
	bl	__ActorMessage
	b	.L37
.L36:
	ldr	r0, .L38+16
	bl	__MessageID
	mov	r0, #18
	mov	r1, #0
	bl	__Func_8093054
.L37:
	bl	__CutsceneEnd
.L35:
	pop	{r0}
	bx	r0
.L39:
	.align	2, 0
.L38:
	.word	24575
	.word	1073610752
	.word	2313
	.word	6471
	.word	6389
.Lfe11:
	.size	 OvlFunc_931_20084bc,.Lfe11-OvlFunc_931_20084bc
	.include "asm/maps/altin/ovl_30_c_c_c_c_c_c_c_c_c_a_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_931_200884c
	.thumb_func
	.type	 OvlFunc_931_200884c,function
OvlFunc_931_200884c:
	push	{lr}
	mov	r0, #19
	bl	__MapActor_GetActor
	ldr	r3, [r0, #8]
	asr	r3, r3, #20
	cmp	r3, #22
	bne	.L41
	ldr	r0, .L43
	bl	__SetFlag
	b	.L42
.L41:
	ldr	r0, .L43
	bl	__ClearFlag
.L42:
	pop	{r0}
	bx	r0
.L44:
	.align	2, 0
.L43:
	.word	2310
.Lfe12:
	.size	 OvlFunc_931_200884c,.Lfe12-OvlFunc_931_200884c
	.include "asm/maps/altin/ovl_30_c_c_c_c_c_c_c_c_c_c.s"
	.text

	.include "asm/maps/altin/imports.s"
	.text


	.text
	.align	2, 0
