@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"altin_peak.c"
	.code	16
.gcc2_compiled.:
	.include "asm/maps/altin_peak/exports.s"
	.text

	.code	16
.text
	.align	2, 0
	.global	OvlFunc_932_2008030
	.thumb_func
	.type	 OvlFunc_932_2008030,function
OvlFunc_932_2008030:
	push	{lr}
	mov	r0, #14
	mov	r1, #23
	bl	__Func_8091f14
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_932_2008030,.Lfe1-OvlFunc_932_2008030
	.include "asm/maps/altin_peak/ovl_30_a_a_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_932_2008098
	.thumb_func
	.type	 OvlFunc_932_2008098,function
OvlFunc_932_2008098:
	push	{r5, lr}
	mov	r5, r0
	mov	r0, #8
	bl	__MapActor_GetActor
	ldr	r3, [r0, #8]
	str	r3, [r5, #8]
	ldr	r3, .L4
	str	r3, [r5, #12]
	ldr	r3, [r0, #16]
	mov	r0, #0
	str	r3, [r5, #16]
	pop	{r5}
	pop	{r1}
	bx	r1
.L5:
	.align	2, 0
.L4:
	.word	-786432
.Lfe2:
	.size	 OvlFunc_932_2008098,.Lfe2-OvlFunc_932_2008098
	.align	2, 0
	.global	OvlFunc_932_20080bc
	.thumb_func
	.type	 OvlFunc_932_20080bc,function
OvlFunc_932_20080bc:
	ldr	r3, [r0, #8]
	ldr	r2, [r0, #36]
	add	r3, r3, r2
	str	r3, [r0, #8]
	ldr	r2, [r0, #40]
	ldr	r3, [r0, #12]
	add	r3, r3, r2
	ldr	r1, [r0, #44]
	str	r3, [r0, #12]
	ldr	r3, [r0, #24]
	add	r3, r3, r1
	str	r3, [r0, #24]
	ldr	r3, [r0, #28]
	add	r3, r3, r1
	str	r3, [r0, #28]
	ldr	r3, [r0, #72]
	sub	r2, r2, r3
	str	r2, [r0, #40]
	mov	r0, #0
	bx	lr
.Lfe3:
	.size	 OvlFunc_932_20080bc,.Lfe3-OvlFunc_932_20080bc
	.include "asm/maps/altin_peak/ovl_30_a_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	AltinPeak_GetExits
	.thumb_func
	.type	 AltinPeak_GetExits,function
AltinPeak_GetExits:
	ldr	r0, .L8
	bx	lr
.L9:
	.align	2, 0
.L8:
	.word	gOvl_0200c85c
.Lfe4:
	.size	 AltinPeak_GetExits,.Lfe4-AltinPeak_GetExits
	.include "asm/maps/altin_peak/ovl_30_a_c_c_a_a_a_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_932_200847c
	.thumb_func
	.type	 OvlFunc_932_200847c,function
OvlFunc_932_200847c:
	push	{r5, lr}
	mov	r0, #8
	sub	sp, sp, #8
	bl	__MapActor_GetActor
	mov	r3, #9
	mov	r2, #13
	mov	r5, r0
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #7
	mov	r1, #13
	mov	r2, #1
	mov	r3, #1
	bl	__Func_8010704
	cmp	r5, #0
	beq	.L11
	mov	r0, r5
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	ldr	r3, [r5, #12]
	ldr	r2, .L12
	add	r3, r3, r2
	mov	r2, r5
	str	r3, [r5, #12]
	add	r2, r2, #35
	mov	r3, #2
	strb	r3, [r2]
.L11:
	mov	r0, #128
	lsl	r0, r0, #2
	bl	__SetFlag
	add	sp, sp, #8
	pop	{r5}
	pop	{r0}
	bx	r0
.L13:
	.align	2, 0
.L12:
	.word	-2097152
.Lfe5:
	.size	 OvlFunc_932_200847c,.Lfe5-OvlFunc_932_200847c
	.include "asm/maps/altin_peak/ovl_30_a_c_c_a_a_a_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_932_200850c
	.thumb_func
	.type	 OvlFunc_932_200850c,function
OvlFunc_932_200850c:
	push	{r5, lr}
	mov	r0, #9
	sub	sp, sp, #8
	bl	__MapActor_GetActor
	mov	r3, #26
	mov	r5, r0
	str	r3, [sp]
	str	r3, [sp, #4]
	mov	r0, #0
	mov	r1, #0
	mov	r2, #1
	mov	r3, #1
	bl	__Func_8010704
	cmp	r5, #0
	beq	.L15
	mov	r0, r5
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	ldr	r3, [r5, #12]
	ldr	r2, .L16
	add	r3, r3, r2
	mov	r2, r5
	str	r3, [r5, #12]
	add	r2, r2, #35
	mov	r3, #2
	strb	r3, [r2]
.L15:
	mov	r0, #128
	lsl	r0, r0, #2
	bl	__SetFlag
	add	sp, sp, #8
	pop	{r5}
	pop	{r0}
	bx	r0
.L17:
	.align	2, 0
.L16:
	.word	-2097152
.Lfe6:
	.size	 OvlFunc_932_200850c,.Lfe6-OvlFunc_932_200850c
	.align	2, 0
	.global	OvlFunc_932_200855c
	.thumb_func
	.type	 OvlFunc_932_200855c,function
OvlFunc_932_200855c:
	push	{r5, lr}
	mov	r0, #9
	sub	sp, sp, #8
	bl	__MapActor_GetActor
	mov	r3, #25
	mov	r2, #13
	mov	r5, r0
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #23
	mov	r1, #13
	mov	r2, #1
	mov	r3, #1
	bl	__Func_8010704
	cmp	r5, #0
	beq	.L19
	mov	r0, r5
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	ldr	r3, [r5, #12]
	ldr	r2, .L20
	add	r3, r3, r2
	mov	r2, r5
	str	r3, [r5, #12]
	add	r2, r2, #35
	mov	r3, #2
	strb	r3, [r2]
.L19:
	mov	r0, #128
	lsl	r0, r0, #2
	bl	__SetFlag
	add	sp, sp, #8
	pop	{r5}
	pop	{r0}
	bx	r0
.L21:
	.align	2, 0
.L20:
	.word	-2097152
.Lfe7:
	.size	 OvlFunc_932_200855c,.Lfe7-OvlFunc_932_200855c
	.align	2, 0
	.global	OvlFunc_932_20085ac
	.thumb_func
	.type	 OvlFunc_932_20085ac,function
OvlFunc_932_20085ac:
	push	{r5, lr}
	mov	r0, #9
	sub	sp, sp, #8
	bl	__MapActor_GetActor
	mov	r3, #43
	mov	r2, #41
	mov	r5, r0
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #45
	mov	r1, #41
	mov	r2, #1
	mov	r3, #1
	bl	__Func_8010704
	cmp	r5, #0
	beq	.L23
	mov	r0, r5
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	ldr	r3, [r5, #12]
	ldr	r2, .L24
	add	r3, r3, r2
	mov	r2, r5
	str	r3, [r5, #12]
	add	r2, r2, #35
	mov	r3, #2
	strb	r3, [r2]
.L23:
	mov	r0, #128
	lsl	r0, r0, #2
	bl	__SetFlag
	add	sp, sp, #8
	pop	{r5}
	pop	{r0}
	bx	r0
.L25:
	.align	2, 0
.L24:
	.word	-2097152
.Lfe8:
	.size	 OvlFunc_932_20085ac,.Lfe8-OvlFunc_932_20085ac
	.align	2, 0
	.global	OvlFunc_932_20085fc
	.thumb_func
	.type	 OvlFunc_932_20085fc,function
OvlFunc_932_20085fc:
	push	{r5, lr}
	mov	r0, #11
	sub	sp, sp, #8
	bl	__MapActor_GetActor
	mov	r3, #17
	mov	r2, #10
	mov	r5, r0
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #1
	mov	r1, #0
	mov	r2, #1
	mov	r3, #1
	bl	__Func_8010704
	cmp	r5, #0
	beq	.L27
	mov	r0, r5
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	ldr	r3, [r5, #12]
	ldr	r2, .L28
	add	r3, r3, r2
	mov	r2, r5
	str	r3, [r5, #12]
	add	r2, r2, #35
	mov	r3, #2
	strb	r3, [r2]
.L27:
	ldr	r0, .L28+4
	bl	__SetFlag
	add	sp, sp, #8
	pop	{r5}
	pop	{r0}
	bx	r0
.L29:
	.align	2, 0
.L28:
	.word	-2097152
	.word	513
.Lfe9:
	.size	 OvlFunc_932_20085fc,.Lfe9-OvlFunc_932_20085fc
	.align	2, 0
	.global	OvlFunc_932_2008650
	.thumb_func
	.type	 OvlFunc_932_2008650,function
OvlFunc_932_2008650:
	push	{r5, lr}
	mov	r0, #12
	sub	sp, sp, #8
	bl	__MapActor_GetActor
	mov	r3, #26
	mov	r2, #15
	mov	r5, r0
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #1
	mov	r1, #0
	mov	r2, #1
	mov	r3, #1
	bl	__Func_8010704
	cmp	r5, #0
	beq	.L31
	mov	r0, r5
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	ldr	r3, [r5, #12]
	ldr	r2, .L32
	add	r3, r3, r2
	mov	r2, r5
	str	r3, [r5, #12]
	add	r2, r2, #35
	mov	r3, #2
	strb	r3, [r2]
.L31:
	mov	r0, #129
	lsl	r0, r0, #2
	bl	__SetFlag
	add	sp, sp, #8
	pop	{r5}
	pop	{r0}
	bx	r0
.L33:
	.align	2, 0
.L32:
	.word	-2097152
.Lfe10:
	.size	 OvlFunc_932_2008650,.Lfe10-OvlFunc_932_2008650
	.include "asm/maps/altin_peak/ovl_30_a_c_c_a_a_a_c_c_c_c_c_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_932_2008a64
	.thumb_func
	.type	 OvlFunc_932_2008a64,function
OvlFunc_932_2008a64:
	push	{lr}
	bl	__CutsceneStart
	mov	r1, #1
	ldr	r0, .L35
	bl	__Func_801776c
	mov	r0, #125
	bl	__PlaySound
	bl	OvlFunc_932_20089ec
	mov	r0, #20
	bl	__WaitFrames
	bl	__MapActor_PlayPendingSound
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L36:
	.align	2, 0
.L35:
	.word	5416
.Lfe11:
	.size	 OvlFunc_932_2008a64,.Lfe11-OvlFunc_932_2008a64
	.include "asm/maps/altin_peak/ovl_30_a_c_c_a_a_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_932_2008b0c
	.thumb_func
	.type	 OvlFunc_932_2008b0c,function
OvlFunc_932_2008b0c:
	push	{lr}
	bl	__CutsceneStart
	mov	r1, #1
	ldr	r0, .L38
	bl	__Func_801776c
	mov	r0, #125
	bl	__PlaySound
	bl	OvlFunc_932_2008a94
	mov	r0, #20
	bl	__WaitFrames
	bl	__MapActor_PlayPendingSound
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L39:
	.align	2, 0
.L38:
	.word	5416
.Lfe12:
	.size	 OvlFunc_932_2008b0c,.Lfe12-OvlFunc_932_2008b0c
	.include "asm/maps/altin_peak/ovl_30_a_c_c_a_a_c_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_932_2008c74
	.thumb_func
	.type	 OvlFunc_932_2008c74,function
OvlFunc_932_2008c74:
	push	{lr}
	mov	r0, #10
	bl	__MapActor_GetActor
	mov	r3, #3
	add	r0, r0, #35
	strb	r3, [r0]
	pop	{r0}
	bx	r0
.Lfe13:
	.size	 OvlFunc_932_2008c74,.Lfe13-OvlFunc_932_2008c74
	.align	2, 0
	.global	OvlFunc_932_2008c88
	.thumb_func
	.type	 OvlFunc_932_2008c88,function
OvlFunc_932_2008c88:
	push	{lr}
	mov	r0, #10
	bl	__MapActor_GetActor
	mov	r3, #1
	add	r0, r0, #35
	strb	r3, [r0]
	pop	{r0}
	bx	r0
.Lfe14:
	.size	 OvlFunc_932_2008c88,.Lfe14-OvlFunc_932_2008c88
	.include "asm/maps/altin_peak/ovl_30_a_c_c_a_c_c_a_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_932_200abb0
	.thumb_func
	.type	 OvlFunc_932_200abb0,function
OvlFunc_932_200abb0:
	push	{lr}
	ldr	r4, .L43
	str	r2, [r4, #8]
	ldr	r2, .L43+4
	str	r0, [r4]
	str	r1, [r4, #4]
	mov	r0, #170
	str	r3, [r2]
	bl	__Func_8091ff0
	mov	r1, #200
	lsl	r1, r1, #4
	ldr	r0, .L43+8
	bl	__StartTask
	pop	{r0}
	bx	r0
.L44:
	.align	2, 0
.L43:
	.word	.Lm932_5240
	.word	.Lm932_523c
	.word	OvlFunc_932_200ab58
.Lfe15:
	.size	 OvlFunc_932_200abb0,.Lfe15-OvlFunc_932_200abb0
	.include "asm/maps/altin_peak/ovl_30_a_c_c_a_c_c_a_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_932_200ace0
	.thumb_func
	.type	 OvlFunc_932_200ace0,function
OvlFunc_932_200ace0:
	push	{lr}
	ldr	r3, .L49
	ldr	r2, [r3]
	mov	r3, #7
	and	r2, r2, r3
	cmp	r2, #0
	bne	.L46
	mov	r1, #2
	bl	__Func_80929d8
	b	.L47
.L46:
	cmp	r2, #2
	bne	.L47
	mov	r1, #0
	bl	__Func_80929d8
.L47:
	pop	{r0}
	bx	r0
.L50:
	.align	2, 0
.L49:
	.word	iwram_3001e40
.Lfe16:
	.size	 OvlFunc_932_200ace0,.Lfe16-OvlFunc_932_200ace0
	.align	2, 0
	.global	OvlFunc_932_200ad08
	.thumb_func
	.type	 OvlFunc_932_200ad08,function
OvlFunc_932_200ad08:
	push	{lr}
	mov	r0, #24
	mov	r1, #1
	bl	__Func_8096fb0
	mov	r0, #10
	mov	r1, #9
	bl	__Func_80970f8
	bl	__Func_809728c
	mov	r1, #2
	mov	r0, #10
	bl	__Func_8092950
	mov	r0, #1
	bl	__FieldMove
	mov	r0, #10
	mov	r1, #2
	bl	__Func_8092950
	bl	__Func_8097174
	mov	r1, #2
	mov	r0, #10
	bl	__Func_8092950
	bl	__Func_8097194
	mov	r0, #144
	lsl	r0, r0, #1
	bl	__PlaySound
	mov	r0, #10
	mov	r1, #2
	bl	__Func_8092950
	pop	{r0}
	bx	r0
.Lfe17:
	.size	 OvlFunc_932_200ad08,.Lfe17-OvlFunc_932_200ad08
	.include "asm/maps/altin_peak/ovl_30_a_c_c_a_c_c_a_c_c_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_932_200ae1c
	.thumb_func
	.type	 OvlFunc_932_200ae1c,function
OvlFunc_932_200ae1c:
	push	{r5, r6, lr}
	bl	__CutsceneStart
	mov	r0, #9
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	mov	r1, #164
	mov	r2, #212
	lsl	r1, r1, #17
	lsl	r2, r2, #17
	mov	r0, #8
	bl	__MapActor_SetPos
	ldr	r0, .L73
	bl	__SetFlag
	bl	OvlFunc_932_20089ec
	bl	__Func_800fe9c
	mov	r0, #1
	bl	__WaitFrames
	ldr	r5, .L73+4
	ldr	r3, .L73+8
	ldr	r2, [r5]
	mov	r6, #224
	lsl	r6, r6, #1
	str	r3, [r2, r6]
	bl	__MapTransitionIn
	bl	__WaitMapTransition
	bl	OvlFunc_932_20087e8
	ldr	r2, [r5]
	mov	r3, #129
	lsl	r3, r3, #2
	str	r3, [r2, r6]
	bl	__CutsceneEnd
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L74:
	.align	2, 0
.L73:
	.word	803
	.word	iwram_3001ebc
	.word	513
.Lfe18:
	.size	 OvlFunc_932_200ae1c,.Lfe18-OvlFunc_932_200ae1c
	.align	2, 0
	.global	OvlFunc_932_200ae84
	.thumb_func
	.type	 OvlFunc_932_200ae84,function
OvlFunc_932_200ae84:
	push	{r5, r6, lr}
	bl	__CutsceneStart
	mov	r0, #10
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	mov	r1, #244
	mov	r2, #138
	lsl	r1, r1, #17
	lsl	r2, r2, #16
	mov	r0, #8
	bl	__MapActor_SetPos
	ldr	r0, .L80
	bl	__SetFlag
	bl	OvlFunc_932_2008a94
	bl	__Func_800fe9c
	mov	r0, #1
	bl	__WaitFrames
	ldr	r5, .L80+4
	ldr	r3, .L80+8
	ldr	r2, [r5]
	mov	r6, #224
	lsl	r6, r6, #1
	str	r3, [r2, r6]
	bl	__MapTransitionIn
	bl	__WaitMapTransition
	bl	OvlFunc_932_20088d4
	ldr	r2, [r5]
	mov	r3, #129
	lsl	r3, r3, #2
	str	r3, [r2, r6]
	bl	__CutsceneEnd
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L81:
	.align	2, 0
.L80:
	.word	805
	.word	iwram_3001ebc
	.word	513
.Lfe19:
	.size	 OvlFunc_932_200ae84,.Lfe19-OvlFunc_932_200ae84
	.align	2, 0
	.global	OvlFunc_932_200aeec
	.thumb_func
	.type	 OvlFunc_932_200aeec,function
OvlFunc_932_200aeec:
	push	{r5, lr}
	ldr	r5, .L84
	ldr	r3, [r5]
	add	r3, r3, #1
	str	r3, [r5]
	cmp	r3, #60
	bne	.L82
	mov	r0, #183
	bl	__PlaySound
	mov	r3, #0
	str	r3, [r5]
.L82:
	pop	{r5}
	pop	{r0}
	bx	r0
.L85:
	.align	2, 0
.L84:
	.word	.Lm932_51b0
.Lfe20:
	.size	 OvlFunc_932_200aeec,.Lfe20-OvlFunc_932_200aeec
	.include "asm/maps/altin_peak/ovl_30_a_c_c_a_c_c_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_932_200affc
	.thumb_func
	.type	 OvlFunc_932_200affc,function
OvlFunc_932_200affc:
	push	{lr}
	ldr	r3, .L89
	ldr	r3, [r3]
	mov	r2, #1
	lsr	r3, r3, #1
	and	r3, r3, r2
	cmp	r3, #0
	beq	.L87
	mov	r0, #8
	mov	r1, #7
	bl	__Func_8092950
	b	.L88
.L87:
	mov	r0, #8
	mov	r1, #6
	bl	__Func_8092950
.L88:
	pop	{r0}
	bx	r0
.L90:
	.align	2, 0
.L89:
	.word	iwram_3001e40
.Lfe21:
	.size	 OvlFunc_932_200affc,.Lfe21-OvlFunc_932_200affc
	.include "asm/maps/altin_peak/ovl_30_a_c_c_c_a_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_932_200b410
	.thumb_func
	.type	 OvlFunc_932_200b410,function
OvlFunc_932_200b410:
	ldr	r3, .L92
	mov	r1, #191
	ldr	r3, [r3]
	lsl	r1, r1, #1
	add	r2, r3, r1
	ldr	r3, .L92+4
	strh	r3, [r2]
	bx	lr
.L93:
	.align	2, 0
.L92:
	.word	iwram_3001ebc
	.word	4120
.Lfe22:
	.size	 OvlFunc_932_200b410,.Lfe22-OvlFunc_932_200b410
	.include "asm/maps/altin_peak/ovl_30_a_c_c_c_a_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_932_200b460
	.thumb_func
	.type	 OvlFunc_932_200b460,function
OvlFunc_932_200b460:
	push	{lr}
	bl	__MapActor_GetActor
	mov	r1, r0
	add	r1, r1, #89
	ldrb	r2, [r1]
	mov	r3, #254
	and	r3, r3, r2
	strb	r3, [r1]
	mov	r3, #255
	ldr	r1, [r0, #8]
	ldr	r2, [r0, #16]
	mov	r0, #0
	bl	__Func_8012078
	pop	{r0}
	bx	r0
.Lfe23:
	.size	 OvlFunc_932_200b460,.Lfe23-OvlFunc_932_200b460
	.include "asm/maps/altin_peak/ovl_30_a_c_c_c_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_932_200b5a8
	.thumb_func
	.type	 OvlFunc_932_200b5a8,function
OvlFunc_932_200b5a8:
	bx	lr
.Lfe24:
	.size	 OvlFunc_932_200b5a8,.Lfe24-OvlFunc_932_200b5a8
	.include "asm/maps/altin_peak/ovl_30_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_932_200b724
	.thumb_func
	.type	 OvlFunc_932_200b724,function
OvlFunc_932_200b724:
	push	{lr}
	add	r0, r0, #102
	mov	r3, #33
	strh	r3, [r0]
	mov	r0, #144
	lsl	r0, r0, #1
	bl	__PlaySound
	pop	{r0}
	bx	r0
.Lfe25:
	.size	 OvlFunc_932_200b724,.Lfe25-OvlFunc_932_200b724
	.include "asm/maps/altin_peak/ovl_30_c_c.s"
	.text

	.include "asm/maps/altin_peak/imports.s"
	.text


	.text
	.align	2, 0
