@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"crossbone_isle_dungeon_4.c"
	.code	16
.gcc2_compiled.:
	.include "asm/maps/crossbone_isle_dungeon_4/exports.s"
	.text

	.code	16
.text
	.align	2, 0
	.global	OvlFunc_948_2008030
	.thumb_func
	.type	 OvlFunc_948_2008030,function
OvlFunc_948_2008030:
	push	{r5, lr}
	ldmia	r0!, {r5}
	ldmia	r1!, {r3}
	ldmia	r0!, {r4}
	sub	r5, r5, r3
	ldmia	r1!, {r3}
	ldr	r2, [r1]
	sub	r4, r4, r3
	ldr	r3, [r0]
	sub	r3, r3, r2
	asr	r5, r5, #16
	asr	r4, r4, #16
	asr	r3, r3, #16
	mov	r0, r5
	mul	r0, r0, r5
	mov	r2, r4
	mul	r2, r2, r4
	mov	r1, r3
	mul	r1, r1, r3
	add	r0, r0, r2
	mov	r3, r1
	add	r0, r0, r3
	ldr	r3, .L4
	bl	_call_via_r3
	pop	{r5}
	pop	{r1}
	bx	r1
.L5:
	.align	2, 0
.L4:
	.word	Func_8000948
.Lfe1:
	.size	 OvlFunc_948_2008030,.Lfe1-OvlFunc_948_2008030
	.include "asm/maps/crossbone_isle_dungeon_4/ovl_30_a_a_a_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_948_20082a8
	.thumb_func
	.type	 OvlFunc_948_20082a8,function
OvlFunc_948_20082a8:
	push	{r5, r6, r7, lr}
	mov	r5, r0
	ldrh	r3, [r5, #6]
	ldr	r2, .L15
	lsr	r3, r3, #12
	lsl	r7, r3, #2
	ldr	r1, [r2, r7]
	ldr	r2, .L15+4
	ldr	r3, [r5, #8]
	and	r2, r2, r1
	sub	sp, sp, #12
	mov	r6, sp
	add	r3, r3, r2
	str	r3, [r6]
	ldr	r3, [r5, #12]
	str	r3, [r6, #4]
	ldr	r3, [r5, #16]
	lsl	r1, r1, #16
	add	r3, r3, r1
	mov	r0, r6
	mov	r1, r5
	str	r3, [r6, #8]
	bl	OvlFunc_948_200806c
	cmp	r0, #0
	beq	.L7
	ldr	r3, [r0, #80]
	ldr	r3, [r3, #40]
	mov	r2, #0
	ldrsh	r0, [r3, r2]
	ldr	r2, .L15+8
	mov	r1, #0
.L13:
	ldmia	r2!, {r3}
	cmp	r0, r3
	beq	.L12
	add	r1, r1, #1
	cmp	r1, #5
	bls	.L13
	mov	r3, #0
	str	r3, [r5, #36]
	str	r3, [r5, #44]
	mov	r3, #128
	lsl	r3, r3, #24
	str	r3, [r5, #56]
	str	r3, [r5, #64]
.L7:
	ldr	r3, .L15
	ldr	r2, .L15+4
	ldr	r1, [r3, r7]
	ldr	r3, [r5, #8]
	and	r2, r2, r1
	add	r3, r3, r2
	str	r3, [r6]
	ldr	r3, [r5, #12]
	str	r3, [r6, #4]
	ldr	r3, [r5, #16]
	lsl	r1, r1, #16
	add	r3, r3, r1
	mov	r0, r5
	mov	r1, r6
	str	r3, [r6, #8]
	bl	__TestCollision
	cmp	r0, #0
	ble	.L12
	mov	r3, #0
	str	r3, [r5, #36]
	str	r3, [r5, #44]
	mov	r3, #128
	lsl	r3, r3, #24
	str	r3, [r5, #56]
	str	r3, [r5, #64]
.L12:
	mov	r0, #0
	add	sp, sp, #12
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L16:
	.align	2, 0
.L15:
	.word	.Lm948_2644
	.word	-65536
	.word	.Lm948_2684
.Lfe2:
	.size	 OvlFunc_948_20082a8,.Lfe2-OvlFunc_948_20082a8
	.include "asm/maps/crossbone_isle_dungeon_4/ovl_30_a_a_a_c_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_948_2008474
	.thumb_func
	.type	 OvlFunc_948_2008474,function
OvlFunc_948_2008474:
	push	{r5, r6, r7, lr}
	mov	r7, fp
	mov	r6, sl
	mov	r5, r9
	push	{r5, r6, r7}
	mov	r7, r8
	push	{r7}
	mov	r6, r0
	sub	sp, sp, #32
	mov	r3, #0
	add	r0, sp, #16
	add	r1, r6, #4
	mov	r2, r6
	str	r3, [r6, #20]
	bl	OvlFunc_948_200834c
	mov	sl, r0
	cmp	r0, #0
	bne	.L18
	mov	r0, #0
	b	.L17
.L18:
	mov	r0, sl
	add	r0, r0, #34
	mov	r3, #2
	str	r0, [sp, #4]
	strb	r3, [r0]
	ldr	r3, [r6]
	mov	r1, #0
	str	r1, [sp, #12]
	ldr	r5, .L41
	lsl	r1, r3, #4
	add	r3, r1, #4
	ldr	r2, [r5, r3]
	cmp	r2, #0
	bge	.L19
	neg	r2, r2
.L19:
	mov	r3, r1
	add	r3, r3, #12
	ldr	r3, [r5, r3]
	cmp	r3, #0
	bge	.L20
	neg	r3, r3
.L20:
	add	r3, r2, r3
	asr	r3, r3, #4
	str	r3, [sp, #8]
	ldr	r2, [r5, r1]
	cmp	r2, #0
	bge	.L21
	neg	r2, r2
.L21:
	mov	r3, r1
	add	r3, r3, #8
	ldr	r3, [r5, r3]
	cmp	r3, #0
	bge	.L22
	neg	r3, r3
.L22:
	add	r3, r2, r3
	asr	r3, r3, #4
	mov	r9, r3
	ldr	r3, [sp, #16]
	ldr	r1, .L41+4
	add	r2, sp, #20
	lsl	r3, r3, #2
	mov	r8, r2
	ldr	r2, [r1, r3]
	ldr	r3, .L41+8
	mov	r4, sl
	and	r2, r2, r3
	ldr	r3, [r4, #8]
	mov	r0, r8
	add	r3, r3, r2
	str	r3, [r0]
	ldr	r0, [r4, #12]
	mov	r2, r8
	str	r0, [r2, #4]
	ldr	r3, [sp, #16]
	lsl	r3, r3, #2
	ldr	r2, [r1, r3]
	ldr	r3, [r4, #16]
	lsl	r2, r2, #16
	mov	r4, r8
	add	r3, r3, r2
	str	r3, [r4, #8]
	mov	r4, r6
	str	r0, [r6, #12]
	add	r4, r4, #8
	mov	fp, r8
.L23:
	ldr	r3, [r6]
	ldr	r0, .L41
	lsl	r3, r3, #4
	add	r3, r3, #4
	ldr	r2, [r0, r3]
	mov	r1, r8
	ldr	r3, [r1, #8]
	lsl	r2, r2, #16
	add	r3, r3, r2
	ldr	r2, [sp, #8]
	mov	r7, #0
	str	r3, [r6, #16]
	cmp	r7, r2
	bge	.L39
.L29:
	ldr	r3, [r6]
	ldr	r0, .L41
	lsl	r3, r3, #4
	ldr	r2, [r0, r3]
	mov	r1, r8
	ldr	r3, [r1]
	lsl	r2, r2, #16
	add	r3, r3, r2
	mov	r5, #0
	str	r3, [r6, #8]
	cmp	r5, r9
	bge	.L40
.L33:
	mov	r1, r4
	mov	r0, sl
	str	r4, [sp]
	bl	__TestCollision
	ldr	r4, [sp]
	cmp	r0, #2
	beq	.L35
	ldr	r3, [r4]
	mov	r2, #128
	lsl	r2, r2, #13
	add	r3, r3, r2
	add	r5, r5, #1
	str	r3, [r4]
	cmp	r5, r9
	blt	.L33
.L40:
	ldr	r3, [r6, #16]
	mov	r0, #128
	lsl	r0, r0, #13
	ldr	r1, [sp, #8]
	add	r3, r3, r0
	add	r7, r7, #1
	str	r3, [r6, #16]
	cmp	r7, r1
	blt	.L29
.L39:
	ldr	r2, [sp, #12]
	ldr	r3, [sp, #16]
	add	r2, r2, #1
	str	r2, [sp, #12]
	ldr	r0, .L41+4
	lsl	r3, r3, #2
	ldr	r2, [r0, r3]
	ldr	r3, .L41+8
	mov	r1, fp
	and	r2, r2, r3
	ldr	r3, [r1]
	add	r3, r3, r2
	str	r3, [r1]
	ldr	r3, [sp, #16]
	lsl	r3, r3, #2
	ldr	r2, [r0, r3]
	ldr	r3, [r1, #8]
	lsl	r2, r2, #16
	add	r3, r3, r2
	str	r3, [r1, #8]
	b	.L23
.L35:
	ldr	r2, [sp, #4]
	mov	r3, #0
	strb	r3, [r2]
	ldr	r3, [sp, #12]
	mov	r0, #0
	cmp	r3, #0
	beq	.L17
	ldr	r3, [sp, #16]
	ldr	r2, .L41+4
	lsl	r3, r3, #2
	ldr	r2, [r2, r3]
	ldr	r3, .L41+8
	ldr	r4, [sp, #12]
	and	r3, r3, r2
	mov	r1, r4
	mul	r1, r1, r3
	lsl	r2, r2, #16
	mul	r2, r2, r4
	mov	r0, sl
	ldr	r3, [r0, #8]
	add	r3, r3, r1
	str	r3, [r6, #8]
	ldr	r3, [r0, #12]
	str	r3, [r6, #12]
	ldr	r3, [r0, #16]
	add	r3, r3, r2
	str	r3, [r6, #16]
	mov	r0, #1
.L17:
	add	sp, sp, #32
	pop	{r3, r5, r6, r7}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	mov	fp, r7
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L42:
	.align	2, 0
.L41:
	.word	.Lm948_269c
	.word	.Lm948_2644
	.word	-65536
.Lfe3:
	.size	 OvlFunc_948_2008474,.Lfe3-OvlFunc_948_2008474
	.align	2, 0
	.global	OvlFunc_948_2008608
	.thumb_func
	.type	 OvlFunc_948_2008608,function
OvlFunc_948_2008608:
	sub	sp, sp, #16
	push	{r5, r6, r7, lr}
	mov	r7, fp
	mov	r6, sl
	mov	r5, r9
	push	{r5, r6, r7}
	mov	r7, r8
	push	{r7}
	sub	sp, sp, #40
	str	r0, [sp, #72]
	str	r1, [sp, #76]
	str	r2, [sp, #80]
	str	r3, [sp, #84]
	ldr	r3, .L53
	ldr	r3, [r3]
	mov	r0, #0
	str	r3, [sp, #12]
	bl	__MapActor_GetActor
	ldrh	r3, [r0, #6]
	ldr	r0, [sp, #76]
	lsr	r3, r3, #12
	mov	r8, r3
	bl	__MapActor_GetActor
	ldr	r3, [sp, #72]
	ldr	r4, .L53+4
	lsl	r1, r3, #4
	add	r3, r1, #4
	ldr	r2, [r4, r3]
	mov	r7, r0
	cmp	r2, #0
	bge	.L44
	neg	r2, r2
.L44:
	mov	r3, r1
	add	r3, r3, #12
	ldr	r3, [r4, r3]
	cmp	r3, #0
	bge	.L45
	neg	r3, r3
.L45:
	add	r3, r2, r3
	asr	r3, r3, #4
	str	r3, [sp, #8]
	ldr	r2, [r4, r1]
	cmp	r2, #0
	bge	.L46
	neg	r2, r2
.L46:
	mov	r3, r1
	add	r3, r3, #8
	ldr	r3, [r4, r3]
	cmp	r3, #0
	bge	.L47
	neg	r3, r3
.L47:
	add	r3, r2, r3
	asr	r3, r3, #4
	mov	r9, r3
	ldr	r5, .L53+8
	ldr	r3, [r7, #8]
	mov	r6, #128
	add	r0, sp, #28
	lsl	r6, r6, #8
	str	r6, [r7, #48]
	str	r5, [r7, #52]
	str	r3, [r0]
	ldr	r3, [r7, #16]
	str	r3, [r0, #8]
	ldr	r2, [sp, #72]
	lsl	r2, r2, #4
	ldr	r3, [r4, r2]
	ldr	r1, [r7, #8]
	lsl	r3, r3, #16
	add	r1, r1, r3
	mov	fp, r0
	add	r0, sp, #16
	str	r1, [r0]
	add	r2, r2, #4
	ldr	r3, [r4, r2]
	ldr	r2, [r7, #16]
	lsl	r3, r3, #16
	add	r2, r2, r3
	asr	r1, r1, #20
	asr	r2, r2, #20
	str	r1, [r0]
	str	r2, [r0, #8]
	ldr	r3, [sp, #8]
	str	r3, [sp]
	mov	r3, #0
	str	r3, [sp, #4]
	mov	r0, #0
	mov	r3, r9
	bl	OvlFunc_948_2008244
	mov	r2, r5
	mov	r0, #0
	mov	r1, r6
	bl	__MapActor_SetSpeed
	mov	r1, #8
	mov	r0, #0
	bl	__MapActor_SetAnim
	mov	r0, #15
	bl	__CutsceneWait
	mov	r4, fp
	ldr	r2, [sp, #80]
	ldr	r3, [r4]
	sub	r1, r2, r3
	cmp	r1, #0
	bge	.L48
	ldr	r0, .L53+12
	add	r1, r1, r0
.L48:
	mov	r4, fp
	ldr	r2, [sp, #88]
	ldr	r3, [r4, #8]
	sub	r2, r2, r3
	asr	r1, r1, #17
	cmp	r2, #0
	bge	.L49
	ldr	r0, .L53+12
	add	r2, r2, r0
.L49:
	asr	r2, r2, #17
	mov	r0, #0
	bl	__MapActor_TravelBy
	mov	r0, #0
	bl	__MapActor_GetActor
	ldr	r3, .L53+16
	str	r3, [r0, #108]
	mov	r0, #4
	bl	__CutsceneWait
	mov	r3, r8
	sub	r3, r3, #6
	cmp	r3, #7
	bhi	.L50
	mov	r0, r7
	mov	r1, #3
	bl	__Actor_SetAnim
	b	.L51
.L50:
	mov	r0, r7
	mov	r1, #2
	bl	__Actor_SetAnim
.L51:
	mov	r0, #239
	bl	__PlaySound
	mov	r0, r7
	ldr	r1, [sp, #80]
	ldr	r2, [sp, #84]
	ldr	r3, [sp, #88]
	bl	__Actor_TravelTo
	mov	r0, #0
	bl	__MapActor_WaitMovement
	mov	r0, #0
	mov	r1, #2
	bl	__MapActor_SetAnim
	mov	r0, #0
	ldr	r1, .L53+20
	ldr	r2, .L53+8
	.code	16
	bl	__MapActor_SetSpeed
	ldr	r2, .L53+24
	mov	r1, r8
	lsl	r3, r1, #2
	ldr	r0, [r2, r3]
	asr	r3, r0, #16
	lsl	r3, r3, #16
	lsl	r0, r0, #16
	asr	r1, r3, #16
	asr	r2, r0, #16
	lsr	r3, r3, #31
	lsr	r0, r0, #31
	add	r1, r1, r3
	add	r2, r2, r0
	asr	r1, r1, #1
	asr	r2, r2, #1
	mov	r0, #0
	bl	__MapActor_TravelBy
	ldr	r3, [sp, #92]
	cmp	r3, #0
	beq	.L52
	bl	_call_via_r3
.L52:
	mov	r0, #0
	bl	__MapActor_WaitMovement
	mov	r1, #1
	mov	r0, #0
	bl	__MapActor_SetAnim
	mov	r0, #0
	bl	__MapActor_GetActor
	mov	r2, #0
	str	r2, [r0, #108]
	mov	r0, r7
	bl	__Actor_WaitMovement
	mov	r0, #144
	lsl	r0, r0, #1
	bl	__PlaySound
	mov	r0, #213
	bl	__PlaySound
	ldr	r3, [sp, #80]
	str	r3, [r7, #8]
	ldr	r3, [sp, #88]
	str	r3, [r7, #16]
	mov	r3, #0
	str	r3, [r7, #36]
	str	r3, [r7, #44]
	mov	r0, r7
	mov	r1, #1
	bl	__Actor_SetAnim
	ldr	r2, [sp, #72]
	ldr	r4, .L53+4
	lsl	r2, r2, #4
	ldr	r3, [r4, r2]
	ldr	r0, [sp, #80]
	lsl	r3, r3, #16
	add	r2, r2, #4
	add	r0, r0, r3
	ldr	r3, [r4, r2]
	ldr	r1, [sp, #88]
	lsl	r3, r3, #16
	add	r1, r1, r3
	ldr	r2, [sp, #12]
	asr	r0, r0, #20
	asr	r1, r1, #20
	mov	sl, r4
	mov	r4, #158
	str	r0, [sp, #80]
	str	r1, [sp, #88]
	lsl	r4, r4, #1
	add	r3, r2, r4
	ldr	r3, [r3]
	mov	r8, r3
	mov	r2, r8
	asr	r2, r2, #20
	ldr	r4, [sp, #12]
	mov	r8, r2
	mov	r2, #160
	lsl	r2, r2, #1
	add	r3, r4, r2
	ldr	r6, [r3]
	mov	r4, r8
	asr	r6, r6, #20
	add	r3, r4, r0
	add	r2, r6, r1
	str	r3, [sp]
	str	r2, [sp, #4]
	ldr	r3, [sp, #8]
	mov	r2, r9
	bl	__Func_8010704
	ldr	r0, [sp, #8]
	ldr	r1, [sp, #80]
	ldr	r2, [sp, #88]
	str	r0, [sp]
	mov	r5, #255
	mov	r3, r9
	mov	r0, #0
	str	r5, [sp, #4]
	bl	OvlFunc_948_2008244
	ldr	r3, [sp, #8]
	ldr	r1, [sp, #80]
	ldr	r2, [sp, #88]
	str	r3, [sp]
	mov	r0, #2
	mov	r3, r9
	str	r5, [sp, #4]
	bl	OvlFunc_948_2008244
	ldr	r2, [sp, #72]
	mov	r4, sl
	lsl	r2, r2, #4
	ldr	r3, [r4, r2]
	mov	r0, fp
	ldr	r1, [r0]
	lsl	r3, r3, #16
	add	r2, r2, #4
	add	r1, r1, r3
	ldr	r3, [r4, r2]
	ldr	r2, [r0, #8]
	lsl	r3, r3, #16
	add	r2, r2, r3
	asr	r1, r1, #20
	asr	r2, r2, #20
	str	r1, [r0]
	str	r2, [r0, #8]
	add	r8, r8, r1
	add	r6, r6, r2
	str	r1, [sp]
	str	r2, [sp, #4]
	ldr	r3, [sp, #8]
	mov	r0, r8
	mov	r1, r6
	mov	r2, r9
	bl	__Func_8010704
	ldr	r3, [sp, #8]
	mov	r2, fp
	ldr	r1, [r2]
	mov	r4, #0
	ldr	r2, [r2, #8]
	mov	r0, #2
	str	r3, [sp]
	mov	r3, r9
	str	r4, [sp, #4]
	bl	OvlFunc_948_2008244
	bl	__MapActor_PlayPendingSound
	add	sp, sp, #40
	pop	{r3, r5, r6, r7}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	mov	fp, r7
	pop	{r5, r6, r7}
	pop	{r3}
	add	sp, sp, #16
	bx	r3
.L54:
	.align	2, 0
.L53:
	.word	iwram_3001e70
	.word	.Lm948_269c
	.word	6553
	.word	131071
	.word	OvlFunc_948_20082a8
	.word	19660
	.word	.Lm948_2644
.Lfe4:
	.size	 OvlFunc_948_2008608,.Lfe4-OvlFunc_948_2008608
	.include "asm/maps/crossbone_isle_dungeon_4/ovl_30_a_a_a_c_c_c_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_948_20089dc
	.thumb_func
	.type	 OvlFunc_948_20089dc,function
OvlFunc_948_20089dc:
	push	{lr}
	mov	r0, #15
	mov	r1, #0
	mov	r2, #6
	bl	__Func_80955b0
	pop	{r0}
	bx	r0
.Lfe5:
	.size	 OvlFunc_948_20089dc,.Lfe5-OvlFunc_948_20089dc
	.align	2, 0
	.global	OvlFunc_948_20089ec
	.thumb_func
	.type	 OvlFunc_948_20089ec,function
OvlFunc_948_20089ec:
	bx	lr
.Lfe6:
	.size	 OvlFunc_948_20089ec,.Lfe6-OvlFunc_948_20089ec
	.include "asm/maps/crossbone_isle_dungeon_4/ovl_30_a_c.s"
	.text

	.code	16
	.align	2, 0
	.global	CrossboneIsleDungeon4_GetSpecialExits
	.thumb_func
	.type	 CrossboneIsleDungeon4_GetSpecialExits,function
CrossboneIsleDungeon4_GetSpecialExits:
	mov	r0, #0
	bx	lr
.Lfe7:
	.size	 CrossboneIsleDungeon4_GetSpecialExits,.Lfe7-CrossboneIsleDungeon4_GetSpecialExits
	.align	2, 0
	.global	CrossboneIsleDungeon4_GetExits
	.thumb_func
	.type	 CrossboneIsleDungeon4_GetExits,function
CrossboneIsleDungeon4_GetExits:
	ldr	r0, .L59
	bx	lr
.L60:
	.align	2, 0
.L59:
	.word	gOvl_0200a970
.Lfe8:
	.size	 CrossboneIsleDungeon4_GetExits,.Lfe8-CrossboneIsleDungeon4_GetExits
	.include "asm/maps/crossbone_isle_dungeon_4/ovl_30_c_a_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_948_2008aa4
	.thumb_func
	.type	 OvlFunc_948_2008aa4,function
OvlFunc_948_2008aa4:
	bx	lr
.Lfe9:
	.size	 OvlFunc_948_2008aa4,.Lfe9-OvlFunc_948_2008aa4
	.align	2, 0
	.global	OvlFunc_948_2008aa8
	.thumb_func
	.type	 OvlFunc_948_2008aa8,function
OvlFunc_948_2008aa8:
	push	{r5, lr}
	mov	r5, r0
	mov	r0, #0
	bl	__MapActor_GetActor
	mov	r2, r0
	ldr	r3, [r5, #16]
	ldr	r0, [r2, #16]
	ldr	r1, [r2, #8]
	sub	r0, r0, r3
	ldr	r3, [r5, #8]
	sub	r1, r1, r3
	bl	__atan2
	strh	r0, [r5, #6]
	mov	r0, #0
	pop	{r5}
	pop	{r1}
	bx	r1
.Lfe10:
	.size	 OvlFunc_948_2008aa8,.Lfe10-OvlFunc_948_2008aa8
	.include "asm/maps/crossbone_isle_dungeon_4/ovl_30_c_a_c_c_a_a_a_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_948_2008e50
	.thumb_func
	.type	 OvlFunc_948_2008e50,function
OvlFunc_948_2008e50:
	push	{r5, r6, lr}
	ldr	r3, .L66
	ldr	r0, .L66+4
	ldr	r5, [r3]
	bl	__GetFlag
	cmp	r0, #0
	beq	.L64
	ldr	r2, .L66+8
	ldr	r3, .L66+12
	add	r3, r3, r2
	mov	r2, #0
	ldrsh	r3, [r3, r2]
	cmp	r3, #15
	beq	.L64
	mov	r2, #182
	lsl	r2, r2, #1
	add	r3, r5, r2
	mov	r0, #15
	mov	r2, #0
	ldrsh	r5, [r3, r2]
	bl	__MapActor_GetActor
	mov	r6, r0
	mov	r0, #0
	bl	__MapActor_GetActor
	ldr	r3, [r0, #48]
	mov	r0, #15
	str	r3, [r6, #48]
	bl	__MapActor_GetActor
	mov	r6, r0
	mov	r0, #0
	bl	__MapActor_GetActor
	ldr	r3, [r0, #48]
	sub	r5, r5, #30
	str	r3, [r6, #52]
	ldr	r2, .L66+16
	lsl	r5, r5, #3
	add	r3, r5, #4
	ldr	r1, [r2, r5]
	mov	r0, #15
	ldr	r2, [r2, r3]
	bl	__MapActor_TravelToAnim
.L64:
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L67:
	.align	2, 0
.L66:
	.word	iwram_3001ebc
	.word	2506
	.word	586
	.word	gState
	.word	.Lm948_2808
.Lfe11:
	.size	 OvlFunc_948_2008e50,.Lfe11-OvlFunc_948_2008e50
	.include "asm/maps/crossbone_isle_dungeon_4/ovl_30_c_a_c_c_a_a_a_c_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_948_2008f34
	.thumb_func
	.type	 OvlFunc_948_2008f34,function
OvlFunc_948_2008f34:
	push	{lr}
	bl	__Func_8093c00
	pop	{r0}
	bx	r0
.Lfe12:
	.size	 OvlFunc_948_2008f34,.Lfe12-OvlFunc_948_2008f34
	.include "asm/maps/crossbone_isle_dungeon_4/ovl_30_c_a_c_c_a_a_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_948_2009108
	.thumb_func
	.type	 OvlFunc_948_2009108,function
OvlFunc_948_2009108:
	push	{lr}
	mov	r0, #0
	bl	OvlFunc_948_20090b8
	pop	{r0}
	bx	r0
.Lfe13:
	.size	 OvlFunc_948_2009108,.Lfe13-OvlFunc_948_2009108
	.align	2, 0
	.global	OvlFunc_948_2009114
	.thumb_func
	.type	 OvlFunc_948_2009114,function
OvlFunc_948_2009114:
	push	{lr}
	mov	r0, #1
	bl	OvlFunc_948_20090b8
	pop	{r0}
	bx	r0
.Lfe14:
	.size	 OvlFunc_948_2009114,.Lfe14-OvlFunc_948_2009114
	.include "asm/maps/crossbone_isle_dungeon_4/ovl_30_c_a_c_c_a_a_c_c_c_a_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_948_2009198
	.thumb_func
	.type	 OvlFunc_948_2009198,function
OvlFunc_948_2009198:
	push	{lr}
	sub	sp, sp, #8
	mov	r3, #25
	mov	r2, #48
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #25
	mov	r1, #45
	mov	r2, #1
	mov	r3, #2
	bl	__Func_80105d4
	ldr	r0, .L73
	bl	__GetFlag
	cmp	r0, #0
	bne	.L72
	mov	r1, #204
	mov	r2, #194
	mov	r0, #12
	lsl	r1, r1, #17
	lsl	r2, r2, #18
	bl	__MapActor_SetPos
.L72:
	mov	r0, #1
	bl	__CutsceneWait
	add	sp, sp, #8
	pop	{r0}
	bx	r0
.L74:
	.align	2, 0
.L73:
	.word	3819
.Lfe15:
	.size	 OvlFunc_948_2009198,.Lfe15-OvlFunc_948_2009198
	.include "asm/maps/crossbone_isle_dungeon_4/ovl_30_c_a_c_c_a_a_c_c_c_a_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_948_2009204
	.thumb_func
	.type	 OvlFunc_948_2009204,function
OvlFunc_948_2009204:
	push	{lr}
	mov	r0, #244
	mov	r1, #3
	bl	__Func_808f1c0
	mov	r0, #0
	mov	r1, #1
	bl	__MapActor_SetAnim
	mov	r1, #0
	mov	r0, #244
	bl	__Func_8091a58
	mov	r0, #8
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	ldr	r0, .L88
	bl	__SetFlag
	pop	{r0}
	bx	r0
.L89:
	.align	2, 0
.L88:
	.word	3815
.Lfe16:
	.size	 OvlFunc_948_2009204,.Lfe16-OvlFunc_948_2009204
	.align	2, 0
	.global	OvlFunc_948_2009238
	.thumb_func
	.type	 OvlFunc_948_2009238,function
OvlFunc_948_2009238:
	push	{lr}
	mov	r0, #244
	mov	r1, #3
	bl	__Func_808f1c0
	mov	r0, #0
	mov	r1, #1
	bl	__MapActor_SetAnim
	mov	r1, #0
	mov	r0, #244
	bl	__Func_8091a58
	mov	r0, #9
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	ldr	r0, .L103
	bl	__SetFlag
	pop	{r0}
	bx	r0
.L104:
	.align	2, 0
.L103:
	.word	3816
.Lfe17:
	.size	 OvlFunc_948_2009238,.Lfe17-OvlFunc_948_2009238
	.align	2, 0
	.global	OvlFunc_948_200926c
	.thumb_func
	.type	 OvlFunc_948_200926c,function
OvlFunc_948_200926c:
	push	{lr}
	mov	r0, #244
	mov	r1, #3
	bl	__Func_808f1c0
	mov	r0, #0
	mov	r1, #1
	bl	__MapActor_SetAnim
	mov	r1, #0
	mov	r0, #244
	bl	__Func_8091a58
	mov	r0, #10
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	ldr	r0, .L118
	bl	__SetFlag
	pop	{r0}
	bx	r0
.L119:
	.align	2, 0
.L118:
	.word	3817
.Lfe18:
	.size	 OvlFunc_948_200926c,.Lfe18-OvlFunc_948_200926c
	.align	2, 0
	.global	OvlFunc_948_20092a0
	.thumb_func
	.type	 OvlFunc_948_20092a0,function
OvlFunc_948_20092a0:
	push	{lr}
	mov	r0, #244
	mov	r1, #3
	bl	__Func_808f1c0
	mov	r0, #0
	mov	r1, #1
	bl	__MapActor_SetAnim
	mov	r1, #0
	mov	r0, #244
	bl	__Func_8091a58
	mov	r0, #11
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	ldr	r0, .L133
	bl	__SetFlag
	pop	{r0}
	bx	r0
.L134:
	.align	2, 0
.L133:
	.word	3818
.Lfe19:
	.size	 OvlFunc_948_20092a0,.Lfe19-OvlFunc_948_20092a0
	.align	2, 0
	.global	OvlFunc_948_20092d4
	.thumb_func
	.type	 OvlFunc_948_20092d4,function
OvlFunc_948_20092d4:
	push	{lr}
	mov	r0, #243
	mov	r1, #3
	bl	__Func_808f1c0
	mov	r0, #0
	mov	r1, #1
	bl	__MapActor_SetAnim
	mov	r1, #0
	mov	r0, #243
	bl	__Func_8091a58
	mov	r0, #12
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	ldr	r0, .L148
	bl	__SetFlag
	pop	{r0}
	bx	r0
.L149:
	.align	2, 0
.L148:
	.word	3819
.Lfe20:
	.size	 OvlFunc_948_20092d4,.Lfe20-OvlFunc_948_20092d4
	.include "asm/maps/crossbone_isle_dungeon_4/ovl_30_c_a_c_c_a_a_c_c_c_a_c_c_c_c_c_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_948_20095cc
	.thumb_func
	.type	 OvlFunc_948_20095cc,function
OvlFunc_948_20095cc:
	push	{lr}
	mov	r0, #0
	bl	OvlFunc_948_200952c
	pop	{r0}
	bx	r0
.Lfe21:
	.size	 OvlFunc_948_20095cc,.Lfe21-OvlFunc_948_20095cc
	.align	2, 0
	.global	OvlFunc_948_20095d8
	.thumb_func
	.type	 OvlFunc_948_20095d8,function
OvlFunc_948_20095d8:
	push	{lr}
	mov	r0, #1
	bl	OvlFunc_948_200952c
	pop	{r0}
	bx	r0
.Lfe22:
	.size	 OvlFunc_948_20095d8,.Lfe22-OvlFunc_948_20095d8
	.align	2, 0
	.global	OvlFunc_948_20095e4
	.thumb_func
	.type	 OvlFunc_948_20095e4,function
OvlFunc_948_20095e4:
	push	{lr}
	mov	r0, #2
	bl	OvlFunc_948_200952c
	pop	{r0}
	bx	r0
.Lfe23:
	.size	 OvlFunc_948_20095e4,.Lfe23-OvlFunc_948_20095e4
	.include "asm/maps/crossbone_isle_dungeon_4/ovl_30_c_a_c_c_a_a_c_c_c_c_c_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_948_20098c0
	.thumb_func
	.type	 OvlFunc_948_20098c0,function
OvlFunc_948_20098c0:
	ldr	r3, .L154
	mov	r2, #208
	lsl	r2, r2, #4
	strh	r2, [r3]
	bx	lr
.L155:
	.align	2, 0
.L154:
	.word	67108946
.Lfe24:
	.size	 OvlFunc_948_20098c0,.Lfe24-OvlFunc_948_20098c0
	.align	2, 0
	.global	OvlFunc_948_20098d0
	.thumb_func
	.type	 OvlFunc_948_20098d0,function
OvlFunc_948_20098d0:
	ldr	r2, .L157
	ldr	r3, .L157+4
	strh	r2, [r3]
	bx	lr
.L158:
	.align	2, 0
.L157:
	.word	1543
	.word	67108946
.Lfe25:
	.size	 OvlFunc_948_20098d0,.Lfe25-OvlFunc_948_20098d0
	.include "asm/maps/crossbone_isle_dungeon_4/ovl_30_c_a_c_c_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_948_2009980
	.thumb_func
	.type	 OvlFunc_948_2009980,function
OvlFunc_948_2009980:
	bx	lr
.Lfe26:
	.size	 OvlFunc_948_2009980,.Lfe26-OvlFunc_948_2009980
	.align	2, 0
	.global	OvlFunc_948_2009984
	.thumb_func
	.type	 OvlFunc_948_2009984,function
OvlFunc_948_2009984:
	push	{r5, lr}
	mov	r0, #13
	sub	sp, sp, #8
	bl	__MapActor_GetActor
	mov	r3, #40
	mov	r2, #55
	mov	r5, r0
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #40
	mov	r1, #54
	mov	r2, #1
	mov	r3, #1
	bl	__Func_8010704
	cmp	r5, #0
	beq	.L161
	mov	r0, #13
	bl	__MapActor_GetActor
	mov	r3, #0
	add	r0, r0, #85
	mov	r2, r5
	strb	r3, [r0]
	add	r2, r2, #35
	mov	r3, #2
	strb	r3, [r2]
.L161:
	mov	r0, #128
	lsl	r0, r0, #2
	bl	__SetFlag
	add	sp, sp, #8
	pop	{r5}
	pop	{r0}
	bx	r0
.Lfe27:
	.size	 OvlFunc_948_2009984,.Lfe27-OvlFunc_948_2009984
	.align	2, 0
	.global	OvlFunc_948_20099cc
	.thumb_func
	.type	 OvlFunc_948_20099cc,function
OvlFunc_948_20099cc:
	push	{lr}
	mov	r0, #0
	bl	__MapActor_GetActor
	ldrh	r3, [r0, #6]
	cmp	r3, #0
	bne	.L163
	bl	__Func_8093c00
	b	.L164
.L163:
	bl	OvlFunc_948_2009b60
.L164:
	pop	{r0}
	bx	r0
.Lfe28:
	.size	 OvlFunc_948_20099cc,.Lfe28-OvlFunc_948_20099cc
	.include "asm/maps/crossbone_isle_dungeon_4/ovl_30_c_c_a_a_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_948_2009a48
	.thumb_func
	.type	 OvlFunc_948_2009a48,function
OvlFunc_948_2009a48:
	push	{lr}
	sub	sp, sp, #8
	mov	r3, #42
	str	r3, [sp]
	str	r3, [sp, #4]
	mov	r1, #41
	mov	r2, #1
	mov	r3, #1
	mov	r0, #58
	bl	__Func_8010704
	mov	r0, #8
	bl	__MapActor_GetActor
	mov	r3, #2
	add	r0, r0, #35
	strb	r3, [r0]
	add	sp, sp, #8
	pop	{r0}
	bx	r0
.Lfe29:
	.size	 OvlFunc_948_2009a48,.Lfe29-OvlFunc_948_2009a48
	.include "asm/maps/crossbone_isle_dungeon_4/ovl_30_c_c_a_a_c_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_948_2009c28
	.thumb_func
	.type	 OvlFunc_948_2009c28,function
OvlFunc_948_2009c28:
	push	{lr}
	mov	r0, #9
	bl	__MapActor_GetActor
	ldr	r3, [r0, #8]
	cmp	r3, #0
	bge	.L167
	ldr	r2, .L170
	add	r3, r3, r2
.L167:
	ldr	r0, [r0, #16]
	asr	r3, r3, #20
	cmp	r0, #0
	bge	.L168
	ldr	r2, .L170
	add	r0, r0, r2
.L168:
	asr	r0, r0, #20
	cmp	r3, #45
	bne	.L169
	cmp	r0, #43
	bne	.L169
	bl	OvlFunc_948_2009bc4
.L169:
	pop	{r0}
	bx	r0
.L171:
	.align	2, 0
.L170:
	.word	1048575
.Lfe30:
	.size	 OvlFunc_948_2009c28,.Lfe30-OvlFunc_948_2009c28
	.align	2, 0
	.global	OvlFunc_948_2009c5c
	.thumb_func
	.type	 OvlFunc_948_2009c5c,function
OvlFunc_948_2009c5c:
	push	{lr}
	bl	OvlFunc_948_20080c4
	bl	OvlFunc_948_2009c28
	pop	{r0}
	bx	r0
.Lfe31:
	.size	 OvlFunc_948_2009c5c,.Lfe31-OvlFunc_948_2009c5c
	.include "asm/maps/crossbone_isle_dungeon_4/ovl_30_c_c_a_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_948_2009d64
	.thumb_func
	.type	 OvlFunc_948_2009d64,function
OvlFunc_948_2009d64:
	push	{lr}
	bl	OvlFunc_948_2009c6c
	bl	OvlFunc_948_20080c4
	bl	OvlFunc_948_2009cf8
	pop	{r0}
	bx	r0
.Lfe32:
	.size	 OvlFunc_948_2009d64,.Lfe32-OvlFunc_948_2009d64
	.align	2, 0
	.global	OvlFunc_948_2009d78
	.thumb_func
	.type	 OvlFunc_948_2009d78,function
OvlFunc_948_2009d78:
	push	{lr}
	mov	r0, #0
	bl	__MapActor_GetActor
	mov	r2, #128
	ldrh	r3, [r0, #6]
	lsl	r2, r2, #7
	cmp	r3, r2
	bne	.L175
	mov	r0, #0
	mov	r1, #6
	mov	r2, #0
	bl	__Func_8092708
	b	.L176
.L175:
	bl	OvlFunc_948_2009d64
.L176:
	pop	{r0}
	bx	r0
.Lfe33:
	.size	 OvlFunc_948_2009d78,.Lfe33-OvlFunc_948_2009d78
	.include "asm/maps/crossbone_isle_dungeon_4/ovl_30_c_c_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_948_2009e54
	.thumb_func
	.type	 OvlFunc_948_2009e54,function
OvlFunc_948_2009e54:
	push	{lr}
	bl	OvlFunc_948_2009df8
	pop	{r0}
	bx	r0
.Lfe34:
	.size	 OvlFunc_948_2009e54,.Lfe34-OvlFunc_948_2009e54
	.align	2, 0
	.global	OvlFunc_948_2009e60
	.thumb_func
	.type	 OvlFunc_948_2009e60,function
OvlFunc_948_2009e60:
	push	{lr}
	bl	OvlFunc_948_2009da0
	bl	OvlFunc_948_20080c4
	bl	OvlFunc_948_2009e54
	pop	{r0}
	bx	r0
.Lfe35:
	.size	 OvlFunc_948_2009e60,.Lfe35-OvlFunc_948_2009e60
	.align	2, 0
	.global	OvlFunc_948_2009e74
	.thumb_func
	.type	 OvlFunc_948_2009e74,function
OvlFunc_948_2009e74:
	push	{lr}
	bl	OvlFunc_948_2009df8
	pop	{r0}
	bx	r0
.Lfe36:
	.size	 OvlFunc_948_2009e74,.Lfe36-OvlFunc_948_2009e74
	.align	2, 0
	.global	OvlFunc_948_2009e80
	.thumb_func
	.type	 OvlFunc_948_2009e80,function
OvlFunc_948_2009e80:
	push	{lr}
	bl	OvlFunc_948_2009da0
	bl	OvlFunc_948_20080c4
	bl	OvlFunc_948_2009e74
	pop	{r0}
	bx	r0
.Lfe37:
	.size	 OvlFunc_948_2009e80,.Lfe37-OvlFunc_948_2009e80
	.align	2, 0
	.global	OvlFunc_948_2009e94
	.thumb_func
	.type	 OvlFunc_948_2009e94,function
OvlFunc_948_2009e94:
	push	{r5, lr}
	mov	r0, #14
	bl	__MapActor_GetActor
	mov	r5, r0
	mov	r0, #9
	bl	__MapActor_GetActor
	mov	r3, #128
	lsl	r3, r3, #14
	str	r3, [r5, #12]
	ldr	r3, [r0, #8]
	str	r3, [r5, #8]
	mov	r2, #128
	ldr	r3, [r0, #16]
	lsl	r2, r2, #9
	add	r3, r3, r2
	str	r3, [r5, #16]
	pop	{r5}
	pop	{r0}
	bx	r0
.Lfe38:
	.size	 OvlFunc_948_2009e94,.Lfe38-OvlFunc_948_2009e94
	.align	2, 0
	.global	OvlFunc_948_2009ec0
	.thumb_func
	.type	 OvlFunc_948_2009ec0,function
OvlFunc_948_2009ec0:
	push	{lr}
	mov	r0, #9
	bl	__MapActor_GetActor
	mov	r3, #128
	ldr	r2, [r0, #16]
	lsl	r3, r3, #9
	ldr	r1, [r0, #8]
	add	r2, r2, r3
	mov	r0, #107
	bl	__Func_808edac
	pop	{r0}
	bx	r0
.Lfe39:
	.size	 OvlFunc_948_2009ec0,.Lfe39-OvlFunc_948_2009ec0
	.include "asm/maps/crossbone_isle_dungeon_4/ovl_30_c_c_c_c_c_c_c_c.s"
	.text

	.include "asm/maps/crossbone_isle_dungeon_4/imports.s"
	.text


	.text
	.align	2, 0
