@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"crossbone_isle_dungeon_2.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_947_2008314
	.thumb_func
	.type	 OvlFunc_947_2008314,function
OvlFunc_947_2008314:
	push	{r5, lr}
	ldmia	r0!, {r5}
	ldmia	r1!, {r3}
	ldmia	r0!, {r4}
	sub	r5, r5, r3
	ldmia	r1!, {r3}
	ldr	r2, [r1]
	sub	r4, r4, r3
	ldr	r3, [r0]
	sub	r3, r3, r2
	asr	r5, r5, #16
	asr	r4, r4, #16
	asr	r3, r3, #16
	mov	r0, r5
	mul	r0, r0, r5
	mov	r2, r4
	mul	r2, r2, r4
	mov	r1, r3
	mul	r1, r1, r3
	add	r0, r0, r2
	mov	r3, r1
	add	r0, r0, r3
	ldr	r3, .L4
	bl	_call_via_r3
	pop	{r5}
	pop	{r1}
	bx	r1
.L5:
	.align	2, 0
.L4:
	.word	Func_8000948
.Lfe1:
	.size	 OvlFunc_947_2008314,.Lfe1-OvlFunc_947_2008314
	.include "asm/maps/crossbone_isle_dungeon_2/ovl_314_a_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_947_200858c
	.thumb_func
	.type	 OvlFunc_947_200858c,function
OvlFunc_947_200858c:
	push	{r5, r6, r7, lr}
	mov	r5, r0
	ldrh	r3, [r5, #6]
	ldr	r2, .L15
	lsr	r3, r3, #12
	lsl	r7, r3, #2
	ldr	r1, [r2, r7]
	ldr	r2, .L15+4
	ldr	r3, [r5, #8]
	and	r2, r2, r1
	sub	sp, sp, #12
	mov	r6, sp
	add	r3, r3, r2
	str	r3, [r6]
	ldr	r3, [r5, #12]
	str	r3, [r6, #4]
	ldr	r3, [r5, #16]
	lsl	r1, r1, #16
	add	r3, r3, r1
	mov	r0, r6
	mov	r1, r5
	str	r3, [r6, #8]
	bl	OvlFunc_947_2008350
	cmp	r0, #0
	beq	.L7
	ldr	r3, [r0, #80]
	ldr	r3, [r3, #40]
	mov	r2, #0
	ldrsh	r0, [r3, r2]
	ldr	r2, .L15+8
	mov	r1, #0
.L13:
	ldmia	r2!, {r3}
	cmp	r0, r3
	beq	.L12
	add	r1, r1, #1
	cmp	r1, #5
	bls	.L13
	mov	r3, #0
	str	r3, [r5, #36]
	str	r3, [r5, #44]
	mov	r3, #128
	lsl	r3, r3, #24
	str	r3, [r5, #56]
	str	r3, [r5, #64]
.L7:
	ldr	r3, .L15
	ldr	r2, .L15+4
	ldr	r1, [r3, r7]
	ldr	r3, [r5, #8]
	and	r2, r2, r1
	add	r3, r3, r2
	str	r3, [r6]
	ldr	r3, [r5, #12]
	str	r3, [r6, #4]
	ldr	r3, [r5, #16]
	lsl	r1, r1, #16
	add	r3, r3, r1
	mov	r0, r5
	mov	r1, r6
	str	r3, [r6, #8]
	bl	__TestCollision
	cmp	r0, #0
	ble	.L12
	mov	r3, #0
	str	r3, [r5, #36]
	str	r3, [r5, #44]
	mov	r3, #128
	lsl	r3, r3, #24
	str	r3, [r5, #56]
	str	r3, [r5, #64]
.L12:
	mov	r0, #0
	add	sp, sp, #12
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L16:
	.align	2, 0
.L15:
	.word	.Lm947_2ca0
	.word	-65536
	.word	.Lm947_2ce0
.Lfe2:
	.size	 OvlFunc_947_200858c,.Lfe2-OvlFunc_947_200858c
	.include "asm/maps/crossbone_isle_dungeon_2/ovl_314_a_c_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_947_2008758
	.thumb_func
	.type	 OvlFunc_947_2008758,function
OvlFunc_947_2008758:
	push	{r5, r6, r7, lr}
	mov	r7, fp
	mov	r6, sl
	mov	r5, r9
	push	{r5, r6, r7}
	mov	r7, r8
	push	{r7}
	mov	r6, r0
	sub	sp, sp, #32
	mov	r3, #0
	add	r0, sp, #16
	add	r1, r6, #4
	mov	r2, r6
	str	r3, [r6, #20]
	bl	OvlFunc_947_2008630
	mov	sl, r0
	cmp	r0, #0
	bne	.L18
	mov	r0, #0
	b	.L17
.L18:
	mov	r0, sl
	add	r0, r0, #34
	mov	r3, #2
	str	r0, [sp, #4]
	strb	r3, [r0]
	ldr	r3, [r6]
	mov	r1, #0
	str	r1, [sp, #12]
	ldr	r5, .L41
	lsl	r1, r3, #4
	add	r3, r1, #4
	ldr	r2, [r5, r3]
	cmp	r2, #0
	bge	.L19
	neg	r2, r2
.L19:
	mov	r3, r1
	add	r3, r3, #12
	ldr	r3, [r5, r3]
	cmp	r3, #0
	bge	.L20
	neg	r3, r3
.L20:
	add	r3, r2, r3
	asr	r3, r3, #4
	str	r3, [sp, #8]
	ldr	r2, [r5, r1]
	cmp	r2, #0
	bge	.L21
	neg	r2, r2
.L21:
	mov	r3, r1
	add	r3, r3, #8
	ldr	r3, [r5, r3]
	cmp	r3, #0
	bge	.L22
	neg	r3, r3
.L22:
	add	r3, r2, r3
	asr	r3, r3, #4
	mov	r9, r3
	ldr	r3, [sp, #16]
	ldr	r1, .L41+4
	add	r2, sp, #20
	lsl	r3, r3, #2
	mov	r8, r2
	ldr	r2, [r1, r3]
	ldr	r3, .L41+8
	mov	r4, sl
	and	r2, r2, r3
	ldr	r3, [r4, #8]
	mov	r0, r8
	add	r3, r3, r2
	str	r3, [r0]
	ldr	r0, [r4, #12]
	mov	r2, r8
	str	r0, [r2, #4]
	ldr	r3, [sp, #16]
	lsl	r3, r3, #2
	ldr	r2, [r1, r3]
	ldr	r3, [r4, #16]
	lsl	r2, r2, #16
	mov	r4, r8
	add	r3, r3, r2
	str	r3, [r4, #8]
	mov	r4, r6
	str	r0, [r6, #12]
	add	r4, r4, #8
	mov	fp, r8
.L23:
	ldr	r3, [r6]
	ldr	r0, .L41
	lsl	r3, r3, #4
	add	r3, r3, #4
	ldr	r2, [r0, r3]
	mov	r1, r8
	ldr	r3, [r1, #8]
	lsl	r2, r2, #16
	add	r3, r3, r2
	ldr	r2, [sp, #8]
	mov	r7, #0
	str	r3, [r6, #16]
	cmp	r7, r2
	bge	.L39
.L29:
	ldr	r3, [r6]
	ldr	r0, .L41
	lsl	r3, r3, #4
	ldr	r2, [r0, r3]
	mov	r1, r8
	ldr	r3, [r1]
	lsl	r2, r2, #16
	add	r3, r3, r2
	mov	r5, #0
	str	r3, [r6, #8]
	cmp	r5, r9
	bge	.L40
.L33:
	mov	r1, r4
	mov	r0, sl
	str	r4, [sp]
	bl	__TestCollision
	ldr	r4, [sp]
	cmp	r0, #2
	beq	.L35
	ldr	r3, [r4]
	mov	r2, #128
	lsl	r2, r2, #13
	add	r3, r3, r2
	add	r5, r5, #1
	str	r3, [r4]
	cmp	r5, r9
	blt	.L33
.L40:
	ldr	r3, [r6, #16]
	mov	r0, #128
	lsl	r0, r0, #13
	ldr	r1, [sp, #8]
	add	r3, r3, r0
	add	r7, r7, #1
	str	r3, [r6, #16]
	cmp	r7, r1
	blt	.L29
.L39:
	ldr	r2, [sp, #12]
	ldr	r3, [sp, #16]
	add	r2, r2, #1
	str	r2, [sp, #12]
	ldr	r0, .L41+4
	lsl	r3, r3, #2
	ldr	r2, [r0, r3]
	ldr	r3, .L41+8
	mov	r1, fp
	and	r2, r2, r3
	ldr	r3, [r1]
	add	r3, r3, r2
	str	r3, [r1]
	ldr	r3, [sp, #16]
	lsl	r3, r3, #2
	ldr	r2, [r0, r3]
	ldr	r3, [r1, #8]
	lsl	r2, r2, #16
	add	r3, r3, r2
	str	r3, [r1, #8]
	b	.L23
.L35:
	ldr	r2, [sp, #4]
	mov	r3, #0
	strb	r3, [r2]
	ldr	r3, [sp, #12]
	mov	r0, #0
	cmp	r3, #0
	beq	.L17
	ldr	r3, [sp, #16]
	ldr	r2, .L41+4
	lsl	r3, r3, #2
	ldr	r2, [r2, r3]
	ldr	r3, .L41+8
	ldr	r4, [sp, #12]
	and	r3, r3, r2
	mov	r1, r4
	mul	r1, r1, r3
	lsl	r2, r2, #16
	mul	r2, r2, r4
	mov	r0, sl
	ldr	r3, [r0, #8]
	add	r3, r3, r1
	str	r3, [r6, #8]
	ldr	r3, [r0, #12]
	str	r3, [r6, #12]
	ldr	r3, [r0, #16]
	add	r3, r3, r2
	str	r3, [r6, #16]
	mov	r0, #1
.L17:
	add	sp, sp, #32
	pop	{r3, r5, r6, r7}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	mov	fp, r7
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L42:
	.align	2, 0
.L41:
	.word	gScript_884__0200acf8
	.word	.Lm947_2ca0
	.word	-65536
.Lfe3:
	.size	 OvlFunc_947_2008758,.Lfe3-OvlFunc_947_2008758
	.align	2, 0
	.global	OvlFunc_947_20088ec
	.thumb_func
	.type	 OvlFunc_947_20088ec,function
OvlFunc_947_20088ec:
	sub	sp, sp, #16
	push	{r5, r6, r7, lr}
	mov	r7, fp
	mov	r6, sl
	mov	r5, r9
	push	{r5, r6, r7}
	mov	r7, r8
	push	{r7}
	sub	sp, sp, #40
	str	r0, [sp, #72]
	str	r1, [sp, #76]
	str	r2, [sp, #80]
	str	r3, [sp, #84]
	ldr	r3, .L53
	ldr	r3, [r3]
	mov	r0, #0
	str	r3, [sp, #12]
	bl	__MapActor_GetActor
	ldrh	r3, [r0, #6]
	ldr	r0, [sp, #76]
	lsr	r3, r3, #12
	mov	r8, r3
	bl	__MapActor_GetActor
	ldr	r3, [sp, #72]
	ldr	r4, .L53+4
	lsl	r1, r3, #4
	add	r3, r1, #4
	ldr	r2, [r4, r3]
	mov	r7, r0
	cmp	r2, #0
	bge	.L44
	neg	r2, r2
.L44:
	mov	r3, r1
	add	r3, r3, #12
	ldr	r3, [r4, r3]
	cmp	r3, #0
	bge	.L45
	neg	r3, r3
.L45:
	add	r3, r2, r3
	asr	r3, r3, #4
	str	r3, [sp, #8]
	ldr	r2, [r4, r1]
	cmp	r2, #0
	bge	.L46
	neg	r2, r2
.L46:
	mov	r3, r1
	add	r3, r3, #8
	ldr	r3, [r4, r3]
	cmp	r3, #0
	bge	.L47
	neg	r3, r3
.L47:
	add	r3, r2, r3
	asr	r3, r3, #4
	mov	r9, r3
	ldr	r5, .L53+8
	ldr	r3, [r7, #8]
	mov	r6, #128
	add	r0, sp, #28
	lsl	r6, r6, #8
	str	r6, [r7, #48]
	str	r5, [r7, #52]
	str	r3, [r0]
	ldr	r3, [r7, #16]
	str	r3, [r0, #8]
	ldr	r2, [sp, #72]
	lsl	r2, r2, #4
	ldr	r3, [r4, r2]
	ldr	r1, [r7, #8]
	lsl	r3, r3, #16
	add	r1, r1, r3
	mov	fp, r0
	add	r0, sp, #16
	str	r1, [r0]
	add	r2, r2, #4
	ldr	r3, [r4, r2]
	ldr	r2, [r7, #16]
	lsl	r3, r3, #16
	add	r2, r2, r3
	asr	r1, r1, #20
	asr	r2, r2, #20
	str	r1, [r0]
	str	r2, [r0, #8]
	ldr	r3, [sp, #8]
	str	r3, [sp]
	mov	r3, #0
	str	r3, [sp, #4]
	mov	r0, #0
	mov	r3, r9
	bl	OvlFunc_947_2008528
	mov	r2, r5
	mov	r0, #0
	mov	r1, r6
	bl	__MapActor_SetSpeed
	mov	r1, #8
	mov	r0, #0
	bl	__MapActor_SetAnim
	mov	r0, #15
	bl	__CutsceneWait
	mov	r4, fp
	ldr	r2, [sp, #80]
	ldr	r3, [r4]
	sub	r1, r2, r3
	cmp	r1, #0
	bge	.L48
	ldr	r0, .L53+12
	add	r1, r1, r0
.L48:
	mov	r4, fp
	ldr	r2, [sp, #88]
	ldr	r3, [r4, #8]
	sub	r2, r2, r3
	asr	r1, r1, #17
	cmp	r2, #0
	bge	.L49
	ldr	r0, .L53+12
	add	r2, r2, r0
.L49:
	asr	r2, r2, #17
	mov	r0, #0
	bl	__MapActor_TravelBy
	mov	r0, #0
	bl	__MapActor_GetActor
	ldr	r3, .L53+16
	str	r3, [r0, #108]
	mov	r0, #4
	bl	__CutsceneWait
	mov	r3, r8
	sub	r3, r3, #6
	cmp	r3, #7
	bhi	.L50
	mov	r0, r7
	mov	r1, #3
	bl	__Actor_SetAnim
	b	.L51
.L50:
	mov	r0, r7
	mov	r1, #2
	bl	__Actor_SetAnim
.L51:
	mov	r0, #239
	bl	__PlaySound
	mov	r0, r7
	ldr	r1, [sp, #80]
	ldr	r2, [sp, #84]
	ldr	r3, [sp, #88]
	bl	__Actor_TravelTo
	mov	r0, #0
	bl	__MapActor_WaitMovement
	mov	r0, #0
	mov	r1, #2
	bl	__MapActor_SetAnim
	mov	r0, #0
	ldr	r1, .L53+20
	ldr	r2, .L53+8
	.code	16
	bl	__MapActor_SetSpeed
	ldr	r2, .L53+24
	mov	r1, r8
	lsl	r3, r1, #2
	ldr	r0, [r2, r3]
	asr	r3, r0, #16
	lsl	r3, r3, #16
	lsl	r0, r0, #16
	asr	r1, r3, #16
	asr	r2, r0, #16
	lsr	r3, r3, #31
	lsr	r0, r0, #31
	add	r1, r1, r3
	add	r2, r2, r0
	asr	r1, r1, #1
	asr	r2, r2, #1
	mov	r0, #0
	bl	__MapActor_TravelBy
	ldr	r3, [sp, #92]
	cmp	r3, #0
	beq	.L52
	bl	_call_via_r3
.L52:
	mov	r0, #0
	bl	__MapActor_WaitMovement
	mov	r1, #1
	mov	r0, #0
	bl	__MapActor_SetAnim
	mov	r0, #0
	bl	__MapActor_GetActor
	mov	r2, #0
	str	r2, [r0, #108]
	mov	r0, r7
	bl	__Actor_WaitMovement
	mov	r0, #144
	lsl	r0, r0, #1
	bl	__PlaySound
	mov	r0, #213
	bl	__PlaySound
	ldr	r3, [sp, #80]
	str	r3, [r7, #8]
	ldr	r3, [sp, #88]
	str	r3, [r7, #16]
	mov	r3, #0
	str	r3, [r7, #36]
	str	r3, [r7, #44]
	mov	r0, r7
	mov	r1, #1
	bl	__Actor_SetAnim
	ldr	r2, [sp, #72]
	ldr	r4, .L53+4
	lsl	r2, r2, #4
	ldr	r3, [r4, r2]
	ldr	r0, [sp, #80]
	lsl	r3, r3, #16
	add	r2, r2, #4
	add	r0, r0, r3
	ldr	r3, [r4, r2]
	ldr	r1, [sp, #88]
	lsl	r3, r3, #16
	add	r1, r1, r3
	ldr	r2, [sp, #12]
	asr	r0, r0, #20
	asr	r1, r1, #20
	mov	sl, r4
	mov	r4, #158
	str	r0, [sp, #80]
	str	r1, [sp, #88]
	lsl	r4, r4, #1
	add	r3, r2, r4
	ldr	r3, [r3]
	mov	r8, r3
	mov	r2, r8
	asr	r2, r2, #20
	ldr	r4, [sp, #12]
	mov	r8, r2
	mov	r2, #160
	lsl	r2, r2, #1
	add	r3, r4, r2
	ldr	r6, [r3]
	mov	r4, r8
	asr	r6, r6, #20
	add	r3, r4, r0
	add	r2, r6, r1
	str	r3, [sp]
	str	r2, [sp, #4]
	ldr	r3, [sp, #8]
	mov	r2, r9
	bl	__Func_8010704
	ldr	r0, [sp, #8]
	ldr	r1, [sp, #80]
	ldr	r2, [sp, #88]
	str	r0, [sp]
	mov	r5, #255
	mov	r3, r9
	mov	r0, #0
	str	r5, [sp, #4]
	bl	OvlFunc_947_2008528
	ldr	r3, [sp, #8]
	ldr	r1, [sp, #80]
	ldr	r2, [sp, #88]
	str	r3, [sp]
	mov	r0, #2
	mov	r3, r9
	str	r5, [sp, #4]
	bl	OvlFunc_947_2008528
	ldr	r2, [sp, #72]
	mov	r4, sl
	lsl	r2, r2, #4
	ldr	r3, [r4, r2]
	mov	r0, fp
	ldr	r1, [r0]
	lsl	r3, r3, #16
	add	r2, r2, #4
	add	r1, r1, r3
	ldr	r3, [r4, r2]
	ldr	r2, [r0, #8]
	lsl	r3, r3, #16
	add	r2, r2, r3
	asr	r1, r1, #20
	asr	r2, r2, #20
	str	r1, [r0]
	str	r2, [r0, #8]
	add	r8, r8, r1
	add	r6, r6, r2
	str	r1, [sp]
	str	r2, [sp, #4]
	ldr	r3, [sp, #8]
	mov	r0, r8
	mov	r1, r6
	mov	r2, r9
	bl	__Func_8010704
	ldr	r3, [sp, #8]
	mov	r2, fp
	ldr	r1, [r2]
	mov	r4, #0
	ldr	r2, [r2, #8]
	mov	r0, #2
	str	r3, [sp]
	mov	r3, r9
	str	r4, [sp, #4]
	bl	OvlFunc_947_2008528
	bl	__MapActor_PlayPendingSound
	add	sp, sp, #40
	pop	{r3, r5, r6, r7}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	mov	fp, r7
	pop	{r5, r6, r7}
	pop	{r3}
	add	sp, sp, #16
	bx	r3
.L54:
	.align	2, 0
.L53:
	.word	iwram_3001e70
	.word	gScript_884__0200acf8
	.word	6553
	.word	131071
	.word	OvlFunc_947_200858c
	.word	19660
	.word	.Lm947_2ca0
.Lfe4:
	.size	 OvlFunc_947_20088ec,.Lfe4-OvlFunc_947_20088ec
	.include "asm/maps/crossbone_isle_dungeon_2/ovl_314_a_c_c_c_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_947_2008d78
	.thumb_func
	.type	 OvlFunc_947_2008d78,function
OvlFunc_947_2008d78:
	push	{r5, r6, lr}
	mov	r5, r0
	mov	r6, #60
	b	.L56
.L59:
	sub	r6, r6, #1
.L56:
	cmp	r6, #0
	beq	.L57
	mov	r0, #1
	bl	__WaitFrames
	ldr	r2, [r5, #12]
	ldr	r3, [r5, #20]
	cmp	r2, r3
	bne	.L59
.L57:
	mov	r3, #0
	str	r3, [r5, #40]
	mov	r3, #128
	lsl	r3, r3, #24
	str	r3, [r5, #60]
	ldr	r3, [r5, #20]
	str	r3, [r5, #12]
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.Lfe5:
	.size	 OvlFunc_947_2008d78,.Lfe5-OvlFunc_947_2008d78
	.align	2, 0
	.global	OvlFunc_947_2008da8
	.thumb_func
	.type	 OvlFunc_947_2008da8,function
OvlFunc_947_2008da8:
	push	{r5, r6, r7, lr}
	mov	r5, r0
	mov	r7, r1
	mov	r6, #60
	b	.L62
.L66:
	sub	r6, r6, #1
.L62:
	cmp	r6, #0
	beq	.L63
	mov	r0, #1
	bl	__WaitFrames
	ldr	r2, [r5, #12]
	ldr	r3, [r5, #20]
	cmp	r2, r3
	ble	.L63
	cmp	r2, r7
	bgt	.L66
.L63:
	mov	r3, #0
	str	r3, [r5, #40]
	mov	r3, #128
	lsl	r3, r3, #24
	str	r3, [r5, #60]
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe6:
	.size	 OvlFunc_947_2008da8,.Lfe6-OvlFunc_947_2008da8
	.include "asm/maps/crossbone_isle_dungeon_2/ovl_314_c_a_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_947_2009174
	.thumb_func
	.type	 OvlFunc_947_2009174,function
OvlFunc_947_2009174:
	push	{r5, r6, r7, lr}
	bl	__MapActor_GetActor
	mov	r5, r0
	mov	r2, r5
	add	r2, r2, #85
	mov	r3, #0
	strb	r3, [r2]
	ldr	r7, .L75
	mov	r6, #0
.L69:
	cmp	r6, #31
	bhi	.L70
	mov	r0, #1
	bl	__WaitFrames
	ldr	r2, [r5, #28]
	ldr	r1, .L75+4
	ldr	r3, [r5, #12]
	add	r2, r2, r1
	ldr	r1, .L75+8
	add	r3, r3, r1
	str	r3, [r5, #12]
	ldr	r3, .L75+12
	str	r2, [r5, #28]
	add	r6, r6, #1
	cmp	r2, r3
	bgt	.L69
	str	r7, [r5, #28]
.L70:
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L76:
	.align	2, 0
.L75:
	.word	6553
	.word	-6553
	.word	-52428
	.word	6552
.Lfe7:
	.size	 OvlFunc_947_2009174,.Lfe7-OvlFunc_947_2009174
	.include "asm/maps/crossbone_isle_dungeon_2/ovl_314_c_a_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_947_2009428
	.thumb_func
	.type	 OvlFunc_947_2009428,function
OvlFunc_947_2009428:
	push	{lr}
	mov	r3, r0
	add	r3, r3, #100
	ldrh	r3, [r3]
	mov	r1, #15
	and	r1, r1, r3
	bl	__Func_80929d8
	mov	r0, #0
	pop	{r1}
	bx	r1
.Lfe8:
	.size	 OvlFunc_947_2009428,.Lfe8-OvlFunc_947_2009428
	.include "asm/maps/crossbone_isle_dungeon_2/ovl_314_c_c.s"
	.text

	.include "asm/maps/crossbone_isle_dungeon_2/ovl_1440_a.s"
	.text

	.code	16
	.align	2, 0
	.global	CrossboneIsleDungeon2_GetSpecialExits
	.thumb_func
	.type	 CrossboneIsleDungeon2_GetSpecialExits,function
CrossboneIsleDungeon2_GetSpecialExits:
	mov	r0, #0
	bx	lr
.Lfe9:
	.size	 CrossboneIsleDungeon2_GetSpecialExits,.Lfe9-CrossboneIsleDungeon2_GetSpecialExits
	.align	2, 0
	.global	CrossboneIsleDungeon2_GetExits
	.thumb_func
	.type	 CrossboneIsleDungeon2_GetExits,function
CrossboneIsleDungeon2_GetExits:
	ldr	r0, .L80
	bx	lr
.L81:
	.align	2, 0
.L80:
	.word	gOvl_0200b014
.Lfe10:
	.size	 CrossboneIsleDungeon2_GetExits,.Lfe10-CrossboneIsleDungeon2_GetExits
	.include "asm/maps/crossbone_isle_dungeon_2/ovl_1440_c_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_947_2009528
	.thumb_func
	.type	 OvlFunc_947_2009528,function
OvlFunc_947_2009528:
	push	{lr}
	bl	__CutsceneStart
	bl	OvlFunc_947_2009268
	cmp	r0, #0
	bne	.L83
	bl	OvlFunc_947_20083a8
.L83:
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.Lfe11:
	.size	 OvlFunc_947_2009528,.Lfe11-OvlFunc_947_2009528
	.include "asm/maps/crossbone_isle_dungeon_2/ovl_1528_a_a_a_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_947_20095cc
	.thumb_func
	.type	 OvlFunc_947_20095cc,function
OvlFunc_947_20095cc:
	ldr	r3, .L85
	ldr	r2, .L85+4
	ldmia	r3!, {r1}
	stmia	r2!, {r1}
	ldmia	r3!, {r1}
	stmia	r2!, {r1}
	ldr	r3, [r3]
	str	r3, [r2]
	ldr	r2, .L85+4
	ldrh	r3, [r2, #2]
	add	r3, r3, #192
	strh	r3, [r2, #2]
	ldrh	r3, [r2, #6]
	add	r3, r3, #192
	strh	r3, [r2, #6]
	ldrh	r3, [r2, #10]
	add	r3, r3, #192
	strh	r3, [r2, #10]
	bx	lr
.L86:
	.align	2, 0
.L85:
	.word	iwram_3001ad4
	.word	.Lm947_372c
.Lfe12:
	.size	 OvlFunc_947_20095cc,.Lfe12-OvlFunc_947_20095cc
	.include "asm/maps/crossbone_isle_dungeon_2/ovl_1528_a_a_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_947_200a034
	.thumb_func
	.type	 OvlFunc_947_200a034,function
OvlFunc_947_200a034:
	push	{lr}
	bl	__Func_8093fa0
	pop	{r0}
	bx	r0
.Lfe13:
	.size	 OvlFunc_947_200a034,.Lfe13-OvlFunc_947_200a034
	.include "asm/maps/crossbone_isle_dungeon_2/ovl_1528_a_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_947_200a080
	.thumb_func
	.type	 OvlFunc_947_200a080,function
OvlFunc_947_200a080:
	push	{lr}
	mov	r0, #0
	bl	__MapActor_GetActor
	ldr	r3, .L89
	ldr	r3, [r3]
	str	r0, [r3, #24]
	add	r0, r0, #98
	mov	r3, #1
	strb	r3, [r0]
	pop	{r0}
	bx	r0
.L90:
	.align	2, 0
.L89:
	.word	iwram_3001ee0
.Lfe14:
	.size	 OvlFunc_947_200a080,.Lfe14-OvlFunc_947_200a080
	.align	2, 0
	.global	OvlFunc_947_200a09c
	.thumb_func
	.type	 OvlFunc_947_200a09c,function
OvlFunc_947_200a09c:
	push	{lr}
	mov	r0, #0
	bl	__MapActor_GetActor
	ldr	r3, .L92
	ldr	r3, [r3]
	mov	r2, #0
	add	r0, r0, #98
	str	r2, [r3, #24]
	strb	r2, [r0]
	pop	{r0}
	bx	r0
.L93:
	.align	2, 0
.L92:
	.word	iwram_3001ee0
.Lfe15:
	.size	 OvlFunc_947_200a09c,.Lfe15-OvlFunc_947_200a09c
	.align	2, 0
	.global	OvlFunc_947_200a0b8
	.thumb_func
	.type	 OvlFunc_947_200a0b8,function
OvlFunc_947_200a0b8:
	push	{r5, lr}
	mov	r5, r0
	mov	r0, #0
	bl	__MapActor_GetActor
	ldr	r2, [r5, #16]
	ldr	r3, [r0, #16]
	cmp	r2, r3
	ble	.L95
	mov	r1, r5
	add	r1, r1, #35
	ldrb	r3, [r1]
	mov	r4, #253
	and	r4, r4, r3
	strb	r4, [r1]
	ldr	r2, [r5, #12]
	ldr	r3, [r0, #12]
	cmp	r2, r3
	bge	.L95
	mov	r2, #2
	mov	r3, r4
	orr	r3, r3, r2
	strb	r3, [r1]
.L95:
	mov	r0, #0
	pop	{r5}
	pop	{r1}
	bx	r1
.Lfe16:
	.size	 OvlFunc_947_200a0b8,.Lfe16-OvlFunc_947_200a0b8
	.include "asm/maps/crossbone_isle_dungeon_2/ovl_1528_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_947_200a144
	.thumb_func
	.type	 OvlFunc_947_200a144,function
OvlFunc_947_200a144:
	push	{lr}
	mov	r0, #11
	bl	OvlFunc_947_200a0f0
	pop	{r0}
	bx	r0
.Lfe17:
	.size	 OvlFunc_947_200a144,.Lfe17-OvlFunc_947_200a144
	.align	2, 0
	.global	OvlFunc_947_200a150
	.thumb_func
	.type	 OvlFunc_947_200a150,function
OvlFunc_947_200a150:
	push	{lr}
	mov	r0, #12
	bl	OvlFunc_947_200a0f0
	pop	{r0}
	bx	r0
.Lfe18:
	.size	 OvlFunc_947_200a150,.Lfe18-OvlFunc_947_200a150
	.align	2, 0
	.global	OvlFunc_947_200a15c
	.thumb_func
	.type	 OvlFunc_947_200a15c,function
OvlFunc_947_200a15c:
	push	{r5, r6, lr}
	mov	r0, #0
	bl	__MapActor_GetActor
	mov	r5, r0
	mov	r0, #13
	bl	__MapActor_GetActor
	ldr	r3, .L102
	ldr	r2, [r0, #8]
	ldr	r6, [r3]
	ldr	r3, [r5, #8]
	asr	r2, r2, #20
	asr	r3, r3, #20
	cmp	r2, r3
	bne	.L100
	ldr	r2, [r0, #16]
	ldr	r3, [r5, #16]
	asr	r2, r2, #20
	asr	r3, r3, #20
	cmp	r2, r3
	bne	.L100
	ldr	r0, .L102+4
	bl	__SetFlag
	mov	r2, r6
	add	r2, r2, #53
	mov	r3, #1
	strb	r3, [r2]
	b	.L101
.L100:
	ldr	r0, .L102+4
	bl	__ClearFlag
.L101:
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L103:
	.align	2, 0
.L102:
	.word	iwram_3001f30
	.word	515
.Lfe19:
	.size	 OvlFunc_947_200a15c,.Lfe19-OvlFunc_947_200a15c
	.include "asm/maps/crossbone_isle_dungeon_2/ovl_1528_c_c_c_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_947_200a498
	.thumb_func
	.type	 OvlFunc_947_200a498,function
OvlFunc_947_200a498:
	push	{r5, lr}
	mov	r0, #10
	sub	sp, sp, #8
	bl	__MapActor_GetActor
	mov	r5, r0
	bl	__CutsceneStart
	ldr	r1, [r5, #8]
	ldr	r2, [r5, #16]
	mov	r3, #1
	str	r3, [sp]
	mov	r3, #0
	str	r3, [sp, #4]
	asr	r1, r1, #20
	asr	r2, r2, #20
	mov	r3, #1
	mov	r0, #2
	bl	OvlFunc_947_2008528
	bl	__CutsceneEnd
	add	sp, sp, #8
	pop	{r5}
	pop	{r0}
	bx	r0
.Lfe20:
	.size	 OvlFunc_947_200a498,.Lfe20-OvlFunc_947_200a498
	.include "asm/maps/crossbone_isle_dungeon_2/ovl_1528_c_c_c_c_c.s"
	.text

	.include "asm/maps/crossbone_isle_dungeon_2/ovl_2580_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_947_200a694
	.thumb_func
	.type	 OvlFunc_947_200a694,function
OvlFunc_947_200a694:
	push	{lr}
	bl	__MapActor_GetActor
	mov	r3, #2
	mov	r1, r0
	add	r0, r0, #34
	strb	r3, [r0]
	mov	r3, r1
	mov	r2, #0
	add	r3, r3, #85
	strb	r2, [r3]
	ldr	r3, .L106
	str	r3, [r1, #108]
	pop	{r0}
	bx	r0
.L107:
	.align	2, 0
.L106:
	.word	OvlFunc_947_2009aa8
.Lfe21:
	.size	 OvlFunc_947_200a694,.Lfe21-OvlFunc_947_200a694
	.include "asm/maps/crossbone_isle_dungeon_2/ovl_2580_c.s"
	.text

	.include "asm/maps/crossbone_isle_dungeon_2/ovl_2d64.s"
	.text


	.text
	.align	2, 0
