@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"elemental_stars.c"
	.code	16
.gcc2_compiled.:
	.include "asm/maps/elemental_stars/ovl_314_a_a.s"
	.text

	.code	16
.text
	.align	2, 0
	.global	ElementalStars_GetEntrances
	.thumb_func
	.type	 ElementalStars_GetEntrances,function
ElementalStars_GetEntrances:
	ldr	r0, .L3
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	gOvl_0200cd88
.Lfe1:
	.size	 ElementalStars_GetEntrances,.Lfe1-ElementalStars_GetEntrances
	.align	2, 0
	.global	ElementalStars_GetSpecialExits
	.thumb_func
	.type	 ElementalStars_GetSpecialExits,function
ElementalStars_GetSpecialExits:
	mov	r0, #0
	bx	lr
.Lfe2:
	.size	 ElementalStars_GetSpecialExits,.Lfe2-ElementalStars_GetSpecialExits
	.align	2, 0
	.global	ElementalStars_GetExits
	.thumb_func
	.type	 ElementalStars_GetExits,function
ElementalStars_GetExits:
	ldr	r0, .L7
	bx	lr
.L8:
	.align	2, 0
.L7:
	.word	gOvl_0200cdb8
.Lfe3:
	.size	 ElementalStars_GetExits,.Lfe3-ElementalStars_GetExits
	.align	2, 0
	.global	ElementalStars_GetActors
	.thumb_func
	.type	 ElementalStars_GetActors,function
ElementalStars_GetActors:
	ldr	r0, .L10
	bx	lr
.L11:
	.align	2, 0
.L10:
	.word	gOvl_0200cdc4
.Lfe4:
	.size	 ElementalStars_GetActors,.Lfe4-ElementalStars_GetActors
	.align	2, 0
	.global	ElementalStars_GetEvents
	.thumb_func
	.type	 ElementalStars_GetEvents,function
ElementalStars_GetEvents:
	ldr	r0, .L13
	bx	lr
.L14:
	.align	2, 0
.L13:
	.word	gOvl_0200cfa4
.Lfe5:
	.size	 ElementalStars_GetEvents,.Lfe5-ElementalStars_GetEvents
	.include "asm/maps/elemental_stars/ovl_314_c_c_a_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_896_2008a64
	.thumb_func
	.type	 OvlFunc_896_2008a64,function
OvlFunc_896_2008a64:
	push	{lr}
	bl	__CutsceneStart
	bl	OvlFunc_896_2008a98
	bl	OvlFunc_896_2008d5c
	bl	OvlFunc_896_2008f8c
	bl	OvlFunc_896_2009450
	bl	OvlFunc_896_200978c
	bl	OvlFunc_896_2009d04
	ldr	r0, .L16
	bl	__SetFlag
	bl	__CutsceneEnd
	bl	OvlFunc_896_200a27c
	pop	{r0}
	bx	r0
.L17:
	.align	2, 0
.L16:
	.word	2110
.Lfe6:
	.size	 OvlFunc_896_2008a64,.Lfe6-OvlFunc_896_2008a64
	.include "asm/maps/elemental_stars/ovl_314_c_c_a_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_896_200a74c
	.thumb_func
	.type	 OvlFunc_896_200a74c,function
OvlFunc_896_200a74c:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L23
	bl	__MessageID
	mov	r0, #10
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L24:
	.align	2, 0
.L23:
	.word	4298
.Lfe7:
	.size	 OvlFunc_896_200a74c,.Lfe7-OvlFunc_896_200a74c
	.align	2, 0
	.global	OvlFunc_896_200a76c
	.thumb_func
	.type	 OvlFunc_896_200a76c,function
OvlFunc_896_200a76c:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L30
	bl	__MessageID
	mov	r0, #11
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L31:
	.align	2, 0
.L30:
	.word	4295
.Lfe8:
	.size	 OvlFunc_896_200a76c,.Lfe8-OvlFunc_896_200a76c
	.align	2, 0
	.global	OvlFunc_896_200a78c
	.thumb_func
	.type	 OvlFunc_896_200a78c,function
OvlFunc_896_200a78c:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L37
	bl	__MessageID
	mov	r0, #13
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L38:
	.align	2, 0
.L37:
	.word	4296
.Lfe9:
	.size	 OvlFunc_896_200a78c,.Lfe9-OvlFunc_896_200a78c
	.align	2, 0
	.global	OvlFunc_896_200a7ac
	.thumb_func
	.type	 OvlFunc_896_200a7ac,function
OvlFunc_896_200a7ac:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L44
	bl	__MessageID
	mov	r0, #14
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L45:
	.align	2, 0
.L44:
	.word	4300
.Lfe10:
	.size	 OvlFunc_896_200a7ac,.Lfe10-OvlFunc_896_200a7ac
	.align	2, 0
	.global	OvlFunc_896_200a7cc
	.thumb_func
	.type	 OvlFunc_896_200a7cc,function
OvlFunc_896_200a7cc:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L51
	bl	__MessageID
	mov	r0, #9
	mov	r1, #10
	bl	OvlFunc_896_200c248
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L52:
	.align	2, 0
.L51:
	.word	4210
.Lfe11:
	.size	 OvlFunc_896_200a7cc,.Lfe11-OvlFunc_896_200a7cc
	.align	2, 0
	.global	OvlFunc_896_200a7ec
	.thumb_func
	.type	 OvlFunc_896_200a7ec,function
OvlFunc_896_200a7ec:
	push	{lr}
	bl	__Func_8093c00
	pop	{r0}
	bx	r0
.Lfe12:
	.size	 OvlFunc_896_200a7ec,.Lfe12-OvlFunc_896_200a7ec
	.include "asm/maps/elemental_stars/ovl_314_c_c_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_896_200c248
	.thumb_func
	.type	 OvlFunc_896_200c248,function
OvlFunc_896_200c248:
	push	{r5, lr}
	mov	r5, r1
	mov	r1, #0
	bl	__ActorMessage
	mov	r0, r5
	bl	__CutsceneWait
	pop	{r5}
	pop	{r0}
	bx	r0
.Lfe13:
	.size	 OvlFunc_896_200c248,.Lfe13-OvlFunc_896_200c248
	.include "asm/maps/elemental_stars/ovl_314_c_c_c_c.s"
	.text


	.text
	.align	2, 0
