@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"gondowan.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_958_2008314
	.thumb_func
	.type	 OvlFunc_958_2008314,function
OvlFunc_958_2008314:
	push	{r5, lr}
	ldmia	r0!, {r5}
	ldmia	r1!, {r3}
	ldmia	r0!, {r4}
	sub	r5, r5, r3
	ldmia	r1!, {r3}
	ldr	r2, [r1]
	sub	r4, r4, r3
	ldr	r3, [r0]
	sub	r3, r3, r2
	asr	r5, r5, #16
	asr	r4, r4, #16
	asr	r3, r3, #16
	mov	r0, r5
	mul	r0, r0, r5
	mov	r2, r4
	mul	r2, r2, r4
	mov	r1, r3
	mul	r1, r1, r3
	add	r0, r0, r2
	mov	r3, r1
	add	r0, r0, r3
	ldr	r3, .L4
	bl	_call_via_r3
	pop	{r5}
	pop	{r1}
	bx	r1
.L5:
	.align	2, 0
.L4:
	.word	Func_8000948
.Lfe1:
	.size	 OvlFunc_958_2008314,.Lfe1-OvlFunc_958_2008314
	.include "asm/maps/gondowan/ovl_314_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_958_200858c
	.thumb_func
	.type	 OvlFunc_958_200858c,function
OvlFunc_958_200858c:
	push	{r5, r6, r7, lr}
	mov	r5, r0
	ldrh	r3, [r5, #6]
	ldr	r2, .L15
	lsr	r3, r3, #12
	lsl	r7, r3, #2
	ldr	r1, [r2, r7]
	ldr	r2, .L15+4
	ldr	r3, [r5, #8]
	and	r2, r2, r1
	sub	sp, sp, #12
	mov	r6, sp
	add	r3, r3, r2
	str	r3, [r6]
	ldr	r3, [r5, #12]
	str	r3, [r6, #4]
	ldr	r3, [r5, #16]
	lsl	r1, r1, #16
	add	r3, r3, r1
	mov	r0, r6
	mov	r1, r5
	str	r3, [r6, #8]
	bl	OvlFunc_958_2008350
	cmp	r0, #0
	beq	.L7
	ldr	r3, [r0, #80]
	ldr	r3, [r3, #40]
	mov	r2, #0
	ldrsh	r0, [r3, r2]
	ldr	r2, .L15+8
	mov	r1, #0
.L13:
	ldmia	r2!, {r3}
	cmp	r0, r3
	beq	.L12
	add	r1, r1, #1
	cmp	r1, #5
	bls	.L13
	mov	r3, #0
	str	r3, [r5, #36]
	str	r3, [r5, #44]
	mov	r3, #128
	lsl	r3, r3, #24
	str	r3, [r5, #56]
	str	r3, [r5, #64]
.L7:
	ldr	r3, .L15
	ldr	r2, .L15+4
	ldr	r1, [r3, r7]
	ldr	r3, [r5, #8]
	and	r2, r2, r1
	add	r3, r3, r2
	str	r3, [r6]
	ldr	r3, [r5, #12]
	str	r3, [r6, #4]
	ldr	r3, [r5, #16]
	lsl	r1, r1, #16
	add	r3, r3, r1
	mov	r0, r5
	mov	r1, r6
	str	r3, [r6, #8]
	bl	__TestCollision
	cmp	r0, #0
	ble	.L12
	mov	r3, #0
	str	r3, [r5, #36]
	str	r3, [r5, #44]
	mov	r3, #128
	lsl	r3, r3, #24
	str	r3, [r5, #56]
	str	r3, [r5, #64]
.L12:
	mov	r0, #0
	add	sp, sp, #12
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L16:
	.align	2, 0
.L15:
	.word	.Lm958_16c0
	.word	-65536
	.word	.Lm958_1700
.Lfe2:
	.size	 OvlFunc_958_200858c,.Lfe2-OvlFunc_958_200858c
	.include "asm/maps/gondowan/ovl_314_c_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_958_2008758
	.thumb_func
	.type	 OvlFunc_958_2008758,function
OvlFunc_958_2008758:
	push	{r5, r6, r7, lr}
	mov	r7, fp
	mov	r6, sl
	mov	r5, r9
	push	{r5, r6, r7}
	mov	r7, r8
	push	{r7}
	mov	r6, r0
	sub	sp, sp, #32
	mov	r3, #0
	add	r0, sp, #16
	add	r1, r6, #4
	mov	r2, r6
	str	r3, [r6, #20]
	bl	OvlFunc_958_2008630
	mov	sl, r0
	cmp	r0, #0
	bne	.L18
	mov	r0, #0
	b	.L17
.L18:
	mov	r0, sl
	add	r0, r0, #34
	mov	r3, #2
	str	r0, [sp, #4]
	strb	r3, [r0]
	ldr	r3, [r6]
	mov	r1, #0
	str	r1, [sp, #12]
	ldr	r5, .L41
	lsl	r1, r3, #4
	add	r3, r1, #4
	ldr	r2, [r5, r3]
	cmp	r2, #0
	bge	.L19
	neg	r2, r2
.L19:
	mov	r3, r1
	add	r3, r3, #12
	ldr	r3, [r5, r3]
	cmp	r3, #0
	bge	.L20
	neg	r3, r3
.L20:
	add	r3, r2, r3
	asr	r3, r3, #4
	str	r3, [sp, #8]
	ldr	r2, [r5, r1]
	cmp	r2, #0
	bge	.L21
	neg	r2, r2
.L21:
	mov	r3, r1
	add	r3, r3, #8
	ldr	r3, [r5, r3]
	cmp	r3, #0
	bge	.L22
	neg	r3, r3
.L22:
	add	r3, r2, r3
	asr	r3, r3, #4
	mov	r9, r3
	ldr	r3, [sp, #16]
	ldr	r1, .L41+4
	add	r2, sp, #20
	lsl	r3, r3, #2
	mov	r8, r2
	ldr	r2, [r1, r3]
	ldr	r3, .L41+8
	mov	r4, sl
	and	r2, r2, r3
	ldr	r3, [r4, #8]
	mov	r0, r8
	add	r3, r3, r2
	str	r3, [r0]
	ldr	r0, [r4, #12]
	mov	r2, r8
	str	r0, [r2, #4]
	ldr	r3, [sp, #16]
	lsl	r3, r3, #2
	ldr	r2, [r1, r3]
	ldr	r3, [r4, #16]
	lsl	r2, r2, #16
	mov	r4, r8
	add	r3, r3, r2
	str	r3, [r4, #8]
	mov	r4, r6
	str	r0, [r6, #12]
	add	r4, r4, #8
	mov	fp, r8
.L23:
	ldr	r3, [r6]
	ldr	r0, .L41
	lsl	r3, r3, #4
	add	r3, r3, #4
	ldr	r2, [r0, r3]
	mov	r1, r8
	ldr	r3, [r1, #8]
	lsl	r2, r2, #16
	add	r3, r3, r2
	ldr	r2, [sp, #8]
	mov	r7, #0
	str	r3, [r6, #16]
	cmp	r7, r2
	bge	.L39
.L29:
	ldr	r3, [r6]
	ldr	r0, .L41
	lsl	r3, r3, #4
	ldr	r2, [r0, r3]
	mov	r1, r8
	ldr	r3, [r1]
	lsl	r2, r2, #16
	add	r3, r3, r2
	mov	r5, #0
	str	r3, [r6, #8]
	cmp	r5, r9
	bge	.L40
.L33:
	mov	r1, r4
	mov	r0, sl
	str	r4, [sp]
	bl	__TestCollision
	ldr	r4, [sp]
	cmp	r0, #2
	beq	.L35
	ldr	r3, [r4]
	mov	r2, #128
	lsl	r2, r2, #13
	add	r3, r3, r2
	add	r5, r5, #1
	str	r3, [r4]
	cmp	r5, r9
	blt	.L33
.L40:
	ldr	r3, [r6, #16]
	mov	r0, #128
	lsl	r0, r0, #13
	ldr	r1, [sp, #8]
	add	r3, r3, r0
	add	r7, r7, #1
	str	r3, [r6, #16]
	cmp	r7, r1
	blt	.L29
.L39:
	ldr	r2, [sp, #12]
	ldr	r3, [sp, #16]
	add	r2, r2, #1
	str	r2, [sp, #12]
	ldr	r0, .L41+4
	lsl	r3, r3, #2
	ldr	r2, [r0, r3]
	ldr	r3, .L41+8
	mov	r1, fp
	and	r2, r2, r3
	ldr	r3, [r1]
	add	r3, r3, r2
	str	r3, [r1]
	ldr	r3, [sp, #16]
	lsl	r3, r3, #2
	ldr	r2, [r0, r3]
	ldr	r3, [r1, #8]
	lsl	r2, r2, #16
	add	r3, r3, r2
	str	r3, [r1, #8]
	b	.L23
.L35:
	ldr	r2, [sp, #4]
	mov	r3, #0
	strb	r3, [r2]
	ldr	r3, [sp, #12]
	mov	r0, #0
	cmp	r3, #0
	beq	.L17
	ldr	r3, [sp, #16]
	ldr	r2, .L41+4
	lsl	r3, r3, #2
	ldr	r2, [r2, r3]
	ldr	r3, .L41+8
	ldr	r4, [sp, #12]
	and	r3, r3, r2
	mov	r1, r4
	mul	r1, r1, r3
	lsl	r2, r2, #16
	mul	r2, r2, r4
	mov	r0, sl
	ldr	r3, [r0, #8]
	add	r3, r3, r1
	str	r3, [r6, #8]
	ldr	r3, [r0, #12]
	str	r3, [r6, #12]
	ldr	r3, [r0, #16]
	add	r3, r3, r2
	str	r3, [r6, #16]
	mov	r0, #1
.L17:
	add	sp, sp, #32
	pop	{r3, r5, r6, r7}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	mov	fp, r7
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L42:
	.align	2, 0
.L41:
	.word	.Lm958_1718
	.word	.Lm958_16c0
	.word	-65536
.Lfe3:
	.size	 OvlFunc_958_2008758,.Lfe3-OvlFunc_958_2008758
	.align	2, 0
	.global	OvlFunc_958_20088ec
	.thumb_func
	.type	 OvlFunc_958_20088ec,function
OvlFunc_958_20088ec:
	sub	sp, sp, #16
	push	{r5, r6, r7, lr}
	mov	r7, fp
	mov	r6, sl
	mov	r5, r9
	push	{r5, r6, r7}
	mov	r7, r8
	push	{r7}
	sub	sp, sp, #40
	str	r0, [sp, #72]
	str	r1, [sp, #76]
	str	r2, [sp, #80]
	str	r3, [sp, #84]
	ldr	r3, .L53
	ldr	r3, [r3]
	mov	r0, #0
	str	r3, [sp, #12]
	bl	__MapActor_GetActor
	ldrh	r3, [r0, #6]
	ldr	r0, [sp, #76]
	lsr	r3, r3, #12
	mov	r8, r3
	bl	__MapActor_GetActor
	ldr	r3, [sp, #72]
	ldr	r4, .L53+4
	lsl	r1, r3, #4
	add	r3, r1, #4
	ldr	r2, [r4, r3]
	mov	r7, r0
	cmp	r2, #0
	bge	.L44
	neg	r2, r2
.L44:
	mov	r3, r1
	add	r3, r3, #12
	ldr	r3, [r4, r3]
	cmp	r3, #0
	bge	.L45
	neg	r3, r3
.L45:
	add	r3, r2, r3
	asr	r3, r3, #4
	str	r3, [sp, #8]
	ldr	r2, [r4, r1]
	cmp	r2, #0
	bge	.L46
	neg	r2, r2
.L46:
	mov	r3, r1
	add	r3, r3, #8
	ldr	r3, [r4, r3]
	cmp	r3, #0
	bge	.L47
	neg	r3, r3
.L47:
	add	r3, r2, r3
	asr	r3, r3, #4
	mov	r9, r3
	ldr	r5, .L53+8
	ldr	r3, [r7, #8]
	mov	r6, #128
	add	r0, sp, #28
	lsl	r6, r6, #8
	str	r6, [r7, #48]
	str	r5, [r7, #52]
	str	r3, [r0]
	ldr	r3, [r7, #16]
	str	r3, [r0, #8]
	ldr	r2, [sp, #72]
	lsl	r2, r2, #4
	ldr	r3, [r4, r2]
	ldr	r1, [r7, #8]
	lsl	r3, r3, #16
	add	r1, r1, r3
	mov	fp, r0
	add	r0, sp, #16
	str	r1, [r0]
	add	r2, r2, #4
	ldr	r3, [r4, r2]
	ldr	r2, [r7, #16]
	lsl	r3, r3, #16
	add	r2, r2, r3
	asr	r1, r1, #20
	asr	r2, r2, #20
	str	r1, [r0]
	str	r2, [r0, #8]
	ldr	r3, [sp, #8]
	str	r3, [sp]
	mov	r3, #0
	str	r3, [sp, #4]
	mov	r0, #0
	mov	r3, r9
	bl	OvlFunc_958_2008528
	mov	r2, r5
	mov	r0, #0
	mov	r1, r6
	bl	__MapActor_SetSpeed
	mov	r1, #8
	mov	r0, #0
	bl	__MapActor_SetAnim
	mov	r0, #15
	bl	__CutsceneWait
	mov	r4, fp
	ldr	r2, [sp, #80]
	ldr	r3, [r4]
	sub	r1, r2, r3
	cmp	r1, #0
	bge	.L48
	ldr	r0, .L53+12
	add	r1, r1, r0
.L48:
	mov	r4, fp
	ldr	r2, [sp, #88]
	ldr	r3, [r4, #8]
	sub	r2, r2, r3
	asr	r1, r1, #17
	cmp	r2, #0
	bge	.L49
	ldr	r0, .L53+12
	add	r2, r2, r0
.L49:
	asr	r2, r2, #17
	mov	r0, #0
	bl	__MapActor_TravelBy
	mov	r0, #0
	bl	__MapActor_GetActor
	ldr	r3, .L53+16
	str	r3, [r0, #108]
	mov	r0, #4
	bl	__CutsceneWait
	mov	r3, r8
	sub	r3, r3, #6
	cmp	r3, #7
	bhi	.L50
	mov	r0, r7
	mov	r1, #3
	bl	__Actor_SetAnim
	b	.L51
.L50:
	mov	r0, r7
	mov	r1, #2
	bl	__Actor_SetAnim
.L51:
	mov	r0, #239
	bl	__PlaySound
	mov	r0, r7
	ldr	r1, [sp, #80]
	ldr	r2, [sp, #84]
	ldr	r3, [sp, #88]
	bl	__Actor_TravelTo
	mov	r0, #0
	bl	__MapActor_WaitMovement
	mov	r0, #0
	mov	r1, #2
	bl	__MapActor_SetAnim
	mov	r0, #0
	ldr	r1, .L53+20
	ldr	r2, .L53+8
	.code	16
	bl	__MapActor_SetSpeed
	ldr	r2, .L53+24
	mov	r1, r8
	lsl	r3, r1, #2
	ldr	r0, [r2, r3]
	asr	r3, r0, #16
	lsl	r3, r3, #16
	lsl	r0, r0, #16
	asr	r1, r3, #16
	asr	r2, r0, #16
	lsr	r3, r3, #31
	lsr	r0, r0, #31
	add	r1, r1, r3
	add	r2, r2, r0
	asr	r1, r1, #1
	asr	r2, r2, #1
	mov	r0, #0
	bl	__MapActor_TravelBy
	ldr	r3, [sp, #92]
	cmp	r3, #0
	beq	.L52
	bl	_call_via_r3
.L52:
	mov	r0, #0
	bl	__MapActor_WaitMovement
	mov	r1, #1
	mov	r0, #0
	bl	__MapActor_SetAnim
	mov	r0, #0
	bl	__MapActor_GetActor
	mov	r2, #0
	str	r2, [r0, #108]
	mov	r0, r7
	bl	__Actor_WaitMovement
	mov	r0, #144
	lsl	r0, r0, #1
	bl	__PlaySound
	mov	r0, #213
	bl	__PlaySound
	ldr	r3, [sp, #80]
	str	r3, [r7, #8]
	ldr	r3, [sp, #88]
	str	r3, [r7, #16]
	mov	r3, #0
	str	r3, [r7, #36]
	str	r3, [r7, #44]
	mov	r0, r7
	mov	r1, #1
	bl	__Actor_SetAnim
	ldr	r2, [sp, #72]
	ldr	r4, .L53+4
	lsl	r2, r2, #4
	ldr	r3, [r4, r2]
	ldr	r0, [sp, #80]
	lsl	r3, r3, #16
	add	r2, r2, #4
	add	r0, r0, r3
	ldr	r3, [r4, r2]
	ldr	r1, [sp, #88]
	lsl	r3, r3, #16
	add	r1, r1, r3
	ldr	r2, [sp, #12]
	asr	r0, r0, #20
	asr	r1, r1, #20
	mov	sl, r4
	mov	r4, #158
	str	r0, [sp, #80]
	str	r1, [sp, #88]
	lsl	r4, r4, #1
	add	r3, r2, r4
	ldr	r3, [r3]
	mov	r8, r3
	mov	r2, r8
	asr	r2, r2, #20
	ldr	r4, [sp, #12]
	mov	r8, r2
	mov	r2, #160
	lsl	r2, r2, #1
	add	r3, r4, r2
	ldr	r6, [r3]
	mov	r4, r8
	asr	r6, r6, #20
	add	r3, r4, r0
	add	r2, r6, r1
	str	r3, [sp]
	str	r2, [sp, #4]
	ldr	r3, [sp, #8]
	mov	r2, r9
	bl	__Func_8010704
	ldr	r0, [sp, #8]
	ldr	r1, [sp, #80]
	ldr	r2, [sp, #88]
	str	r0, [sp]
	mov	r5, #255
	mov	r3, r9
	mov	r0, #0
	str	r5, [sp, #4]
	bl	OvlFunc_958_2008528
	ldr	r3, [sp, #8]
	ldr	r1, [sp, #80]
	ldr	r2, [sp, #88]
	str	r3, [sp]
	mov	r0, #2
	mov	r3, r9
	str	r5, [sp, #4]
	bl	OvlFunc_958_2008528
	ldr	r2, [sp, #72]
	mov	r4, sl
	lsl	r2, r2, #4
	ldr	r3, [r4, r2]
	mov	r0, fp
	ldr	r1, [r0]
	lsl	r3, r3, #16
	add	r2, r2, #4
	add	r1, r1, r3
	ldr	r3, [r4, r2]
	ldr	r2, [r0, #8]
	lsl	r3, r3, #16
	add	r2, r2, r3
	asr	r1, r1, #20
	asr	r2, r2, #20
	str	r1, [r0]
	str	r2, [r0, #8]
	add	r8, r8, r1
	add	r6, r6, r2
	str	r1, [sp]
	str	r2, [sp, #4]
	ldr	r3, [sp, #8]
	mov	r0, r8
	mov	r1, r6
	mov	r2, r9
	bl	__Func_8010704
	ldr	r3, [sp, #8]
	mov	r2, fp
	ldr	r1, [r2]
	mov	r4, #0
	ldr	r2, [r2, #8]
	mov	r0, #2
	str	r3, [sp]
	mov	r3, r9
	str	r4, [sp, #4]
	bl	OvlFunc_958_2008528
	bl	__MapActor_PlayPendingSound
	add	sp, sp, #40
	pop	{r3, r5, r6, r7}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	mov	fp, r7
	pop	{r5, r6, r7}
	pop	{r3}
	add	sp, sp, #16
	bx	r3
.L54:
	.align	2, 0
.L53:
	.word	iwram_3001e70
	.word	.Lm958_1718
	.word	6553
	.word	131071
	.word	OvlFunc_958_200858c
	.word	19660
	.word	.Lm958_16c0
.Lfe4:
	.size	 OvlFunc_958_20088ec,.Lfe4-OvlFunc_958_20088ec
	.include "asm/maps/gondowan/ovl_314_c_c_c_c.s"
	.text

	.include "asm/maps/gondowan/ovl_cc0_a.s"
	.text

	.code	16
	.align	2, 0
	.global	Gondowan_GetSpecialExits
	.thumb_func
	.type	 Gondowan_GetSpecialExits,function
Gondowan_GetSpecialExits:
	mov	r0, #0
	bx	lr
.Lfe5:
	.size	 Gondowan_GetSpecialExits,.Lfe5-Gondowan_GetSpecialExits
	.align	2, 0
	.global	Gondowan_GetExits
	.thumb_func
	.type	 Gondowan_GetExits,function
Gondowan_GetExits:
	ldr	r0, .L57
	bx	lr
.L58:
	.align	2, 0
.L57:
	.word	gOvl_0200991c
.Lfe6:
	.size	 Gondowan_GetExits,.Lfe6-Gondowan_GetExits
	.include "asm/maps/gondowan/ovl_cc0_c_a_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_958_2009040
	.thumb_func
	.type	 OvlFunc_958_2009040,function
OvlFunc_958_2009040:
	push	{lr}
	mov	r0, #149
	lsl	r0, r0, #4
	bl	__GetFlag
	cmp	r0, #0
	beq	.L60
	ldr	r0, .L62
	bl	__GetFlag
	cmp	r0, #0
	bne	.L60
	ldr	r0, .L62+4
	bl	__MessageID
	b	.L61
.L60:
	ldr	r0, .L62+8
	bl	__MessageID
.L61:
	mov	r0, #9
	mov	r1, #0
	bl	__ActorMessage
	pop	{r0}
	bx	r0
.L63:
	.align	2, 0
.L62:
	.word	2415
	.word	9173
	.word	9170
.Lfe7:
	.size	 OvlFunc_958_2009040,.Lfe7-OvlFunc_958_2009040
	.align	2, 0
	.global	OvlFunc_958_2009080
	.thumb_func
	.type	 OvlFunc_958_2009080,function
OvlFunc_958_2009080:
	push	{r5, lr}
	ldr	r3, .L66
	ldr	r5, [r3]
	bl	__CutsceneStart
	mov	r0, #129
	lsl	r0, r0, #2
	bl	__GetFlag
	cmp	r0, #0
	beq	.L65
	ldr	r0, .L66+4
	bl	__ClearFlag
	ldr	r0, .L66+8
	.code	16
	bl	__ClearFlag
	ldr	r0, .L66+12
	.code	16
	bl	__ClearFlag
	ldr	r0, .L66+16
	bl	__ClearFlag
	ldr	r0, .L66+8
	.code	16
	bl	__SetFlag
	ldr	r0, .L66+12
	.code	16
	bl	__SetFlag
.L65:
	mov	r2, #182
	lsl	r2, r2, #1
	add	r3, r5, r2
	mov	r2, #0
	ldrsh	r0, [r3, r2]
	bl	__Func_8091e9c
	bl	__MapTransitionOut
	bl	__WaitMapTransition
	bl	__CutsceneEnd
	pop	{r5}
	pop	{r0}
	bx	r0
.L67:
	.align	2, 0
.L66:
	.word	iwram_3001ebc
	.word	2467
	.word	2469
	.word	2468
	.word	2470
.Lfe8:
	.size	 OvlFunc_958_2009080,.Lfe8-OvlFunc_958_2009080
	.align	2, 0
	.global	OvlFunc_958_20090f0
	.thumb_func
	.type	 OvlFunc_958_20090f0,function
OvlFunc_958_20090f0:
	push	{lr}
	bl	__Func_8093c00
	pop	{r0}
	bx	r0
.Lfe9:
	.size	 OvlFunc_958_20090f0,.Lfe9-OvlFunc_958_20090f0
	.align	2, 0
	.global	OvlFunc_958_20090fc
	.thumb_func
	.type	 OvlFunc_958_20090fc,function
OvlFunc_958_20090fc:
	push	{lr}
	mov	r0, #8
	sub	sp, sp, #8
	bl	__MapActor_GetActor
	bl	__CutsceneStart
	mov	r0, #8
	bl	__MapActor_GetActor
	ldr	r3, [r0, #8]
	asr	r3, r3, #20
	cmp	r3, #30
	bgt	.L70
	mov	r0, #8
	bl	OvlFunc_958_20091f8
	mov	r3, #27
	mov	r2, #19
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #29
	mov	r1, #19
	mov	r2, #1
	mov	r3, #1
	bl	__Func_8010704
	ldr	r0, .L71
	bl	__SetFlag
.L70:
	bl	__CutsceneEnd
	add	sp, sp, #8
	pop	{r0}
	bx	r0
.L72:
	.align	2, 0
.L71:
	.word	2466
.Lfe10:
	.size	 OvlFunc_958_20090fc,.Lfe10-OvlFunc_958_20090fc
	.align	2, 0
	.global	OvlFunc_958_2009148
	.thumb_func
	.type	 OvlFunc_958_2009148,function
OvlFunc_958_2009148:
	push	{lr}
	bl	OvlFunc_958_20083a8
	bl	OvlFunc_958_2009158
	pop	{r0}
	bx	r0
.Lfe11:
	.size	 OvlFunc_958_2009148,.Lfe11-OvlFunc_958_2009148
	.include "asm/maps/gondowan/ovl_cc0_c_a_c_c_c_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_958_20091c4
	.thumb_func
	.type	 OvlFunc_958_20091c4,function
OvlFunc_958_20091c4:
	bx	lr
.Lfe12:
	.size	 OvlFunc_958_20091c4,.Lfe12-OvlFunc_958_20091c4
	.align	2, 0
	.global	OvlFunc_958_20091c8
	.thumb_func
	.type	 OvlFunc_958_20091c8,function
OvlFunc_958_20091c8:
	ldr	r2, [r0, #80]
	ldr	r1, .L76
	ldrh	r3, [r2, #30]
	add	r3, r3, r1
	strh	r3, [r2, #30]
	bx	lr
.L77:
	.align	2, 0
.L76:
	.word	-1024
.Lfe13:
	.size	 OvlFunc_958_20091c8,.Lfe13-OvlFunc_958_20091c8
	.align	2, 0
	.global	OvlFunc_958_20091d8
	.thumb_func
	.type	 OvlFunc_958_20091d8,function
OvlFunc_958_20091d8:
	push	{r5, r6, r7, lr}
	mov	r7, r0
	mov	r6, r1
	mov	r5, #40
.L82:
	cmp	r5, #0
	beq	.L80
	mov	r0, #1
	bl	__WaitFrames
	ldr	r3, [r7, #12]
	sub	r5, r5, #1
	cmp	r3, r6
	bgt	.L82
.L80:
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe14:
	.size	 OvlFunc_958_20091d8,.Lfe14-OvlFunc_958_20091d8
	.include "asm/maps/gondowan/ovl_cc0_c_c_a_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_958_2009380
	.thumb_func
	.type	 OvlFunc_958_2009380,function
OvlFunc_958_2009380:
	bx	lr
.Lfe15:
	.size	 OvlFunc_958_2009380,.Lfe15-OvlFunc_958_2009380
	.align	2, 0
	.global	OvlFunc_958_2009384
	.thumb_func
	.type	 OvlFunc_958_2009384,function
OvlFunc_958_2009384:
	push	{lr}
	mov	r0, #12
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	pop	{r0}
	bx	r0
.Lfe16:
	.size	 OvlFunc_958_2009384,.Lfe16-OvlFunc_958_2009384
	.include "asm/maps/gondowan/ovl_cc0_c_c_c_c.s"
	.text


	.text
	.align	2, 0
