@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"hammet_palace.c"
	.code	16
.gcc2_compiled.:
	.include "asm/maps/hammet_palace/exports.s"
	.text

	.include "asm/maps/hammet_palace/ovl_30_a.s"
	.text

	.code	16
.text
	.align	2, 0
	.global	HammetPalace_GetSpecialExits
	.thumb_func
	.type	 HammetPalace_GetSpecialExits,function
HammetPalace_GetSpecialExits:
	mov	r0, #0
	bx	lr
.Lfe1:
	.size	 HammetPalace_GetSpecialExits,.Lfe1-HammetPalace_GetSpecialExits
	.align	2, 0
	.global	HammetPalace_GetExits
	.thumb_func
	.type	 HammetPalace_GetExits,function
HammetPalace_GetExits:
	ldr	r0, .L4
	bx	lr
.L5:
	.align	2, 0
.L4:
	.word	gScript_917__02009d9c
.Lfe2:
	.size	 HammetPalace_GetExits,.Lfe2-HammetPalace_GetExits
	.include "asm/maps/hammet_palace/ovl_30_c_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_938_20080d4
	.thumb_func
	.type	 OvlFunc_938_20080d4,function
OvlFunc_938_20080d4:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L7
	bl	__MessageID
	mov	r1, #0
	mov	r0, #13
	bl	__Func_8093054
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L8:
	.align	2, 0
.L7:
	.word	7043
.Lfe3:
	.size	 OvlFunc_938_20080d4,.Lfe3-OvlFunc_938_20080d4
	.align	2, 0
	.global	OvlFunc_938_20080f4
	.thumb_func
	.type	 OvlFunc_938_20080f4,function
OvlFunc_938_20080f4:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L10
	bl	__MessageID
	mov	r1, #0
	mov	r0, #16
	bl	__Func_8093054
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L11:
	.align	2, 0
.L10:
	.word	7048
.Lfe4:
	.size	 OvlFunc_938_20080f4,.Lfe4-OvlFunc_938_20080f4
	.align	2, 0
	.global	OvlFunc_938_2008114
	.thumb_func
	.type	 OvlFunc_938_2008114,function
OvlFunc_938_2008114:
	push	{lr}
	bl	__CutsceneStart
	mov	r1, #128
	lsl	r1, r1, #1
	mov	r2, #60
	mov	r0, #8
	bl	__MapActor_Emote
	ldr	r0, .L37
	bl	__MessageID
	mov	r2, #10
	mov	r0, #8
	mov	r1, #0
	bl	__ActorMessage_Wait
	mov	r0, #8
	mov	r1, #2
	bl	__Func_80925cc
	mov	r2, #10
	mov	r0, #8
	mov	r1, #0
	bl	__ActorMessage_Wait
	mov	r0, #8
	mov	r1, #4
	bl	__MapActor_DoAnim
	mov	r2, #10
	mov	r0, #8
	mov	r1, #0
	bl	__ActorMessage_Wait
	mov	r0, #8
	mov	r1, #3
	bl	__MapActor_DoAnim
	mov	r1, #0
	mov	r2, #10
	mov	r0, #8
	bl	__ActorMessage_Wait
	ldr	r0, .L37+4
	bl	__SetFlag
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L38:
	.align	2, 0
.L37:
	.word	7057
	.word	2323
.Lfe5:
	.size	 OvlFunc_938_2008114,.Lfe5-OvlFunc_938_2008114
	.include "asm/maps/hammet_palace/ovl_30_c_c_c_c_c.s"
	.text

	.include "asm/maps/hammet_palace/imports.s"
	.text


	.text
	.align	2, 0
