@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"kalay_rooms.c"
	.code	16
.gcc2_compiled.:
	.include "asm/maps/kalay_rooms/exports.s"
	.text

	.include "asm/maps/kalay_rooms/ovl_30_a.s"
	.text

	.code	16
.text
	.align	2, 0
	.global	KalayRooms_GetSpecialExits
	.thumb_func
	.type	 KalayRooms_GetSpecialExits,function
KalayRooms_GetSpecialExits:
	mov	r0, #0
	bx	lr
.Lfe1:
	.size	 KalayRooms_GetSpecialExits,.Lfe1-KalayRooms_GetSpecialExits
	.align	2, 0
	.global	KalayRooms_GetExits
	.thumb_func
	.type	 KalayRooms_GetExits,function
KalayRooms_GetExits:
	ldr	r0, .L4
	bx	lr
.L5:
	.align	2, 0
.L4:
	.word	gOvl_02008728
.Lfe2:
	.size	 KalayRooms_GetExits,.Lfe2-KalayRooms_GetExits
	.include "asm/maps/kalay_rooms/ovl_30_c_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_937_2008144
	.thumb_func
	.type	 OvlFunc_937_2008144,function
OvlFunc_937_2008144:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L7
	bl	__MessageID
	mov	r1, #0
	mov	r0, #12
	bl	__ActorMessage
	mov	r0, #145
	lsl	r0, r0, #4
	bl	__SetFlag
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L8:
	.align	2, 0
.L7:
	.word	6877
.Lfe3:
	.size	 OvlFunc_937_2008144,.Lfe3-OvlFunc_937_2008144
	.align	2, 0
	.global	OvlFunc_937_200816c
	.thumb_func
	.type	 OvlFunc_937_200816c,function
OvlFunc_937_200816c:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L10
	bl	__MessageID
	mov	r1, #0
	mov	r0, #16
	bl	__Func_8093054
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L11:
	.align	2, 0
.L10:
	.word	6883
.Lfe4:
	.size	 OvlFunc_937_200816c,.Lfe4-OvlFunc_937_200816c
	.align	2, 0
	.global	OvlFunc_937_200818c
	.thumb_func
	.type	 OvlFunc_937_200818c,function
OvlFunc_937_200818c:
	push	{lr}
	mov	r0, #0
	bl	__MapActor_GetActor
	ldr	r2, .L17
	ldrh	r3, [r0, #6]
	add	r3, r3, r2
	ldr	r2, .L17+4
	lsl	r3, r3, #16
	cmp	r3, r2
	bhi	.L13
	mov	r0, #7
	mov	r1, #8
	bl	__Func_80b3284
	b	.L14
.L13:
	bl	__CutsceneStart
	ldr	r0, .L17+8
	bl	__GetFlag
	cmp	r0, #0
	beq	.L15
	ldr	r0, .L17+12
	bl	__MessageID
	mov	r0, #8
	mov	r1, #0
	bl	__ActorMessage
	b	.L16
.L15:
	ldr	r0, .L17+16
	bl	__MessageID
	mov	r0, #8
	mov	r1, #0
	bl	__Func_8093054
	mov	r0, #145
	lsl	r0, r0, #4
	bl	__SetFlag
.L16:
	bl	__CutsceneEnd
.L14:
	pop	{r0}
	bx	r0
.L18:
	.align	2, 0
.L17:
	.word	-24577
	.word	1073610752
	.word	2321
	.word	6907
	.word	6871
.Lfe5:
	.size	 OvlFunc_937_200818c,.Lfe5-OvlFunc_937_200818c
	.include "asm/maps/kalay_rooms/ovl_30_c_c_c_c_c.s"
	.text

	.include "asm/maps/kalay_rooms/imports.s"
	.text


	.text
	.align	2, 0
