@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"kolima_forest_3.c"
	.code	16
.gcc2_compiled.:
	.include "asm/maps/kolima_forest_3/exports.s"
	.text

	.code	16
.text
	.align	2, 0
	.global	OvlFunc_915_2008030
	.thumb_func
	.type	 OvlFunc_915_2008030,function
OvlFunc_915_2008030:
	push	{r5, lr}
	ldmia	r0!, {r5}
	ldmia	r1!, {r3}
	ldmia	r0!, {r4}
	sub	r5, r5, r3
	ldmia	r1!, {r3}
	ldr	r2, [r1]
	sub	r4, r4, r3
	ldr	r3, [r0]
	sub	r3, r3, r2
	asr	r5, r5, #16
	asr	r4, r4, #16
	asr	r3, r3, #16
	mov	r0, r5
	mul	r0, r0, r5
	mov	r2, r4
	mul	r2, r2, r4
	mov	r1, r3
	mul	r1, r1, r3
	add	r0, r0, r2
	mov	r3, r1
	add	r0, r0, r3
	ldr	r3, .L4
	bl	_call_via_r3
	pop	{r5}
	pop	{r1}
	bx	r1
.L5:
	.align	2, 0
.L4:
	.word	Func_8000948
.Lfe1:
	.size	 OvlFunc_915_2008030,.Lfe1-OvlFunc_915_2008030
	.include "asm/maps/kolima_forest_3/ovl_30_a_a_a_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_915_20082a8
	.thumb_func
	.type	 OvlFunc_915_20082a8,function
OvlFunc_915_20082a8:
	push	{r5, r6, r7, lr}
	mov	r5, r0
	ldrh	r3, [r5, #6]
	ldr	r2, .L15
	lsr	r3, r3, #12
	lsl	r7, r3, #2
	ldr	r1, [r2, r7]
	ldr	r2, .L15+4
	ldr	r3, [r5, #8]
	and	r2, r2, r1
	sub	sp, sp, #12
	mov	r6, sp
	add	r3, r3, r2
	str	r3, [r6]
	ldr	r3, [r5, #12]
	str	r3, [r6, #4]
	ldr	r3, [r5, #16]
	lsl	r1, r1, #16
	add	r3, r3, r1
	mov	r0, r6
	mov	r1, r5
	str	r3, [r6, #8]
	bl	OvlFunc_915_200806c
	cmp	r0, #0
	beq	.L7
	ldr	r3, [r0, #80]
	ldr	r3, [r3, #40]
	mov	r2, #0
	ldrsh	r0, [r3, r2]
	ldr	r2, .L15+8
	mov	r1, #0
.L13:
	ldmia	r2!, {r3}
	cmp	r0, r3
	beq	.L12
	add	r1, r1, #1
	cmp	r1, #5
	bls	.L13
	mov	r3, #0
	str	r3, [r5, #36]
	str	r3, [r5, #44]
	mov	r3, #128
	lsl	r3, r3, #24
	str	r3, [r5, #56]
	str	r3, [r5, #64]
.L7:
	ldr	r3, .L15
	ldr	r2, .L15+4
	ldr	r1, [r3, r7]
	ldr	r3, [r5, #8]
	and	r2, r2, r1
	add	r3, r3, r2
	str	r3, [r6]
	ldr	r3, [r5, #12]
	str	r3, [r6, #4]
	ldr	r3, [r5, #16]
	lsl	r1, r1, #16
	add	r3, r3, r1
	mov	r0, r5
	mov	r1, r6
	str	r3, [r6, #8]
	bl	__TestCollision
	cmp	r0, #0
	ble	.L12
	mov	r3, #0
	str	r3, [r5, #36]
	str	r3, [r5, #44]
	mov	r3, #128
	lsl	r3, r3, #24
	str	r3, [r5, #56]
	str	r3, [r5, #64]
.L12:
	mov	r0, #0
	add	sp, sp, #12
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L16:
	.align	2, 0
.L15:
	.word	.Lm915_f10
	.word	-65536
	.word	.Lm915_f50
.Lfe2:
	.size	 OvlFunc_915_20082a8,.Lfe2-OvlFunc_915_20082a8
	.include "asm/maps/kolima_forest_3/ovl_30_a_a_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_915_2008474
	.thumb_func
	.type	 OvlFunc_915_2008474,function
OvlFunc_915_2008474:
	push	{r5, r6, r7, lr}
	mov	r7, fp
	mov	r6, sl
	mov	r5, r9
	push	{r5, r6, r7}
	mov	r7, r8
	push	{r7}
	mov	r6, r0
	sub	sp, sp, #32
	mov	r3, #0
	add	r0, sp, #16
	add	r1, r6, #4
	mov	r2, r6
	str	r3, [r6, #20]
	bl	OvlFunc_915_200834c
	mov	sl, r0
	cmp	r0, #0
	bne	.L18
	mov	r0, #0
	b	.L17
.L18:
	mov	r0, sl
	add	r0, r0, #34
	mov	r3, #2
	str	r0, [sp, #4]
	strb	r3, [r0]
	ldr	r3, [r6]
	mov	r1, #0
	str	r1, [sp, #12]
	ldr	r5, .L41
	lsl	r1, r3, #4
	add	r3, r1, #4
	ldr	r2, [r5, r3]
	cmp	r2, #0
	bge	.L19
	neg	r2, r2
.L19:
	mov	r3, r1
	add	r3, r3, #12
	ldr	r3, [r5, r3]
	cmp	r3, #0
	bge	.L20
	neg	r3, r3
.L20:
	add	r3, r2, r3
	asr	r3, r3, #4
	str	r3, [sp, #8]
	ldr	r2, [r5, r1]
	cmp	r2, #0
	bge	.L21
	neg	r2, r2
.L21:
	mov	r3, r1
	add	r3, r3, #8
	ldr	r3, [r5, r3]
	cmp	r3, #0
	bge	.L22
	neg	r3, r3
.L22:
	add	r3, r2, r3
	asr	r3, r3, #4
	mov	r9, r3
	ldr	r3, [sp, #16]
	ldr	r1, .L41+4
	add	r2, sp, #20
	lsl	r3, r3, #2
	mov	r8, r2
	ldr	r2, [r1, r3]
	ldr	r3, .L41+8
	mov	r4, sl
	and	r2, r2, r3
	ldr	r3, [r4, #8]
	mov	r0, r8
	add	r3, r3, r2
	str	r3, [r0]
	ldr	r0, [r4, #12]
	mov	r2, r8
	str	r0, [r2, #4]
	ldr	r3, [sp, #16]
	lsl	r3, r3, #2
	ldr	r2, [r1, r3]
	ldr	r3, [r4, #16]
	lsl	r2, r2, #16
	mov	r4, r8
	add	r3, r3, r2
	str	r3, [r4, #8]
	mov	r4, r6
	str	r0, [r6, #12]
	add	r4, r4, #8
	mov	fp, r8
.L23:
	ldr	r3, [r6]
	ldr	r0, .L41
	lsl	r3, r3, #4
	add	r3, r3, #4
	ldr	r2, [r0, r3]
	mov	r1, r8
	ldr	r3, [r1, #8]
	lsl	r2, r2, #16
	add	r3, r3, r2
	ldr	r2, [sp, #8]
	mov	r7, #0
	str	r3, [r6, #16]
	cmp	r7, r2
	bge	.L39
.L29:
	ldr	r3, [r6]
	ldr	r0, .L41
	lsl	r3, r3, #4
	ldr	r2, [r0, r3]
	mov	r1, r8
	ldr	r3, [r1]
	lsl	r2, r2, #16
	add	r3, r3, r2
	mov	r5, #0
	str	r3, [r6, #8]
	cmp	r5, r9
	bge	.L40
.L33:
	mov	r1, r4
	mov	r0, sl
	str	r4, [sp]
	bl	__TestCollision
	ldr	r4, [sp]
	cmp	r0, #2
	beq	.L35
	ldr	r3, [r4]
	mov	r2, #128
	lsl	r2, r2, #13
	add	r3, r3, r2
	add	r5, r5, #1
	str	r3, [r4]
	cmp	r5, r9
	blt	.L33
.L40:
	ldr	r3, [r6, #16]
	mov	r0, #128
	lsl	r0, r0, #13
	ldr	r1, [sp, #8]
	add	r3, r3, r0
	add	r7, r7, #1
	str	r3, [r6, #16]
	cmp	r7, r1
	blt	.L29
.L39:
	ldr	r2, [sp, #12]
	ldr	r3, [sp, #16]
	add	r2, r2, #1
	str	r2, [sp, #12]
	ldr	r0, .L41+4
	lsl	r3, r3, #2
	ldr	r2, [r0, r3]
	ldr	r3, .L41+8
	mov	r1, fp
	and	r2, r2, r3
	ldr	r3, [r1]
	add	r3, r3, r2
	str	r3, [r1]
	ldr	r3, [sp, #16]
	lsl	r3, r3, #2
	ldr	r2, [r0, r3]
	ldr	r3, [r1, #8]
	lsl	r2, r2, #16
	add	r3, r3, r2
	str	r3, [r1, #8]
	b	.L23
.L35:
	ldr	r2, [sp, #4]
	mov	r3, #0
	strb	r3, [r2]
	ldr	r3, [sp, #12]
	mov	r0, #0
	cmp	r3, #0
	beq	.L17
	ldr	r3, [sp, #16]
	ldr	r2, .L41+4
	lsl	r3, r3, #2
	ldr	r2, [r2, r3]
	ldr	r3, .L41+8
	ldr	r4, [sp, #12]
	and	r3, r3, r2
	mov	r1, r4
	mul	r1, r1, r3
	lsl	r2, r2, #16
	mul	r2, r2, r4
	mov	r0, sl
	ldr	r3, [r0, #8]
	add	r3, r3, r1
	str	r3, [r6, #8]
	ldr	r3, [r0, #12]
	str	r3, [r6, #12]
	ldr	r3, [r0, #16]
	add	r3, r3, r2
	str	r3, [r6, #16]
	mov	r0, #1
.L17:
	add	sp, sp, #32
	pop	{r3, r5, r6, r7}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	mov	fp, r7
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L42:
	.align	2, 0
.L41:
	.word	.Lm915_f68
	.word	.Lm915_f10
	.word	-65536
.Lfe3:
	.size	 OvlFunc_915_2008474,.Lfe3-OvlFunc_915_2008474
	.align	2, 0
	.global	OvlFunc_915_2008608
	.thumb_func
	.type	 OvlFunc_915_2008608,function
OvlFunc_915_2008608:
	sub	sp, sp, #16
	push	{r5, r6, r7, lr}
	mov	r7, fp
	mov	r6, sl
	mov	r5, r9
	push	{r5, r6, r7}
	mov	r7, r8
	push	{r7}
	sub	sp, sp, #40
	str	r0, [sp, #72]
	str	r1, [sp, #76]
	str	r2, [sp, #80]
	str	r3, [sp, #84]
	ldr	r3, .L53
	ldr	r3, [r3]
	mov	r0, #0
	str	r3, [sp, #12]
	bl	__MapActor_GetActor
	ldrh	r3, [r0, #6]
	ldr	r0, [sp, #76]
	lsr	r3, r3, #12
	mov	r8, r3
	bl	__MapActor_GetActor
	ldr	r3, [sp, #72]
	ldr	r4, .L53+4
	lsl	r1, r3, #4
	add	r3, r1, #4
	ldr	r2, [r4, r3]
	mov	r7, r0
	cmp	r2, #0
	bge	.L44
	neg	r2, r2
.L44:
	mov	r3, r1
	add	r3, r3, #12
	ldr	r3, [r4, r3]
	cmp	r3, #0
	bge	.L45
	neg	r3, r3
.L45:
	add	r3, r2, r3
	asr	r3, r3, #4
	str	r3, [sp, #8]
	ldr	r2, [r4, r1]
	cmp	r2, #0
	bge	.L46
	neg	r2, r2
.L46:
	mov	r3, r1
	add	r3, r3, #8
	ldr	r3, [r4, r3]
	cmp	r3, #0
	bge	.L47
	neg	r3, r3
.L47:
	add	r3, r2, r3
	asr	r3, r3, #4
	mov	r9, r3
	ldr	r5, .L53+8
	ldr	r3, [r7, #8]
	mov	r6, #128
	add	r0, sp, #28
	lsl	r6, r6, #8
	str	r6, [r7, #48]
	str	r5, [r7, #52]
	str	r3, [r0]
	ldr	r3, [r7, #16]
	str	r3, [r0, #8]
	ldr	r2, [sp, #72]
	lsl	r2, r2, #4
	ldr	r3, [r4, r2]
	ldr	r1, [r7, #8]
	lsl	r3, r3, #16
	add	r1, r1, r3
	mov	fp, r0
	add	r0, sp, #16
	str	r1, [r0]
	add	r2, r2, #4
	ldr	r3, [r4, r2]
	ldr	r2, [r7, #16]
	lsl	r3, r3, #16
	add	r2, r2, r3
	asr	r1, r1, #20
	asr	r2, r2, #20
	str	r1, [r0]
	str	r2, [r0, #8]
	ldr	r3, [sp, #8]
	str	r3, [sp]
	mov	r3, #0
	str	r3, [sp, #4]
	mov	r0, #0
	mov	r3, r9
	bl	OvlFunc_915_2008244
	mov	r2, r5
	mov	r0, #0
	mov	r1, r6
	bl	__MapActor_SetSpeed
	mov	r1, #8
	mov	r0, #0
	bl	__MapActor_SetAnim
	mov	r0, #15
	bl	__CutsceneWait
	mov	r4, fp
	ldr	r2, [sp, #80]
	ldr	r3, [r4]
	sub	r1, r2, r3
	cmp	r1, #0
	bge	.L48
	ldr	r0, .L53+12
	add	r1, r1, r0
.L48:
	mov	r4, fp
	ldr	r2, [sp, #88]
	ldr	r3, [r4, #8]
	sub	r2, r2, r3
	asr	r1, r1, #17
	cmp	r2, #0
	bge	.L49
	ldr	r0, .L53+12
	add	r2, r2, r0
.L49:
	asr	r2, r2, #17
	mov	r0, #0
	bl	__MapActor_TravelBy
	mov	r0, #0
	bl	__MapActor_GetActor
	ldr	r3, .L53+16
	str	r3, [r0, #108]
	mov	r0, #4
	bl	__CutsceneWait
	mov	r3, r8
	sub	r3, r3, #6
	cmp	r3, #7
	bhi	.L50
	mov	r0, r7
	mov	r1, #3
	bl	__Actor_SetAnim
	b	.L51
.L50:
	mov	r0, r7
	mov	r1, #2
	bl	__Actor_SetAnim
.L51:
	mov	r0, #239
	bl	__PlaySound
	mov	r0, r7
	ldr	r1, [sp, #80]
	ldr	r2, [sp, #84]
	ldr	r3, [sp, #88]
	bl	__Actor_TravelTo
	mov	r0, #0
	bl	__MapActor_WaitMovement
	mov	r0, #0
	mov	r1, #2
	bl	__MapActor_SetAnim
	mov	r0, #0
	ldr	r1, .L53+20
	ldr	r2, .L53+8
	.code	16
	bl	__MapActor_SetSpeed
	ldr	r2, .L53+24
	mov	r1, r8
	lsl	r3, r1, #2
	ldr	r0, [r2, r3]
	asr	r3, r0, #16
	lsl	r3, r3, #16
	lsl	r0, r0, #16
	asr	r1, r3, #16
	asr	r2, r0, #16
	lsr	r3, r3, #31
	lsr	r0, r0, #31
	add	r1, r1, r3
	add	r2, r2, r0
	asr	r1, r1, #1
	asr	r2, r2, #1
	mov	r0, #0
	bl	__MapActor_TravelBy
	ldr	r3, [sp, #92]
	cmp	r3, #0
	beq	.L52
	bl	_call_via_r3
.L52:
	mov	r0, #0
	bl	__MapActor_WaitMovement
	mov	r1, #1
	mov	r0, #0
	bl	__MapActor_SetAnim
	mov	r0, #0
	bl	__MapActor_GetActor
	mov	r2, #0
	str	r2, [r0, #108]
	mov	r0, r7
	bl	__Actor_WaitMovement
	mov	r0, #144
	lsl	r0, r0, #1
	bl	__PlaySound
	mov	r0, #213
	bl	__PlaySound
	ldr	r3, [sp, #80]
	str	r3, [r7, #8]
	ldr	r3, [sp, #88]
	str	r3, [r7, #16]
	mov	r3, #0
	str	r3, [r7, #36]
	str	r3, [r7, #44]
	mov	r0, r7
	mov	r1, #1
	bl	__Actor_SetAnim
	ldr	r2, [sp, #72]
	ldr	r4, .L53+4
	lsl	r2, r2, #4
	ldr	r3, [r4, r2]
	ldr	r0, [sp, #80]
	lsl	r3, r3, #16
	add	r2, r2, #4
	add	r0, r0, r3
	ldr	r3, [r4, r2]
	ldr	r1, [sp, #88]
	lsl	r3, r3, #16
	add	r1, r1, r3
	ldr	r2, [sp, #12]
	asr	r0, r0, #20
	asr	r1, r1, #20
	mov	sl, r4
	mov	r4, #158
	str	r0, [sp, #80]
	str	r1, [sp, #88]
	lsl	r4, r4, #1
	add	r3, r2, r4
	ldr	r3, [r3]
	mov	r8, r3
	mov	r2, r8
	asr	r2, r2, #20
	ldr	r4, [sp, #12]
	mov	r8, r2
	mov	r2, #160
	lsl	r2, r2, #1
	add	r3, r4, r2
	ldr	r6, [r3]
	mov	r4, r8
	asr	r6, r6, #20
	add	r3, r4, r0
	add	r2, r6, r1
	str	r3, [sp]
	str	r2, [sp, #4]
	ldr	r3, [sp, #8]
	mov	r2, r9
	bl	__Func_8010704
	ldr	r0, [sp, #8]
	ldr	r1, [sp, #80]
	ldr	r2, [sp, #88]
	str	r0, [sp]
	mov	r5, #255
	mov	r3, r9
	mov	r0, #0
	str	r5, [sp, #4]
	bl	OvlFunc_915_2008244
	ldr	r3, [sp, #8]
	ldr	r1, [sp, #80]
	ldr	r2, [sp, #88]
	str	r3, [sp]
	mov	r0, #2
	mov	r3, r9
	str	r5, [sp, #4]
	bl	OvlFunc_915_2008244
	ldr	r2, [sp, #72]
	mov	r4, sl
	lsl	r2, r2, #4
	ldr	r3, [r4, r2]
	mov	r0, fp
	ldr	r1, [r0]
	lsl	r3, r3, #16
	add	r2, r2, #4
	add	r1, r1, r3
	ldr	r3, [r4, r2]
	ldr	r2, [r0, #8]
	lsl	r3, r3, #16
	add	r2, r2, r3
	asr	r1, r1, #20
	asr	r2, r2, #20
	str	r1, [r0]
	str	r2, [r0, #8]
	add	r8, r8, r1
	add	r6, r6, r2
	str	r1, [sp]
	str	r2, [sp, #4]
	ldr	r3, [sp, #8]
	mov	r0, r8
	mov	r1, r6
	mov	r2, r9
	bl	__Func_8010704
	ldr	r3, [sp, #8]
	mov	r2, fp
	ldr	r1, [r2]
	mov	r4, #0
	ldr	r2, [r2, #8]
	mov	r0, #2
	str	r3, [sp]
	mov	r3, r9
	str	r4, [sp, #4]
	bl	OvlFunc_915_2008244
	bl	__MapActor_PlayPendingSound
	add	sp, sp, #40
	pop	{r3, r5, r6, r7}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	mov	fp, r7
	pop	{r5, r6, r7}
	pop	{r3}
	add	sp, sp, #16
	bx	r3
.L54:
	.align	2, 0
.L53:
	.word	iwram_3001e70
	.word	.Lm915_f68
	.word	6553
	.word	131071
	.word	OvlFunc_915_20082a8
	.word	19660
	.word	.Lm915_f10
.Lfe4:
	.size	 OvlFunc_915_2008608,.Lfe4-OvlFunc_915_2008608
	.include "asm/maps/kolima_forest_3/ovl_30_a_a_c_c_c.s"
	.text

	.code	16
	.align	2, 0
	.global	KolimaForest3_GetEntrances
	.thumb_func
	.type	 KolimaForest3_GetEntrances,function
KolimaForest3_GetEntrances:
	ldr	r0, .L56
	bx	lr
.L57:
	.align	2, 0
.L56:
	.word	gOvl_02008fc8
.Lfe5:
	.size	 KolimaForest3_GetEntrances,.Lfe5-KolimaForest3_GetEntrances
	.align	2, 0
	.global	KolimaForest3_GetSpecialExits
	.thumb_func
	.type	 KolimaForest3_GetSpecialExits,function
KolimaForest3_GetSpecialExits:
	mov	r0, #0
	bx	lr
.Lfe6:
	.size	 KolimaForest3_GetSpecialExits,.Lfe6-KolimaForest3_GetSpecialExits
	.align	2, 0
	.global	KolimaForest3_GetExits
	.thumb_func
	.type	 KolimaForest3_GetExits,function
KolimaForest3_GetExits:
	ldr	r0, .L60
	bx	lr
.L61:
	.align	2, 0
.L60:
	.word	gOvl_02009028
.Lfe7:
	.size	 KolimaForest3_GetExits,.Lfe7-KolimaForest3_GetExits
	.align	2, 0
	.global	KolimaForest3_GetActors
	.thumb_func
	.type	 KolimaForest3_GetActors,function
KolimaForest3_GetActors:
	ldr	r0, .L63
	bx	lr
.L64:
	.align	2, 0
.L63:
	.word	gOvl_02009038
.Lfe8:
	.size	 KolimaForest3_GetActors,.Lfe8-KolimaForest3_GetActors
	.include "asm/maps/kolima_forest_3/ovl_30_c_c_a_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_915_2008ba4
	.thumb_func
	.type	 OvlFunc_915_2008ba4,function
OvlFunc_915_2008ba4:
	push	{r5, lr}
	ldr	r3, .L66
	mov	r2, #250
	lsl	r2, r2, #1
	add	r3, r3, r2
	ldr	r0, [r3]
	sub	sp, sp, #12
	bl	__MapActor_GetActor
	ldr	r5, .L66+4
	ldr	r2, [r0, #8]
	mov	r4, #128
	lsl	r4, r4, #12
	and	r2, r2, r5
	mov	r1, sp
	add	r3, r2, r4
	str	r3, [r1]
	ldr	r3, [r0, #12]
	str	r3, [r1, #4]
	ldr	r3, [r0, #16]
	and	r3, r3, r5
	add	r3, r3, r4
	str	r3, [r1, #8]
	mov	r3, #160
	lsl	r3, r3, #14
	add	r2, r2, r3
	str	r2, [r1]
	mov	r0, r1
	bl	OvlFunc_915_2008aac
	add	sp, sp, #12
	pop	{r5}
	pop	{r0}
	bx	r0
.L67:
	.align	2, 0
.L66:
	.word	gState
	.word	-1048576
.Lfe9:
	.size	 OvlFunc_915_2008ba4,.Lfe9-OvlFunc_915_2008ba4
	.align	2, 0
	.global	KolimaForest3_GetEvents
	.thumb_func
	.type	 KolimaForest3_GetEvents,function
KolimaForest3_GetEvents:
	ldr	r0, .L69
	bx	lr
.L70:
	.align	2, 0
.L69:
	.word	gOvl_02009098
.Lfe10:
	.size	 KolimaForest3_GetEvents,.Lfe10-KolimaForest3_GetEvents
	.include "asm/maps/kolima_forest_3/ovl_30_c_c_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_915_2008d5c
	.thumb_func
	.type	 OvlFunc_915_2008d5c,function
OvlFunc_915_2008d5c:
	ldr	r2, .L79
	ldr	r3, .L79+4
	ldr	r0, [r2]
	ldr	r1, .L79+8
	ldr	r2, .L79+12
	stmia	r3!, {r0, r1, r2}
	sub	r3, #0xc
	.code	16
	bx	lr
.L80:
	.align	2, 0
.L79:
	.word	iwram_3001ed0
	.word	67109076
	.word	.Lm915_10e0
	.word	-2080374560
.Lfe11:
	.size	 OvlFunc_915_2008d5c,.Lfe11-OvlFunc_915_2008d5c
	.align	2, 0
	.global	OvlFunc_915_2008d7c
	.thumb_func
	.type	 OvlFunc_915_2008d7c,function
OvlFunc_915_2008d7c:
	ldr	r2, .L83
	ldr	r3, .L83+4
	ldr	r0, [r2]
	ldr	r1, .L83+8
	ldr	r2, .L83+12
	stmia	r3!, {r0, r1, r2}
	sub	r3, #0xc
	.code	16
	bx	lr
.L84:
	.align	2, 0
.L83:
	.word	iwram_3001ed0
	.word	67109076
	.word	.Lm915_17e0
	.word	-2080374560
.Lfe12:
	.size	 OvlFunc_915_2008d7c,.Lfe12-OvlFunc_915_2008d7c
	.include "asm/maps/kolima_forest_3/ovl_30_c_c_c_c_c.s"
	.text

	.include "asm/maps/kolima_forest_3/imports.s"
	.text


	.text
	.align	2, 0
