@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"lalivero.c"
	.code	16
.gcc2_compiled.:
	.include "asm/maps/lalivero/exports.s"
	.text

	.code	16
.text
	.align	2, 0
	.global	OvlFunc_966_2008030
	.thumb_func
	.type	 OvlFunc_966_2008030,function
OvlFunc_966_2008030:
	push	{lr}
	mov	r0, #23
	mov	r1, #2
	mov	r2, #6
	bl	__Func_80955b0
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_966_2008030,.Lfe1-OvlFunc_966_2008030
	.align	2, 0
	.global	Lalivero_GetEntrances
	.thumb_func
	.type	 Lalivero_GetEntrances,function
Lalivero_GetEntrances:
	ldr	r0, .L4
	bx	lr
.L5:
	.align	2, 0
.L4:
	.word	gOvl_0200975c
.Lfe2:
	.size	 Lalivero_GetEntrances,.Lfe2-Lalivero_GetEntrances
	.align	2, 0
	.global	Lalivero_GetSpecialExits
	.thumb_func
	.type	 Lalivero_GetSpecialExits,function
Lalivero_GetSpecialExits:
	mov	r0, #0
	bx	lr
.Lfe3:
	.size	 Lalivero_GetSpecialExits,.Lfe3-Lalivero_GetSpecialExits
	.align	2, 0
	.global	Lalivero_GetExits
	.thumb_func
	.type	 Lalivero_GetExits,function
Lalivero_GetExits:
	ldr	r0, .L8
	bx	lr
.L9:
	.align	2, 0
.L8:
	.word	gOvl_020098c4
.Lfe4:
	.size	 Lalivero_GetExits,.Lfe4-Lalivero_GetExits
	.align	2, 0
	.global	Lalivero_GetActors
	.thumb_func
	.type	 Lalivero_GetActors,function
Lalivero_GetActors:
	push	{lr}
	ldr	r0, .L12
	bl	__GetFlag
	cmp	r0, #0
	beq	.L11
	ldr	r0, .L12+4
	b	.L10
.L11:
	ldr	r0, .L12+8
.L10:
	pop	{r1}
	bx	r1
.L13:
	.align	2, 0
.L12:
	.word	2471
	.word	.Lm966_1a98
	.word	.Lm966_1900
.Lfe5:
	.size	 Lalivero_GetActors,.Lfe5-Lalivero_GetActors
	.include "asm/maps/lalivero/ovl_30_c_c_a_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_966_20081f0
	.thumb_func
	.type	 OvlFunc_966_20081f0,function
OvlFunc_966_20081f0:
	push	{lr}
	ldr	r3, .L15
	mov	r1, #182
	ldr	r2, [r3]
	lsl	r1, r1, #1
	add	r3, r2, r1
	mov	r1, #0
	ldrsh	r0, [r3, r1]
	mov	r3, #228
	lsl	r3, r3, #1
	add	r2, r2, r3
	mov	r3, #16
	str	r3, [r2]
	bl	__Func_8091e9c
	pop	{r0}
	bx	r0
.L16:
	.align	2, 0
.L15:
	.word	iwram_3001ebc
.Lfe6:
	.size	 OvlFunc_966_20081f0,.Lfe6-OvlFunc_966_20081f0
	.include "asm/maps/lalivero/ovl_30_c_c_c_a_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_966_20091bc
	.thumb_func
	.type	 OvlFunc_966_20091bc,function
OvlFunc_966_20091bc:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L30
	bl	__MessageID
	mov	r0, #1
	mov	r1, #0
	bl	__ActorMessage
	mov	r2, #16
	mov	r0, #0
	mov	r1, #0
	neg	r2, r2
	bl	__Func_8092304
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L31:
	.align	2, 0
.L30:
	.word	10423
.Lfe7:
	.size	 OvlFunc_966_20091bc,.Lfe7-OvlFunc_966_20091bc
	.align	2, 0
	.global	Lalivero_GetEvents
	.thumb_func
	.type	 Lalivero_GetEvents,function
Lalivero_GetEvents:
	push	{lr}
	ldr	r0, .L34
	bl	__GetFlag
	cmp	r0, #0
	beq	.L33
	ldr	r0, .L34+4
	b	.L32
.L33:
	ldr	r0, .L34+8
.L32:
	pop	{r1}
	bx	r1
.L35:
	.align	2, 0
.L34:
	.word	2471
	.word	.Lm966_1ee4
	.word	.Lm966_1d04
.Lfe8:
	.size	 Lalivero_GetEvents,.Lfe8-Lalivero_GetEvents
	.include "asm/maps/lalivero/ovl_30_c_c_c_c.s"
	.text

	.include "asm/maps/lalivero/imports.s"
	.text


	.text
	.align	2, 0
