@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"lunpa_rooms.c"
	.code	16
.gcc2_compiled.:
	.include "asm/maps/lunpa_rooms/exports.s"
	.text

	.code	16
.text
	.align	2, 0
	.global	LunpaRooms_GetEntrances
	.thumb_func
	.type	 LunpaRooms_GetEntrances,function
LunpaRooms_GetEntrances:
	ldr	r0, .L3
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	gOvl_020084f8
.Lfe1:
	.size	 LunpaRooms_GetEntrances,.Lfe1-LunpaRooms_GetEntrances
	.align	2, 0
	.global	LunpaRooms_GetSpecialExits
	.thumb_func
	.type	 LunpaRooms_GetSpecialExits,function
LunpaRooms_GetSpecialExits:
	mov	r0, #0
	bx	lr
.Lfe2:
	.size	 LunpaRooms_GetSpecialExits,.Lfe2-LunpaRooms_GetSpecialExits
	.align	2, 0
	.global	LunpaRooms_GetExits
	.thumb_func
	.type	 LunpaRooms_GetExits,function
LunpaRooms_GetExits:
	ldr	r0, .L7
	bx	lr
.L8:
	.align	2, 0
.L7:
	.word	gOvl_02008630
.Lfe3:
	.size	 LunpaRooms_GetExits,.Lfe3-LunpaRooms_GetExits
	.align	2, 0
	.global	LunpaRooms_GetActors
	.thumb_func
	.type	 LunpaRooms_GetActors,function
LunpaRooms_GetActors:
	ldr	r0, .L10
	bx	lr
.L11:
	.align	2, 0
.L10:
	.word	gOvl_0200865c
.Lfe4:
	.size	 LunpaRooms_GetActors,.Lfe4-LunpaRooms_GetActors
	.align	2, 0
	.global	LunpaRooms_GetEvents
	.thumb_func
	.type	 LunpaRooms_GetEvents,function
LunpaRooms_GetEvents:
	push	{lr}
	ldr	r3, .L17
	mov	r2, #225
	lsl	r2, r2, #1
	add	r3, r3, r2
	mov	r2, #0
	ldrsh	r3, [r3, r2]
	cmp	r3, #10
	bne	.L13
	ldr	r0, .L17+4
	b	.L12
.L13:
	ldr	r0, .L17+8
	bl	__GetFlag
	cmp	r0, #0
	beq	.L15
	ldr	r0, .L17+12
	b	.L12
.L15:
	ldr	r0, .L17+16
.L12:
	pop	{r1}
	bx	r1
.L18:
	.align	2, 0
.L17:
	.word	gState
	.word	.Lm940_c98
	.word	2369
	.word	.Lm940_a64
	.word	.Lm940_824
.Lfe5:
	.size	 LunpaRooms_GetEvents,.Lfe5-LunpaRooms_GetEvents
	.include "asm/maps/lunpa_rooms/ovl_30_c_c_a_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_940_20080fc
	.thumb_func
	.type	 OvlFunc_940_20080fc,function
OvlFunc_940_20080fc:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L20
	bl	__MessageID
	mov	r1, #0
	mov	r0, #20
	bl	__Func_8093054
	mov	r0, #148
	lsl	r0, r0, #4
	bl	__SetFlag
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L21:
	.align	2, 0
.L20:
	.word	7125
.Lfe6:
	.size	 OvlFunc_940_20080fc,.Lfe6-OvlFunc_940_20080fc
	.align	2, 0
	.global	OvlFunc_940_2008124
	.thumb_func
	.type	 OvlFunc_940_2008124,function
OvlFunc_940_2008124:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L23
	bl	__MessageID
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #148
	lsl	r0, r0, #4
	bl	__SetFlag
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L24:
	.align	2, 0
.L23:
	.word	7131
.Lfe7:
	.size	 OvlFunc_940_2008124,.Lfe7-OvlFunc_940_2008124
	.align	2, 0
	.global	OvlFunc_940_200814c
	.thumb_func
	.type	 OvlFunc_940_200814c,function
OvlFunc_940_200814c:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L26
	bl	__MessageID
	mov	r1, #0
	mov	r0, #18
	bl	__Func_8093054
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L27:
	.align	2, 0
.L26:
	.word	9470
.Lfe8:
	.size	 OvlFunc_940_200814c,.Lfe8-OvlFunc_940_200814c
	.include "asm/maps/lunpa_rooms/ovl_30_c_c_a_c_c_c_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_940_20081d8
	.thumb_func
	.type	 OvlFunc_940_20081d8,function
OvlFunc_940_20081d8:
	push	{lr}
	ldr	r0, .L39
	bl	__GetFlag
	cmp	r0, #0
	beq	.L29
	bl	__CutsceneStart
	ldr	r0, .L39+4
	bl	__MessageID
	mov	r0, #16
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	b	.L34
.L29:
	bl	__CutsceneStart
	ldr	r0, .L39+8
	bl	__MessageID
	mov	r0, #16
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
.L34:
	pop	{r0}
	bx	r0
.L40:
	.align	2, 0
.L39:
	.word	2369
	.word	9466
	.word	_MSG_1be0
.Lfe9:
	.size	 OvlFunc_940_20081d8,.Lfe9-OvlFunc_940_20081d8
	.include "asm/maps/lunpa_rooms/ovl_30_c_c_a_c_c_c_c_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_940_2008294
	.thumb_func
	.type	 OvlFunc_940_2008294,function
OvlFunc_940_2008294:
	push	{lr}
	ldr	r0, .L44
	bl	__GetFlag
	cmp	r0, #0
	beq	.L42
	ldr	r0, .L44+4
	bl	__MessageID
	mov	r0, #14
	mov	r1, #0
	bl	__ActorMessage
	b	.L43
.L42:
	ldr	r0, .L44+8
	bl	__MessageID
	mov	r0, #14
	mov	r1, #0
	bl	__ActorMessage
.L43:
	pop	{r0}
	bx	r0
.L45:
	.align	2, 0
.L44:
	.word	2369
	.word	9462
	.word	7134
.Lfe10:
	.size	 OvlFunc_940_2008294,.Lfe10-OvlFunc_940_2008294
	.align	2, 0
	.global	OvlFunc_940_20082d0
	.thumb_func
	.type	 OvlFunc_940_20082d0,function
OvlFunc_940_20082d0:
	push	{r5, lr}
	mov	r0, #0
	bl	__MapActor_GetActor
	ldrh	r5, [r0, #6]
	ldr	r0, .L55
	bl	__GetFlag
	cmp	r0, #0
	beq	.L47
	ldr	r2, .L55+4
	add	r3, r5, r2
	ldr	r2, .L55+8
	cmp	r3, r2
	bhi	.L48
	mov	r0, #29
	mov	r1, #14
	bl	__Func_80b0278
	b	.L54
.L48:
	bl	__CutsceneStart
	ldr	r0, .L55+12
	bl	__MessageID
	mov	r0, #14
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	b	.L54
.L47:
	ldr	r0, .L55+16
	bl	__MessageID
	mov	r0, #14
	mov	r1, #0
	bl	__ActorMessage
.L54:
	pop	{r5}
	pop	{r0}
	bx	r0
.L56:
	.align	2, 0
.L55:
	.word	2369
	.word	-40961
	.word	16382
	.word	9461
	.word	7117
.Lfe11:
	.size	 OvlFunc_940_20082d0,.Lfe11-OvlFunc_940_20082d0
	.align	2, 0
	.global	OvlFunc_940_2008338
	.thumb_func
	.type	 OvlFunc_940_2008338,function
OvlFunc_940_2008338:
	push	{lr}
	ldr	r0, .L60
	bl	__GetFlag
	cmp	r0, #0
	beq	.L58
	ldr	r0, .L60+4
	bl	__MessageID
	mov	r0, #15
	mov	r1, #0
	bl	__ActorMessage
	b	.L59
.L58:
	ldr	r0, .L60+8
	bl	__MessageID
	mov	r0, #15
	mov	r1, #0
	bl	__ActorMessage
.L59:
	pop	{r0}
	bx	r0
.L61:
	.align	2, 0
.L60:
	.word	2369
	.word	9464
	.word	7135
.Lfe12:
	.size	 OvlFunc_940_2008338,.Lfe12-OvlFunc_940_2008338
	.align	2, 0
	.global	OvlFunc_940_2008374
	.thumb_func
	.type	 OvlFunc_940_2008374,function
OvlFunc_940_2008374:
	push	{r5, lr}
	mov	r0, #0
	bl	__MapActor_GetActor
	ldrh	r5, [r0, #6]
	ldr	r0, .L71
	bl	__GetFlag
	cmp	r0, #0
	beq	.L63
	ldr	r2, .L71+4
	add	r3, r5, r2
	ldr	r2, .L71+8
	cmp	r3, r2
	bhi	.L64
	mov	r0, #30
	mov	r1, #15
	bl	__Func_80b0278
	b	.L70
.L64:
	bl	__CutsceneStart
	ldr	r0, .L71+12
	bl	__MessageID
	mov	r0, #15
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	b	.L70
.L63:
	ldr	r0, .L71+16
	bl	__MessageID
	mov	r0, #15
	mov	r1, #0
	bl	__ActorMessage
.L70:
	pop	{r5}
	pop	{r0}
	bx	r0
.L72:
	.align	2, 0
.L71:
	.word	2369
	.word	-40961
	.word	16382
	.word	9463
	.word	7118
.Lfe13:
	.size	 OvlFunc_940_2008374,.Lfe13-OvlFunc_940_2008374
	.include "asm/maps/lunpa_rooms/ovl_30_c_c_c_c_a_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_940_2008454
	.thumb_func
	.type	 OvlFunc_940_2008454,function
OvlFunc_940_2008454:
	push	{lr}
	mov	r0, #0
	bl	__MapActor_GetActor
	ldr	r2, .L76
	ldrh	r3, [r0, #6]
	add	r3, r3, r2
	ldr	r2, .L76+4
	cmp	r3, r2
	bhi	.L74
	mov	r0, #21
	bl	__UI_Sanctum
	b	.L75
.L74:
	ldr	r0, .L76+8
	bl	__MessageID
	mov	r0, #22
	mov	r1, #0
	bl	__ActorMessage
.L75:
	pop	{r0}
	bx	r0
.L77:
	.align	2, 0
.L76:
	.word	-40961
	.word	16382
	.word	9835
.Lfe14:
	.size	 OvlFunc_940_2008454,.Lfe14-OvlFunc_940_2008454
	.include "asm/maps/lunpa_rooms/ovl_30_c_c_c_c_c.s"
	.text

	.include "asm/maps/lunpa_rooms/imports.s"
	.text


	.text
	.align	2, 0
