@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"mercury_lighthouse_aerie.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	MercuryLighthouseAerie_GetEntrances
	.thumb_func
	.type	 MercuryLighthouseAerie_GetEntrances,function
MercuryLighthouseAerie_GetEntrances:
	ldr	r0, .L3
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	gOvl_0200b938
.Lfe1:
	.size	 MercuryLighthouseAerie_GetEntrances,.Lfe1-MercuryLighthouseAerie_GetEntrances
	.align	2, 0
	.global	MercuryLighthouseAerie_GetSpecialExits
	.thumb_func
	.type	 MercuryLighthouseAerie_GetSpecialExits,function
MercuryLighthouseAerie_GetSpecialExits:
	mov	r0, #0
	bx	lr
.Lfe2:
	.size	 MercuryLighthouseAerie_GetSpecialExits,.Lfe2-MercuryLighthouseAerie_GetSpecialExits
	.align	2, 0
	.global	MercuryLighthouseAerie_GetExits
	.thumb_func
	.type	 MercuryLighthouseAerie_GetExits,function
MercuryLighthouseAerie_GetExits:
	ldr	r0, .L7
	bx	lr
.L8:
	.align	2, 0
.L7:
	.word	gOvl_0200b9c8
.Lfe3:
	.size	 MercuryLighthouseAerie_GetExits,.Lfe3-MercuryLighthouseAerie_GetExits
	.align	2, 0
	.global	MercuryLighthouseAerie_GetActors
	.thumb_func
	.type	 MercuryLighthouseAerie_GetActors,function
MercuryLighthouseAerie_GetActors:
	push	{lr}
	ldr	r3, .L11
	mov	r2, #225
	lsl	r2, r2, #1
	add	r3, r3, r2
	mov	r2, #0
	ldrsh	r3, [r3, r2]
	cmp	r3, #1
	beq	.L10
	ldr	r0, .L11+4
	bl	__SetFlag
.L10:
	ldr	r0, .L11+8
	pop	{r1}
	bx	r1
.L12:
	.align	2, 0
.L11:
	.word	gState
	.word	595
	.word	.Lm925_39d4
.Lfe4:
	.size	 MercuryLighthouseAerie_GetActors,.Lfe4-MercuryLighthouseAerie_GetActors
	.align	2, 0
	.global	MercuryLighthouseAerie_GetEvents
	.thumb_func
	.type	 MercuryLighthouseAerie_GetEvents,function
MercuryLighthouseAerie_GetEvents:
	ldr	r0, .L14
	bx	lr
.L15:
	.align	2, 0
.L14:
	.word	gOvl_0200bbe4
.Lfe5:
	.size	 MercuryLighthouseAerie_GetEvents,.Lfe5-MercuryLighthouseAerie_GetEvents
	.include "asm/maps/mercury_lighthouse_aerie/ovl_314_c_c_c_a_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_925_2008890
	.thumb_func
	.type	 OvlFunc_925_2008890,function
OvlFunc_925_2008890:
	push	{r5, lr}
	ldmia	r0!, {r5}
	ldmia	r1!, {r3}
	ldmia	r0!, {r4}
	sub	r5, r5, r3
	ldmia	r1!, {r3}
	ldr	r2, [r1]
	sub	r4, r4, r3
	ldr	r3, [r0]
	sub	r3, r3, r2
	asr	r5, r5, #16
	asr	r4, r4, #16
	asr	r3, r3, #16
	mov	r0, r5
	mul	r0, r0, r5
	mov	r2, r4
	mul	r2, r2, r4
	mov	r1, r3
	mul	r1, r1, r3
	add	r0, r0, r2
	mov	r3, r1
	add	r0, r0, r3
	ldr	r3, .L18
	bl	_call_via_r3
	pop	{r5}
	pop	{r1}
	bx	r1
.L19:
	.align	2, 0
.L18:
	.word	Func_8000948
.Lfe6:
	.size	 OvlFunc_925_2008890,.Lfe6-OvlFunc_925_2008890
	.include "asm/maps/mercury_lighthouse_aerie/ovl_314_c_c_c_a_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_925_2008ad0
	.thumb_func
	.type	 OvlFunc_925_2008ad0,function
OvlFunc_925_2008ad0:
	push	{r5, lr}
	mov	r0, #0
	bl	__MapActor_GetActor
	mov	r3, #3
	add	r0, r0, #85
	strb	r3, [r0]
	mov	r0, #14
	bl	__MapActor_GetActor
	mov	r5, #4
	add	r0, r0, #85
	strb	r5, [r0]
	mov	r0, #15
	bl	__MapActor_GetActor
	add	r0, r0, #85
	strb	r5, [r0]
	mov	r0, #16
	bl	__MapActor_GetActor
	add	r0, r0, #85
	strb	r5, [r0]
	mov	r0, #17
	bl	__MapActor_GetActor
	add	r0, r0, #85
	strb	r5, [r0]
	mov	r0, #18
	bl	__MapActor_GetActor
	add	r0, r0, #85
	strb	r5, [r0]
	mov	r0, #19
	bl	__MapActor_GetActor
	add	r0, r0, #85
	strb	r5, [r0]
	pop	{r5}
	pop	{r0}
	bx	r0
.Lfe7:
	.size	 OvlFunc_925_2008ad0,.Lfe7-OvlFunc_925_2008ad0
	.include "asm/maps/mercury_lighthouse_aerie/ovl_314_c_c_c_a_c_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_925_200aeb8
	.thumb_func
	.type	 OvlFunc_925_200aeb8,function
OvlFunc_925_200aeb8:
	push	{lr}
	bl	__CutsceneStart
	mov	r1, #128
	.code	16
	mov	r2, #128
	.code	16
	mov	r0, #0
	.code	16
	lsl	r1, r1, #8
	lsl	r2, r2, #7
	bl	__MapActor_SetSpeed
	mov	r0, #0
	.code	16
	mov	r1, #104
	mov	r2, #152
	bl	__MapActor_TravelToAnimWait
	mov	r1, #128
	.code	16
	mov	r2, #60
	.code	16
	mov	r0, #0
	.code	16
	lsl	r1, r1, #7
	bl	__Func_8092adc
	mov	r0, #17
	.code	16
	mov	r1, #0
	bl	__Func_8092b08
	mov	r0, #18
	.code	16
	mov	r1, #0
	bl	__Func_8092b08
	bl	OvlFunc_925_200b208
	mov	r0, #1
	.code	16
	mov	r1, #1
	.code	16
	mov	r2, #1
	.code	16
	neg	r1, r1
	neg	r2, r2
	mov	r3, #0
	neg	r0, r0
	bl	__Func_80933f8
	mov	r0, #1
	bl	__Func_8091e9c
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.Lfe8:
	.size	 OvlFunc_925_200aeb8,.Lfe8-OvlFunc_925_200aeb8
	.include "asm/maps/mercury_lighthouse_aerie/ovl_314_c_c_c_a_c_c_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_925_200b438
	.thumb_func
	.type	 OvlFunc_925_200b438,function
OvlFunc_925_200b438:
	push	{lr}
	mov	r0, #93
	mov	r1, #1
	bl	__Func_8096fb0
	mov	r1, #9
	mov	r0, #24
	bl	__Func_80970f8
	bl	__Func_809728c
	mov	r0, #1
	bl	__FieldMove
	bl	__Func_8097174
	bl	__Func_8097194
	pop	{r0}
	bx	r0
.Lfe9:
	.size	 OvlFunc_925_200b438,.Lfe9-OvlFunc_925_200b438
	.include "asm/maps/mercury_lighthouse_aerie/ovl_314_c_c_c_c.s"
	.text


	.text
	.align	2, 0
