@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"sol.c"
	.code	16
.gcc2_compiled.:
	.include "asm/maps/sol/exports.s"
	.text

	.include "asm/maps/sol/ovl_30_a.s"
	.text

	.code	16
.text
	.align	2, 0
	.global	Sol_GetSpecialExits
	.thumb_func
	.type	 Sol_GetSpecialExits,function
Sol_GetSpecialExits:
	mov	r0, #0
	bx	lr
.Lfe1:
	.size	 Sol_GetSpecialExits,.Lfe1-Sol_GetSpecialExits
	.align	2, 0
	.global	Sol_GetExits
	.thumb_func
	.type	 Sol_GetExits,function
Sol_GetExits:
	ldr	r0, .L4
	bx	lr
.L5:
	.align	2, 0
.L4:
	.word	gOvl_02009f14
.Lfe2:
	.size	 Sol_GetExits,.Lfe2-Sol_GetExits
	.include "asm/maps/sol/ovl_30_c_c_a_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_895_20083bc
	.thumb_func
	.type	 OvlFunc_895_20083bc,function
OvlFunc_895_20083bc:
	push	{r5, lr}
	bl	__CutsceneStart
	ldr	r0, .L11
	bl	__GetFlag
	cmp	r0, #0
	beq	.L7
	ldr	r0, .L11+4
	mov	r1, #1
	bl	__Func_801776c
	b	.L8
.L7:
	ldr	r0, .L11+8
	bl	__GetFlag
	cmp	r0, #0
	beq	.L9
	ldr	r3, .L11+12
	ldr	r0, .L11+16
	mov	r1, #1
	ldr	r5, [r3]
	bl	__Func_801776c
	mov	r3, #185
	lsl	r3, r3, #1
	add	r2, r5, r3
	mov	r3, #1
	strh	r3, [r2]
	b	.L8
.L9:
	ldr	r0, .L11+16
	mov	r1, #1
	bl	__Func_801776c
.L8:
	bl	__CutsceneEnd
	pop	{r5}
	pop	{r0}
	bx	r0
.L12:
	.align	2, 0
.L11:
	.word	2081
	.word	4148
	.word	3842
	.word	iwram_3001ebc
	.word	4145
.Lfe3:
	.size	 OvlFunc_895_20083bc,.Lfe3-OvlFunc_895_20083bc
	.include "asm/maps/sol/ovl_30_c_c_a_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_895_200879c
	.thumb_func
	.type	 OvlFunc_895_200879c,function
OvlFunc_895_200879c:
	push	{r5, lr}
	ldr	r3, .L20
	ldr	r3, [r3]
	mov	r2, r3
	mov	r5, r0
	mov	r4, #8
	add	r2, r2, #52
.L19:
	ldmia	r2!, {r0}
	ldr	r3, [r0, #8]
	asr	r3, r3, #20
	cmp	r5, r3
	bne	.L17
	ldr	r3, [r0, #16]
	asr	r3, r3, #20
	cmp	r1, r3
	beq	.L13
.L17:
	add	r4, r4, #1
	cmp	r4, #65
	bls	.L19
	mov	r0, #0
.L13:
	pop	{r5}
	pop	{r1}
	bx	r1
.L21:
	.align	2, 0
.L20:
	.word	iwram_3001ebc
.Lfe4:
	.size	 OvlFunc_895_200879c,.Lfe4-OvlFunc_895_200879c
	.include "asm/maps/sol/ovl_30_c_c_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_895_2009aac
	.thumb_func
	.type	 OvlFunc_895_2009aac,function
OvlFunc_895_2009aac:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L27
	mov	r1, #1
	bl	__Func_801776c
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L28:
	.align	2, 0
.L27:
	.word	2387
.Lfe5:
	.size	 OvlFunc_895_2009aac,.Lfe5-OvlFunc_895_2009aac
	.include "asm/maps/sol/ovl_30_c_c_c_c.s"
	.text

	.include "asm/maps/sol/imports.s"
	.text


	.text
	.align	2, 0
