@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"sol_sanctum_4.c"
	.code	16
.gcc2_compiled.:
	.include "asm/maps/sol_sanctum_4/exports.s"
	.text

	.code	16
.text
	.align	2, 0
	.global	SolSanctum4_GetEntrances
	.thumb_func
	.type	 SolSanctum4_GetEntrances,function
SolSanctum4_GetEntrances:
	ldr	r0, .L3
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	gOvl_020080c0
.Lfe1:
	.size	 SolSanctum4_GetEntrances,.Lfe1-SolSanctum4_GetEntrances
	.align	2, 0
	.global	SolSanctum4_GetSpecialExits
	.thumb_func
	.type	 SolSanctum4_GetSpecialExits,function
SolSanctum4_GetSpecialExits:
	mov	r0, #0
	bx	lr
.Lfe2:
	.size	 SolSanctum4_GetSpecialExits,.Lfe2-SolSanctum4_GetSpecialExits
	.align	2, 0
	.global	SolSanctum4_GetExits
	.thumb_func
	.type	 SolSanctum4_GetExits,function
SolSanctum4_GetExits:
	ldr	r0, .L7
	bx	lr
.L8:
	.align	2, 0
.L7:
	.word	gOvl_02008120
.Lfe3:
	.size	 SolSanctum4_GetExits,.Lfe3-SolSanctum4_GetExits
	.align	2, 0
	.global	SolSanctum4_GetActors
	.thumb_func
	.type	 SolSanctum4_GetActors,function
SolSanctum4_GetActors:
	ldr	r0, .L10
	bx	lr
.L11:
	.align	2, 0
.L10:
	.word	gOvl_02008130
.Lfe4:
	.size	 SolSanctum4_GetActors,.Lfe4-SolSanctum4_GetActors
	.align	2, 0
	.global	SolSanctum4_GetEvents
	.thumb_func
	.type	 SolSanctum4_GetEvents,function
SolSanctum4_GetEvents:
	ldr	r0, .L13
	bx	lr
.L14:
	.align	2, 0
.L13:
	.word	gOvl_02008148
.Lfe5:
	.size	 SolSanctum4_GetEvents,.Lfe5-SolSanctum4_GetEvents
	.include "asm/maps/sol_sanctum_4/ovl_30_c_c.s"
	.text

	.include "asm/maps/sol_sanctum_4/imports.s"
	.text


	.text
	.align	2, 0
