@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"suhalla_gate_1.c"
	.code	16
.gcc2_compiled.:
	.include "asm/maps/suhalla_gate_1/exports.s"
	.text

	.code	16
.text
	.align	2, 0
	.global	OvlFunc_963_2008030
	.thumb_func
	.type	 OvlFunc_963_2008030,function
OvlFunc_963_2008030:
	push	{lr}
	mov	r0, #13
	mov	r1, #26
	bl	__Func_8091f14
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_963_2008030,.Lfe1-OvlFunc_963_2008030
	.include "asm/maps/suhalla_gate_1/ovl_30_a_c.s"
	.text

	.code	16
	.align	2, 0
	.global	SuhallaGate1_GetSpecialExits
	.thumb_func
	.type	 SuhallaGate1_GetSpecialExits,function
SuhallaGate1_GetSpecialExits:
	mov	r0, #0
	bx	lr
.Lfe2:
	.size	 SuhallaGate1_GetSpecialExits,.Lfe2-SuhallaGate1_GetSpecialExits
	.align	2, 0
	.global	SuhallaGate1_GetExits
	.thumb_func
	.type	 SuhallaGate1_GetExits,function
SuhallaGate1_GetExits:
	ldr	r0, .L5
	bx	lr
.L6:
	.align	2, 0
.L5:
	.word	gOvl_02008b48
.Lfe3:
	.size	 SuhallaGate1_GetExits,.Lfe3-SuhallaGate1_GetExits
	.include "asm/maps/suhalla_gate_1/ovl_30_c_c_a_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_963_20082f8
	.thumb_func
	.type	 OvlFunc_963_20082f8,function
OvlFunc_963_20082f8:
	push	{r5, lr}
	ldr	r3, .L8
	mov	r2, #182
	ldr	r3, [r3]
	lsl	r2, r2, #1
	add	r3, r3, r2
	mov	r0, #123
	mov	r2, #0
	ldrsh	r5, [r3, r2]
	bl	__PlaySound
	ldr	r0, .L8+4
	bl	__ClearFlag
	ldr	r0, .L8+8
	bl	__ClearFlag
	mov	r0, r5
	bl	__Func_8091e9c
	pop	{r5}
	pop	{r0}
	bx	r0
.L9:
	.align	2, 0
.L8:
	.word	iwram_3001ebc
	.word	2299
	.word	2300
.Lfe4:
	.size	 OvlFunc_963_20082f8,.Lfe4-OvlFunc_963_20082f8
	.include "asm/maps/suhalla_gate_1/ovl_30_c_c_a_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_963_20087ac
	.thumb_func
	.type	 OvlFunc_963_20087ac,function
OvlFunc_963_20087ac:
	push	{r5, lr}
	bl	__CutsceneStart
	ldr	r0, .L19
	bl	__MessageID
	mov	r0, #10
	mov	r1, #0
	mov	r2, #10
	bl	__ActorMessage_Wait
	mov	r5, #0
.L14:
	mov	r1, #0
	mov	r0, #10
	bl	__Func_8092950
	mov	r0, #10
	bl	__MapActor_GetActor
	mov	r1, #1
	bl	__Actor_SetSpriteFlags
	mov	r0, #4
	bl	__WaitFrames
	mov	r1, #15
	mov	r0, #10
	bl	__Func_8092950
	mov	r0, #10
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	add	r5, r5, #1
	mov	r0, #4
	bl	__WaitFrames
	cmp	r5, #5
	bls	.L14
	mov	r5, #0
.L18:
	mov	r1, #0
	mov	r0, #10
	bl	__Func_8092950
	mov	r0, #10
	bl	__MapActor_GetActor
	mov	r1, #1
	bl	__Actor_SetSpriteFlags
	mov	r0, #2
	bl	__WaitFrames
	mov	r1, #15
	mov	r0, #10
	bl	__Func_8092950
	mov	r0, #10
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	add	r5, r5, #1
	mov	r0, #2
	bl	__WaitFrames
	cmp	r5, #11
	bls	.L18
	mov	r1, #0
	mov	r2, #0
	mov	r0, #10
	bl	__MapActor_SetPos
	ldr	r0, .L19+4
	bl	__SetFlag
	bl	__CutsceneEnd
	pop	{r5}
	pop	{r0}
	bx	r0
.L20:
	.align	2, 0
.L19:
	.word	9837
	.word	2199
.Lfe5:
	.size	 OvlFunc_963_20087ac,.Lfe5-OvlFunc_963_20087ac
	.include "asm/maps/suhalla_gate_1/ovl_30_c_c_c.s"
	.text

	.include "asm/maps/suhalla_gate_1/imports.s"
	.text


	.text
	.align	2, 0
