@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"tolbi_bound_ship_hull.c"
	.code	16
.gcc2_compiled.:
	.include "asm/maps/tolbi_bound_ship_hull/exports.s"
	.text

	.code	16
.text
	.align	2, 0
	.global	OvlFunc_945_2008030
	.thumb_func
	.type	 OvlFunc_945_2008030,function
OvlFunc_945_2008030:
	push	{r5, lr}
	mov	r1, #1
	mov	r5, r0
	bl	__Actor_SetAnim
	mov	r3, #0
	str	r3, [r5, #8]
	str	r3, [r5, #12]
	str	r3, [r5, #16]
	str	r3, [r5, #36]
	str	r3, [r5, #40]
	str	r3, [r5, #44]
	mov	r3, #128
	lsl	r3, r3, #24
	str	r3, [r5, #60]
	str	r3, [r5, #56]
	mov	r0, #0
	pop	{r5}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 OvlFunc_945_2008030,.Lfe1-OvlFunc_945_2008030
	.include "asm/maps/tolbi_bound_ship_hull/ovl_30_a_a_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_945_20080b0
	.thumb_func
	.type	 OvlFunc_945_20080b0,function
OvlFunc_945_20080b0:
	push	{r5, lr}
	mov	r5, r0
	bl	__Random
	lsl	r0, r0, #6
	lsr	r0, r0, #16
	cmp	r0, #6
	bne	.L4
	mov	r3, #192
	lsl	r3, r3, #6
	b	.L7
.L4:
	cmp	r0, #9
	bne	.L5
	mov	r3, #160
	lsl	r3, r3, #7
.L7:
	strh	r3, [r5, #6]
.L5:
	mov	r0, #1
	pop	{r5}
	pop	{r1}
	bx	r1
.Lfe2:
	.size	 OvlFunc_945_20080b0,.Lfe2-OvlFunc_945_20080b0
	.align	2, 0
	.global	OvlFunc_945_20080d8
	.thumb_func
	.type	 OvlFunc_945_20080d8,function
OvlFunc_945_20080d8:
	push	{lr}
	mov	r1, r0
	add	r1, r1, #98
	ldrb	r3, [r1]
	mov	r2, #160
	add	r3, r3, #1
	strb	r3, [r1]
	lsl	r2, r2, #23
	lsl	r3, r3, #24
	cmp	r3, r2
	bls	.L9
	mov	r2, r0
	add	r2, r2, #102
	ldrh	r3, [r2]
	add	r3, r3, #1
	strh	r3, [r2]
.L9:
	pop	{r0}
	bx	r0
.Lfe3:
	.size	 OvlFunc_945_20080d8,.Lfe3-OvlFunc_945_20080d8
	.include "asm/maps/tolbi_bound_ship_hull/ovl_30_a_c_c.s"
	.text

	.code	16
	.align	2, 0
	.global	TolbiBoundShipHull_GetSpecialExits
	.thumb_func
	.type	 TolbiBoundShipHull_GetSpecialExits,function
TolbiBoundShipHull_GetSpecialExits:
	mov	r0, #0
	bx	lr
.Lfe4:
	.size	 TolbiBoundShipHull_GetSpecialExits,.Lfe4-TolbiBoundShipHull_GetSpecialExits
	.align	2, 0
	.global	TolbiBoundShipHull_GetExits
	.thumb_func
	.type	 TolbiBoundShipHull_GetExits,function
TolbiBoundShipHull_GetExits:
	ldr	r0, .L12
	bx	lr
.L13:
	.align	2, 0
.L12:
	.word	gOvl_0200eb94
.Lfe5:
	.size	 TolbiBoundShipHull_GetExits,.Lfe5-TolbiBoundShipHull_GetExits
	.include "asm/maps/tolbi_bound_ship_hull/ovl_30_c_c_a_a_a_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_945_2008708
	.thumb_func
	.type	 OvlFunc_945_2008708,function
OvlFunc_945_2008708:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L15
	bl	__MessageID
	mov	r1, #0
	mov	r0, #12
	bl	__Func_8093054
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L16:
	.align	2, 0
.L15:
	.word	7633
.Lfe6:
	.size	 OvlFunc_945_2008708,.Lfe6-OvlFunc_945_2008708
	.include "asm/maps/tolbi_bound_ship_hull/ovl_30_c_c_a_a_a_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_945_20088a8
	.thumb_func
	.type	 OvlFunc_945_20088a8,function
OvlFunc_945_20088a8:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L20
	bl	__GetFlag
	cmp	r0, #0
	beq	.L18
	ldr	r0, .L20+4
	bl	__MessageID
	mov	r0, #10
	mov	r1, #0
	bl	__Func_8093054
	b	.L19
.L18:
	ldr	r0, .L20+8
	bl	__MessageID
	mov	r0, #10
	mov	r1, #0
	bl	__ActorMessage
.L19:
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L21:
	.align	2, 0
.L20:
	.word	2341
	.word	7705
	.word	7504
.Lfe7:
	.size	 OvlFunc_945_20088a8,.Lfe7-OvlFunc_945_20088a8
	.include "asm/maps/tolbi_bound_ship_hull/ovl_30_c_c_a_a_c_a_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_945_2008a80
	.thumb_func
	.type	 OvlFunc_945_2008a80,function
OvlFunc_945_2008a80:
	push	{r5, lr}
	mov	r0, #138
	lsl	r0, r0, #4
	bl	__GetFlag
	cmp	r0, #0
	beq	.L23
	bl	__CutsceneStart
	mov	r1, #129
	lsl	r1, r1, #1
	mov	r0, #11
	bl	__MapActor_Surprise
	mov	r0, #40
	bl	__CutsceneWait
	ldr	r0, .L35
	bl	__MessageID
	mov	r0, #11
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	b	.L24
.L23:
	mov	r0, #192
	lsl	r0, r0, #2
	bl	__GetFlag
	cmp	r0, #0
	beq	.L25
	bl	OvlFunc_945_20092dc
	mov	r5, r0
	bl	__CutsceneStart
	mov	r0, r5
	bl	OvlFunc_945_2009190
	ldr	r0, .L35+4
	bl	__MessageID
	mov	r0, #11
	bl	OvlFunc_945_200c86c
	mov	r0, r5
	mov	r1, #2
	bl	__MapActor_SetAnim
	mov	r0, #0
	bl	__MapActor_GetActor
	cmp	r0, #0
	beq	.L26
	mov	r3, #10
	ldrsh	r1, [r0, r3]
	mov	r3, #18
	ldrsh	r2, [r0, r3]
	mov	r0, r5
	bl	__MapActor_TravelTo
.L26:
	mov	r0, r5
	bl	__MapActor_WaitMovement
	mov	r0, r5
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	bl	__CutsceneEnd
	b	.L24
.L25:
	ldr	r0, .L35+8
	bl	__GetFlag
	cmp	r0, #0
	beq	.L28
	ldr	r1, .L35+12
	ldr	r2, .L35+16
	b	.L34
.L28:
	ldr	r0, .L35+20
	bl	__GetFlag
	cmp	r0, #0
	beq	.L30
	ldr	r1, .L35+12
	ldr	r2, .L35+24
	b	.L34
.L30:
	ldr	r0, .L35+28
	bl	__GetFlag
	cmp	r0, #0
	beq	.L32
	ldr	r1, .L35+12
	ldr	r2, .L35+32
.L34:
	mov	r0, #11
	bl	OvlFunc_945_2009804
	b	.L24
.L32:
	ldr	r1, .L35+12
	ldr	r2, .L35+36
	mov	r0, #11
	bl	OvlFunc_945_2009804
.L24:
	pop	{r5}
	pop	{r0}
	bx	r0
.L36:
	.align	2, 0
.L35:
	.word	8007
	.word	_MSG_1ea0
	.word	2347
	.word	7806
	.word	2451
	.word	2346
	.word	2330
	.word	2345
	.word	2360
	.word	2351
.Lfe8:
	.size	 OvlFunc_945_2008a80,.Lfe8-OvlFunc_945_2008a80
	.include "asm/maps/tolbi_bound_ship_hull/ovl_30_c_c_a_a_c_a_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_945_20092dc
	.thumb_func
	.type	 OvlFunc_945_20092dc,function
OvlFunc_945_20092dc:
	push	{r5, lr}
	ldr	r0, .L43
	mov	r5, #0
	bl	__GetFlag
	cmp	r0, #0
	beq	.L38
	mov	r5, #3
	b	.L39
.L38:
	ldr	r0, .L43+4
	bl	__GetFlag
	cmp	r0, #0
	beq	.L40
	mov	r5, #2
	b	.L39
.L40:
	ldr	r0, .L43+8
	bl	__GetFlag
	cmp	r0, #0
	beq	.L39
	mov	r5, #1
.L39:
	mov	r0, r5
	mov	r1, #1
	bl	OvlFunc_945_200cfa8
	pop	{r5}
	pop	{r1}
	bx	r1
.L44:
	.align	2, 0
.L43:
	.word	2347
	.word	2346
	.word	2345
.Lfe9:
	.size	 OvlFunc_945_20092dc,.Lfe9-OvlFunc_945_20092dc
	.align	2, 0
	.global	OvlFunc_945_2009324
	.thumb_func
	.type	 OvlFunc_945_2009324,function
OvlFunc_945_2009324:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L50
	bl	__GetFlag
	cmp	r0, #0
	beq	.L46
	ldr	r0, .L50+4
	bl	__MessageID
	b	.L47
.L46:
	ldr	r0, .L50+8
	bl	__GetFlag
	cmp	r0, #0
	beq	.L48
	ldr	r0, .L50+12
	bl	__MessageID
	b	.L47
.L48:
	ldr	r0, .L50+16
	bl	__MessageID
.L47:
	mov	r0, #18
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L51:
	.align	2, 0
.L50:
	.word	2348
	.word	7886
	.word	2357
	.word	7887
	.word	7888
.Lfe10:
	.size	 OvlFunc_945_2009324,.Lfe10-OvlFunc_945_2009324
	.align	2, 0
	.global	OvlFunc_945_2009378
	.thumb_func
	.type	 OvlFunc_945_2009378,function
OvlFunc_945_2009378:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L57
	bl	__GetFlag
	cmp	r0, #0
	beq	.L53
	ldr	r0, .L57+4
	bl	__MessageID
	b	.L54
.L53:
	ldr	r0, .L57+8
	bl	__GetFlag
	cmp	r0, #0
	beq	.L55
	ldr	r0, .L57+12
	bl	__MessageID
	b	.L54
.L55:
	ldr	r0, .L57+16
	bl	__MessageID
.L54:
	mov	r0, #19
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L58:
	.align	2, 0
.L57:
	.word	2349
	.word	7886
	.word	2358
	.word	7887
	.word	7888
.Lfe11:
	.size	 OvlFunc_945_2009378,.Lfe11-OvlFunc_945_2009378
	.align	2, 0
	.global	OvlFunc_945_20093cc
	.thumb_func
	.type	 OvlFunc_945_20093cc,function
OvlFunc_945_20093cc:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L64
	bl	__GetFlag
	cmp	r0, #0
	beq	.L60
	ldr	r0, .L64+4
	bl	__MessageID
	b	.L61
.L60:
	ldr	r0, .L64+8
	bl	__GetFlag
	cmp	r0, #0
	beq	.L62
	ldr	r0, .L64+12
	bl	__MessageID
	b	.L61
.L62:
	ldr	r0, .L64+16
	bl	__MessageID
.L61:
	mov	r0, #20
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L65:
	.align	2, 0
.L64:
	.word	2350
	.word	7886
	.word	2359
	.word	7887
	.word	7888
.Lfe12:
	.size	 OvlFunc_945_20093cc,.Lfe12-OvlFunc_945_20093cc
	.align	2, 0
	.global	OvlFunc_945_2009420
	.thumb_func
	.type	 OvlFunc_945_2009420,function
OvlFunc_945_2009420:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L69
	bl	__GetFlag
	cmp	r0, #0
	beq	.L67
	ldr	r0, .L69+4
	bl	__MessageID
	b	.L68
.L67:
	ldr	r0, .L69+8
	bl	__MessageID
.L68:
	mov	r0, #21
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L70:
	.align	2, 0
.L69:
	.word	2351
	.word	7889
	.word	7890
.Lfe13:
	.size	 OvlFunc_945_2009420,.Lfe13-OvlFunc_945_2009420
	.align	2, 0
	.global	OvlFunc_945_200945c
	.thumb_func
	.type	 OvlFunc_945_200945c,function
OvlFunc_945_200945c:
	push	{lr}
	bl	__CutsceneStart
	mov	r0, #147
	lsl	r0, r0, #4
	bl	__GetFlag
	cmp	r0, #0
	beq	.L72
	ldr	r0, .L76
	bl	__MessageID
	b	.L73
.L72:
	ldr	r0, .L76+4
	bl	__GetFlag
	cmp	r0, #0
	beq	.L74
	ldr	r0, .L76+8
	bl	__MessageID
	b	.L73
.L74:
	ldr	r0, .L76+12
	bl	__MessageID
.L73:
	mov	r0, #22
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L77:
	.align	2, 0
.L76:
	.word	7886
	.word	2361
	.word	7887
	.word	7888
.Lfe14:
	.size	 OvlFunc_945_200945c,.Lfe14-OvlFunc_945_200945c
	.align	2, 0
	.global	OvlFunc_945_20094b0
	.thumb_func
	.type	 OvlFunc_945_20094b0,function
OvlFunc_945_20094b0:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L83
	bl	__GetFlag
	cmp	r0, #0
	beq	.L79
	ldr	r0, .L83+4
	bl	__MessageID
	b	.L80
.L79:
	ldr	r0, .L83+8
	bl	__GetFlag
	cmp	r0, #0
	beq	.L81
	ldr	r0, .L83+12
	bl	__MessageID
	b	.L80
.L81:
	ldr	r0, .L83+16
	bl	__MessageID
.L80:
	mov	r0, #23
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L84:
	.align	2, 0
.L83:
	.word	2353
	.word	7886
	.word	2362
	.word	7887
	.word	7888
.Lfe15:
	.size	 OvlFunc_945_20094b0,.Lfe15-OvlFunc_945_20094b0
	.align	2, 0
	.global	OvlFunc_945_2009504
	.thumb_func
	.type	 OvlFunc_945_2009504,function
OvlFunc_945_2009504:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L90
	bl	__GetFlag
	cmp	r0, #0
	beq	.L86
	ldr	r0, .L90+4
	bl	__MessageID
	b	.L87
.L86:
	ldr	r0, .L90+8
	bl	__GetFlag
	cmp	r0, #0
	beq	.L88
	ldr	r0, .L90+12
	bl	__MessageID
	b	.L87
.L88:
	ldr	r0, .L90+16
	bl	__MessageID
.L87:
	mov	r0, #24
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L91:
	.align	2, 0
.L90:
	.word	2354
	.word	7886
	.word	2363
	.word	7887
	.word	7888
.Lfe16:
	.size	 OvlFunc_945_2009504,.Lfe16-OvlFunc_945_2009504
	.align	2, 0
	.global	OvlFunc_945_2009558
	.thumb_func
	.type	 OvlFunc_945_2009558,function
OvlFunc_945_2009558:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L95
	bl	__GetFlag
	cmp	r0, #0
	beq	.L93
	ldr	r0, .L95+4
	bl	__MessageID
	b	.L94
.L93:
	ldr	r0, .L95+8
	bl	__MessageID
.L94:
	mov	r0, #25
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L96:
	.align	2, 0
.L95:
	.word	2355
	.word	7889
	.word	7890
.Lfe17:
	.size	 OvlFunc_945_2009558,.Lfe17-OvlFunc_945_2009558
	.align	2, 0
	.global	OvlFunc_945_2009594
	.thumb_func
	.type	 OvlFunc_945_2009594,function
OvlFunc_945_2009594:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L102
	bl	__GetFlag
	cmp	r0, #0
	beq	.L98
	ldr	r0, .L102+4
	bl	__MessageID
	b	.L99
.L98:
	ldr	r0, .L102+8
	bl	__GetFlag
	cmp	r0, #0
	beq	.L100
	ldr	r0, .L102+12
	bl	__MessageID
	b	.L99
.L100:
	ldr	r0, .L102+16
	bl	__MessageID
.L99:
	mov	r0, #18
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L103:
	.align	2, 0
.L102:
	.word	2348
	.word	7899
	.word	2357
	.word	7900
	.word	7901
.Lfe18:
	.size	 OvlFunc_945_2009594,.Lfe18-OvlFunc_945_2009594
	.align	2, 0
	.global	OvlFunc_945_20095e8
	.thumb_func
	.type	 OvlFunc_945_20095e8,function
OvlFunc_945_20095e8:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L109
	bl	__GetFlag
	cmp	r0, #0
	beq	.L105
	ldr	r0, .L109+4
	bl	__MessageID
	b	.L106
.L105:
	ldr	r0, .L109+8
	bl	__GetFlag
	cmp	r0, #0
	beq	.L107
	ldr	r0, .L109+12
	bl	__MessageID
	b	.L106
.L107:
	ldr	r0, .L109+16
	bl	__MessageID
.L106:
	mov	r0, #19
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L110:
	.align	2, 0
.L109:
	.word	2349
	.word	7899
	.word	2358
	.word	7900
	.word	7901
.Lfe19:
	.size	 OvlFunc_945_20095e8,.Lfe19-OvlFunc_945_20095e8
	.align	2, 0
	.global	OvlFunc_945_200963c
	.thumb_func
	.type	 OvlFunc_945_200963c,function
OvlFunc_945_200963c:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L116
	bl	__GetFlag
	cmp	r0, #0
	beq	.L112
	ldr	r0, .L116+4
	bl	__MessageID
	b	.L113
.L112:
	ldr	r0, .L116+8
	bl	__GetFlag
	cmp	r0, #0
	beq	.L114
	ldr	r0, .L116+12
	bl	__MessageID
	b	.L113
.L114:
	ldr	r0, .L116+16
	bl	__MessageID
.L113:
	mov	r0, #20
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L117:
	.align	2, 0
.L116:
	.word	2350
	.word	7899
	.word	2359
	.word	7900
	.word	7901
.Lfe20:
	.size	 OvlFunc_945_200963c,.Lfe20-OvlFunc_945_200963c
	.align	2, 0
	.global	OvlFunc_945_2009690
	.thumb_func
	.type	 OvlFunc_945_2009690,function
OvlFunc_945_2009690:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L121
	bl	__GetFlag
	cmp	r0, #0
	beq	.L119
	ldr	r0, .L121+4
	bl	__MessageID
	b	.L120
.L119:
	ldr	r0, .L121+8
	bl	__MessageID
.L120:
	mov	r0, #21
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L122:
	.align	2, 0
.L121:
	.word	2351
	.word	7902
	.word	7903
.Lfe21:
	.size	 OvlFunc_945_2009690,.Lfe21-OvlFunc_945_2009690
	.align	2, 0
	.global	OvlFunc_945_20096cc
	.thumb_func
	.type	 OvlFunc_945_20096cc,function
OvlFunc_945_20096cc:
	push	{lr}
	bl	__CutsceneStart
	mov	r0, #147
	lsl	r0, r0, #4
	bl	__GetFlag
	cmp	r0, #0
	beq	.L124
	ldr	r0, .L128
	bl	__MessageID
	b	.L125
.L124:
	ldr	r0, .L128+4
	bl	__GetFlag
	cmp	r0, #0
	beq	.L126
	ldr	r0, .L128+8
	bl	__MessageID
	b	.L125
.L126:
	ldr	r0, .L128+12
	bl	__MessageID
.L125:
	mov	r0, #22
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L129:
	.align	2, 0
.L128:
	.word	7899
	.word	2361
	.word	7900
	.word	7901
.Lfe22:
	.size	 OvlFunc_945_20096cc,.Lfe22-OvlFunc_945_20096cc
	.align	2, 0
	.global	OvlFunc_945_2009720
	.thumb_func
	.type	 OvlFunc_945_2009720,function
OvlFunc_945_2009720:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L135
	bl	__GetFlag
	cmp	r0, #0
	beq	.L131
	ldr	r0, .L135+4
	bl	__MessageID
	b	.L132
.L131:
	ldr	r0, .L135+8
	bl	__GetFlag
	cmp	r0, #0
	beq	.L133
	ldr	r0, .L135+12
	bl	__MessageID
	b	.L132
.L133:
	ldr	r0, .L135+16
	bl	__MessageID
.L132:
	mov	r0, #23
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L136:
	.align	2, 0
.L135:
	.word	2353
	.word	7899
	.word	2362
	.word	7900
	.word	7901
.Lfe23:
	.size	 OvlFunc_945_2009720,.Lfe23-OvlFunc_945_2009720
	.align	2, 0
	.global	OvlFunc_945_2009774
	.thumb_func
	.type	 OvlFunc_945_2009774,function
OvlFunc_945_2009774:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L142
	bl	__GetFlag
	cmp	r0, #0
	beq	.L138
	ldr	r0, .L142+4
	bl	__MessageID
	b	.L139
.L138:
	ldr	r0, .L142+8
	bl	__GetFlag
	cmp	r0, #0
	beq	.L140
	ldr	r0, .L142+12
	bl	__MessageID
	b	.L139
.L140:
	ldr	r0, .L142+16
	bl	__MessageID
.L139:
	mov	r0, #24
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L143:
	.align	2, 0
.L142:
	.word	2354
	.word	7899
	.word	2363
	.word	7900
	.word	7901
.Lfe24:
	.size	 OvlFunc_945_2009774,.Lfe24-OvlFunc_945_2009774
	.align	2, 0
	.global	OvlFunc_945_20097c8
	.thumb_func
	.type	 OvlFunc_945_20097c8,function
OvlFunc_945_20097c8:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L147
	bl	__GetFlag
	cmp	r0, #0
	beq	.L145
	ldr	r0, .L147+4
	bl	__MessageID
	b	.L146
.L145:
	ldr	r0, .L147+8
	bl	__MessageID
.L146:
	mov	r0, #25
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L148:
	.align	2, 0
.L147:
	.word	2355
	.word	7902
	.word	7903
.Lfe25:
	.size	 OvlFunc_945_20097c8,.Lfe25-OvlFunc_945_20097c8
	.include "asm/maps/tolbi_bound_ship_hull/ovl_30_c_c_c_c_c_c_a_a_a_a_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_945_200c0e8
	.thumb_func
	.type	 OvlFunc_945_200c0e8,function
OvlFunc_945_200c0e8:
	push	{lr}
	bl	__CutsceneStart
	mov	r2, #1
	mov	r0, #15
	mov	r1, #1
	bl	OvlFunc_945_200c8e8
	mov	r1, #1
	mov	r0, #8
	bl	__Func_80925cc
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #192
	mov	r2, #20
	mov	r0, #8
	.code	16
	lsl	r1, r1, #6
	bl	__Func_8092adc
	mov	r1, #2
	mov	r0, #8
	bl	__Func_809259c
	ldr	r0, .L150
	bl	__MessageID
	mov	r0, #8
	mov	r1, #0
	mov	r2, #20
	bl	__ActorMessage_Wait
	mov	r0, #9
	mov	r1, #14
	mov	r2, #0
	bl	OvlFunc_945_200c8e8
	pop	{r0}
	bx	r0
.L151:
	.align	2, 0
.L150:
	.word	_MSG_1e40
.Lfe26:
	.size	 OvlFunc_945_200c0e8,.Lfe26-OvlFunc_945_200c0e8
	.include "asm/maps/tolbi_bound_ship_hull/ovl_30_c_c_c_c_c_c_a_a_a_a_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_945_200c218
	.thumb_func
	.type	 OvlFunc_945_200c218,function
OvlFunc_945_200c218:
	push	{lr}
	bl	__CutsceneStart
	mov	r0, #24
	mov	r1, #1
	mov	r2, #0
	bl	OvlFunc_945_200c8e8
	mov	r0, #25
	mov	r1, #0
	mov	r2, #0
	bl	OvlFunc_945_200c8e8
	mov	r1, #11
	mov	r2, #12
	mov	r0, #19
	bl	OvlFunc_945_200c8e8
	bl	OvlFunc_945_200d2f4
	ldr	r0, .L153
	bl	__SetFlag
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L154:
	.align	2, 0
.L153:
	.word	2344
.Lfe27:
	.size	 OvlFunc_945_200c218,.Lfe27-OvlFunc_945_200c218
	.include "asm/maps/tolbi_bound_ship_hull/ovl_30_c_c_c_c_c_c_a_a_a_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_945_200c86c
	.thumb_func
	.type	 OvlFunc_945_200c86c,function
OvlFunc_945_200c86c:
	push	{lr}
	mov	r1, #0
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	pop	{r0}
	bx	r0
.Lfe28:
	.size	 OvlFunc_945_200c86c,.Lfe28-OvlFunc_945_200c86c
	.align	2, 0
	.global	OvlFunc_945_200c880
	.thumb_func
	.type	 OvlFunc_945_200c880,function
OvlFunc_945_200c880:
	push	{lr}
	lsl	r1, r1, #16
	lsr	r1, r1, #16
	mov	r2, #10
	bl	__Func_8092adc
	pop	{r0}
	bx	r0
.Lfe29:
	.size	 OvlFunc_945_200c880,.Lfe29-OvlFunc_945_200c880
	.align	2, 0
	.global	OvlFunc_945_200c890
	.thumb_func
	.type	 OvlFunc_945_200c890,function
OvlFunc_945_200c890:
	push	{r5, r6, lr}
	mov	r5, r0
	lsl	r1, r1, #16
	lsl	r2, r2, #16
	mov	r6, r3
	bl	__MapActor_SetPos
	mov	r0, r5
	bl	__MapActor_GetActor
	strh	r6, [r0, #6]
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.Lfe30:
	.size	 OvlFunc_945_200c890,.Lfe30-OvlFunc_945_200c890
	.align	2, 0
	.global	OvlFunc_945_200c8ac
	.thumb_func
	.type	 OvlFunc_945_200c8ac,function
OvlFunc_945_200c8ac:
	push	{r5, r6, lr}
	mov	r5, r3
	mov	r3, #1
	bic	r3, r3, r5
	bl	__Func_80933f8
	mov	r3, #128
	ldr	r6, .L161
	lsl	r3, r3, #21
	and	r3, r3, r5
	and	r6, r6, r5
	cmp	r3, #0
	beq	.L159
	bl	__Func_8093530
.L159:
	mov	r3, #128
	lsl	r3, r3, #17
	and	r3, r3, r5
	cmp	r3, #0
	beq	.L160
	bl	__Func_800fe9c
.L160:
	mov	r0, r6
	bl	__CutsceneWait
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L162:
	.align	2, 0
.L161:
	.word	4369
.Lfe31:
	.size	 OvlFunc_945_200c8ac,.Lfe31-OvlFunc_945_200c8ac
	.include "asm/maps/tolbi_bound_ship_hull/ovl_30_c_c_c_c_c_c_a_c_c_a_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_945_200d004
	.thumb_func
	.type	 OvlFunc_945_200d004,function
OvlFunc_945_200d004:
	push	{lr}
	ldr	r1, .L164
	mov	r0, #8
	bl	OvlFunc_945_200d038
	ldr	r1, .L164+4
	mov	r0, #8
	bl	OvlFunc_945_200d038
	ldr	r1, .L164+8
	mov	r0, #8
	bl	OvlFunc_945_200d038
	mov	r1, #153
	lsl	r1, r1, #4
	mov	r0, #8
	bl	OvlFunc_945_200d038
	pop	{r0}
	bx	r0
.L165:
	.align	2, 0
.L164:
	.word	2348
	.word	2357
	.word	2327
.Lfe32:
	.size	 OvlFunc_945_200d004,.Lfe32-OvlFunc_945_200d004
	.align	2, 0
	.global	OvlFunc_945_200d038
	.thumb_func
	.type	 OvlFunc_945_200d038,function
OvlFunc_945_200d038:
	push	{r5, r6, r7, lr}
	mov	r6, r0
	mov	r5, r1
	mov	r7, #0
.L170:
	mov	r0, r5
	bl	__GetFlag
	cmp	r0, #0
	beq	.L169
	mov	r0, r6
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	b	.L166
.L169:
	add	r7, r7, #1
	add	r6, r6, #1
	add	r5, r5, #1
	cmp	r7, #8
	bls	.L170
.L166:
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe33:
	.size	 OvlFunc_945_200d038,.Lfe33-OvlFunc_945_200d038
	.include "asm/maps/tolbi_bound_ship_hull/ovl_30_c_c_c_c_c_c_c_a_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_945_200d684
	.thumb_func
	.type	 OvlFunc_945_200d684,function
OvlFunc_945_200d684:
	push	{r5, lr}
	mov	r1, #0
	mov	r0, #0
	bl	OvlFunc_945_200cfa8
	mov	r5, r0
	bl	__CutsceneStart
	mov	r0, #24
	mov	r1, #1
	mov	r2, #0
	bl	OvlFunc_945_200c8e8
	mov	r1, #0
	mov	r2, #0
	mov	r0, #25
	bl	OvlFunc_945_200c8e8
	mov	r0, #0
	bl	OvlFunc_945_200b7d8
	mov	r1, r5
	mov	r0, #19
	mov	r2, #12
	bl	OvlFunc_945_200c8e8
	mov	r1, #0
	mov	r2, #0
	mov	r0, #11
	bl	__MapActor_SetPos
	bl	OvlFunc_945_200d2f4
	ldr	r0, .L174
	bl	__SetFlag
	bl	__CutsceneEnd
	pop	{r5}
	pop	{r0}
	bx	r0
.L175:
	.align	2, 0
.L174:
	.word	2345
.Lfe34:
	.size	 OvlFunc_945_200d684,.Lfe34-OvlFunc_945_200d684
	.include "asm/maps/tolbi_bound_ship_hull/ovl_30_c_c_c_c_c_c_c_a_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_945_200d780
	.thumb_func
	.type	 OvlFunc_945_200d780,function
OvlFunc_945_200d780:
	push	{r5, r6, lr}
	mov	r1, #0
	mov	r0, #0
	bl	OvlFunc_945_200cfa8
	mov	r1, #0
	mov	r6, r0
	mov	r0, #1
	bl	OvlFunc_945_200cfa8
	mov	r5, r0
	bl	__CutsceneStart
	mov	r0, #24
	mov	r1, #1
	mov	r2, #0
	bl	OvlFunc_945_200c8e8
	mov	r1, #0
	mov	r2, #0
	mov	r0, #25
	bl	OvlFunc_945_200c8e8
	mov	r0, #0
	bl	OvlFunc_945_200b7d8
	mov	r1, r6
	mov	r2, r5
	mov	r0, #19
	bl	OvlFunc_945_200c8e8
	mov	r0, #11
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	mov	r1, #0
	mov	r2, #0
	mov	r0, #12
	bl	__MapActor_SetPos
	bl	OvlFunc_945_200d2f4
	ldr	r0, .L181
	bl	__SetFlag
	bl	__CutsceneEnd
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L182:
	.align	2, 0
.L181:
	.word	2346
.Lfe35:
	.size	 OvlFunc_945_200d780,.Lfe35-OvlFunc_945_200d780
	.include "asm/maps/tolbi_bound_ship_hull/ovl_30_c_c_c_c_c_c_c_c.s"
	.text

	.include "asm/maps/tolbi_bound_ship_hull/imports.s"
	.text


	.text
	.align	2, 0
