@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"tolbi.c"
	.code	16
.gcc2_compiled.:
	.include "asm/maps/tolbi/exports.s"
	.text

	.code	16
.text
	.align	2, 0
	.global	OvlFunc_949_2008030
	.thumb_func
	.type	 OvlFunc_949_2008030,function
OvlFunc_949_2008030:
	push	{lr}
	mov	r0, #31
	mov	r1, #2
	mov	r2, #4
	bl	__Func_80955b0
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_949_2008030,.Lfe1-OvlFunc_949_2008030
	.align	2, 0
	.global	OvlFunc_949_2008040
	.thumb_func
	.type	 OvlFunc_949_2008040,function
OvlFunc_949_2008040:
	push	{r5, lr}
	ldmia	r0!, {r5}
	ldmia	r1!, {r3}
	ldmia	r0!, {r4}
	sub	r5, r5, r3
	ldmia	r1!, {r3}
	ldr	r2, [r1]
	sub	r4, r4, r3
	ldr	r3, [r0]
	sub	r3, r3, r2
	asr	r5, r5, #16
	asr	r4, r4, #16
	asr	r3, r3, #16
	mov	r0, r5
	mul	r0, r0, r5
	mov	r2, r4
	mul	r2, r2, r4
	mov	r1, r3
	mul	r1, r1, r3
	add	r0, r0, r2
	mov	r3, r1
	add	r0, r0, r3
	ldr	r3, .L5
	bl	_call_via_r3
	pop	{r5}
	pop	{r1}
	bx	r1
.L6:
	.align	2, 0
.L5:
	.word	Func_8000948
.Lfe2:
	.size	 OvlFunc_949_2008040,.Lfe2-OvlFunc_949_2008040
	.include "asm/maps/tolbi/ovl_30_a_a_c_c.s"
	.text

	.code	16
	.align	2, 0
	.global	Tolbi_GetEntrances
	.thumb_func
	.type	 Tolbi_GetEntrances,function
Tolbi_GetEntrances:
	ldr	r0, .L8
	bx	lr
.L9:
	.align	2, 0
.L8:
	.word	gOvl_02009060
.Lfe3:
	.size	 Tolbi_GetEntrances,.Lfe3-Tolbi_GetEntrances
	.align	2, 0
	.global	Tolbi_GetSpecialExits
	.thumb_func
	.type	 Tolbi_GetSpecialExits,function
Tolbi_GetSpecialExits:
	mov	r0, #0
	bx	lr
.Lfe4:
	.size	 Tolbi_GetSpecialExits,.Lfe4-Tolbi_GetSpecialExits
	.align	2, 0
	.global	Tolbi_GetExits
	.thumb_func
	.type	 Tolbi_GetExits,function
Tolbi_GetExits:
	ldr	r0, .L12
	bx	lr
.L13:
	.align	2, 0
.L12:
	.word	gOvl_020091f8
.Lfe5:
	.size	 Tolbi_GetExits,.Lfe5-Tolbi_GetExits
	.align	2, 0
	.global	Tolbi_GetActors
	.thumb_func
	.type	 Tolbi_GetActors,function
Tolbi_GetActors:
	ldr	r0, .L15
	bx	lr
.L16:
	.align	2, 0
.L15:
	.word	gOvl_02009238
.Lfe6:
	.size	 Tolbi_GetActors,.Lfe6-Tolbi_GetActors
	.include "asm/maps/tolbi/ovl_30_c_c_a_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_949_20082b8
	.thumb_func
	.type	 OvlFunc_949_20082b8,function
OvlFunc_949_20082b8:
	push	{lr}
	ldr	r0, .L18
	bl	__MessageID
	mov	r0, #1
	neg	r0, r0
	mov	r1, #0
	bl	__ActorMessage
	pop	{r0}
	bx	r0
.L19:
	.align	2, 0
.L18:
	.word	3638
.Lfe7:
	.size	 OvlFunc_949_20082b8,.Lfe7-OvlFunc_949_20082b8
	.align	2, 0
	.global	OvlFunc_949_20082d4
	.thumb_func
	.type	 OvlFunc_949_20082d4,function
OvlFunc_949_20082d4:
	push	{lr}
	ldr	r0, .L21
	bl	__MessageID
	mov	r0, #1
	neg	r0, r0
	mov	r1, #0
	bl	__ActorMessage
	pop	{r0}
	bx	r0
.L22:
	.align	2, 0
.L21:
	.word	3639
.Lfe8:
	.size	 OvlFunc_949_20082d4,.Lfe8-OvlFunc_949_20082d4
	.include "asm/maps/tolbi/ovl_30_c_c_a_c_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	Tolbi_GetEvents
	.thumb_func
	.type	 Tolbi_GetEvents,function
Tolbi_GetEvents:
	push	{lr}
	mov	r0, #149
	lsl	r0, r0, #4
	bl	__GetFlag
	cmp	r0, #0
	beq	.L24
	ldr	r0, .L28
	b	.L23
.L24:
	ldr	r0, .L28+4
	bl	__GetFlag
	cmp	r0, #0
	beq	.L26
	ldr	r0, .L28+8
	b	.L23
.L26:
	ldr	r0, .L28+12
.L23:
	pop	{r1}
	bx	r1
.L29:
	.align	2, 0
.L28:
	.word	.Lm949_1a9c
	.word	2402
	.word	gScript_960__020097a8
	.word	.Lm949_14a8
.Lfe9:
	.size	 Tolbi_GetEvents,.Lfe9-Tolbi_GetEvents
	.align	2, 0
	.global	OvlFunc_949_20084e8
	.thumb_func
	.type	 OvlFunc_949_20084e8,function
OvlFunc_949_20084e8:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L31
	bl	__MessageID
	mov	r1, #0
	mov	r0, #15
	bl	__Func_8093054
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L32:
	.align	2, 0
.L31:
	.word	8082
.Lfe10:
	.size	 OvlFunc_949_20084e8,.Lfe10-OvlFunc_949_20084e8
	.align	2, 0
	.global	OvlFunc_949_2008508
	.thumb_func
	.type	 OvlFunc_949_2008508,function
OvlFunc_949_2008508:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L34
	bl	__MessageID
	mov	r1, #0
	mov	r0, #24
	bl	__Func_8093054
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L35:
	.align	2, 0
.L34:
	.word	8093
.Lfe11:
	.size	 OvlFunc_949_2008508,.Lfe11-OvlFunc_949_2008508
	.align	2, 0
	.global	OvlFunc_949_2008528
	.thumb_func
	.type	 OvlFunc_949_2008528,function
OvlFunc_949_2008528:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L37
	bl	__MessageID
	mov	r1, #192
	mov	r2, #0
	mov	r0, #25
	.code	16
	lsl	r1, r1, #8
	bl	__Func_8092adc
	mov	r0, #25
	mov	r1, #0
	bl	__ActorMessage
	mov	r1, #128
	mov	r2, #0
	mov	r0, #25
	.code	16
	lsl	r1, r1, #8
	bl	__Func_8092adc
	mov	r0, #25
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L38:
	.align	2, 0
.L37:
	.word	_MSG_1fa0
.Lfe12:
	.size	 OvlFunc_949_2008528,.Lfe12-OvlFunc_949_2008528
	.align	2, 0
	.global	OvlFunc_949_2008568
	.thumb_func
	.type	 OvlFunc_949_2008568,function
OvlFunc_949_2008568:
	push	{lr}
	bl	__CutsceneStart
	mov	r1, #128
	mov	r2, #0
	mov	r0, #26
	.code	16
	lsl	r1, r1, #7
	bl	__Func_8092adc
	mov	r1, #2
	mov	r0, #26
	bl	__Func_809259c
	ldr	r0, .L40
	bl	__MessageID
	mov	r0, #26
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L41:
	.align	2, 0
.L40:
	.word	8098
.Lfe13:
	.size	 OvlFunc_949_2008568,.Lfe13-OvlFunc_949_2008568
	.align	2, 0
	.global	OvlFunc_949_200859c
	.thumb_func
	.type	 OvlFunc_949_200859c,function
OvlFunc_949_200859c:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L47
	bl	__MessageID
	mov	r0, #27
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L48:
	.align	2, 0
.L47:
	.word	8099
.Lfe14:
	.size	 OvlFunc_949_200859c,.Lfe14-OvlFunc_949_200859c
	.align	2, 0
	.global	OvlFunc_949_20085bc
	.thumb_func
	.type	 OvlFunc_949_20085bc,function
OvlFunc_949_20085bc:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L50
	bl	__MessageID
	mov	r1, #0
	mov	r0, #24
	bl	__Func_8093054
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L51:
	.align	2, 0
.L50:
	.word	9055
.Lfe15:
	.size	 OvlFunc_949_20085bc,.Lfe15-OvlFunc_949_20085bc
	.include "asm/maps/tolbi/ovl_30_c_c_a_c_c_c_c_c_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_949_2008954
	.thumb_func
	.type	 OvlFunc_949_2008954,function
OvlFunc_949_2008954:
	push	{lr}
	mov	r0, #30
	bl	__Func_8091e9c
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.Lfe16:
	.size	 OvlFunc_949_2008954,.Lfe16-OvlFunc_949_2008954
	.align	2, 0
	.global	OvlFunc_949_2008964
	.thumb_func
	.type	 OvlFunc_949_2008964,function
OvlFunc_949_2008964:
	push	{lr}
	ldr	r3, .L54
	mov	r2, #182
	ldr	r3, [r3]
	lsl	r2, r2, #1
	add	r3, r3, r2
	mov	r2, #0
	ldrsh	r0, [r3, r2]
	bl	__Func_8091e9c
	pop	{r0}
	bx	r0
.L55:
	.align	2, 0
.L54:
	.word	iwram_3001ebc
.Lfe17:
	.size	 OvlFunc_949_2008964,.Lfe17-OvlFunc_949_2008964
	.include "asm/maps/tolbi/ovl_30_c_c_c_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_949_2008ca8
	.thumb_func
	.type	 OvlFunc_949_2008ca8,function
OvlFunc_949_2008ca8:
	push	{r5, lr}
	mov	r0, #9
	sub	sp, sp, #8
	bl	__MapActor_GetActor
	mov	r5, r0
	cmp	r5, #0
	beq	.L57
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r1, r5
	mov	r2, #2
	add	r1, r1, #35
	strb	r2, [r1]
	mov	r2, r5
	mov	r3, #0
	add	r2, r2, #85
	strb	r3, [r2]
.L57:
	mov	r0, #9
	mov	r1, #5
	bl	__MapActor_SetAnim
	mov	r3, #34
	mov	r2, #16
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r1, #16
	mov	r2, #1
	mov	r3, #1
	mov	r0, #36
	bl	__Func_8010704
	ldr	r0, .L62
	bl	__SetFlag
	add	sp, sp, #8
	pop	{r5}
	pop	{r0}
	bx	r0
.L63:
	.align	2, 0
.L62:
	.word	513
.Lfe18:
	.size	 OvlFunc_949_2008ca8,.Lfe18-OvlFunc_949_2008ca8
	.include "asm/maps/tolbi/ovl_30_c_c_c_c_c.s"
	.text

	.include "asm/maps/tolbi/imports.s"
	.text


	.text
	.align	2, 0
