@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"vale_sanctum.c"
	.code	16
.gcc2_compiled.:
	.include "asm/maps/vale_sanctum/exports.s"
	.text

	.code	16
.text
	.align	2, 0
	.global	OvlFunc_888_2008030
	.thumb_func
	.type	 OvlFunc_888_2008030,function
OvlFunc_888_2008030:
	push	{r5, lr}
	mov	r5, r0
	mov	r3, r5
	add	r3, r3, #100
	mov	r2, #0
	ldrsh	r0, [r3, r2]
	bl	__MapActor_GetActor
	mov	r2, r0
	ldr	r3, [r5, #16]
	ldr	r0, [r2, #16]
	ldr	r1, [r2, #8]
	sub	r0, r0, r3
	ldr	r3, [r5, #8]
	sub	r1, r1, r3
	bl	__atan2
	strh	r0, [r5, #6]
	mov	r0, #0
	pop	{r5}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 OvlFunc_888_2008030,.Lfe1-OvlFunc_888_2008030
	.align	2, 0
	.global	ValeSanctum_GetEntrances
	.thumb_func
	.type	 ValeSanctum_GetEntrances,function
ValeSanctum_GetEntrances:
	ldr	r0, .L4
	bx	lr
.L5:
	.align	2, 0
.L4:
	.word	gOvl_0200baa8
.Lfe2:
	.size	 ValeSanctum_GetEntrances,.Lfe2-ValeSanctum_GetEntrances
	.align	2, 0
	.global	ValeSanctum_GetSpecialExits
	.thumb_func
	.type	 ValeSanctum_GetSpecialExits,function
ValeSanctum_GetSpecialExits:
	mov	r0, #0
	bx	lr
.Lfe3:
	.size	 ValeSanctum_GetSpecialExits,.Lfe3-ValeSanctum_GetSpecialExits
	.align	2, 0
	.global	ValeSanctum_GetExits
	.thumb_func
	.type	 ValeSanctum_GetExits,function
ValeSanctum_GetExits:
	ldr	r0, .L8
	bx	lr
.L9:
	.align	2, 0
.L8:
	.word	gOvl_0200bbc8
.Lfe4:
	.size	 ValeSanctum_GetExits,.Lfe4-ValeSanctum_GetExits
	.include "asm/maps/vale_sanctum/ovl_30_c_c_a_a_a_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_888_2008574
	.thumb_func
	.type	 OvlFunc_888_2008574,function
OvlFunc_888_2008574:
	push	{lr}
	bl	__CutsceneStart
	mov	r1, #0
	mov	r2, #0
	mov	r0, #10
	bl	__MapActor_Face
	mov	r0, #10
	bl	__CutsceneWait
	ldr	r0, .L16
	bl	__MessageID
	mov	r1, #0
	mov	r0, #10
	bl	__ShowActorMessage_NoWait
	mov	r0, #0
	mov	r1, #0
	bl	__Func_8091c7c
	cmp	r0, #1
	bne	.L11
	ldr	r3, .L16+4
	ldr	r2, [r3]
	mov	r3, #236
	lsl	r3, r3, #1
	add	r2, r2, r3
	ldrh	r3, [r2]
	add	r3, r3, #1
	strh	r3, [r2]
.L11:
	mov	r0, #10
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L17:
	.align	2, 0
.L16:
	.word	4511
	.word	iwram_3001ebc
.Lfe5:
	.size	 OvlFunc_888_2008574,.Lfe5-OvlFunc_888_2008574
	.include "asm/maps/vale_sanctum/ovl_30_c_c_a_a_a_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_888_200b2a8
	.thumb_func
	.type	 OvlFunc_888_200b2a8,function
OvlFunc_888_200b2a8:
	push	{lr}
	mov	r0, #0
	bl	__MapActor_GetActor
	ldr	r2, .L20
	ldrh	r3, [r0, #6]
	add	r3, r3, r2
	ldr	r2, .L20+4
	lsl	r3, r3, #16
	mov	r0, #1
	cmp	r3, r2
	bls	.L18
	mov	r0, #0
.L18:
	pop	{r1}
	bx	r1
.L21:
	.align	2, 0
.L20:
	.word	24575
	.word	1073610752
.Lfe6:
	.size	 OvlFunc_888_200b2a8,.Lfe6-OvlFunc_888_200b2a8
	.align	2, 0
	.global	OvlFunc_888_200b2d0
	.thumb_func
	.type	 OvlFunc_888_200b2d0,function
OvlFunc_888_200b2d0:
	push	{lr}
	bl	OvlFunc_888_200b2a8
	cmp	r0, #0
	beq	.L23
	mov	r0, #8
	bl	__UI_Sanctum
	b	.L24
.L23:
	bl	__CutsceneStart
	ldr	r0, .L29
	bl	__GetFlag
	cmp	r0, #0
	beq	.L25
	ldr	r0, .L29+4
	bl	__MessageID
	b	.L26
.L25:
	ldr	r0, .L29+8
	bl	__GetFlag
	cmp	r0, #0
	beq	.L27
	ldr	r0, .L29+12
	bl	__MessageID
	b	.L26
.L27:
	ldr	r0, .L29+16
	bl	__MessageID
.L26:
	mov	r0, #8
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
.L24:
	pop	{r0}
	bx	r0
.L30:
	.align	2, 0
.L29:
	.word	2170
	.word	7164
	.word	2069
	.word	4509
	.word	4149
.Lfe7:
	.size	 OvlFunc_888_200b2d0,.Lfe7-OvlFunc_888_200b2d0
	.include "asm/maps/vale_sanctum/ovl_30_c_c_a_a_c_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_888_200b45c
	.thumb_func
	.type	 OvlFunc_888_200b45c,function
OvlFunc_888_200b45c:
	push	{lr}
	bl	OvlFunc_888_200b2a8
	cmp	r0, #0
	beq	.L32
	mov	r0, #8
	bl	__UI_Sanctum
	b	.L33
.L32:
	bl	__CutsceneStart
	ldr	r0, .L36
	bl	__GetFlag
	cmp	r0, #0
	beq	.L34
	ldr	r0, .L36+4
	bl	__MessageID
	b	.L35
.L34:
	ldr	r0, .L36+8
	bl	__MessageID
.L35:
	mov	r0, #8
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
.L33:
	pop	{r0}
	bx	r0
.L37:
	.align	2, 0
.L36:
	.word	2117
	.word	5916
	.word	5128
.Lfe8:
	.size	 OvlFunc_888_200b45c,.Lfe8-OvlFunc_888_200b45c
	.align	2, 0
	.global	OvlFunc_888_200b4a8
	.thumb_func
	.type	 OvlFunc_888_200b4a8,function
OvlFunc_888_200b4a8:
	push	{lr}
	bl	OvlFunc_888_200b2a8
	cmp	r0, #0
	beq	.L39
	mov	r0, #8
	bl	__UI_Sanctum
	b	.L40
.L39:
	bl	__CutsceneStart
	ldr	r0, .L42
	bl	__MessageID
	ldr	r0, .L42+4
	bl	__GetFlag
	cmp	r0, #0
	beq	.L41
	ldr	r0, .L42+8
	bl	__MessageID
.L41:
	mov	r0, #8
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
.L40:
	pop	{r0}
	bx	r0
.L43:
	.align	2, 0
.L42:
	.word	6410
	.word	2313
	.word	6481
.Lfe9:
	.size	 OvlFunc_888_200b4a8,.Lfe9-OvlFunc_888_200b4a8
	.align	2, 0
	.global	OvlFunc_888_200b4f0
	.thumb_func
	.type	 OvlFunc_888_200b4f0,function
OvlFunc_888_200b4f0:
	push	{lr}
	bl	OvlFunc_888_200b2a8
	cmp	r0, #0
	beq	.L45
	mov	r0, #8
	bl	__UI_Sanctum
	b	.L46
.L45:
	bl	__CutsceneStart
	ldr	r0, .L47
	bl	__MessageID
	mov	r0, #8
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
.L46:
	pop	{r0}
	bx	r0
.L48:
	.align	2, 0
.L47:
	.word	6179
.Lfe10:
	.size	 OvlFunc_888_200b4f0,.Lfe10-OvlFunc_888_200b4f0
	.include "asm/maps/vale_sanctum/ovl_30_c_c_c.s"
	.text

	.include "asm/maps/vale_sanctum/imports.s"
	.text


	.text
	.align	2, 0
