@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"venus_lighthouse.c"
	.code	16
.gcc2_compiled.:
	.include "asm/maps/venus_lighthouse/exports.s"
	.text

	.code	16
.text
	.align	2, 0
	.global	OvlFunc_968_2008030
	.thumb_func
	.type	 OvlFunc_968_2008030,function
OvlFunc_968_2008030:
	push	{r5, r6, lr}
	mov	r5, r0
	mov	r2, r5
	add	r2, r2, #85
	mov	r3, #0
	strb	r3, [r2]
	add	r2, r2, #4
	mov	r3, #8
	mov	r6, r1
	strb	r3, [r2]
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, r5
	mov	r1, r6
	bl	__Func_80929d8
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_968_2008030,.Lfe1-OvlFunc_968_2008030
	.include "asm/maps/venus_lighthouse/ovl_30_a_a_a_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_968_20082f0
	.thumb_func
	.type	 OvlFunc_968_20082f0,function
OvlFunc_968_20082f0:
	push	{r5, lr}
	ldmia	r0!, {r5}
	ldmia	r1!, {r3}
	ldmia	r0!, {r4}
	sub	r5, r5, r3
	ldmia	r1!, {r3}
	ldr	r2, [r1]
	sub	r4, r4, r3
	ldr	r3, [r0]
	sub	r3, r3, r2
	asr	r5, r5, #16
	asr	r4, r4, #16
	asr	r3, r3, #16
	mov	r0, r5
	mul	r0, r0, r5
	mov	r2, r4
	mul	r2, r2, r4
	mov	r1, r3
	mul	r1, r1, r3
	add	r0, r0, r2
	mov	r3, r1
	add	r0, r0, r3
	ldr	r3, .L5
	bl	_call_via_r3
	pop	{r5}
	pop	{r1}
	bx	r1
.L6:
	.align	2, 0
.L5:
	.word	Func_8000948
.Lfe2:
	.size	 OvlFunc_968_20082f0,.Lfe2-OvlFunc_968_20082f0
	.include "asm/maps/venus_lighthouse/ovl_30_a_a_a_c_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_968_2008690
	.thumb_func
	.type	 OvlFunc_968_2008690,function
OvlFunc_968_2008690:
	push	{lr}
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, #0
	pop	{r1}
	bx	r1
.Lfe3:
	.size	 OvlFunc_968_2008690,.Lfe3-OvlFunc_968_2008690
	.include "asm/maps/venus_lighthouse/ovl_30_a_a_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_968_20088a0
	.thumb_func
	.type	 OvlFunc_968_20088a0,function
OvlFunc_968_20088a0:
	push	{lr}
	mov	r0, #0
	bl	__MapActor_GetActor
	ldr	r3, .L9
	ldr	r3, [r3]
	str	r0, [r3, #24]
	pop	{r0}
	bx	r0
.L10:
	.align	2, 0
.L9:
	.word	iwram_3001ee0
.Lfe4:
	.size	 OvlFunc_968_20088a0,.Lfe4-OvlFunc_968_20088a0
	.align	2, 0
	.global	OvlFunc_968_20088b8
	.thumb_func
	.type	 OvlFunc_968_20088b8,function
OvlFunc_968_20088b8:
	ldr	r3, .L12
	ldr	r2, [r3]
	mov	r3, #0
	str	r3, [r2, #24]
	bx	lr
.L13:
	.align	2, 0
.L12:
	.word	iwram_3001ee0
.Lfe5:
	.size	 OvlFunc_968_20088b8,.Lfe5-OvlFunc_968_20088b8
	.include "asm/maps/venus_lighthouse/ovl_30_a_c_a_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_968_2008910
	.thumb_func
	.type	 OvlFunc_968_2008910,function
OvlFunc_968_2008910:
	push	{r5, r6, lr}
	mov	r5, r1
	bl	__MapActor_GetActor
	mov	r6, r0
	mov	r0, r5
	bl	__MapActor_GetActor
	ldr	r2, [r6, #16]
	ldr	r3, [r0, #16]
	cmp	r2, r3
	bgt	.L15
	ldr	r3, [r0, #8]
	ldr	r2, [r6, #8]
	str	r3, [r6, #8]
	str	r2, [r0, #8]
	ldr	r3, [r0, #12]
	ldr	r2, [r6, #12]
	str	r3, [r6, #12]
	str	r2, [r0, #12]
	ldr	r3, [r0, #16]
	ldr	r2, [r6, #16]
	str	r3, [r6, #16]
	str	r2, [r0, #16]
	mov	r0, #1
	bl	__WaitFrames
.L15:
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.Lfe6:
	.size	 OvlFunc_968_2008910,.Lfe6-OvlFunc_968_2008910
	.align	2, 0
	.global	OvlFunc_968_200894c
	.thumb_func
	.type	 OvlFunc_968_200894c,function
OvlFunc_968_200894c:
	push	{r5, r6, lr}
	mov	r6, r0
	mov	r5, #60
.L17:
	cmp	r5, #0
	beq	.L18
	mov	r0, #1
	bl	__WaitFrames
	ldr	r3, [r6, #40]
	sub	r5, r5, #1
	cmp	r3, #0
	bne	.L17
.L18:
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.Lfe7:
	.size	 OvlFunc_968_200894c,.Lfe7-OvlFunc_968_200894c
	.include "asm/maps/venus_lighthouse/ovl_30_a_c_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_968_2008c5c
	.thumb_func
	.type	 OvlFunc_968_2008c5c,function
OvlFunc_968_2008c5c:
	push	{r5, r6, lr}
	mov	r4, r0
	mov	r3, r1
	lsl	r4, r4, #16
	mov	r0, #142
	mov	r6, r2
	lsl	r3, r3, #16
	lsl	r0, r0, #1
	mov	r1, r4
	mov	r2, #0
	bl	__CreateActor
	mov	r5, r0
	mov	r0, #0
	cmp	r5, #0
	beq	.L22
	mov	r3, #128
	lsl	r3, r3, #9
	str	r3, [r5, #48]
	str	r3, [r5, #52]
	mov	r0, r5
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, r5
	mov	r1, #7
	bl	__Actor_SetAnim
	mov	r3, r5
	mov	r2, #0
	add	r3, r3, #85
	strb	r2, [r3]
	mov	r1, r5
	add	r3, r3, #4
	str	r2, [r5, #12]
	add	r1, r1, #35
	strb	r2, [r3]
	mov	r3, #2
	strb	r3, [r1]
	ldr	r3, .L24
	str	r3, [r5, #108]
	mov	r3, r5
	add	r3, r3, #99
	mov	r0, r5
	strb	r2, [r3]
	mov	r1, r6
	bl	__Actor_SetScript
	mov	r0, r5
.L22:
	pop	{r5, r6}
	pop	{r1}
	bx	r1
.L25:
	.align	2, 0
.L24:
	.word	OvlFunc_968_2008b98
.Lfe8:
	.size	 OvlFunc_968_2008c5c,.Lfe8-OvlFunc_968_2008c5c
	.include "asm/maps/venus_lighthouse/ovl_30_a_c_c_c.s"
	.text

	.code	16
	.align	2, 0
	.global	VenusLighthouse_GetSpecialExits
	.thumb_func
	.type	 VenusLighthouse_GetSpecialExits,function
VenusLighthouse_GetSpecialExits:
	mov	r0, #0
	bx	lr
.Lfe9:
	.size	 VenusLighthouse_GetSpecialExits,.Lfe9-VenusLighthouse_GetSpecialExits
	.align	2, 0
	.global	VenusLighthouse_GetExits
	.thumb_func
	.type	 VenusLighthouse_GetExits,function
VenusLighthouse_GetExits:
	ldr	r0, .L28
	bx	lr
.L29:
	.align	2, 0
.L28:
	.word	gOvl_0200e740
.Lfe10:
	.size	 VenusLighthouse_GetExits,.Lfe10-VenusLighthouse_GetExits
	.include "asm/maps/venus_lighthouse/ovl_30_c_a_c_a_a_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_968_2008f1c
	.thumb_func
	.type	 OvlFunc_968_2008f1c,function
OvlFunc_968_2008f1c:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L35
	mov	r1, #1
	bl	__Func_801776c
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L36:
	.align	2, 0
.L35:
	.word	2387
.Lfe11:
	.size	 OvlFunc_968_2008f1c,.Lfe11-OvlFunc_968_2008f1c
	.include "asm/maps/venus_lighthouse/ovl_30_c_a_c_a_a_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_968_2008ff0
	.thumb_func
	.type	 OvlFunc_968_2008ff0,function
OvlFunc_968_2008ff0:
	push	{r5, lr}
	mov	r0, #12
	bl	__MapActor_GetActor
	mov	r5, r0
	bl	__CutsceneStart
	ldr	r3, [r5, #8]
	asr	r3, r3, #20
	cmp	r3, #54
	beq	.L39
	ldr	r3, [r5, #16]
	asr	r3, r3, #20
	cmp	r3, #6
	bne	.L38
.L39:
	ldr	r0, .L40
	bl	__SetFlag
.L38:
	bl	__CutsceneEnd
	pop	{r5}
	pop	{r0}
	bx	r0
.L41:
	.align	2, 0
.L40:
	.word	2439
.Lfe12:
	.size	 OvlFunc_968_2008ff0,.Lfe12-OvlFunc_968_2008ff0
	.align	2, 0
	.global	OvlFunc_968_2009024
	.thumb_func
	.type	 OvlFunc_968_2009024,function
OvlFunc_968_2009024:
	push	{lr}
	bl	__CutsceneStart
	mov	r0, #0
	mov	r1, #1
	bl	__MapActor_SetAnim
	ldr	r0, .L43
	mov	r1, #1
	bl	__Func_801776c
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L44:
	.align	2, 0
.L43:
	.word	9858
.Lfe13:
	.size	 OvlFunc_968_2009024,.Lfe13-OvlFunc_968_2009024
	.include "asm/maps/venus_lighthouse/ovl_30_c_a_c_a_c_a_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_968_2009628
	.thumb_func
	.type	 OvlFunc_968_2009628,function
OvlFunc_968_2009628:
	push	{lr}
	bl	__CutsceneStart
	bl	OvlFunc_968_2008374
	mov	r0, #20
	bl	__CutsceneWait
	bl	__CutsceneEnd
	bl	OvlFunc_968_20094f4
	pop	{r0}
	bx	r0
.Lfe14:
	.size	 OvlFunc_968_2009628,.Lfe14-OvlFunc_968_2009628
	.include "asm/maps/venus_lighthouse/ovl_30_c_a_c_a_c_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_968_200996c
	.thumb_func
	.type	 OvlFunc_968_200996c,function
OvlFunc_968_200996c:
	push	{lr}
	sub	sp, sp, #8
	bl	__CutsceneStart
	mov	r3, #12
	mov	r2, #44
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #19
	mov	r1, #44
	mov	r2, #4
	mov	r3, #1
	bl	__Func_8010704
	bl	OvlFunc_968_2008374
	bl	OvlFunc_968_20098f8
	bl	__CutsceneEnd
	add	sp, sp, #8
	pop	{r0}
	bx	r0
.Lfe15:
	.size	 OvlFunc_968_200996c,.Lfe15-OvlFunc_968_200996c
	.align	2, 0
	.global	OvlFunc_968_200999c
	.thumb_func
	.type	 OvlFunc_968_200999c,function
OvlFunc_968_200999c:
	push	{r5, lr}
	mov	r5, #0
.L51:
	mov	r0, r5
	add	r0, r0, #11
	bl	__MapActor_GetActor
	add	r5, r5, #1
	ldr	r1, [r0, #8]
	ldr	r2, [r0, #16]
	mov	r3, #45
	mov	r0, #0
	bl	__Func_8012078
	cmp	r5, #1
	bls	.L51
	pop	{r5}
	pop	{r0}
	bx	r0
.Lfe16:
	.size	 OvlFunc_968_200999c,.Lfe16-OvlFunc_968_200999c
	.align	2, 0
	.global	OvlFunc_968_20099c0
	.thumb_func
	.type	 OvlFunc_968_20099c0,function
OvlFunc_968_20099c0:
	push	{r5, lr}
	mov	r5, #0
.L57:
	mov	r0, r5
	add	r0, r0, #11
	bl	__MapActor_GetActor
	ldr	r2, .L58
	ldr	r3, [r0, #12]
	cmp	r3, r2
	ble	.L56
	ldr	r1, [r0, #8]
	ldr	r2, [r0, #16]
	mov	r3, #255
	mov	r0, #0
	bl	__Func_8012078
.L56:
	add	r5, r5, #1
	cmp	r5, #1
	bls	.L57
	pop	{r5}
	pop	{r0}
	bx	r0
.L59:
	.align	2, 0
.L58:
	.word	-1048576
.Lfe17:
	.size	 OvlFunc_968_20099c0,.Lfe17-OvlFunc_968_20099c0
	.align	2, 0
	.global	OvlFunc_968_20099f0
	.thumb_func
	.type	 OvlFunc_968_20099f0,function
OvlFunc_968_20099f0:
	push	{lr}
	bl	__CutsceneStart
	bl	OvlFunc_968_2008cc8
	cmp	r0, #0
	bne	.L61
	bl	OvlFunc_968_200999c
	bl	OvlFunc_968_2008374
	bl	OvlFunc_968_20099c0
.L61:
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.Lfe18:
	.size	 OvlFunc_968_20099f0,.Lfe18-OvlFunc_968_20099f0
	.include "asm/maps/venus_lighthouse/ovl_30_c_a_c_c_c_a_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_968_2009a9c
	.thumb_func
	.type	 OvlFunc_968_2009a9c,function
OvlFunc_968_2009a9c:
	push	{r5, lr}
	bl	__CutsceneStart
	mov	r0, #11
	bl	__MapActor_GetActor
	mov	r5, r0
	ldr	r3, [r5, #8]
	asr	r3, r3, #20
	cmp	r3, #8
	bne	.L63
	bl	OvlFunc_968_200894c
	mov	r0, r5
	bl	OvlFunc_968_2009a14
	b	.L64
.L63:
	mov	r0, r5
	bl	OvlFunc_968_2009a50
.L64:
	mov	r0, #12
	bl	__MapActor_GetActor
	mov	r5, r0
	ldr	r3, [r5, #8]
	asr	r3, r3, #20
	cmp	r3, #7
	bne	.L65
	bl	OvlFunc_968_200894c
	mov	r0, r5
	bl	OvlFunc_968_2009a14
	b	.L66
.L65:
	mov	r0, r5
	bl	OvlFunc_968_2009a50
.L66:
	bl	__CutsceneEnd
	pop	{r5}
	pop	{r0}
	bx	r0
.Lfe19:
	.size	 OvlFunc_968_2009a9c,.Lfe19-OvlFunc_968_2009a9c
	.include "asm/maps/venus_lighthouse/ovl_30_c_a_c_c_c_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_968_200a2a4
	.thumb_func
	.type	 OvlFunc_968_200a2a4,function
OvlFunc_968_200a2a4:
	push	{r5, lr}
	mov	r5, r0
	mov	r3, r5
	add	r3, r3, #100
	mov	r2, #0
	ldrsh	r0, [r3, r2]
	bl	__MapActor_GetActor
	mov	r2, #128
	ldr	r3, [r0, #12]
	lsl	r2, r2, #13
	add	r3, r3, r2
	str	r3, [r5, #12]
	mov	r0, #0
	pop	{r5}
	pop	{r1}
	bx	r1
.Lfe20:
	.size	 OvlFunc_968_200a2a4,.Lfe20-OvlFunc_968_200a2a4
	.include "asm/maps/venus_lighthouse/ovl_30_c_c_a_a_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_968_200a6e4
	.thumb_func
	.type	 OvlFunc_968_200a6e4,function
OvlFunc_968_200a6e4:
	push	{lr}
	bl	__CutsceneStart
	bl	OvlFunc_968_2008374
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.Lfe21:
	.size	 OvlFunc_968_200a6e4,.Lfe21-OvlFunc_968_200a6e4
	.include "asm/maps/venus_lighthouse/ovl_30_c_c_a_a_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_968_200b00c
	.thumb_func
	.type	 OvlFunc_968_200b00c,function
OvlFunc_968_200b00c:
	push	{r5, r6, lr}
	mov	r6, r0
	bl	__MapActor_GetActor
	mov	r5, r0
	mov	r2, r5
	add	r2, r2, #85
	mov	r3, #0
	strb	r3, [r2]
	mov	r1, r5
	add	r1, r1, #89
	ldrb	r2, [r1]
	mov	r3, #252
	and	r3, r3, r2
	strb	r3, [r1]
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, r5
	mov	r1, #5
	bl	__Actor_SetAnim
	mov	r0, r6
	mov	r1, #3
	bl	__Func_8092b08
	add	r5, r5, #35
	ldrb	r2, [r5]
	mov	r3, #2
	orr	r3, r3, r2
	strb	r3, [r5]
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.Lfe22:
	.size	 OvlFunc_968_200b00c,.Lfe22-OvlFunc_968_200b00c
	.align	2, 0
	.global	OvlFunc_968_200b050
	.thumb_func
	.type	 OvlFunc_968_200b050,function
OvlFunc_968_200b050:
	push	{r5, lr}
	mov	r5, #15
.L74:
	mov	r0, r5
	add	r5, r5, #1
	bl	__MapActor_GetActor
	cmp	r5, #18
	bls	.L74
	pop	{r5}
	pop	{r0}
	bx	r0
.Lfe23:
	.size	 OvlFunc_968_200b050,.Lfe23-OvlFunc_968_200b050
	.include "asm/maps/venus_lighthouse/ovl_30_c_c_a_c_a_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_968_200bfe4
	.thumb_func
	.type	 OvlFunc_968_200bfe4,function
OvlFunc_968_200bfe4:
	push	{lr}
	sub	sp, sp, #12
	mov	r0, sp
	mov	r3, #0
	str	r3, [r0]
	sub	r3, r3, #1
	str	r3, [r0, #8]
	bl	OvlFunc_968_200c048
	add	sp, sp, #12
	pop	{r0}
	bx	r0
.Lfe24:
	.size	 OvlFunc_968_200bfe4,.Lfe24-OvlFunc_968_200bfe4
	.align	2, 0
	.global	OvlFunc_968_200bffc
	.thumb_func
	.type	 OvlFunc_968_200bffc,function
OvlFunc_968_200bffc:
	push	{lr}
	sub	sp, sp, #12
	mov	r0, sp
	mov	r3, #0
	str	r3, [r0]
	mov	r3, #1
	str	r3, [r0, #8]
	bl	OvlFunc_968_200c048
	add	sp, sp, #12
	pop	{r0}
	bx	r0
.Lfe25:
	.size	 OvlFunc_968_200bffc,.Lfe25-OvlFunc_968_200bffc
	.align	2, 0
	.global	OvlFunc_968_200c014
	.thumb_func
	.type	 OvlFunc_968_200c014,function
OvlFunc_968_200c014:
	push	{lr}
	sub	sp, sp, #12
	mov	r3, #1
	mov	r0, sp
	neg	r3, r3
	str	r3, [r0]
	mov	r3, #0
	str	r3, [r0, #8]
	bl	OvlFunc_968_200c048
	add	sp, sp, #12
	pop	{r0}
	bx	r0
.Lfe26:
	.size	 OvlFunc_968_200c014,.Lfe26-OvlFunc_968_200c014
	.align	2, 0
	.global	OvlFunc_968_200c030
	.thumb_func
	.type	 OvlFunc_968_200c030,function
OvlFunc_968_200c030:
	push	{lr}
	sub	sp, sp, #12
	mov	r0, sp
	mov	r3, #1
	str	r3, [r0]
	mov	r3, #0
	str	r3, [r0, #8]
	bl	OvlFunc_968_200c048
	add	sp, sp, #12
	pop	{r0}
	bx	r0
.Lfe27:
	.size	 OvlFunc_968_200c030,.Lfe27-OvlFunc_968_200c030
	.include "asm/maps/venus_lighthouse/ovl_30_c_c_a_c_c.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_968_200c5f0
	.thumb_func
	.type	 OvlFunc_968_200c5f0,function
OvlFunc_968_200c5f0:
	push	{lr}
	mov	r0, #216
	lsl	r0, r0, #1
	mov	r1, #32
	bl	OvlFunc_968_200c520
	pop	{r0}
	bx	r0
.Lfe28:
	.size	 OvlFunc_968_200c5f0,.Lfe28-OvlFunc_968_200c5f0
	.align	2, 0
	.global	OvlFunc_968_200c600
	.thumb_func
	.type	 OvlFunc_968_200c600,function
OvlFunc_968_200c600:
	push	{lr}
	mov	r0, #140
	lsl	r0, r0, #2
	mov	r1, #44
	bl	OvlFunc_968_200c520
	pop	{r0}
	bx	r0
.Lfe29:
	.size	 OvlFunc_968_200c600,.Lfe29-OvlFunc_968_200c600
	.include "asm/maps/venus_lighthouse/ovl_30_c_c_c_c.s"
	.text

	.include "asm/maps/venus_lighthouse/imports.s"
	.text


	.text
	.align	2, 0
