@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"west_lunpa_cave.c"
	.code	16
.gcc2_compiled.:
	.include "asm/maps/west_lunpa_cave/exports.s"
	.text

	.code	16
.text
	.align	2, 0
	.global	WestLunpaCave_GetEntrances
	.thumb_func
	.type	 WestLunpaCave_GetEntrances,function
WestLunpaCave_GetEntrances:
	ldr	r0, .L3
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	gOvl_02009c34
.Lfe1:
	.size	 WestLunpaCave_GetEntrances,.Lfe1-WestLunpaCave_GetEntrances
	.align	2, 0
	.global	WestLunpaCave_GetSpecialExits
	.thumb_func
	.type	 WestLunpaCave_GetSpecialExits,function
WestLunpaCave_GetSpecialExits:
	mov	r0, #0
	bx	lr
.Lfe2:
	.size	 WestLunpaCave_GetSpecialExits,.Lfe2-WestLunpaCave_GetSpecialExits
	.align	2, 0
	.global	WestLunpaCave_GetExits
	.thumb_func
	.type	 WestLunpaCave_GetExits,function
WestLunpaCave_GetExits:
	ldr	r0, .L7
	bx	lr
.L8:
	.align	2, 0
.L7:
	.word	gOvl_02009cac
.Lfe3:
	.size	 WestLunpaCave_GetExits,.Lfe3-WestLunpaCave_GetExits
	.include "asm/maps/west_lunpa_cave/ovl_30_c_a_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	WestLunpaCave_GetEvents
	.thumb_func
	.type	 WestLunpaCave_GetEvents,function
WestLunpaCave_GetEvents:
	ldr	r0, .L10
	bx	lr
.L11:
	.align	2, 0
.L10:
	.word	gOvl_02009dd4
.Lfe4:
	.size	 WestLunpaCave_GetEvents,.Lfe4-WestLunpaCave_GetEvents
	.align	2, 0
	.global	OvlFunc_941_200807c
	.thumb_func
	.type	 OvlFunc_941_200807c,function
OvlFunc_941_200807c:
	push	{lr}
	mov	r0, #8
	bl	__MapActor_GetActor
	cmp	r0, #0
	beq	.L13
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
.L13:
	pop	{r0}
	bx	r0
.Lfe5:
	.size	 OvlFunc_941_200807c,.Lfe5-OvlFunc_941_200807c
	.include "asm/maps/west_lunpa_cave/ovl_30_c_a_c_c_a_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_941_20081b0
	.thumb_func
	.type	 OvlFunc_941_20081b0,function
OvlFunc_941_20081b0:
	push	{r5, lr}
	mov	r0, #10
	bl	__MapActor_GetActor
	mov	r5, r0
	mov	r0, #128
	lsl	r0, r0, #2
	bl	__SetFlag
	cmp	r5, #0
	beq	.L15
	mov	r0, r5
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r2, r5
	add	r2, r2, #35
	mov	r3, #1
	strb	r3, [r2]
.L15:
	ldr	r0, .L17
	.code	16
	bl	__GetFlag
	cmp	r0, #0
	bne	.L16
	mov	r0, #157
	bl	__PlaySound
	bl	OvlFunc_941_20080d4
	mov	r0, #80
	bl	__PlaySound
	ldr	r0, .L17
	bl	__SetFlag
.L16:
	pop	{r5}
	pop	{r0}
	bx	r0
.L18:
	.align	2, 0
.L17:
	.word	514
.Lfe6:
	.size	 OvlFunc_941_20081b0,.Lfe6-OvlFunc_941_20081b0
	.align	2, 0
	.global	OvlFunc_941_2008200
	.thumb_func
	.type	 OvlFunc_941_2008200,function
OvlFunc_941_2008200:
	push	{lr}
	ldr	r0, .L20
	bl	__SetFlag
	pop	{r0}
	bx	r0
.L21:
	.align	2, 0
.L20:
	.word	515
.Lfe7:
	.size	 OvlFunc_941_2008200,.Lfe7-OvlFunc_941_2008200
	.include "asm/maps/west_lunpa_cave/ovl_30_c_a_c_c_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_941_20092ac
	.thumb_func
	.type	 OvlFunc_941_20092ac,function
OvlFunc_941_20092ac:
	push	{lr}
	mov	r1, #0
	mov	r0, #0
	bl	__Func_8091c7c
	neg	r3, r0
	orr	r3, r3, r0
	lsr	r3, r3, #31
	mov	r0, #1
	sub	r0, r0, r3
	pop	{r1}
	bx	r1
.Lfe8:
	.size	 OvlFunc_941_20092ac,.Lfe8-OvlFunc_941_20092ac
	.align	2, 0
	.global	OvlFunc_941_20092c4
	.thumb_func
	.type	 OvlFunc_941_20092c4,function
OvlFunc_941_20092c4:
	push	{lr}
	ldr	r0, .L24
	bl	__MessageID
	mov	r1, #0
	mov	r0, #1
	bl	__ShowActorMessage_NoWait
	mov	r1, #0
	mov	r0, #0
	bl	__Func_8091c7c
	neg	r3, r0
	orr	r3, r3, r0
	lsr	r3, r3, #31
	mov	r0, #1
	sub	r0, r0, r3
	pop	{r1}
	bx	r1
.L25:
	.align	2, 0
.L24:
	.word	9545
.Lfe9:
	.size	 OvlFunc_941_20092c4,.Lfe9-OvlFunc_941_20092c4
	.align	2, 0
	.global	OvlFunc_941_20092f0
	.thumb_func
	.type	 OvlFunc_941_20092f0,function
OvlFunc_941_20092f0:
	push	{lr}
	ldr	r0, .L27
	bl	__MessageID
	mov	r1, #0
	mov	r0, #1
	bl	__ShowActorMessage_NoWait
	mov	r1, #0
	mov	r0, #0
	bl	__Func_8091c7c
	neg	r3, r0
	orr	r3, r3, r0
	lsr	r3, r3, #31
	mov	r0, #1
	sub	r0, r0, r3
	pop	{r1}
	bx	r1
.L28:
	.align	2, 0
.L27:
	.word	9549
.Lfe10:
	.size	 OvlFunc_941_20092f0,.Lfe10-OvlFunc_941_20092f0
	.align	2, 0
	.global	OvlFunc_941_200931c
	.thumb_func
	.type	 OvlFunc_941_200931c,function
OvlFunc_941_200931c:
	mov	r0, #1
	bx	lr
.Lfe11:
	.size	 OvlFunc_941_200931c,.Lfe11-OvlFunc_941_200931c
	.align	2, 0
	.global	OvlFunc_941_2009320
	.thumb_func
	.type	 OvlFunc_941_2009320,function
OvlFunc_941_2009320:
	push	{lr}
	ldr	r0, .L31
	bl	__MessageID
	mov	r1, #0
	mov	r0, #12
	bl	__ShowActorMessage_NoWait
	mov	r1, #0
	mov	r0, #0
	bl	__Func_8091c7c
	neg	r3, r0
	orr	r3, r3, r0
	lsr	r3, r3, #31
	mov	r0, #1
	sub	r0, r0, r3
	pop	{r1}
	bx	r1
.L32:
	.align	2, 0
.L31:
	.word	9559
.Lfe12:
	.size	 OvlFunc_941_2009320,.Lfe12-OvlFunc_941_2009320
	.align	2, 0
	.global	OvlFunc_941_200934c
	.thumb_func
	.type	 OvlFunc_941_200934c,function
OvlFunc_941_200934c:
	push	{lr}
	ldr	r0, .L34
	bl	__MessageID
	mov	r1, #0
	mov	r0, #1
	bl	__ShowActorMessage_NoWait
	mov	r0, #1
	pop	{r1}
	bx	r1
.L35:
	.align	2, 0
.L34:
	.word	9565
.Lfe13:
	.size	 OvlFunc_941_200934c,.Lfe13-OvlFunc_941_200934c
	.align	2, 0
	.global	OvlFunc_941_2009368
	.thumb_func
	.type	 OvlFunc_941_2009368,function
OvlFunc_941_2009368:
	push	{lr}
	ldr	r0, .L37
	bl	__MessageID
	mov	r1, #0
	mov	r0, #3
	bl	__ShowActorMessage_NoWait
	mov	r1, #0
	mov	r0, #0
	bl	__Func_8091c7c
	neg	r3, r0
	orr	r3, r3, r0
	lsr	r3, r3, #31
	mov	r0, #1
	sub	r0, r0, r3
	pop	{r1}
	bx	r1
.L38:
	.align	2, 0
.L37:
	.word	9546
.Lfe14:
	.size	 OvlFunc_941_2009368,.Lfe14-OvlFunc_941_2009368
	.include "asm/maps/west_lunpa_cave/ovl_30_c_c_c_c_a.s"
	.text

	.code	16
	.align	2, 0
	.global	OvlFunc_941_200941c
	.thumb_func
	.type	 OvlFunc_941_200941c,function
OvlFunc_941_200941c:
	push	{lr}
	ldr	r0, .L40
	bl	__MessageID
	mov	r1, #0
	mov	r0, #1
	bl	__ShowActorMessage_NoWait
	mov	r1, #0
	mov	r0, #0
	bl	__Func_8091c7c
	neg	r3, r0
	orr	r3, r3, r0
	lsr	r3, r3, #31
	mov	r0, #1
	sub	r0, r0, r3
	pop	{r1}
	bx	r1
.L41:
	.align	2, 0
.L40:
	.word	9564
.Lfe15:
	.size	 OvlFunc_941_200941c,.Lfe15-OvlFunc_941_200941c
	.include "asm/maps/west_lunpa_cave/ovl_30_c_c_c_c_c.s"
	.text

	.include "asm/maps/west_lunpa_cave/imports.s"
	.text


	.text
	.align	2, 0
