@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_896_200c260
	.thumb_func
	.type	 OvlFunc_896_200c260,function
OvlFunc_896_200c260:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	mov r10, r0
	movs r0, #0
	mov r8, r0
	movs r0, #22
	bl __CreateActor
	mov r6, r0
	.code	16
	mov	r0, #224
	bl	__CheckPartyItem
	mov	r1, #224
	mov	r7, r0
	bl	__CheckItem
	mov	r9, r0
	mov	r0, r7
	cmp	r6, #0
	beq	.L2
	ldr r1, =gScript_881__0200cbe4
	mov r0, r6
	bl __Actor_SetScript
	.code	16
	ldr	r5, [r6, #80]
	mov	r3, r5
	mov	r2, r8
	add	r3, r3, #38
	strb	r2, [r3]
	add	r3, r3, #1
	strb	r2, [r3]
	mov	r3, #33
	ldrb	r2, [r5, #5]
	neg	r3, r3
	and	r3, r3, r2
	ldrb	r2, [r5, #9]
	strb	r3, [r5, #5]
	mov	r3, #15
	and	r3, r3, r2
	strb	r3, [r5, #9]
	mov	r3, #160
	lsl	r3, r3, #10
	str	r3, [r6, #40]
	mov	r3, #128
	lsl	r3, r3, #7
	mov	r1, #193
	str	r3, [r6, #72]
	lsl	r1, r1, #3
	mov	r0, #17
	bl	__galloc_iwram
	mov	r8, r0
	mov	r0, sl
	bl	__LoadItemIcon
	mov	r2, #128
	lsl	r2, r2, #3
	add	r2, r2, r8
	mov	r1, #128
	ldrb	r0, [r5, #28]
	bl	__UploadSpriteGFX
	mov	r0, #17
	bl	__gfree
	mov	r0, #83
	bl	__PlaySound
	mov	r0, r6
	mov	r1, #3
	bl	__Func_808f140
	mov r1, r9
	mov r0, r7
	bl __Func_8078948
	.code	16
	mov	r1, sl
	mov	r0, r7
	bl	__GiveItemTo
	mov	r0, r6
	bl	__DeleteActor
	mov	r0, #0
	mov	r1, #1
	bl	__MapActor_SetAnim
	mov	r0, r7
.L2:
	pop	{r3, r5, r6}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 OvlFunc_896_200c260,.Lfe1-OvlFunc_896_200c260

	.text
	.align	2, 0
