@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_923_2008eac
	.thumb_func
	.type	 OvlFunc_923_2008eac,function
OvlFunc_923_2008eac:
	push	{lr}
	bl	__CutsceneStart
	mov	r0, #0
	mov	r1, #1
	bl	__MapActor_SetAnim
	ldr	r0, .L3
	mov	r1, #1
	bl	__Func_801776c
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	5682
.Lfe1:
	.size	 OvlFunc_923_2008eac,.Lfe1-OvlFunc_923_2008eac
	.align	2, 0
	.global	OvlFunc_923_2008ed0
	.thumb_func
	.type	 OvlFunc_923_2008ed0,function
OvlFunc_923_2008ed0:
	push	{r5, r6, lr}
	mov	r6, r0
	mov	r0, #0
	bl	__MapActor_GetActor
	mov	r5, r0
	bl	__CutsceneStart
	mov	r0, #228
	bl	__PlaySound
	ldr	r3, .L6
	str	r3, [r5, #108]
	ldr	r3, .L6+4
	mov	r0, #0
	str	r3, [r5, #48]
	mov	r1, #2
	bl	__MapActor_SetAnim
	mov	r2, #6
	neg	r2, r2
	mov	r1, #0
	mov	r0, #0
	bl	__Func_809228c
	mov	r0, #0
	bl	__MapActor_WaitMovement
	mov	r1, #15
	mov	r0, #0
	bl	__Func_8092950
	mov	r0, #0
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r3, #0
	str	r3, [r5, #108]
	mov	r0, #30
	bl	__CutsceneWait
	bl	__MapTransitionOut
	bl	__WaitMapTransition
	mov	r0, r6
	bl	__Func_8091e9c
	bl	__CutsceneEnd
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L7:
	.align	2, 0
.L6:
	.word	OvlFunc_923_2008cc0
	.word	13107
.Lfe2:
	.size	 OvlFunc_923_2008ed0,.Lfe2-OvlFunc_923_2008ed0
	.align	2, 0
	.global	OvlFunc_923_2008f48
	.thumb_func
	.type	 OvlFunc_923_2008f48,function
OvlFunc_923_2008f48:
	push	{r5, lr}
	mov	r5, r0
	bl	__CutsceneStart
	mov	r0, #228
	bl	__PlaySound
	ldr	r2, .L9
	.code	16
	mov	r0, #0
	.code	16
	ldr	r1, .L9+4
	.code	16
	bl	__MapActor_SetSpeed
	mov	r0, #0
	mov	r1, #2
	bl	__Func_8092b08
	mov	r2, #8
	neg	r2, r2
	mov	r1, #0
	mov	r0, #0
	bl	__Func_809228c
	mov	r0, #0
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, #8
	bl	__CutsceneWait
	mov	r3, #128
	lsl	r3, r3, #12
	lsl	r5, r5, #19
	add	r5, r5, r3
	mov	r0, #0
	mov	r1, r5
	mov	r2, #0
	bl	__MapActor_SetPos
	mov	r0, #30
	bl	__CutsceneWait
	pop	{r5}
	pop	{r0}
	bx	r0
.L10:
	.align	2, 0
.L9:
	.word	13107
	.word	26214
.Lfe3:
	.size	 OvlFunc_923_2008f48,.Lfe3-OvlFunc_923_2008f48

	.text
	.align	2, 0
