@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_971_20087b0
	.thumb_func
	.type	 OvlFunc_971_20087b0,function
OvlFunc_971_20087b0:
	push	{r5, r6, lr}
	mov	r6, #0
	.code	16
	ldr	r0, .L14
	bl	__GetFlag
	ldr	r3, .L14+4
	strb	r6, [r3]
	cmp	r0, #0
	bne	.L3
	mov	r0, #5
	bl	__WaitFrames
	bl	OvlFunc_971_2008580
	mov	r6, r0
	cmp	r6, #0
	blt	.L11
	mov	r0, #5
	bl	__WaitFrames
	bl	OvlFunc_971_2008398
	mov	r6, r0
	mov	r5, r6
	cmp	r6, #0
	bge	.L6
	
	.code	16
	b	.L7
.L3:
	bl	OvlFunc_971_2008398
	mov	r6, r0
	mov	r5, r6
	cmp	r6, #0
	blt	.L11
	mov	r0, #10
	bl	__WaitFrames
	bl	OvlFunc_971_2008580
	mov	r6, r0
	cmp	r6, #0
	blt	.L11
.L6:
	mov	r0, #252
	lsl	r0, r0, #2
	mov	r1, r5
	bl	__SetFlagByte
	mov	r6, r5
.L7:
	cmp	r5, #0
	bge	.L13
.L11:
	ldr	r1, .L14+8
	.code	16
	ldr	r0, .L14+12
	ldrh	r4, [r0]
	.code	16
	strh	r0, [r0]
	.code	16
	mov	r2, #0
	mov	r3, #128
	.code	16
	strb	r3, [r1, #1]
	ldr	r3, .L14+16
	str	r2, [r3]
	ldr	r3, .L14+20
	strh	r2, [r3]
	ldr	r3, .L14+24
	str	r2, [r3]
	ldr	r3, .L14+28
	strb	r2, [r1, #3]
	strb	r2, [r1, #2]
	strh	r2, [r3]
	strh	r4, [r0]
.L13:
	mov	r0, r6
	pop	{r5, r6}
	pop	{r1}
	bx	r1
.L15:
	.align	2, 0
.L14:
	.word	770
	.word	ewram_20023a0
	.word	ewram_2002220
	.word	67109384
	.word	ewram_2002080
	.word	ewram_2002008
	.word	ewram_20023ac
	.word	ewram_2002238
.Lfe1:
	.size	 OvlFunc_971_20087b0,.Lfe1-OvlFunc_971_20087b0

	.text
	.align	2, 0
