@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_971_20090e8
	.thumb_func
	.type	 OvlFunc_971_20090e8,function
OvlFunc_971_20090e8:
	push	{r5, r6, lr}
	mov	r6, r0
	.code	16
	bl	__CutsceneStart
	ldr	r3, .L7
	mov	r2, #250
	.code	16
	lsl	r2, r2, #1
	add	r3, r3, r2
	.code	16
	mov	r0, r6
	.code	16
	ldr	r1, [r3]
	.code	16
	mov	r2, #0
	.code	16
	bl	__Func_809280c
	mov	r0, #129
	.code	16
	lsl	r0, r0, #2
	.code	16
	bl	__GetFlag
	cmp	r0, #0
	bne	.L3
	bl	__GetPartySize
	.code	16
	cmp	r0, #3
	bgt	.L4
	ldr	r5, .L7+4
	.code	16
	b	.L5
.L4:
	ldr	r5, .L7+8
	.code	16
.L5:
	mov	r0, #129
	.code	16
	lsl	r0, r0, #2
	.code	16
	bl	__SetFlag
	b	.L6
.L3:
	mov	r0, #129
	.code	16
	lsl	r0, r0, #2
	.code	16
	ldr	r5, .L7+12
	.code	16
	bl	__ClearFlag
.L6:
	mov	r0, r5
	.code	16
	bl	__MessageID
	mov	r1, #0
	.code	16
	mov	r0, r6
	.code	16
	bl	__Func_8092c40
	bl	__CutsceneEnd
	pop	{r5, r6}
	pop	{r1}
	bx	r1
.L8:
	.align	2, 0
.L7:
	.word	gState
	.word	10637
	.word	10636
	.word	10638
.Lfe1:
	.size	 OvlFunc_971_20090e8,.Lfe1-OvlFunc_971_20090e8

	.text
	.align	2, 0
