@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_964_200a52c
	.thumb_func
	.type	 OvlFunc_964_200a52c,function
OvlFunc_964_200a52c:
	push	{r5, r6, lr}
	mov	r6, r8
	push	{r6}
	sub	sp, sp, #8
	mov	r3, #44
	mov	r2, #19
	.code	16
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r1, #19
	mov	r2, #4
	mov	r3, #1
	mov	r0, #108
	bl	__Func_8010704
	mov	r0, #17
	bl	__MapActor_GetActor
	ldr	r5, [r0, #8]
	.code	16
	mov	r0, #17
	bl	__MapActor_GetActor
	ldr	r2, [r0, #16]
	.code	16
	asr	r5, r5, #20
	mov r3, #1
	mov r1, r5
	asr r2, #20
	mov r6, #0xff
	mov r0, #0
	str r3, [sp]
	str r6, [sp, #4]
	mov r8, r3
	bl OvlFunc_964_2008244
	.code	16
	mov	r0, #18
	bl	__MapActor_GetActor
	ldr	r5, [r0, #8]
	.code	16
	mov	r0, #18
	bl	__MapActor_GetActor
	ldr	r2, [r0, #16]
	.code	16
	asr	r5, r5, #20
	mov r3, r8
	asr r2, #20
	mov r1, r5
	mov r0, #0
	str r3, [sp]
	str r6, [sp, #4]
	bl OvlFunc_964_2008244
	.code	16
	add	sp, sp, #8
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_964_200a52c,.Lfe1-OvlFunc_964_200a52c

	.text
	.align	2, 0
