@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_964_200a480
	.thumb_func
	.type	 OvlFunc_964_200a480,function
OvlFunc_964_200a480:
	push	{r5, lr}
	sub	sp, sp, #8
	mov	r3, #49
	str	r3, [sp, #4]
	mov	r5, #25
	mov	r0, #89
	mov	r1, #49
	mov	r2, #3
	mov	r3, #2
	str	r5, [sp]
	bl	__Func_8010704
	mov	r3, #51
	str	r3, [sp, #4]
	mov	r1, #51
	mov	r2, #8
	mov	r3, #5
	mov	r0, #89
	str	r5, [sp]
	bl	__Func_8010704
	mov	r0, #14
	bl	__MapActor_GetActor
	mov	r3, #1
	add	r0, r0, #34
	strb	r3, [r0]
	mov	r0, #12
	bl	__MapActor_GetActor
	ldr	r5, [r0, #8]
	mov	r0, #12
	bl	__MapActor_GetActor
	ldr	r3, [r0, #16]
	asr	r3, r3, #20
	str	r3, [sp, #4]
	mov	r1, #52
	mov	r2, #1
	mov	r3, #1
	asr	r5, r5, #20
	mov	r0, #22
	str	r5, [sp]
	bl	__Func_8010704
	mov	r0, #13
	bl	__MapActor_GetActor
	ldr	r5, [r0, #8]
	mov	r0, #13
	bl	__MapActor_GetActor
	ldr	r3, [r0, #16]
	asr	r3, r3, #20
	str	r3, [sp, #4]
	mov	r1, #52
	mov	r2, #1
	mov	r3, #1
	asr	r5, r5, #20
	mov	r0, #22
	str	r5, [sp]
	bl	__Func_8010704
	mov	r0, #14
	bl	__MapActor_GetActor
	ldr	r5, [r0, #8]
	mov	r0, #14
	bl	__MapActor_GetActor
	ldr	r3, [r0, #16]
	asr	r3, r3, #20
	str	r3, [sp, #4]
	asr	r5, r5, #20
	mov	r0, #22
	mov	r1, #52
	mov	r2, #1
	mov	r3, #1
	str	r5, [sp]
	bl	__Func_8010704
	add	sp, sp, #8
	pop	{r5}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_964_200a480,.Lfe1-OvlFunc_964_200a480

	.text
	.align	2, 0
