@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_964_2009fdc
	.thumb_func
	.type	 OvlFunc_964_2009fdc,function
OvlFunc_964_2009fdc:
	push	{r5, lr}
	sub	sp, sp, #8
	mov	r3, #8
	str	r3, [sp]
	mov	r5, #49
	mov	r0, #72
	mov	r1, #49
	mov	r2, #1
	mov	r3, #1
	str	r5, [sp, #4]
	bl	__Func_8010704
	mov	r3, #43
	str	r3, [sp, #4]
	mov	r0, #113
	mov	r3, #1
	mov	r1, #43
	mov	r2, #1
	str	r5, [sp]
	bl	__Func_8010704
	mov	r0, #100
	mov	r1, #0
	mov	r2, #0
	bl	__Func_808edac
	mov	r0, #101
	mov	r1, #0
	mov	r2, #0
	bl	__Func_808edac
	mov	r1, #136
	mov	r2, #198
	mov	r0, #15
	.code	16
	lsl	r1, r1, #16
	lsl	r2, r2, #18
	bl	__MapActor_SetPos
	mov	r1, #198
	mov	r2, #174
	mov	r0, #16
	.code	16
	lsl	r1, r1, #18
	lsl	r2, r2, #18
	bl	__MapActor_SetPos
	add	sp, sp, #8
	pop	{r5}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_964_2009fdc,.Lfe1-OvlFunc_964_2009fdc

	.text
	.align	2, 0
