@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_956_2008ba4
	.thumb_func
	.type	 OvlFunc_956_2008ba4,function
OvlFunc_956_2008ba4:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r8
	push	{r6, r7}
	ldr	r3, .L6
	ldr	r2, .L6+4
	ldr	r3, [r3]
	mov	r1, #250
	lsl	r1, r1, #1
	mov	sl, r3
	add	r3, r2, r1
	.code	16
	ldr	r3, [r3]
	sub	r1, r1, #50
	mov	r8, r3
	add	r3, r2, r1
	.code	16
	mov	r2, #0
	ldrsh	r3, [r3, r2]
	mov	r6, r0
	cmp	r3, #2
	bne	.L3
	bl	__CutsceneStart
	.code	16
	lsl	r3, r6, #1
	ldr	r7, .L6+8
	add	r5, r3, r6
	.code	16
	add	r0, r5, r7
	bl	__MessageID
	movs r1, #0
	add r0, r6, #0
	bl __Func_8092c40
	.code	16
	mov	r0, r8
	mov	r1, #0
	bl	__Func_8091c7c
	cmp	r0, #0
	bne	.L4
	add	r0, r7, #1
	add	r0, r5, r0
	bl	__MessageID
	mov	r1, #0
	mov	r0, r6
	bl	__ActorMessage
	mov	r2, #224
	lsl	r2, r2, #1
	mov	r3, #128
	add	r2, r2, sl
	lsl	r3, r3, #2
	str	r3, [r2]
	mov	r2, #228
	lsl	r2, r2, #1
	add	r2, r2, sl
	mov	r3, #15
	str	r3, [r2]
	bl	__MapTransitionOut
	bl	__WaitMapTransition
	mov	r0, r6
	bl	OvlFunc_common1_78
	bl	__MapTransitionIn
	bl	__WaitMapTransition
	b	.L5
.L4:
	add	r0, r7, #2
	add	r0, r5, r0
	bl	__MessageID
	mov	r0, r6
	mov	r1, #0
	bl	__ActorMessage
.L5:
	bl	__CutsceneEnd
.L3:
	pop	{r3, r5}
	mov	r8, r3
	mov	sl, r5
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L7:
	.align	2, 0
.L6:
	.word	iwram_3001ebc
	.word	gState
	.word	8307
.Lfe1:
	.size	 OvlFunc_956_2008ba4,.Lfe1-OvlFunc_956_2008ba4

	.text
	.align	2, 0
