@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_f88
	.thumb_func
	.type	 OvlFunc_f88,function
OvlFunc_f88:
	bx	lr
.Lfe1:
	.size	 OvlFunc_f88,.Lfe1-OvlFunc_f88

	.text
	.align	2, 0
