@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_954_2008178
	.thumb_func
	.type	 OvlFunc_954_2008178,function
OvlFunc_954_2008178:
	push	{r5, r6, lr}
	mov	r0, #10
	bl	__WaitFrames
	ldr	r2, .L9
	.code	16
	ldr	r3, [r2]
	mov	r5, #0
	.code	16
	cmp	r3, #22
	beq	.L3
	mov	r6, r2
	.code	16
.L8:
	mov	r0, #1
	.code	16
	add	r5, r5, #1
	.code	16
	bl	__WaitFrames
	cmp	r5, #119
	bgt	.L3
	ldr	r3, [r6]
	.code	16
	cmp	r3, #22
	bne	.L8
.L3:
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L10:
	.align	2, 0
.L9:
	.word	.L441c
.Lfe1:
	.size	 OvlFunc_954_2008178,.Lfe1-OvlFunc_954_2008178

	.text
	.align	2, 0
