@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_884_2008780
	.thumb_func
	.type	 OvlFunc_884_2008780,function
OvlFunc_884_2008780:
	push	{r5, lr}
	mov	r0, #188
	sub	sp, sp, #8
	bl	__PlaySound
	.code	16
	mov	r5, #2
	.code	16
	mov	r1, #63
	.code	16
	mov	r2, #51
	.code	16
	mov	r3, #8
	.code	16
	mov	r0, #0
	.code	16
	str	r5, [sp]
	str	r5, [sp, #4]
	bl	__CopyMapTiles
	mov	r0, #10
	.code	16
	bl	__WaitFrames
	mov	r3, #8
	.code	16
	mov	r1, #63
	.code	16
	mov	r2, #51
	.code	16
	mov	r0, #2
	.code	16
	str	r5, [sp]
	str	r5, [sp, #4]
	bl	__CopyMapTiles
	mov	r0, #10
	.code	16
	bl	__WaitFrames
	mov	r1, #176
	.code	16
	mov	r2, #153
	.code	16
	lsl	r2, r2, #1
	.code	16
	mov	r0, #0
	.code	16
	lsl	r1, r1, #1
	.code	16
	bl	__Func_80921c4
	mov	r0, #0
	.code	16
	mov	r1, #3
	.code	16
	bl	__Func_8092b08
	mov	r1, #176
	.code	16
	mov	r2, #148
	.code	16
	lsl	r1, r1, #1
	.code	16
	lsl	r2, r2, #1
	.code	16
	mov	r0, #0
	.code	16
	bl	__Func_80921c4
	mov	r0, #2
	.code	16
	bl	OvlFunc_884_2008714
	add	sp, sp, #8
	pop	{r5}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_884_2008780,.Lfe1-OvlFunc_884_2008780

	.text
	.align	2, 0
