@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	Func_fb790
	.type	 Func_fb790,function
	.thumb_func
Func_fb790:
	bx	lr
.Lfe1:
	.size	 Func_fb790,.Lfe1-Func_fb790

	.text
	.align	2, 0
