@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_918_20097ec
	.thumb_func
	.type	 OvlFunc_918_20097ec,function
OvlFunc_918_20097ec:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	ldr	r6, .L10
	mov	r2, #0
	ldrsh	r3, [r6, r2]
	mov	r2, #1
	neg	r2, r2
	sub	sp, sp, #8
	cmp	r3, r2
	beq	.L2
	mov	r8, r2
	mov	r5, #0
	mov	r7, #1
	.code	16
.L9:
	ldrsh	r0, [r6, r5]
	.code	16
	bl	__GetFlag
	cmp	r0, #0
	beq	.L7
	add	r3, r5, #2
	.code	16
	ldrsh	r3, [r6, r3]
	cmp	r3, #0
	beq	.L7
	add	r3, r5, #4
	.code	16
	ldrsh	r0, [r6, r3]
	add	r3, r5, #6
	.code	16
	ldrsh	r1, [r6, r3]
	add	r3, r3, #2
	.code	16
	ldrsh	r2, [r6, r3]
	add	r3, r3, #2
	.code	16
	ldrsh	r3, [r6, r3]
	.code	16
	str	r7, [sp]
	str	r7, [sp, #4]
	bl	__CopyMapTiles
.L7:
	ldr	r6, .L10
	add	r5, r5, #12
	ldrsh	r3, [r6, r5]
	.code	16
	cmp	r3, r8
	bne	.L9
.L2:
	add	sp, sp, #8
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L11:
	.align	2, 0
.L10:
	.word	.L1ca8
.Lfe1:
	.size	 OvlFunc_918_20097ec,.Lfe1-OvlFunc_918_20097ec

	.text
	.align	2, 0
