@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80063bc
	.thumb_func
	.type	 Func_80063bc,function
Func_80063bc:
	push	{r5, r6, r7, lr}
	ldr	r5, .L4
	ldr	r4, [r5]
	mov	r6, r1
	ldr	r7, .L4+4
	cmp	r4, #0
	beq	.L3
	mov	r0, #1
	neg	r0, r0
	b	.L2
.L3:
	ldr	r2, .L4+8
	ldrh	r1, [r2]
	strh	r2, [r2]
	.code	16
	mov	r3, #128
	strb	r3, [r7, #1]
	ldr	r3, .L4+12
	strh	r6, [r3]
	ldr	r3, .L4+16
	strb	r4, [r3]
	mov	r3, #1
	str	r0, [r5]
	strb	r3, [r7]
	strh	r1, [r2]
	mov	r0, #0
.L2:
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L5:
	.align	2, 0
.L4:
	.word	ewram_2002080
	.word	ewram_2002220
	.word	67109384
	.word	ewram_2002008
	.word	ewram_20023a4
.Lfe1:
	.size	 Func_80063bc,.Lfe1-Func_80063bc

	.text
	.align	2, 0
