// gs2/files.h
#ifndef GS2_FILES_H
#define GS2_FILES_H

#define FILE_BUILD_DATE                       2

#define FILE_UI_GFX                           19
//      ?                                     20
//      ?                                     21
//      ?                                     22
//      ?                                     23
#define FILE_INTRO_TEXT                       24
//      ?                                     25
#define FILE_TITLE                            26
//      ?                                     27
//      ?                                     28
//      ?                                     29
//      ?                                     30
//      ?                                     31
#define FILE_NINTENDO_LOGO                    32
#define FILE_CAMELOT_LOGO                     33
#define FILE_MAIN_MENU_BG                     34
#define FILE_WORLD_MAP_SMALL                  35
#define FILE_WORLD_MAP                        36
//      ?                                     37
//      ?                                     38

// Backgrounds
#define FILE_BG_ARTEMIS                       39  // (unused)
#define FILE_BG_SUHALLA_GATE_GS1              40
#define FILE_BG_PIRATE_SHIP                   41
#define FILE_BG_CROSSBONE_ISLE_CAVE           42
#define FILE_BG_COLOSSEUM                     43
#define FILE_BG_FUSION_DRAGON                 44
#define FILE_BG_VENUS_LIGHTHOUSE_AERIE        45
#define FILE_BG_VENUS_LIGHTHOUSE              46
#define FILE_BG_SUHALLA_DESERT                47
#define FILE_BG_ALTMILLER_CAVE                48
#define FILE_BG_TUNNEL_RUINS                  49
#define FILE_BG_BABI_LIGHTHOUSE               50
#define FILE_BG_LAMAKAN_DESERT                51
#define FILE_BG_MOGALL_FOREST                 52
#define FILE_BG_MERCURY_LIGHTHOUSE_AERIE      53
#define FILE_BG_TOLBI_BOUND_SHIP_INTERIOR     54
#define FILE_BG_FUCHIN_FALLS_CAVE             55
#define FILE_BG_KOLIMA_FOREST                 56
#define FILE_BG_TRET_TREE_INTERIOR            57
#define FILE_BG_VAULT_ATTIC                   58
#define FILE_BG_ALTIN_PEAK                    59
#define FILE_BG_TOLBI_BOUND_SHIP_DECK         60
#define FILE_BG_MERCURY_LIGHTHOUSE            61
#define FILE_BG_PROLOGUE                      62
#define FILE_BG_TRET_TREE_EXTERIOR            63
#define FILE_BG_OVERWORLD_BEACH_GS1           64
#define FILE_BG_OVERWORLD_SNOW_GS1            65
#define FILE_BG_OVERWORLD_PLAINS_GS1          66
#define FILE_BG_SOL_SANCTUM                   67
#define FILE_BG_OVERWORLD_FOREST_GS1          68
#define FILE_BG_SUMMON_SKY                    69
#define FILE_BG_OVERWORLD_PLAINS              70
#define FILE_BG_OVERWORLD_BEACH               71
#define FILE_BG_OVERWORLD_FOREST              72
#define FILE_BG_CAVE_GS2                      73
#define FILE_BG_SUHALLA_GATE_GS2              74
#define FILE_BG_TAOPO_SWAMP                   75
#define FILE_BG_DEHKAN_PLATEAU                76
#define FILE_BG_AIRS_ROCK_EXTERIOR_1          77
#define FILE_BG_AIRS_ROCK_EXTERIOR_2          78
#define FILE_BG_AIRS_ROCK_INTERIOR            79
#define FILE_BG_KIBOMBO_MOUNTAINS             80
#define FILE_BG_GABOMBA_STATUE                81
#define FILE_BG_LEMURIAN_SHIP_INTERIOR        82
#define FILE_BG_LEMURIAN_SHIP_SAILING         83
#define FILE_BG_GAIA_ROCK_EXTERIOR            84
#define FILE_BG_GAIA_ROCK_INTERIOR            85
#define FILE_BG_ANKOHL_RUINS                  86
#define FILE_BG_YAMPI_DESERT                  87
#define FILE_BG_TAOPO_SWAMP_LAVA              88
#define FILE_BG_AQUA_ROCK_EXTERIOR            89
#define FILE_BG_YAMPI_DESERT_CAVE             90
#define FILE_BG_AQUA_ROCK_INTERIOR            91
#define FILE_BG_ISLET_CAVE                    92
#define FILE_BG_MAGMA_ROCK_EXTERIOR           93
#define FILE_BG_MAGMA_ROCK_INTERIOR           94
#define FILE_BG_MOAPA                         95
#define FILE_BG_SEA_OF_TIME                   96
#define FILE_BG_JUPITER_LIGHTHOUSE            97
#define FILE_BG_JUPITER_LIGHTHOUSE_EXTERIOR   98
#define FILE_BG_MARS_LIGHTHOUSE_EXTERIOR      99
#define FILE_BG_DOOM_DRAGON                   100
#define FILE_BG_TUNDARIA_TOWER                101
#define FILE_BG_JUPITER_LIGHTHOUSE_AERIE      102
#define FILE_BG_TREASURE_ISLE                 103
#define FILE_BG_MARS_LIGHTHOUSE_FROZEN        104
#define FILE_BG_MARS_LIGHTHOUSE               105
#define FILE_BG_FLAME_DRAGONS                 106
#define FILE_BG_TRIAL_ROAD                    107
#define FILE_BG_ANEMOS_INNER_SANCTUM          108
#define FILE_BG_OVERWORLD_SNOW_GS2            109
#define FILE_BG_OVERWORLD_SNOWSTORM           110
#define FILE_BG_UNUSED_OVERWORLD_SNOW_COPY    111
#define FILE_BG_UNUSED_DOOM_DRAGON_COPY       112
#define FILE_BG_CRUEL_RUIN                    113
#define FILE_BG_CATASTROPHE                   114
#define FILE_BG_RAMSES                        115
#define FILE_BG_STORM                         116
#define FILE_BG_LANDSCAPE                     117
#define FILE_BG_IRIS_SKY                      118
#define FILE_BG_IRIS_SPACE                    119
#define FILE_BG_ECLIPSE                       120

// Epilogue
#define FILE_EPILOGUE_VALE_DESTROYED_1        121
#define FILE_EPILOGUE_VALE_DESTROYED_2        122
#define FILE_EPILOGUE_EVERYONES_SAFE          123
#define FILE_EPILOGUE_EVERYONES_SAFE_UNUSED   124 // (unused)
#define FILE_EPILOGUE_ISAAC_FAMILY_HUG        125
#define FILE_EPILOGUE_CELEBRATION             126
#define FILE_EPILOGUE_THE_END_1               127
#define FILE_EPILOGUE_THE_END_2               128

// Minigames
#define FILE_LUCKY_WHEELS_BG                  129
#define FILE_LUCKY_WHEELS_GFX                 130
#define FILE_LUCKY_WHEELS_JACKPOT             131
#define FILE_LUCKY_DICE_BG                    132
#define FILE_SUPER_LUCKY_DICE_BG              133
#define FILE_LUCKY_DICE_GFX                   134
#define FILE_SUPER_LUCKY_DICE_GFX             135
#define FILE_SUPER_LUCKY_DICE_WIN             136
#define FILE_SUPER_LUCKY_DICE_LOSE            137
#define FILE_SUPER_LUCKY_DICE_HIGHER          138
#define FILE_SUPER_LUCKY_DICE_LOWER           139
#define FILE_SUPER_LUCKY_DICE_DOUBLE_UP       140
#define FILE_SUPER_LUCKY_DICE_CASH_OUT        141
#define FILE_SUPER_LUCKY_DICE_DIGITS_1        142
#define FILE_SUPER_LUCKY_DICE_DIGITS_2        143
#define FILE_SUPER_LUCKY_DICE_DIGITS_3        144
#define FILE_SUPER_LUCKY_DICE_X_OR            145
#define FILE_SUPER_LUCKY_DICE_DOUBLE_UP_2     146
#define FILE_SUPER_LUCKY_DICE_ONE_PAIR        147
#define FILE_SUPER_LUCKY_DICE_TWO_PAIR        148
#define FILE_SUPER_LUCKY_DICE_TRIPLE          149
#define FILE_SUPER_LUCKY_DICE_PERFECT         150
#define FILE_SUPER_LUCKY_DICE_FINAL_GAME      151

// Summon sprites
#define FILE_SPRITE_FLORA                     152
#define FILE_SPRITE_NEPTUNE                   153
#define FILE_SPRITE_FLORA_PETALS              154
#define FILE_SPRITE_CHARON                    155
#define FILE_SPRITE_CHARON_SEAL               156
#define FILE_SPRITE_CHARON_ATTACK             157
#define FILE_SPRITE_CHARON_SHARDS             158
#define FILE_SPRITE_CHARON_SHADOW             159
#define FILE_SPRITE_DAEDALUS_FOREST           160
#define FILE_SPRITE_DAEDALUS                  161
#define FILE_SPRITE_DAEDALUS_SMALL_MISSILE    162
#define FILE_SPRITE_ECLIPSE_MOUTH             163
#define FILE_SPRITE_ECLIPSE                   164
#define FILE_SPRITE_IRIS                      165
#define FILE_SPRITE_ATALANTA                  166
#define FILE_SPRITE_COATLICUE                 167
#define FILE_SPRITE_JUDGMENT_1                168
#define FILE_SPRITE_JUDGMENT_2                169
#define FILE_SPRITE_JUDGMENT_3                170
#define FILE_SPRITE_CATASTROPHE               171
#define FILE_SPRITE_CATASTROPHE_SWORD_HILT    172
#define FILE_SPRITE_CATASTROPHE_SWORD         173
#define FILE_SPRITE_CATASTROPHE_SHIELD        174

// VFX (GS2)
#define FILE_VFX_METEOR_BLOW_STARS            175
#define FILE_VFX_VENGEANCE                    176
#define FILE_VFX_ULYSSES_SILHOUETTE           177
#define FILE_VFX_ULYSSES_SILHOUETTE_UNUSED    178 // (unused)
#define FILE_VFX_ULYSSES_OFUDA                179
#define FILE_VFX_VORTEX                       180
#define FILE_VFX_CHARON_SUMMON_CIRCLE         181
#define FILE_VFX_CHARON_SMALL_CIRCLE          182
#define FILE_VFX_MEGAERA_TORNADO              183
#define FILE_PAL_CHARON_SPELL                 184
#define FILE_PAL_IRON                         185
#define FILE_VFX_DAEDALUS_STEAM               186
#define FILE_VFX_DAEDALUS_BIRD                187
#define FILE_VFX_UNUSED_LIGHTNING             188 // (unused)
#define FILE_VFX_CHARON_LIGHTNING             189
#define FILE_VFX_CHARON_MAGIC_CIRCLE          190
#define FILE_VFX_WATERY_GRAVE                 191
#define FILE_VFX_PURGATORY                    192
#define FILE_VFX_SHOCKWAVE_3D                 193
#define FILE_VFX_SHOCKWAVE                    194
#define FILE_VFX_SHOCKWAVE_SMALL              195
#define FILE_VFX_LENS_FLARE                   196
#define FILE_VFX_ZAGAN_AURA                   197
#define FILE_VFX_ZAGAN_SLASH                  198
#define FILE_VFX_ULYSSES_SUMMON_CIRCLE        199
#define FILE_VFX_ULYSSES_JAWS                 200
#define FILE_VFX_BEAM_1                       201
#define FILE_VFX_BEAM_2                       202
#define FILE_VFX_LIQUIFIER                    203
#define FILE_VFX_UNUSED_FIRE_SWIRL            204 // (unused)
#define FILE_VFX_CLOUDY_TEXTURE               205
#define FILE_VFX_COOL                         206
#define FILE_VFX_SERAC_CLOUD                  207
#define FILE_VFX_BALM                         208
#define FILE_VFX_TINDER                       209
#define FILE_VFX_WIND_TEXTURE_1               210
#define FILE_VFX_WIND_TEXTURE_2               211
#define FILE_VFX_UNUSED_X_GLOW                212 // (unused)
#define FILE_VFX_GLEAM                        213
#define FILE_VFX_GLEAM_BIG                    214
#define FILE_VFX_MUSIC_NOTES                  215
#define FILE_VFX_WYRD_CURSE                   216
#define FILE_VFX_WHEEZE                       217
#define FILE_VFX_EXPLOSION_TEXTURE            218
#define FILE_VFX_HEAVY_DIVIDE                 219
#define FILE_VFX_HEARTBREAK                   220
#define FILE_VFX_APOCALYPSE                   221
#define FILE_VFX_CARD_FLAME                   222
#define FILE_VFX_CARD_BRAMBLE                 223
#define FILE_VFX_CARD_FROST                   224
#define FILE_VFX_CARD_THUNDER                 225
#define FILE_VFX_CARD_BAFFLE                  226
#define FILE_VFX_CARD_SLEEP                   227
#define FILE_VFX_CARD_DEATH                   228
#define FILE_VFX_CARD_SWORD                   229
#define FILE_VFX_MOTHER_EARTH                 230
#define FILE_VFX_LEGEND_SWORD                 231
#define FILE_VFX_DRAGON_HEAD                  232
#define FILE_VFX_LIGHT_RAY                    233
#define FILE_VFX_DIAMOND_BERG                 234
#define FILE_VFX_JUGGLE                       235
#define FILE_VFX_LEGEND_MAGIC_CIRCLE          236
#define FILE_VFX_RAGING_HEAT_MAGIC_CIRCLE     237
#define FILE_VFX_CATASTROPHE_PYRAMID_SIDE     238
#define FILE_VFX_CATASTROPHE_PYRAMID_BASE     239
#define FILE_VFX_SARCOPHAGUS                  240
#define FILE_VFX_RAIDENS_WRATH                241
#define FILE_VFX_FEAR_PUPPET                  242
#define FILE_VFX_WHIPLASH                     243
#define FILE_VFX_HAURES_SLASH                 244
#define FILE_VFX_LIFE_SHEAR                   245
#define FILE_VFX_ROLLING_FLAME                246
#define FILE_VFX_HAURES_MAGIC_CIRCLE          247
#define FILE_VFX_CATASTROPHE_LIGHTNING_1      248
#define FILE_VFX_CATASTROPHE_LIGHTNING_2      249
#define FILE_VFX_CATASTROPHE_LIGHTNING_3      250
#define FILE_VFX_COATLICUE_MAGIC_CIRCLE       251
#define FILE_VFX_COATLICUE_RING_TEXTURE       252
#define FILE_VFX_COATLICUE_BUBBLES            253
#define FILE_VFX_TWIN_SHEAR                   254
#define FILE_VFX_BEAST_NEEDLE                 255
#define FILE_VFX_STRONG_HIT                   256
#define FILE_VFX_ODYSSEY_SWORD                257
#define FILE_VFX_ODYSSEY_SMALL_SWORD          258
#define FILE_VFX_MEGIDDO_CORONA               259
#define FILE_VFX_CRUEL_RUIN_BEAM              260
#define FILE_VFX_CHILL                        261

// VFX (GS1)
#define FILE_VFX_SCREEN_SHATTER               262
#define FILE_VFX_DJINN_SET                    263
#define FILE_PAL_DJINN_SET_JUPITER            264
#define FILE_PAL_DJINN_SET_MARS               265
#define FILE_PAL_DJINN_SET_VENUS              266
#define FILE_VFX_CRITICAL_HIT_1               267
#define FILE_VFX_CRITICAL_HIT_2               268
#define FILE_VFX_VORPAL_SLASH_1               269
#define FILE_VFX_VORPAL_SLASH_2               270
#define FILE_VFX_QUICK_STRIKE_1               271
#define FILE_VFX_QUICK_STRIKE_2               272
#define FILE_VFX_UNUSED_SLASH_1               273 // (unused)
#define FILE_VFX_UNUSED_SLASH_2               274 // (unused)
#define FILE_VFX_UNDEAD_SWORD                 275
#define FILE_VFX_ATTACK_UNUSED                276 // (unused)
#define FILE_VFX_FORCEFUL_ARM                 277
#define FILE_VFX_DEMON_BREATH                 278
#define FILE_VFX_RAGNAROK                     279
#define FILE_VFX_TITAN_BLADE                  280
#define FILE_VFX_EPOWER_UP                    281
#define FILE_VFX_SONIC_WAVE                   282
#define FILE_VFX_SPIDER_WEB                   283
#define FILE_VFX_STORM_BREATH                 284
#define FILE_VFX_WING_FLUTTER                 285
#define FILE_VFX_CRAZY_VOICE                  286
#define FILE_VFX_SHURIKEN                     287
#define FILE_VFX_UNSUMMON_FLASH               288
#define FILE_VFX_UNSUMMON_RING                289
#define FILE_PAL_PLASMA                       290
#define FILE_VFX_HELM_SPLITTER_SLASH          291
#define FILE_VFX_THOR_LIGHTNING               292
#define FILE_VFX_ANNIHILATION                 293
#define FILE_VFX_JUDGMENT_SPARKLE             294
#define FILE_VFX_JUDGMENT_IMPACT              295
#define FILE_VFX_THOR_HAMMER_GLOW             296
#define FILE_VFX_HEAT_WAVE                    297
#define FILE_VFX_HAUNT_ATTACK                 298
#define FILE_VFX_ATALANTA_ARROW               299
#define FILE_VFX_ATTACK_SIDESWIPE             300
#define FILE_VFX_UNUSED_SKULL_CLOUD           301 // (unused)
#define FILE_VFX_HELM_SPLITTER_STAR           302
#define FILE_VFX_NEPTUNE                      303
#define FILE_VFX_NEPTUNE_SPOUT                304
#define FILE_VFX_JUDGMENT_EXPLOSION           305
#define FILE_VFX_TENTACLE_1                   306
#define FILE_VFX_TENTACLE_2                   307
#define FILE_VFX_PARTICLE                     308
#define FILE_VFX_PARTICLE_FAINT               309
#define FILE_VFX_PARTICLE_BIG                 310
#define FILE_VFX_PARTICLE_WIDE                311
#define FILE_PAL_ROTTEN_BLOOD                 312
#define FILE_VFX_SABRE_DANCE                  313
#define FILE_VFX_BIND                         314
#define FILE_VFX_CURSE                        315
#define FILE_VFX_GAIA                         316
#define FILE_PAL_GAIA                         317
#define FILE_VFX_EXPLOSION                    318
#define FILE_VFX_THORN                        319
#define FILE_VFX_SLASH_1                      320
#define FILE_VFX_SLASH_2                      321
#define FILE_VFX_SLASH_3                      322
#define FILE_VFX_PROCNE_CYCLONE               323
#define FILE_VFX_PUNJI                        324
#define FILE_VFX_GROWTH                       325
#define FILE_VFX_VOLCANO                      326
#define FILE_PAL_VOLCANO                      327
#define FILE_PAL_FIRE                         328
#define FILE_PAL_LIGHTNING                    329
#define FILE_PAL_FELL_DOOM_DRAGON             330
#define FILE_VFX_PROCNE_ATTACK                331
#define FILE_VFX_PLANET_DIVER                 332
#define FILE_VFX_SPIRE                        333
#define FILE_VFX_QUAKE                        334
#define FILE_VFX_UNUSED_ELEMENT_PARTICLE      335 // (unused)
#define FILE_VFX_DJINNI_MARS                  336
#define FILE_VFX_DJINNI_MARS_SMALL            337
#define FILE_VFX_DJINNI_JUPITER               338
#define FILE_VFX_DJINNI_JUPITER_SMALL         339
#define FILE_VFX_DJINNI_MERCURY               340
#define FILE_VFX_DJINNI_MERCURY_SMALL         341
#define FILE_VFX_DJINNI_VENUS                 342
#define FILE_VFX_DJINNI_VENUS_SMALL           343
#define FILE_VFX_KIRIN_FIRE                   344
#define FILE_VFX_SPECIAL_SLASH                345
#define FILE_VFX_UNUSED_PLASMA_BALL           346 // (unused)
#define FILE_VFX_HIT_V                        347
#define FILE_VFX_HIT                          348
#define FILE_VFX_UNUSED_PARTICLE              349 // (unused)
#define FILE_VFX_STAT_DEFENSE                 350
#define FILE_VFX_STAT_ATTACK                  351
#define FILE_VFX_STAT_DOWN                    352
#define FILE_VFX_CLOUD                        353
#define FILE_PAL_BONE_CHILLER                 354
#define FILE_PAL_POISON                       355
#define FILE_PAL_VENOM                        356
#define FILE_PAL_EARTH_FORCE                  357
#define FILE_PAL_SMOG                         358
#define FILE_PAL_MURK                         359
#define FILE_PAL_GRAYSCALE                    360 // (unused)
#define FILE_PAL_STUN_BOLT                    361
#define FILE_VFX_STAT_AGILITY_UP              362
#define FILE_VFX_VINE                         363
#define FILE_VFX_GROUND                       364
#define FILE_VFX_HAUNT                        365
#define FILE_VFX_CHARM                        366
#define FILE_VFX_CONDEMN_1                    367
#define FILE_VFX_CONDEMN_2                    368
#define FILE_VFX_ASURA_1                      369
#define FILE_VFX_ASURA_2                      370
#define FILE_VFX_CONFUSE                      371 // (unused)
#define FILE_VFX_BARRIER                      372
#define FILE_VFX_REVIVE                       373
#define FILE_VFX_CYBELE                       374
#define FILE_VFX_ICE                          375
#define FILE_VFX_FLARE                        376
#define FILE_VFX_ATTACK_SLASH                 377
#define FILE_VFX_ATTACK_CLAWS                 378
#define FILE_VFX_FIREBALL                     379
#define FILE_VFX_FROST                        380
#define FILE_VFX_BOREAS                       381
#define FILE_VFX_SPARKLE                      382
#define FILE_VFX_JUDGMENT_SHOT                383
#define FILE_VFX_THOR_STRIKE                  384
#define FILE_VFX_TACKLE                       385
#define FILE_VFX_CLOUD_NON_ELEMENTAL          386
#define FILE_VFX_MUD                          387
#define FILE_VFX_BLAST                        388
#define FILE_VFX_METEOR_FLAMES                389
#define FILE_VFX_DRAGON_CLOUD                 390
#define FILE_VFX_TERRA_STRIKE                 391
#define FILE_VFX_BOLT                         392
#define FILE_VFX_STING                        393
#define FILE_VFX_BITE                         394
#define FILE_VFX_SLASH_HIT                    395
#define FILE_PAL_CAST_VENUS                   396
#define FILE_VFX_CAST_MERCURY                 397
#define FILE_PAL_CAST_MARS                    398
#define FILE_PAL_CAST_JUPITER                 399
#define FILE_VFX_DOUSE                        400
#define FILE_VFX_FROTH                        401
#define FILE_VFX_WHIRLWIND                    402
#define FILE_VFX_PRISM                        403
#define FILE_VFX_PLASMA                       404

#define FILE_ATALANTA_MOTION                  405
#define FILE_DRAGON_CLOUD_MOTION              406

//      ?                                     407
//      ?                                     408
//      ?                                     409
//      ?                                     410
//      ?                                     411
//      ?                                     412
//      ?                                     413
//      ?                                     414
//      ?                                     415
//      ?                                     416
//      ?                                     417
//      ?                                     418
//      ?                                     419
//      ?                                     420
//      ?                                     421
//      ?                                     422
//      ?                                     423
//      ?                                     424
//      ?                                     425
//      ?                                     426
//      ?                                     427
//      ?                                     428
//      ?                                     429
//      ?                                     430
//      ?                                     431
//      ?                                     432
//      ?                                     433
//      ?                                     434
//      ?                                     435
//      ?                                     436
//      ?                                     437
//      ?                                     438
//      ?                                     439
//      ?                                     440
//      ?                                     441
//      ?                                     442
//      ?                                     443
//      ?                                     444
//      ?                                     445

#define FILE_WHIRLWIND_STONE_VFX              446
//      ?                                     447
//      ?                                     448
//      ?                                     449
//      ?                                     450
//      ?                                     451
//      ?                                     452
//      ?                                     453
//      ?                                     454
//      ?                                     455
//      ?                                     456
//      ?                                     457
//      ?                                     458
//      ?                                     459

#define FILE_TRIAL_ROAD_TEXT                  460
#define FILE_UI_SLIDER_HANDLE                 461 // 8 files
#define FILE_UI_BOX_ANIM                      469

#define FILE_PORTRAITS                        470
#define FILE_UI_ICONS                         471

#define FILE_TRIAL_ROAD_HUD                   472

#define FILE_FIELD_PARCH                      473
#define FILE_FIELD_HOVER                      474
#define FILE_FIELD_MAGNET                     475 // (unused)
#define FILE_FIELD_BLAZE                      476
#define FILE_FIELD_BLAZE_JUPITER              477
#define FILE_FIELD_BLAZE_VENUS                478
#define FILE_FIELD_BLAZE_MERCURY              479
#define FILE_FIELD_CYCLONE_LEAF               480
#define FILE_FIELD_DUST_CLOUD                 481
#define FILE_FIELD_DUST_CLOUD_COPY            482
#define FILE_FIELD_UNUSED_SHINY_TILE          483 // (unused)
#define FILE_FIELD_POUND_STAR                 484
#define FILE_FIELD_POUND_STAR_2               485 // (unused)
#define FILE_FIELD_ARROW                      486 // (unused)
#define FILE_FIELD_ARROW_BOW                  487 // (unused)
#define FILE_FIELD_BURST                      488
#define FILE_FIELD_SCOOP_DIRT                 489
#define FILE_FIELD_SPARKLE_1                  490
#define FILE_FIELD_SPARKLE_2                  491
#define FILE_FIELD_PARCH_STEAM                492
#define FILE_FIELD_MAGNET_SPARKS              493 // (unused)
#define FILE_FIELD_TREMOR_DEBRIS              494
#define FILE_FIELD_PARTICLES                  495
#define FILE_FIELD_BURST_DEBRIS               496
#define FILE_FIELD_GRIND_BUBBLE               497

#define FILE_NORTHERN_REACHES_ICE_DEBRIS      498
#define FILE_FIELD_SCOOP_SNOW                 499
#define FILE_SUMMON_TABLET_RUNES              500
#define FILE_SUMMON_TABLET_DEBRIS             501
#define FILE_JUPITER_LIGHTHOUSE_ARROW         502
#define FILE_CHAMPA_FORGE_VFX                 503
#define FILE_EPILOGUE_PORTRAIT_BOX            504

#define FILE_UI_UNUSED_SPRITES                505 // (unused)
#define FILE_UI_CURSOR                        506
#define FILE_UI_PARTY_SCROLL_SIDE             507
#define FILE_UI_EQUIP_STAT_DOWN               508
#define FILE_UI_EQUIP_STAT_UP                 509
#define FILE_UI_PARTY_SCROLL_UP               510
#define FILE_UI_PARTY_SCROLL_DOWN             511
#define FILE_UI_DJINN_STAT_UP                 512
#define FILE_UI_DJINN_STAT_DOWN               513
#define FILE_UI_PENCIL                        514

// (enemy GFX: 515-619)

#define FILE_OFFSET_MAPS                      620
// (maps: 620-1722)

#endif // GS2_FILES_H