// gs2/sprites.h
#ifndef GS2_SPRITES_H
#define GS2_SPRITES_H

#define SPR_ISAAC                   0
#define SPR_GARET                   1
#define SPR_IVAN                    2
#define SPR_MIA                     3
#define SPR_FELIX                   4
#define SPR_JENNA                   5
#define SPR_SHEBA                   6
#define SPR_PIERS                   7

#define SPR_SHIP_WORLD              9
#define SPR_SHIP_WINGS_WORLD        10
#define SPR_SHIP                    11
#define SPR_SHIP_WINGS              12
#define SPR_UNUSED_SAND             13 // unused
#define SPR_SPLASH                  14
#define SPR_UNUSED_BUBBLE           15 // unused
#define SPR_BRIGGS                  16
#define SPR_TAVI                    17
#define SPR_RIKI                    18
#define SPR_MADRAN_ELDER            19
#define SPR_MADRAN_MAYOR            20
#define SPR_MASTER_POI              21
#define SPR_WEREWOLF_CHILD          22
#define SPR_KARST                   23
#define SPR_ALHAFRAN_MAYOR          24
#define SPR_NARIBWE_FORTUNE_TELLER  25
#define SPR_AKAFUBU                 26
#define SPR_AKAFUBU_CROWNED         27
#define SPR_AKAFUBUS_FATHER         28
#define SPR_SUSA                    29
#define SPR_UZUME                   30
#define SPR_HYDROS                  31
#define SPR_KUSHINADA               32
#define SPR_AGATIO                  33
#define SPR_CONSERVATO              34
#define SPR_LEMURIAN_SENATOR        35
#define SPR_OBABA                   36
#define SPR_CHAUCHA                 37
#define SPR_EOLEO                   38
#define SPR_CHAMPA_SAILOR           39
#define SPR_KNIGHT                  40
#define SPR_MOAPA                   41
#define SPR_MAHA                    42
#define SPR_LUNPA                   43
#define SPR_PUELLE                  44
#define SPR_PROX_ELDER              45
#define SPR_SHAMAN_FORTUNE_TELLER   46
#define SPR_FELIX_PACKED            47
#define SPR_JENNA_PACKED            48
#define SPR_SHEBA_PACKED            49
#define SPR_PIERS_PACKED            50
#define SPR_ISAAC_PACKED            51
#define SPR_GARET_PACKED            52
#define SPR_IVAN_PACKED             53
#define SPR_MIA_PACKED              54
#define SPR_KRADEN_PACKED           55
#define SPR_KRADEN                  56
#define SPR_ALEX                    57
#define SPR_IODEM                   58
#define SPR_HAMA                    59
#define SPR_JENNAS_FATHER           60
#define SPR_JENNAS_MOTHER           61
#define SPR_KYLE                    62
#define SPR_FEIZHI                  63
#define SPR_GARETS_FATHER           64
#define SPR_GARETS_MOTHER           65
#define SPR_DORA                    66
#define SPR_SEAN                    67
#define SPR_OURANOS                 68
#define SPR_GARETS_BROTHER          69
#define SPR_GARETS_SISTER           70
//      ?                           71
//      ?                           72
//      ?                           73
//      ?                           74
//      ?                           75
//      ?                           76
//      ?                           77
//      ?                           78
//      ?                           79
#define SPR_COW                     80
#define SPR_SHEEP                   81
//      ?                           82
//      ?                           83
//      ?                           84
//      ?                           85
//      ?                           86
//      ?                           87
//      ?                           88
//      ?                           89
//      ?                           90
#define SPR_MONK                    91
#define SPR_SEAGULL                 92
#define SPR_RUFFIAN                 93
//      ?                           94
//      ?                           95
//      ?                           96
//      ?                           97
//      ?                           98
//      ?                           99
//      ?                           100
//      ?                           101
//      ?                           102
#define SPR_KING_SCORPION           103
#define SPR_SUNSHINE                104
//      ?                           105
//      ?                           106
//      ?                           107
//      ?                           108
//      ?                           109
//      ?                           110
//      ?                           111
//      ?                           112
//      ?                           113
//      ?                           114
//      ?                           115
//      ?                           116
//      ?                           117
//      ?                           118
//      ?                           119
//      ?                           120
//      ?                           121
//      ?                           122
//      ?                           123
//      ?                           124
//      ?                           125
//      ?                           126
//      ?                           127
//      ?                           128
#define SPR_UNUSED_SHOPKEEPER       129
//      ?                           130
#define SPR_CLOAKED_WEREWOLF        131
#define SPR_MOUSE                   132
//      ?                           133
//      ?                           134
//      ?                           135
//      ?                           136
//      ?                           137
//      ?                           138
//      ?                           139
//      ?                           140
//      ?                           141
//      ?                           142
//      ?                           143
//      ?                           144
//      ?                           145
//      ?                           146
//      ?                           147
#define SPR_SERPENT                 148
//      ?                           149
//      ?                           150
//      ?                           151
//      ?                           152
//      ?                           153
//      ?                           154
//      ?                           155
//      ?                           156
//      ?                           157
#define SPR_AVIMANDER               158
#define SPR_POSEIDON                159
//      ?                           160
#define SPR_AHRI                    161
#define SPR_TURTLE                  162
#define SPR_LIL_TURTLE              163
//      ?                           164
//      ?                           165
//      ?                           166
//      ?                           167
//      ?                           168
#define SPR_STAR_MAGICIAN           169
#define SPR_SENTINEL                170
//      ?                           171
//      ?                           172
//      ?                           173
//      ?                           174
//      ?                           175
//      ?                           176
#define SPR_VALUKAR                 177
//      ?                           178
//      ?                           179
#define SPR_DULLAHAN                180
#define SPR_FLAME_DRAGON            181
#define SPR_DOOM_DRAGON             182
#define SPR_DOOM_DRAGON_HEAD        183
#define SPR_CHESTBEATER             184
//      ?                           185
//      ?                           186
//      ?                           187
//      ?                           188
//      ?                           189
//      ?                           190
//      ?                           191
//      ?                           192
//      ?                           193
//      ?                           194
//      ?                           195
//      ?                           196
//      ?                           197
//      ?                           198
//      ?                           199
//      ?                           200
#define SPR_GREAT_HEALER            201
#define SPR_HEALER                  202
#define SPR_CHICKEN                 203
#define SPR_CHICK                   204
//      ?                           205
//      ?                           206
//      ?                           207
//      ?                           208
//      ?                           209
//      ?                           210
//      ?                           211
//      ?                           212
//      ?                           213
//      ?                           214
//      ?                           215
//      ?                           216
//      ?                           217
#define SPR_BIRD_1                  218 // unused?
#define SPR_BIRD_2                  219 // unused?
#define SPR_ELF_MAN                 220 // unused
#define SPR_LOHO_MAN                221
//      ?                           222
#define SPR_LALIVERO_MAN            223
#define SPR_BANDANA_RED             224
#define SPR_BANDANA_BLUE            225
#define SPR_BANDANA_YELLOW          226
#define SPR_BANDANA_GREEN           227
#define SPR_WAITRESS                228
#define SPR_SCHOLAR_OLD             229
#define SPR_SCHOLAR                 230
#define SPR_GUARD                   231
#define SPR_TOLBI_SOLDIER           232
#define SPR_TOLBI_SOLDIER_TORCH     233
#define SPR_KALAY_SOLDIER           234
#define SPR_SEAGULL_FLYING          235
#define SPR_GAME_OPERATOR           236
#define SPR_NOBLEMAN                237
#define SPR_MERCHANT                238
#define SPR_GLADIATOR               239
#define SPR_BANDIT                  240
#define SPR_THIEF                   241
#define SPR_CAPTAIN                 242
#define SPR_DJINNI_VENUS            243
#define SPR_DJINNI_MERCURY          244
#define SPR_DJINNI_MARS             245
#define SPR_DJINNI_JUPITER          246
#define SPR_PUNCH_ANT               247
#define SPR_JELLY                   248
#define SPR_MAD_PLANT               249
#define SPR_PILLAR_IVY              250
#define SPR_SAND_MOUND              251
#define SPR_MIRROR_STATUE           252
#define SPR_PLUG_STATUE             253
#define SPR_WALL_STATUE             254
#define SPR_BOULDER                 255
#define SPR_PLUG                    256
#define SPR_ROOFING                 257
#define SPR_LOG_H                   258
#define SPR_LOG_V                   259
#define SPR_LOG_SHORT_H             260
#define SPR_LOG_SHORT_V             261
#define SPR_CANDLE_FLAME            262
#define SPR_MAGMA_BALL              263
#define SPR_SURPRISE                264
#define SPR_PSYNERGY_STONE          265
//      ?                           266
//      ?                           267
//      ?                           268
#define SPR_RIPPLE                  269
#define SPR_FOOTPRINT               270
#define SPR_WATER_HOP_POWER         271
#define SPR_PILLAR                  272
#define SPR_PILLAR_SQUAT            273
#define SPR_PILLAR_SUBMERGED        274
#define SPR_HAND_UNUSED             275 // unused
#define SPR_WATERFALL               276
#define SPR_TIDAL_WAVE              277
#define SPR_HAND                    278
#define SPR_FALLING_PSYNERGY_STONE  279
#define SPR_WHIRLWIND               280
#define SPR_GROWTH                  281
#define SPR_BLAZE                   282
#define SPR_PSY_SHIELD              283
#define SPR_SANCTUM_IDOL            284
#define SPR_DUST_CLOUD              285
#define SPR_CRATE_WIDE              286
#define SPR_CRATE_NARROW            287
#define SPR_CRATE                   288
#define SPR_MERCURY_STATUE          289
#define SPR_FROST_PUDDLE            290
#define SPR_ICE_CRACK               291
//      ?                           292
#define SPR_PIPE_H                  293
#define SPR_PIPE_V                  294
//      ?                           295
#define SPR_PRIMULA                 296
#define SPR_SQUARE_LOG_H            297
#define SPR_SQUARE_LOG_V            298
#define SPR_VINE_SPROUT             299
#define SPR_DOUSE_CLOUD             300
#define SPR_DOUSE                   301
#define SPR_AERIE_PLATFORM          302
#define SPR_BEACON                  303
#define SPR_TORCH_SMALL             304
#define SPR_TORCH_SHORT             305
#define SPR_FLAME_SMALL             306
#define SPR_IVY                     307
#define SPR_IVY_LEAF                308
#define SPR_HALT                    309
#define SPR_VASE                    310
#define SPR_WISE_ONE                311
#define SPR_COLUMN                  312
#define SPR_COLUMN_SHORT            313
#define SPR_COLUMN_BASIN            314
#define SPR_CARRY_BLOCK             315
#define SPR_SCALE                   316
#define SPR_JUPITER_SPIRE           317
#define SPR_VENUS_STATUE            318
#define SPR_SMALL_PLATFORM          319
#define SPR_LEAF_PLATFORM           320
#define SPR_PISTON                  321
#define SPR_SUMMON_TABLET           322
#define SPR_PSYNERGY_TABLET         323
#define SPR_PUZZLE_ORB              324
#define SPR_WIND_STONE              325
#define SPR_LOG_BREAKABLE           326
//      ?                           327
//      ?                           328
#define SPR_LIFT_BOULDER            329
#define SPR_TUNNEL_RUINS_GATE       330
#define SPR_ROLLING_COLUMN_V        331
#define SPR_ROLLING_COLUMN_H        332
//      ?                           333
//      ?                           334
#define SPR_COLUMN_TORCH            335
#define SPR_TUNNEL_RUINS_STATUE     336
#define SPR_BLACK_SQUARE            337
#define SPR_AVIMANDER_SMALL         338
#define SPR_JUPITER_PLUG_STATUE     339
#define SPR_ARCHER_STATUE           340
#define SPR_JUPITER_STATUE          341
#define SPR_LEMURIA_DOCKED_SHIP     342
#define SPR_HORN_STATUE             343 // unused?
//      ?                           344
#define SPR_KALAY_SHIP              345
#define SPR_IDEJIMA_SHIP_GS2        346
#define SPR_SHIP_DOCK               347
#define SPR_SHIP_BUBBLE             348
#define SPR_GABOMBA_BUBBLE          349
#define SPR_POUND_UNUSED            350 // unused?
#define SPR_GEYSER                  351
#define SPR_POUND                   352
#define SPR_SCOOP                   353
#define SPR_SCOOP_HOLE              354
#define SPR_SCOOP_HOLE_GRAY         355
//      ?                           356
#define SPR_GEAR                    357
#define SPR_GEAR_NARROW             358
#define SPR_GEAR_SIDE_H             359
#define SPR_GEAR_SIDE_V             360
#define SPR_GEAR_SIDE_V_FULL        361
#define SPR_GEAR_ONE_WAY            362
#define SPR_LASH                    363
#define SPR_FLAME_BIG               364
#define SPR_FLAME                   365
#define SPR_FLAME_SMALL_2           366
#define SPR_BLAZE_TINY              367
#define SPR_CAULDRON                368
#define SPR_BREAKABLE_BRIDGE_H      369
#define SPR_BREAKABLE_BRIDGE_V      370
#define SPR_BROKEN_BRIDGE           371
#define SPR_SWINGING_VINE           372
#define SPR_SWINGING_CHAIN          373
#define SPR_GABOMBA_NODE            374
#define SPR_GABOMBA_STATUE          375
#define SPR_GABOMBA_HEAD            376
#define SPR_MOAI                    377
//      ?                           378
//      ?                           379
#define SPR_AQUA_MOAI               380
#define SPR_AQUA_MOAI_WATER         381
#define SPR_WHIRLWIND_STONE         382
#define SPR_AQUA_STONE              383
#define SPR_FIRE_STONE              384
#define SPR_DANCING_IDOL_PEDESTAL   385
//      ?                           386
//      ?                           387
//      ?                           388
//      ?                           389
//      ?                           390
//      ?                           391
//      ?                           392
//      ?                           393
#define SPR_ARROW_PLANT             394
#define SPR_GABOMBA_EYE             395
#define SPR_GABOMBA_TONGUE          396
#define SPR_DANCING_IDOL            397
#define SPR_BARREL                  398
#define SPR_PENGUS                  399
#define SPR_PENGULINA               400
#define SPR_FISH                    401
//      ?                           402
//      ?                           403
#define SPR_PILLAR_CRACKED_1        404
#define SPR_TROPICAL_BIRD           405
#define SPR_POUND_POST              406
#define SPR_LASH_POST               407
#define SPR_PILLAR_CRACKED_2        408 // unused?
#define SPR_PILLAR_CRACKED_3        409
#define SPR_EXCLAMATION             410
#define SPR_GABOMBA_CIRCUIT_BLOCK   411
#define SPR_BIG_FIREBALL            412
#define SPR_MARS_STATUE             413
#define SPR_DRAGON_HEAD_STATUE_V    414
#define SPR_DRAGON_HEAD_STATUE_H    415
#define SPR_DRAGON_ARM_STATUE       416
//      ?                           417
#define SPR_MARS_TORCH              418
#define SPR_MARS_TORCH_2            419
#define SPR_CANNON_H                420
#define SPR_CANNON_V                421
#define SPR_UNFINISHED_WINGS_1      422
#define SPR_UNFINISHED_WINGS_2      423
#define SPR_GRIND_ROCK              424
#define SPR_JUPITER_PLUG            425
#define SPR_JUPITER_PLUG_MASK       426
//      ?                           427
#define SPR_CIRCUIT_BLOCK           428
#define SPR_ANEMOS_STATUE           429
#define SPR_ANEMOS_HOVER_BLOCK      430
#define SPR_ANEMOS_MIRROR_TABLET    431
#define SPR_ANEMOS_ELEVATOR         432
#define SPR_IDEJIMA                 433
//      ?                           434
#define SPR_ANKOHL_STATUE_GLOW_R    435
#define SPR_ANHOHL_STATUE_GLOW_L    436
#define SPR_ANKOHL_STATUE_GLOW      437
#define SPR_VILLAGE                 438
#define SPR_CITY                    439
#define SPR_KOLIMA                  440
#define SPR_IMIL                    441
#define SPR_XIAN                    442
#define SPR_FUCHIN_TEMPLE           443
#define SPR_CAVE                    444
#define SPR_MERCURY_LIGHTHOUSE      445
#define SPR_BILIBIN_BARRICADE       446
#define SPR_MT_ALEPH                447
#define SPR_BABI_LIGHTHOUSE         448
#define SPR_CARRIAGE                449
#define SPR_SIGNPOST                450
#define SPR_FOREST                  451
#define SPR_VENUS_LIGHTHOUSE        452
#define SPR_DOCKS                   453
#define SPR_KOLIMA_BRIDGE           454
#define SPR_GONDOWAN_PASSAGE        455
#define SPR_KANDOREAN_TEMPLE        456
#define SPR_MOUNTAIN_PASS           457
#define SPR_SETTLEMENT              458
#define SPR_KALT                    459
#define SPR_ALHAFRA_SHIP            460
//      ?                           461
#define SPR_AIRS_ROCK               462
#define SPR_AQUA_ROCK               463
#define SPR_GAIA_ROCK               464
#define SPR_MAGMA_ROCK              465
#define SPR_VASE_2                  466
//      ?                           467
#define SPR_TAOPO_SWAMP             468
#define SPR_ANKOHL_RUINS            469
#define SPR_SEA_GOD_SHRINE          470
#define SPR_TUNDARIA_TOWER          471
#define SPR_LEMURIA                 472
#define SPR_APOJII_1                473
#define SPR_APOJII_2                474
#define SPR_GONDOWAN_CLIFFS         475
#define SPR_DEHKAN_PLATEAU          476
#define SPR_JUPITER_LIGHTHOUSE      477
#define SPR_MARS_LIGHTHOUSE         478
#define SPR_MARS_LIGHTHOUSE_FROZEN  479
#define SPR_MIKASALLA               480
#define SPR_KIBOMBO                 481
#define SPR_SHAMAN_VILLAGE          482
#define SPR_DAILA                   483
#define SPR_CONTIGO                 484
#define SPR_IZUMO                   485
#define SPR_ATTEKA_INLET            486
#define SPR_CHEST                   487
#define SPR_EMOTE                   488
//      ?                           489

#define SPR_B_ISAAC                 490
#define SPR_B_ISAAC_LONG_SWORD      491
#define SPR_B_ISAAC_LIGHT_BLADE     492
#define SPR_B_ISAAC_AXE             493
#define SPR_B_ISAAC_MACE            494
#define SPR_B_GARET                 495
#define SPR_B_GARET_MACE            496
#define SPR_B_GARET_AXE             497
#define SPR_B_GARET_LONG_SWORD      498
#define SPR_B_GARET_LIGHT_BLADE     499
#define SPR_B_IVAN                  500
#define SPR_B_IVAN_STAFF            501
#define SPR_B_IVAN_ANKH             502
#define SPR_B_IVAN_LIGHT_BLADE      503
#define SPR_B_MIA                   504
#define SPR_B_MIA_ANKH              505
#define SPR_B_MIA_STAFF             506
#define SPR_B_MIA_MACE              507
#define SPR_B_FELIX                 508
#define SPR_B_FELIX_LONG_SWORD      509
#define SPR_B_FELIX_LIGHT_BLADE     510
#define SPR_B_FELIX_AXE             511
#define SPR_B_FELIX_MACE            512
#define SPR_B_JENNA                 513
#define SPR_B_JENNA_STAFF           514
#define SPR_B_JENNA_ANKH            515
#define SPR_B_JENNA_LIGHT_BLADE     516
#define SPR_B_SHEBA                 517
#define SPR_B_SHEBA_STAFF           518
#define SPR_B_SHEBA_ANKH            519
#define SPR_B_SHEBA_MACE            520
#define SPR_B_PIERS                 521
#define SPR_B_PIERS_MACE            522
#define SPR_B_PIERS_AXE             523
#define SPR_B_PIERS_LONG_SWORD      524
#define SPR_B_PIERS_LIGHT_BLADE     525

#define SPR_B_BLUE_DRAGON           526
#define SPR_B_RED_DEMON             527
#define SPR_B_AKA_MANAH             528
#define SPR_B_KOBOLD                529
#define SPR_B_FLAME_DRAGON          530
#define SPR_B_CHESTBEATER           531
#define SPR_B_FAERY                 532
#define SPR_B_NUE                   533 // unused
#define SPR_B_PUNCH_ANT             534
#define SPR_B_SCORPION              535 // unused
#define SPR_B_ASSASSIN              536
#define SPR_B_WYVERN                537
#define SPR_B_DULLAHAN              538
#define SPR_B_DOOMSAYER             539
#define SPR_B_MAD_PLANT             540
#define SPR_B_CRAB                  541 // unused
#define SPR_B_EMU                   542
#define SPR_B_GRESSIL               543
#define SPR_B_STAR_MAGICIAN         544
#define SPR_B_GHOST_SOLDIER         545
#define SPR_B_PHOENIX               546
#define SPR_B_LIVING_ARMOR          547
#define SPR_B_WOOD_WALKER           548
#define SPR_B_GOBLIN                549
#define SPR_B_MINOTAUR              550
#define SPR_B_WOLFKIN               551
#define SPR_B_MUMMY                 552
#define SPR_B_DINO                  553
#define SPR_B_SENTINEL              554
#define SPR_B_SKY_DRAGON            555
#define SPR_B_HYDRA                 556
#define SPR_B_CONCH_SHELL           557
#define SPR_B_WILD_WOLF             558
#define SPR_B_NEEDLE_EGG            559
#define SPR_B_VALUKAR               560
#define SPR_B_SERPENT_1             561
#define SPR_B_SERPENT_2             562
#define SPR_B_SEA_DRAGON            563
#define SPR_B_BRIGGS                564
#define SPR_B_SEABIRD               565
#define SPR_B_ROC                   566
#define SPR_B_MOMONGA               567
#define SPR_B_KARST                 568
#define SPR_B_AVIMANDER             569
#define SPR_B_RUFFIAN               570
#define SPR_B_ANGLE_WORM            571
#define SPR_B_KING_SCORPION         572
#define SPR_B_MERMAN                573
#define SPR_B_SEA_FIGHTER           574
#define SPR_B_AGATIO                575
#define SPR_B_BALL                  576
#define SPR_B_KNIGHT                577
#define SPR_B_MOAPA                 578
#define SPR_B_DOOM_DRAGON_3_1       579
#define SPR_B_DOOM_DRAGON_3_2       580
#define SPR_B_DOOM_DRAGON_2_1       581
#define SPR_B_DOOM_DRAGON_2_2       582
#define SPR_B_DOOM_DRAGON_1_1       583
#define SPR_B_DOOM_DRAGON_1_2       584
#define SPR_B_POSEIDON_1            585
#define SPR_B_POSEIDON_2            586
#define SPR_B_TROLL                 587
#define SPR_B_ZOMBIE                588
#define SPR_B_HARPY                 589
#define SPR_B_GOLEM                 590
#define SPR_B_GHOST                 591
#define SPR_B_GRYPHON               592
#define SPR_B_RAT_SOLDIER           593
#define SPR_B_GHOUL                 594
#define SPR_B_CHIMERA               595
#define SPR_B_MANTICORE             596
#define SPR_B_HOBGOBLIN             597
#define SPR_B_GARGOYLE              598
#define SPR_B_ORC                   599
#define SPR_B_DJINNI_VENUS          600
#define SPR_B_DJINNI_JUPITER        601
#define SPR_B_DJINNI_MARS           602
#define SPR_B_DJINNI_MERCURY        603
#define SPR_B_DREAD_HOUND           604
#define SPR_B_MAULER                605
#define SPR_B_SIREN                 606
#define SPR_B_VERMIN                607
#define SPR_B_WILD_MUSHROOM         608
#define SPR_B_SLIME                 609
#define SPR_B_BAT                   610
#define SPR_B_JELLY                 611
#define SPR_B_RAT                   612
#define SPR_B_STONE_SOLDIER         613
#define SPR_B_BEE                   614
#define SPR_B_SPIDER                615
#define SPR_B_MOLE                  616
#define SPR_B_DIRGE                 617
#define SPR_B_GRUB                  618
#define SPR_B_APE                   619
#define SPR_B_SALAMANDER            620
#define SPR_B_LIVING_STATUE         621
#define SPR_B_GNOME                 622
#define SPR_B_SKELETON              623
#define SPR_B_WILL_HEAD             624
#define SPR_B_TORNADO_LIZARD        625
#define SPR_B_ANT_LION              626
#define SPR_B_MIMIC                 627
#define SPR_B_TOAD                  628
#define SPR_B_AMAZE                 629
#define SPR_B_LIZARD_MAN            630
#define SPR_B_KRAKEN_1              631
#define SPR_B_KRAKEN_2              632
#define SPR_B_SATUROS               633
#define SPR_B_MENARDI               634
#define SPR_B_ISAAC_YOUNG           635
#define SPR_B_TRET                  636
#define SPR_B_GARET_YOUNG           637
#define SPR_B_FUSION_DRAGON_1       638
#define SPR_B_FUSION_DRAGON_2       639
#define SPR_B_GLADIATOR             640
#define SPR_B_BANDIT                641
#define SPR_THOR                    642
#define SPR_BOREAS                  643
#define SPR_KIRIN                   644
#define SPR_CYBELE                  645
#define SPR_PROCNE                  646
#define SPR_TIAMAT                  647
#define SPR_RAMSES                  648
#define SPR_NEREID                  649
#define SPR_METEOR                  650
#define SPR_JUDGMENT                651
#define SPR_AZUL                    652
#define SPR_JUDGMENT_DEBRIS         653
#define SPR_MOLOCH                  654
#define SPR_ULYSSES                 655
#define SPR_MEGAERA                 656
#define SPR_MEGAERA_SWORD           657
#define SPR_ZAGAN                   658
#define SPR_HAURES                  659
#define SPR_HAURES_FLAME            660
//      ?                           661
#define SPR_DAEDALUS_MISSILE        662
#define SPR_DAEDALUS_MISSILE_SMALL  663
#define SPR_TRIDENT                 664
#define SPR_MEGIDDO                 665
#define SPR_GOLDEN_SUN              666
#define SPR_FOUNTAIN_CRAB           667
#define SPR_FOUNTAIN_TURTLE         668
#define SPR_FOUNTAIN_COIN           669
#define SPR_FOUNTAIN_LUCKY_MEDAL    670
#define SPR_FORCE_HIT               671
#define SPR_PARTICLE                672
#define SPR_SPARKLE_1               673
#define SPR_SPARKLE_2               674
#define SPR_PARTICLE_GLOW           675
//      ?                           676
#define SPR_MIND_READ               677
#define SPR_Z                       678 // unused
#define SPR_BOOKSHELF               679
//      ?                           680
#define SPR_FROST                   681
#define SPR_KEY                     682
#define SPR_KEYS                    683 // unused
#define SPR_TORNADO                 684
//      ?                           685
#define SPR_B_SHADOW                686
#define SPR_B_SHADOW_SMALL          687
#define SPR_B_POISON                688
#define SPR_B_VENOM                 689
#define SPR_B_STUN                  690
#define SPR_B_PSY_SEAL              691
#define SPR_B_SLEEP                 692
#define SPR_B_DELUSION              693
#define SPR_B_HAUNT                 694
#define SPR_B_CURSE_1               695
#define SPR_B_CURSE_2               696
#define SPR_B_CURSE_3               697
#define SPR_B_CURSE_4               698
#define SPR_B_CURSE_5               699
#define SPR_B_CURSE_6               700
#define SPR_B_CURSE_7               701
#define SPR_B_POISON_SMALL          702
#define SPR_B_VENOM_SMALL           703
#define SPR_B_STUN_SMALL            704
#define SPR_B_PSY_SEAL_SMALL        705
#define SPR_B_SLEEP_SMALL           706
#define SPR_B_DELUSION_SMALL        707
#define SPR_B_HAUNT_SMALL           708
#define SPR_B_CURSE_1_SMALL         709
#define SPR_B_CURSE_2_SMALL         710
#define SPR_B_CURSE_3_SMALL         711
#define SPR_B_CURSE_4_SMALL         712
#define SPR_B_CURSE_5_SMALL         713
#define SPR_B_CURSE_6_SMALL         714
#define SPR_B_CURSE_7_SMALL         715

#endif // GS2_SPRITES_H