@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_801edec
	.thumb_func
	.type	 Func_801edec,function
Func_801edec:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	ldr r3, =iwram_3001e8c
	ldr r7, [r3]
	sub sp, #4
	mov r8, r0
	cmp r7, #0
	bne .L801edec_nonzero
	mov r0, sp
	ldr r3, 1f
	add r0, #2
	strh r3, [r0]
	mov r1, r8
	ldr r3, =0x040000d4
	ldr r2, =0x810000a0
	stmia r3!, {r0, r1, r2}
	sub r3, #0xc
	b .L801edec_end
	.align 2, 0
1:	.word 0xe0e0
	.pool
.L801edec_nonzero:
	ldr r5, =0x214
	.code	16
	mov	r0, r5
	bl	Func_8004938
	mov r2, #0x84
	mov r6, r0
	lsr r5, #2
	lsl r2, #24
	ldr r3, =0x040000d4
	ldr r0, =Func_80158e8
	mov r1, r6
	orr r2, r5
	stmia r3!, {r0, r1, r2}
	sub r3, #0xc
	.code	16
	mov	r0, r8
	mov	r1, r7
	bl	_call_via_r6
	mov	r0, r6
	bl	free
	.L801edec_end:
	add sp, #4
	.code	16
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Func_801edec,.Lfe1-Func_801edec

	.text
	.align	2, 0
