@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_801671c
	.thumb_func
	.type	 Func_801671c,function
Func_801671c:
	push	{lr}
	mov	r1, #240
	ldr	r3, .L3
	lsl	r1, r1, #4
	mov	r2, #0
	ldr	r0, .L3+4
	.code	16
	bl	_call_via_r3
	pop	{r1}
	bx	r1
.L4:
	.align	2, 0
.L3:
	.word	Func_80008d8
	.word	100672768
.Lfe1:
	.size	 Func_801671c,.Lfe1-Func_801671c
	.align	2, 0
	.global	Func_8016738
	.thumb_func
	.type	 Func_8016738,function
Func_8016738:
	push	{lr}
	mov	r1, #240
	ldr	r3, .L6
	lsl	r1, r1, #4
	ldr	r2, .L6+4
	ldr	r0, .L6+8
	.code	16
	bl	_call_via_r3
	pop	{r1}
	bx	r1
.L7:
	.align	2, 0
.L6:
	.word	Func_80008d8
	.word	1145324612
	.word	100672768
.Lfe2:
	.size	 Func_8016738,.Lfe2-Func_8016738

	.text
	.align	2, 0
