@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_801cbd4
	.thumb_func
	.type	 Func_801cbd4,function
Func_801cbd4:
	push	{r5, r6, r7, lr}
	mov r5, r0
	ldr r0, =0x576
	mov r6, r2
	add r2, r5, r0
	ldrh r0, [r2]
	ldr r4, =Func_8000888
	lsl r0, #16
	.align 2, 0
	mov r12, pc
	bx r4
	mov r1, #0xaf
	lsl r1, #3
	add r2, r5, r1
	asr r7, r0, #16
	ldrh r0, [r2]
	mov r1, r6
	lsl r0, #16
	.align 2, 0
	mov r12, pc
	bx r4
	ldr r2, =0x57a
	add r5, r2
	asr r6, r0, #16
	ldrh r0, [r5]
	mov r1, r3
	lsl r0, #16
	.align 2, 0
	mov r12, pc
	bx r4
	asr r0, #16
	.code	16
	cmp	r7, #0
	bge	.L3
	mov	r7, #0
.L3:
	cmp	r6, #0
	bge	.L4
	mov	r6, #0
.L4:
	cmp	r0, #0
	bge	.L5
	mov	r0, #0
.L5:
	cmp	r7, #31
	ble	.L6
	mov	r7, #31
.L6:
	cmp	r6, #31
	ble	.L7
	mov	r6, #31
.L7:
	cmp	r0, #31
	ble	.L8
	mov	r0, #31
.L8:
	lsl	r3, r6, #5
	lsl	r0, r0, #10
	add	r0, r0, r3
	add r0, r7, r0
	.code	16
	lsl	r0, r0, #16
	lsr	r0, r0, #16
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 Func_801cbd4,.Lfe1-Func_801cbd4

	.text
	.align	2, 0
