@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	YesNoMenu
	.thumb_func
	.type	 YesNoMenu,function
YesNoMenu:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r8
	push	{r6, r7}
	mov	r5, r2
	mov	r6, r3
	mov	r3, #0
	mov	r7, r0
	mov	sl, r1
	mov	r8, r3
	bl	Func_80284dc
	cmp	r5, #0
	bne	.L3
	mov	r5, #3
.L3:
	cmp	r7, #0
	beq	.L4
	mov	r3, #17
	mov	r8, r3
.L4:
	mov	r0, #5
	bl	AddMenuBarOption
	mov	r0, #6
	bl	AddMenuBarOption
	mov	r1, r5
	mov	r2, sl
	mov	r0, r8
	bl	Func_8028808
	mov	r0, r6
	bl	Func_8028574
	mov	r6, r0
	bl	Func_802851c
	mov	r3, #1
	neg	r3, r3
	cmp	r6, r3
	bne	.L5
	mov	r6, #1
.L5:
	mov	r0, r6
	pop	{r3, r5}
	mov	r8, r3
	mov	sl, r5
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 YesNoMenu,.Lfe1-YesNoMenu
	.align	2, 0
	.global	YesNoMenu2
	.thumb_func
	.type	 YesNoMenu2,function
YesNoMenu2:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	ldr	r3, .L8
	mov	r7, r2
	mov	r6, r1
	mov	r8, r3
	mov	r5, r0
	bl	Func_80284dc
	.code	16
	mov	r0, #5
	bl	AddMenuBarOption
	mov	r0, #6
	bl	AddMenuBarOption
	mov	r3, r8
	mov	r1, r6
	mov	r2, #3
	mov	r0, r5
	bl	Func_80288a8
	mov	r0, r7
	bl	Func_8028574
	mov	r7, r0
	bl	Func_802851c
	.code	16
	mov	r3, #1
	neg	r3, r3
	cmp	r7, r3
	bne	.L7
	mov	r7, #1
.L7:
	mov	r0, r7
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L9:
	.align	2, 0
.L8:
	.word	0x24
.Lfe2:
	.size	 YesNoMenu2,.Lfe2-YesNoMenu2

	.text
	.align	2, 0
