@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_801ce90
	.thumb_func
	.type	 Func_801ce90,function
Func_801ce90:
	push	{lr}
	ldr r2, Func_801ce90_FieldOffset
	.code	16
	add	r0, r0, r2
	.code	16
	ldrh	r3, [r0]
	cmp	r3, #1
	beq	.L5
	cmp	r3, #1
	bgt	.L9
	cmp	r3, #0
	beq	.L4
	b	.L2
.L9:
	cmp	r3, #2
	beq	.L6
	b	.L2
.L4:
	ldr r3, Func_801ce90_State
	mov r2, #0x83
	.code	16
	lsl	r2, r2, #2
	b	.L3
.L5:
	ldr r3, Func_801ce90_State
	ldr r2, Func_801ce90_Offset1
	.code	16
	b	.L3
.L6:
	ldr r3, Func_801ce90_State
	ldr r2, Func_801ce90_Offset2
	.code	16
.L3:
	add	r1, r3, r2
	ldrb r2, [r1]
	mov r3, r2
	.code	16
	cmp	r3, #0
	beq	.L2
	add	r3, r3, #255
	strb	r3, [r1]
.L2:
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Func_801ce90,.Lfe1-Func_801ce90
	.align 2, 0
Func_801ce90_FieldOffset:
.word 0x574
Func_801ce90_State:
.word gState
Func_801ce90_Offset1:
.word 0x205
Func_801ce90_Offset2:
.word 0x206

	.text
	.align	2, 0
