@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	GetPortrait
	.thumb_func
	.type	 GetPortrait,function
GetPortrait:
	push	{r5, lr}
	mov	r1, #1
	neg	r1, r1
	mov	r2, #0
	cmp	r0, #19
	bhi	.L3
	ldr	r4, .L21
	mov	r5, #0
	ldrsh	r3, [r4, r5]
	cmp	r3, r1
	beq	.L5
	cmp	r3, r0
	bne	.L11
	mov r2, #2
	ldrsh r1, [r4, r2]
	.code	16
	b	.L5
.L11:
	add r2, #2
	lsl r3, r2, #1
	ldrsh r3, [r4, r3]
	mov r5, #1
	neg r5, r5
	.code	16
	cmp	r3, r5
	beq	.L5
	cmp	r3, r0
	bne	.L11
	add r2, #1
	lsl r3, r2, #1
	ldrsh r1, [r4, r3]
	.code	16
	b	.L5
.L3:
	ldr	r4, .L21+4
	mov	r5, #0
	ldrsh	r3, [r4, r5]
	mov	r5, #1
	neg	r5, r5
	cmp	r3, r5
	beq	.L5
	cmp	r3, r0
	bne	.L20
	mov r2, #2
	ldrsh r1, [r4, r2]
	.code	16
	b	.L15
.L20:
	add r2, #2
	lsl r3, r2, #1
	ldrsh r3, [r4, r3]
	mov r5, #1
	neg r5, r5
	.code	16
	cmp	r3, r5
	beq	.L5
	cmp	r3, r0
	bne	.L20
	add r2, #1
	lsl r3, r2, #1
	ldrsh r1, [r4, r3]
	.code	16
.L15:
	add	r1, r1, #128
.L5:
	mov	r0, r1
	pop	{r5}
	pop	{r1}
	bx	r1
.L22:
	.align	2, 0
.L21:
	.word	Data_367e4
	.word	Data_3680c
.Lfe1:
	.size	 GetPortrait,.Lfe1-GetPortrait

	.text
	.align	2, 0
