@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80160fc
	.thumb_func
	.type	 Func_80160fc,function
Func_80160fc:
	push	{r5, r6, r7, lr}
	ldr	r3, .L11
	ldr	r2, .L11+4
	ldr	r7, [r3]
	add	r3, r7, r2
	.code	16
	ldrb	r3, [r3]
	cmp	r3, #0
	bne	.L3
	sub	r2, r2, #3
	add	r3, r7, r2
	.code	16
	ldrb	r4, [r3]
	cmp	r4, #0
	beq	.L3
	ldr	r3, .L11+8
	.code	16
	mov	ip, r3
	.code	16
	mov	r3, #1
	.code	16
	and	r3, r3, r4
	mov	r5, r7
	.code	16
	cmp	r3, #0
	beq	.L5
	mov	r4, #63
.L5:
	mov	r3, #63
	and	r4, r4, r3
	mov	r2, #1
	mov	r6, #128
	lsr	r4, r4, #1
	mov	lr, r2
	lsl	r6, r6, #1
.L10:
	mov	r3, r4
	mov	r2, lr
	.code	16
	and	r3, r3, r2
	cmp	r3, #0
	beq	.L9
	ldr	r3, .L11+12
	mov	r0, r5
	mov	r1, ip
	ldr	r2, .L11+16
	stmia	r3!, {r0, r1, r2}
	sub	r3, #0xc
	.code	16
.L9:
	lsr	r4, r4, #1
	add	r5, r5, r6
	add	ip, ip, r6
	cmp	r4, #0
	bne	.L10
	.code	16
	ldr	r2, .L11+20
	add	r3, r7, r2
	strb	r4, [r3]
.L3:
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L12:
	.align	2, 0
.L11:
	.word	iwram_3001e8c
	.word	3750
	.word	100671488
	.word	67109076
	.word	-2080374720
	.word	3747
.Lfe1:
	.size	 Func_80160fc,.Lfe1-Func_80160fc

	.text
	.align	2, 0
