@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8017c1c
	.thumb_func
	.type	 Func_8017c1c,function
Func_8017c1c:
	push	{r5, r6, r7, lr}
	mov r6, r3
	ldr r3, =iwram_3001e8c
	mov r5, r1
	mov r7, r2
	ldr r4, [r3]
	.code	16
	cmp	r0, #0
	bne	.L3
	ldr r3, =0x12b2
	add r1, r4, r3
	ldrh r3, [r1]
	mov r2, #0xeb
	lsl r2, #4
	lsl r3, #1
	add r3, r2
	add r0, r4, r2
	ldr r2, 1f
	strh r2, [r4, r3]
	ldrh r3, [r1]
	ldr r2, 2f
	add r3, #1
	and r3, r2
	strh r3, [r1]
	.code	16
.L3:
	ldrh r3, [r5, #0xe]
	ldrh r2, [r5, #0xc]
	add r3, r6
	add r3, #1
	lsl r3, #5
	add r2, r7
	add r3, r2
	add r1, r3, #1
	.code	16
	mov	r3, #160
	lsl	r3, r3, #2
	cmp	r1, r3
	bcs	.L4
	ldr r3, =0x06002000
	lsl r1, #1
	add r2, r1, r3
	add r1, r4, r1
	b .L17c1c_call
	.align 2, 0
1:	.word 0
2:	.word 0x1ff
	.pool
.L17c1c_call:
	.code	16
	bl	Func_801de5c
.L4:
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Func_8017c1c,.Lfe1-Func_8017c1c
	.short 0

	.text
	.align	2, 0
