@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8020b64
	.thumb_func
	.type	 Func_8020b64,function
Func_8020b64:
	push	{r5, r6, lr}
	ldrb r2, [r1]
	mov r3, r2
	sub sp, #0x14
	mov r6, r0
	mov r4, #0
	.code	16
	cmp	r3, #0
	beq	.L3
	mov r0, sp
	mov r5, r0
	.code	16
.L7:
	strb	r2, [r5]
	add	r1, r1, #1
	ldrb r3, [r1]
	mov r2, r3
	mov r3, r2
	.code	16
	add	r5, r5, #1
	add	r4, r4, #1
	cmp	r3, #0
	bne	.L7
	b	.L8
.L3:
	mov r0, sp
	.code	16
.L8:
	mov	r3, #8
	strb	r3, [r0, r4]
	add	r4, r4, #1
	mov	r3, #2
	strb	r3, [r0, r4]
	add	r4, r4, #1
	cmp	r4, #6
	bgt	.L9
	mov r3, #7
	add r2, r4, r0
	mov r1, #0x5f
	sub r4, r3, r4
	.code	16
.L13:
	sub	r4, r4, #1
	strb	r1, [r2]
	add	r2, r2, #1
	cmp	r4, #0
	bne	.L13
	mov	r4, #7
.L9:
	mov	r3, #8
	strb	r3, [r0, r4]
	add	r4, r4, #1
	mov	r3, #15
	strb	r3, [r0, r4]
	add	r4, r4, #1
	mov	r3, #0
	strb	r3, [r0, r4]
	mov	r3, #2
	neg	r3, r3
	mov	r1, r6
	mov	r2, #0
	bl	Func_801e858
	add sp, #0x14
	.code	16
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Func_8020b64,.Lfe1-Func_8020b64
	.short 0

	.text
	.align	2, 0
