@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
.text
	.code	16
.text
	.align	2, 0
	.global	Func_801ffd8
	.thumb_func
	.type	 Func_801ffd8,function
Func_801ffd8:
	push	{r5, r6, r7, lr}
	mov	r7, fp
	mov	r6, sl
	mov	r5, r9
	push	{r5, r6, r7}
	mov	r7, r8
	push	{r7}
	ldr	r3, .L9
	sub	sp, sp, #4
	mov	r8, r0
	mov	fp, r1
	mov	r9, r2
	ldr	r3, [r3]
	cmp	r0, #0
	beq	.L3
	mov r1, #0x8d
	lsl r1, r1, #2
	add r6, r3, r1
	sub r1, r1, #0x10
	add r1, r3, r1
	mov r2, #0
	str r1, [sp]
	mov r7, #0
	mov sl, r2
	
	.code	16
.L8:
	ldr	r3, .L9+4
	lsl	r2, r7, #2
	ldr	r0, [r3, r2]
	bl	_CreateSprite
	mov	r5, r0
	cmp	r5, #0
	beq	.L7
	mov	r1, #2
	bl	_Sprite_SetAnim
	mov	r2, r5
	add	r2, r2, #38
	mov	r3, #0
	strb	r3, [r2]
	mov r1, #13
	ldrb r3, [r5, #9]
	neg r1, r1
	mov r2, r1
	and r3, r2
	strb r3, [r5, #9]
	
	.code	16
.L7:
	ldr r3, [sp]
	stmia r3!, {r5}
	mov r2, r3
	str r2, [sp]
	
	.code	16
	mov	r1, r8
	ldrh	r3, [r1, #12]
	add	r3, r3, fp
	add	r3, r3, sl
	lsl	r3, r3, #3
	add	r3, r3, #16
	strh	r3, [r6]
	ldrh	r3, [r1, #14]
	add	r3, r3, r9
	lsl	r3, r3, #3
	add	r3, r3, #16
	mov	r2, #3
	add	r7, r7, #1
	strh	r3, [r6, #8]
	add	sl, sl, r2
	add	r6, r6, #2
	cmp	r7, #3
	ble	.L8
	mov	r1, #200
	ldr	r0, .L9+8
	lsl	r1, r1, #4
	bl	StartTask
.L3:
	add	sp, sp, #4
	pop	{r3, r5, r6, r7}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	mov	fp, r7
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L10:
	.align	2, 0
.L9:
	.word	iwram_3001f2c
	.word	.rodata
	.word	Func_80200cc
.Lfe1:
	.size	 Func_801ffd8,.Lfe1-Func_801ffd8

	.text
	.align	2, 0
