@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8022a7c
	.thumb_func
	.type	 Func_8022a7c,function
Func_8022a7c:
	push	{r5, r6, r7, lr}
	mov	r7, fp
	mov	r6, sl
	mov	r5, r9
	push	{r5, r6, r7}
	mov	r7, r8
	push	{r7}
	sub	sp, sp, #4
	mov r3, sp
	mov r4, r9
	str r4, [r3]
	mov r8, r0
	mov sl, r1
	mov fp, r2
	.code	16
	bl	Func_8015e8c
	mov	r6, r0
	cmp	r6, #0
	beq	.L3
	mov	r3, #1
	strb	r3, [r6, #5]
	strb	r3, [r6, #4]
	mov	r0, #128
	bl	AllocUploadSpriteGFX
	movs r3, #0xf0
	strb r3, [r6, #0xf]
	movs r3, #0x78
	mov r7, r6
	strh r3, [r6, #6]
	strh r3, [r6, #8]
	.code	16
	ldr	r3, .L6+4
	add r7, #0x10
	movs r5, #0
	strb r0, [r6, #0xe]
	str r3, [r7, #4]
	str r5, [r7, #8]
	.code	16
	mov	r5, r9
	sub	r5, r5, #4
	ldr	r0, [r5]
	ldrh	r2, [r0, #12]
	ldrh	r3, .L6
	lsl	r2, r2, #3
	add	r2, r2, r8
	and	r2, r2, r3
	ldrh	r1, [r7, #6]
	ldr	r3, .L6+8
	and	r3, r3, r1
	orr	r3, r3, r2
	strh	r3, [r7, #6]
	ldrh	r3, [r0, #14]
	lsl	r3, r3, #3
	add	r3, r3, sl
	strb	r3, [r7, #4]
	mov	r3, fp
	ldrb	r0, [r6, #14]
	cmp	r3, #0
	beq	.L4
	ldr	r1, .L6+12
	b	.L5
.L7:
	.align	2, 0
.L6:
	.word	511
	.word	1073742848
	.word	-512
	.word	.L313a4
.L4:
	ldr	r1, .L8+4
.L5:
	bl	UploadSprite2
	ldrh	r3, .L8
	ldrh	r2, [r7, #8]
	and	r0, r0, r3
	ldr	r3, .L8+8
	and	r3, r3, r2
	orr	r3, r3, r0
	strh	r3, [r7, #8]
	ldr	r0, [r5]
	mov	r1, r6
	bl	Func_8016584
	b	.L9
.L10:
	.align	2, 0
.L8:
	.word	1023
	.word	.L31424
	.word	-1024
.L9:
.L3:
	add	sp, sp, #4
	pop	{r3, r5, r6, r7}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	mov	fp, r7
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Func_8022a7c,.Lfe1-Func_8022a7c

	.text
	.align	2, 0
