@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_801f730
	.thumb_func
	.type	 Func_801f730,function
Func_801f730:
	push	{r5, r6, lr}
	mov	r6, r0
	bl	Func_80056cc
	mov	r5, #9
	neg	r5, r5
	cmp	r0, #0
	bne	.L4
	bl	Func_8005c68
	mov	r5, r0
	cmp	r6, #0
	beq	.L4
	ldr	r3, .L11
	ldr	r1, .L11+4
	ldr	r3, [r3]
	add	r2, r3, r1
	mov	r1, #2
.L10:
	ldrb	r3, [r2]
	lsl	r3, r3, #24
	.code	16
	add	r2, r2, #64
	cmp	r3, #0
	beq	.L9
	sub	r5, r5, #1
.L9:
	sub	r1, r1, #1
	cmp	r1, #0
	bge	.L10
.L4:
	bl	Func_8005cf8
	mov	r0, r5
	pop	{r5, r6}
	pop	{r1}
	bx	r1
.L12:
	.align	2, 0
.L11:
	.word	iwram_3001f1c
	.word	4209
.Lfe1:
	.size	 Func_801f730,.Lfe1-Func_801f730

	.text
	.align	2, 0
