@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8028920
	.thumb_func
	.type	 Func_8028920,function
Func_8028920:
	push	{r5, r6, r7, lr}
	mov	r5, r0
	mov	r0, #1
	neg	r0, r0
	mov	r6, #0
	bl	_GetNumDjinn
	cmp	r0, #0
	bne	.L3
	mov	r6, #1
.L3:
	lsl	r3, r6, #1
	add	r3, r3, r6
	ldr	r2, .L7
	lsl	r7, r3, #1
	add	r3, r5, r7
	ldrsb	r3, [r2, r3]
	.code	16
	sub	r5, r3, #1
	cmp	r5, #0
	bge	.L4
	mov	r5, #0
.L4:
	bl	Func_80284dc
	mov	r0, #1
	bl	AddMenuBarOption
	cmp	r6, #0
	bne	.L5
	mov	r0, #15
	bl	AddMenuBarOption
.L5:
	mov	r0, #2
	bl	AddMenuBarOption
	mov	r0, #7
	bl	AddMenuBarOption
	mov	r0, #17
	mov	r1, #7
	mov	r2, #0
	bl	Func_8028808
	mov	r0, r5
	bl	Func_8028574
	mov	r5, r0
	bl	Func_802851c
	cmp	r5, #0
	blt	.L6
	add	r3, r5, r7
	ldr	r2, .L7+4
	add	r3, r3, #1
	ldrsb	r5, [r2, r3]
.L6:
	mov	r0, r5
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L8:
	.align	2, 0
.L7:
	.word	.L37403
	.word	.L373f7
.Lfe1:
	.size	 Func_8028920,.Lfe1-Func_8028920

	.text
	.align	2, 0
