@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8019854
	.thumb_func
	.type	 Func_8019854,function
Func_8019854:
	push	{r5, r6, r7, lr}
	mov	r7, fp
	mov	r6, sl
	mov	r5, r9
	push	{r5, r6, r7}
	mov	r7, r8
	push	{r7}
	mov r5, r0
	ldr r3, [r5]
	ldrh r1, [r3, #0xc]
	mov r9, r1
	ldrh r1, [r3, #0xe]
	mov r11, r1
	ldrh r1, [r3, #8]
	sub sp, #8
	ldrh r2, [r3, #0x12]
	str r1, [sp, #4]
	ldrh r3, [r3, #0xa]
	str r3, [sp]
	.code	16
	cmp	r2, #4
	bne	.L3
	add r1, #2
	mov r6, r9
	mov r7, r11
	mov r8, r1
	sub r6, #1
	sub r7, #1
	add r3, #2
	mov r2, r8
	mov r0, r6
	mov r1, r7
	mov r10, r3
	.code	16
	bl	Func_80170f8
	ldrh r3, [r5, #0x14]
	ldr r2, =0xffff
	add r3, r2
	strh r3, [r5, #0x14]
	lsl r3, #16
	lsr r2, r3, #16
	.code	16
	cmp	r2, #0
	bne	.L3
	ldr r3, [r5]
	mov r0, r6
	strh r2, [r3, #0x12]
	mov r1, r7
	mov r2, r8
	mov r3, r10
	.code	16
	bl	ClearUIRegion
	mov r0, r9
	mov r1, r11
	ldr r2, [sp, #4]
	ldr r3, [sp]
	.code	16
	bl	Func_80170f8
.L3:
	add sp, #8
	.code	16
	pop	{r3, r5, r6, r7}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	mov	fp, r7
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Func_8019854,.Lfe1-Func_8019854

	.text
	.align	2, 0
