@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80197c4
	.thumb_func
	.type	 Func_80197c4,function
Func_80197c4:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	ldr	r3, .L25
	ldr	r3, [r3]
	mov	r5, #196
	mov	r7, #160
	mov	r8, r3
	lsl	r5, r5, #3
	lsl	r7, r7, #3
	add	r5, r5, r8
	add	r7, r7, r8
	mov	r6, #0
.L7:
	ldr	r0, [r5]
	cmp	r0, #0
	beq	.L6
	ldrh	r3, [r0, #22]
	cmp	r3, #0
	beq	.L6
	mov	r1, #0
	bl	CloseUIBox
.L6:
	add	r6, r6, #1
	add	r5, r5, #40
	cmp	r6, #3
	bne	.L7
.L19:
	mov	r5, #196
	lsl	r5, r5, #3
	mov	r1, #1
	add	r5, r5, r8
	mov	r6, #0
.L17:
	ldr	r2, [r5]
	cmp	r2, #0
	beq	.L14
	ldr	r3, [r2, #24]
	cmp	r3, #0
	bne	.L15
	ldrh	r3, [r2, #22]
	cmp	r3, #0
	bne	.L15
	str	r3, [r5]
	b	.L14
.L15:
	mov	r1, #0
.L14:
	add	r6, r6, #1
	add	r5, r5, #40
	cmp	r6, #3
	bne	.L17
	mov	r6, #0
	cmp	r1, #0
	bne	.L20
	mov	r0, #1
	bl	WaitFrames
	b	.L19
.L21:
	ldrh	r3, [r7, #22]
	cmp	r3, #0
	beq	.L22
	mov	r0, r7
	mov	r1, #0
	bl	CloseUIBox
.L22:
	add	r7, r7, #36
	add	r6, r6, #1
.L20:
	cmp	r6, #8
	bne	.L21
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L26:
	.align	2, 0
.L25:
	.word	iwram_3001e8c
.Lfe1:
	.size	 Func_80197c4,.Lfe1-Func_80197c4

	.text
	.align	2, 0
