@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8021950
	.thumb_func
	.type	 Func_8021950,function
Func_8021950:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	mov	r6, r3
	sub	sp, sp, #8
	neg	r3, r6
	.code	16
	str	r0, [sp, #4]
	.code	16
	mov	r7, r2
	.code	16
	mov	r0, #0
	.code	16
	lsl	r3, r3, #2
	.code	16
	lsl	r2, r6, #2
	.code	16
	str	r1, [sp]
	.code	16
	mov	ip, r0
	.code	16
	mov	r8, r3
	mov	lr, r2
	.code	16
.L14:
	ldr	r0, [sp]
	.code	16
	ldmia	r0!, {r4}
	.code	16
	mov	r3, r0
	.code	16
	str	r3, [sp]
	.code	16
	ldr	r0, [sp, #4]
	.code	16
	ldmia	r0!, {r1}
	.code	16
	mov	r3, r0
	.code	16
	mov	r2, #0
	.code	16
	str	r3, [sp, #4]
	.code	16
	cmp	r6, #0
	bge	.L6
	mov	r3, r8
	.code	16
	lsr	r4, r4, r3
	b	.L7
.L6:
	mov	r0, lr
	.code	16
	lsl	r4, r4, r0
.L7:
	ldr	r5, .L16
	mov	r0, #7
	.code	16
.L13:
	lsl	r2, r2, #4
	cmp	r4, r5
	bls	.L11
	lsr	r3, r4, #28
	b	.L15
.L11:
	lsr	r3, r1, #28
.L15:
	add	r2, r2, r3
	sub	r0, r0, #1
	lsl	r4, r4, #4
	lsl	r1, r1, #4
	cmp	r0, #0
	bge	.L13
	stmia	r7!, {r2}
	.code	16
	mov	r2, #1
	.code	16
	add	ip, ip, r2
	mov	r3, ip
	cmp	r3, #7
	ble	.L14
	add	sp, sp, #8
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L17:
	.align	2, 0
.L16:
	.word	268435455
.Lfe1:
	.size	 Func_8021950,.Lfe1-Func_8021950

	.text
	.align	2, 0
