@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_801b36c
	.thumb_func
	.type	 Func_801b36c,function
Func_801b36c:
	push	{lr}
	mov	r2, #210
	lsl	r2, r2, #2
	.code	16
	ldr	r4, .L8
	.code	16
	add	r3, r0, r2
	.code	16
	ldr	r2, [r3]
	add	r3, r0, r4
	.code	16
	ldrh	r3, [r3]
	mov	r1, #0
	cmp	r3, #0
	beq	.L3
	add	r3, r0, r4
	.code	16
	ldrh	r0, [r3]
.L7:
	add	r1, r1, #1
	ldr	r2, [r2, #4]
	cmp	r1, r0
	bne	.L7
.L3:
	mov	r0, r2
	pop	{r1}
	bx	r1
.L9:
	.align	2, 0
.L8:
	.word	926
.Lfe1:
	.size	 Func_801b36c,.Lfe1-Func_801b36c

	.text
	.align	2, 0
