@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8020198
	.thumb_func
	.type	 Func_8020198,function
Func_8020198:
	push	{r5, r6, r7, lr}
	mov	r5, r0
	sub	sp, sp, #20
	mov	r7, r1
	cmp	r5, #0
	beq	.L3
	bl	Func_8016478
	mov	r3, #4
	str	r3, [sp]
	mov	r0, r5
	mov	r1, #0
	mov	r2, #4
	mov	r3, #13
	bl	Func_801e41c
	mov r0, r7
	add r0, #0x10
	mov r1, r5
	mov r2, #0
	mov r3, #0
	.code	16
	bl	Func_801e8b0
	ldr r0, =.L371e0
	mov r1, r5
	mov r2, #0x48
	mov r3, #0
	.code	16
	bl	UIDrawText
	mov r6, #0
	ldrb r0, [r7, #0x1c]
	mov r1, #2
	mov r2, r5
	mov r3, #0x50
	str r6, [sp]
	.code	16
	bl	Func_801e9d4
	ldr r3, =0x741
	ldrb r0, [r7, #0x1d]
	mov r1, r5
	add r0, r3
	mov r2, #0
	mov r3, #0x10
	.code	16
	bl	Func_801e7c0
	mov r2, #0
	mov r3, #0x20
	ldr r0, =9
	mov r1, r5
	.code	16
	bl	Func_801e7c0
	ldr	r0, [r7, #32]
	add	r1, sp, #4
	bl	Func_801f680
	mov	r1, r5
	mov	r2, #48
	mov	r3, #40
	bl	UIDrawText
	mov	r6, #48
	ldr	r0, [r7, #36]
	mov	r1, #6
	mov	r2, r5
	mov	r3, #0
	str	r6, [sp]
	bl	Func_801ea08
	ldr r0, =0xc88
	.code	16
	mov	r1, r5
	mov	r2, #48
	mov	r3, #48
	bl	Func_801e7c0
.L3:
	add	sp, sp, #20
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Func_8020198,.Lfe1-Func_8020198

	.text
	.align	2, 0
