@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_801c0dc
	.thumb_func
	.type	 Func_801c0dc,function
Func_801c0dc:
	push	{r5, r6, lr}
	mov	r6, r8
	push	{r6}
	ldr r3, =.L342f8
	.code	16
	mov	r5, r0
	mov	r8, r3
	mov	r6, r1
	.code	16
	bl	AllocSpriteSlot
	mov	r2, r8
	str	r0, [r6]
	mov	r1, #128
	bl	UploadSpriteGFX
	ldr r3, 9f
	.code	16
	ldrh	r2, [r5, #8]
	and	r0, r0, r3
	ldr r3, =0xfffffc00
	.code	16
	and	r3, r3, r2
	orr	r3, r3, r0
	mov	r0, #13
	strh	r3, [r5, #8]
	neg	r0, r0
	ldrb	r3, [r5, #5]
	mov	r2, r0
	and	r2, r2, r3
	mov	r3, #17
	neg	r3, r3
	and	r2, r2, r3
	mov	r3, #32
	orr	r2, r2, r3
	mov	r3, #4
	.code	16
	ldrb	r1, [r5, #7]
	.code	16
	neg	r3, r3
	and	r2, r2, r3
	sub	r3, r3, #59
	and	r3, r3, r1
	mov	r1, #63
	and	r3, r3, r1
	strb	r3, [r5, #7]
	and	r2, r2, r1
	mov	r3, #128
	orr	r2, r2, r3
	b 8f
	.align 2, 0
9:
	.word 0x3ff
	.pool
8:
	.code	16
	ldrb	r3, [r5, #9]
	and	r0, r0, r3
	strb	r2, [r5, #5]
	strb	r0, [r5, #9]
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Func_801c0dc,.Lfe1-Func_801c0dc

	.text
	.align	2, 0
