@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_801ce48
	.thumb_func
	.type	 Func_801ce48,function
Func_801ce48:
	push	{lr}
	ldr	r1, .L5
	add	r0, r0, r1
	ldrh	r2, [r0]
	mov	r3, r2
	.code	16
	cmp	r3, #0
	bne	.L3
	mov	r3, #2
	.code	16
	b	.L4
.L3:
	ldr	r1, .L5+4
	add	r3, r2, r1
.L4:
	strh	r3, [r0]
	pop	{r0}
	bx	r0
.L6:
	.align	2, 0
.L5:
	.word	1396
	.word	65535
.Lfe1:
	.size	 Func_801ce48,.Lfe1-Func_801ce48

	.text
	.align	2, 0
