@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8019944
	.thumb_func
	.type	 Func_8019944,function
Func_8019944:
	push	{r5, r6, r7, lr}
	ldr	r3, .L14
	ldr	r4, .L14+4
	.code	16
	ldr	r2, [r3]
	.code	16
	ldrh	r3, [r4, r2]
	.code	16
	mov	r5, r0
	.code	16
	mov	r7, r1
	.code	16
	mov	r1, #0
	.code	16
	mov	r6, #0
	.code	16
	mov	ip, r1
	.code	16
	ldr	r0, .L14+8
	.code	16
	cmp	r3, r5
	bne	.L6
	ldr	r6, [r0, r2]
	cmp	r7, #0
	beq	.L10
	str	r1, [r0, r2]
	strh	r1, [r4, r2]
	b	.L10
.L6:
	add	r1, r1, #1
	add	r0, r0, #4
	add	r4, r4, #2
	.code	16
	cmp	r1, #7
	bhi	.L10
	ldrh	r3, [r4, r2]
	.code	16
	cmp	r3, r5
	bne	.L6
	ldr	r6, [r0, r2]
	cmp	r7, #0
	beq	.L10
	mov	r3, ip
	.code	16
	str	r3, [r0, r2]
	mov	r3, ip
	.code	16
	strh	r3, [r4, r2]
.L10:
	mov	r0, r6
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L15:
	.align	2, 0
.L14:
	.word	iwram_3001e8c
	.word	4828
	.word	4796
.Lfe1:
	.size	 Func_8019944,.Lfe1-Func_8019944

	.text
	.align	2, 0
