@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_883_2008f5c
	.thumb_func
	.type	 OvlFunc_883_2008f5c,function
OvlFunc_883_2008f5c:
	push	{lr}
	mov	r0, #158
	bl	__PlaySound
	ldr	r0, .L3
	mov	r1, #49
	mov	r2, #69
	bl	__Func_8010560
	mov	r1, #163
	mov	r0, #0
	lsl	r1, r1, #1
	ldr	r2, .L3+4
	.code	16
	bl	__Func_809218c
	mov	r0, #8
	bl	__Func_8091e9c
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	.L7570
	.word	1126
.Lfe1:
	.size	 OvlFunc_883_2008f5c,.Lfe1-OvlFunc_883_2008f5c
	.align	2, 0
	.global	OvlFunc_883_2008f8c
	.thumb_func
	.type	 OvlFunc_883_2008f8c,function
OvlFunc_883_2008f8c:
	push	{lr}
	mov	r0, #158
	bl	__PlaySound
	ldr	r0, .L6
	mov	r1, #52
	mov	r2, #76
	bl	__Func_8010560
	mov	r1, #187
	mov	r0, #0
	lsl	r1, r1, #1
	ldr	r2, .L6+4
	.code	16
	bl	__Func_809218c
	mov	r0, #9
	bl	__Func_8091e9c
	pop	{r0}
	bx	r0
.L7:
	.align	2, 0
.L6:
	.word	.L7586
	.word	1238
.Lfe2:
	.size	 OvlFunc_883_2008f8c,.Lfe2-OvlFunc_883_2008f8c
	.align	2, 0
	.global	OvlFunc_883_2008fbc
	.thumb_func
	.type	 OvlFunc_883_2008fbc,function
OvlFunc_883_2008fbc:
	push	{lr}
	mov	r0, #158
	bl	__PlaySound
	ldr	r0, .L9
	mov	r1, #35
	mov	r2, #74
	bl	__Func_8010560
	mov	r0, #0
	mov	r1, #102
	ldr	r2, .L9+4
	.code	16
	bl	__Func_809218c
	mov	r0, #10
	bl	__Func_8091e9c
	pop	{r0}
	bx	r0
.L10:
	.align	2, 0
.L9:
	.word	.L755a
	.word	1206
.Lfe3:
	.size	 OvlFunc_883_2008fbc,.Lfe3-OvlFunc_883_2008fbc

	.text
	.align	2, 0
