@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_883_2008d70
	.thumb_func
	.type	 OvlFunc_883_2008d70,function
OvlFunc_883_2008d70:
	push	{lr}
	mov	r0, #132
	lsl	r0, r0, #2
	sub	sp, sp, #8
	bl	__SetFlag
	mov	r3, #10
	mov	r2, #84
	.code	16
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #40
	mov	r1, #84
	mov	r2, #7
	mov	r3, #4
	bl	__Func_8010704
	add	sp, sp, #8
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_883_2008d70,.Lfe1-OvlFunc_883_2008d70
	.align	2, 0
	.global	OvlFunc_883_2008d98
	.thumb_func
	.type	 OvlFunc_883_2008d98,function
OvlFunc_883_2008d98:
	push	{lr}
	mov	r0, #132
	lsl	r0, r0, #2
	sub	sp, sp, #8
	bl	__ClearFlag
	mov	r3, #10
	mov	r2, #84
	.code	16
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #40
	mov	r1, #89
	mov	r2, #7
	mov	r3, #4
	bl	__Func_8010704
	add	sp, sp, #8
	pop	{r0}
	bx	r0
.Lfe2:
	.size	 OvlFunc_883_2008d98,.Lfe2-OvlFunc_883_2008d98
	.align	2, 0
	.global	OvlFunc_883_2008dc0
	.thumb_func
	.type	 OvlFunc_883_2008dc0,function
OvlFunc_883_2008dc0:
	push	{lr}
	mov	r0, #188
	bl	__PlaySound
	ldr	r0, .L5
	mov	r1, #45
	mov	r2, #11
	bl	__Func_8010560
	mov	r2, #210
	mov	r0, #0
	ldr	r1, .L5+4
	lsl	r2, r2, #1
	.code	16
	bl	__Func_809218c
	mov	r0, #11
	bl	__Func_8091e9c
	pop	{r0}
	bx	r0
.L6:
	.align	2, 0
.L5:
	.word	.L7544
	.word	257
.Lfe3:
	.size	 OvlFunc_883_2008dc0,.Lfe3-OvlFunc_883_2008dc0

	.text
	.align	2, 0
