@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_965_200a548
	.thumb_func
	.type	 OvlFunc_965_200a548,function
OvlFunc_965_200a548:
	push	{lr}
	ldr r0, =0x985
	sub sp, #8
	.code	16
	bl	__GetFlag
	cmp	r0, #0
	beq	.L3
	ldr r0, =0x985
	.code	16
	bl	__ClearFlag
	mov	r0, #157
	bl	__PlaySound
	bl	__CutsceneStart
	mov r1, #0x94
	mov r0, #8
	lsl r1, #1
	mov r2, #0xf0
	.code	16
	bl	__MapActor_TravelTo
	mov	r1, #156
	lsl	r1, r1, #1
	mov	r2, #240
	mov	r0, #9
	bl	__MapActor_TravelTo
	mov	r0, #8
	bl	__MapActor_WaitMovement
	mov	r0, #9
	bl	__MapActor_WaitMovement
	mov r3, #0x11
	mov r2, #0xe
	str r3, [sp]
	str r2, [sp, #4]
	.code	16
	mov	r0, #0
	mov	r1, #14
	mov	r2, #4
	mov	r3, #1
	bl	__Func_8010704
	bl	__CutsceneEnd
	ldr r0, =0x301
	.code	16
	bl	__GetFlag
	cmp	r0, #0
	beq	.L4
	ldr r0, =0x301
	.code	16
	bl	__ClearFlag
	b	.L3
.L4:
	ldr r0, =0x301
	.code	16
	bl	__SetFlag
.L3:
	add sp, #8
	.code	16
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_965_200a548,.Lfe1-OvlFunc_965_200a548

	.text
	.align	2, 0
