@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_965_200a660
	.thumb_func
	.type	 OvlFunc_965_200a660,function
OvlFunc_965_200a660:
	push	{r5, r6, lr}
	mov	r5, r0
	ldrh	r3, [r5, #6]
	ldr	r2, .L3
	lsr	r3, r3, #12
	lsl	r3, r3, #2
	ldr	r0, [r2, r3]
	ldr	r3, .L3+4
	ldr	r1, [r5, #8]
	ldr	r2, [r5, #16]
	sub	sp, sp, #12
	and	r3, r3, r0
	lsl	r0, r0, #16
	mov	r6, sp
	add	r2, r2, r0
	add	r1, r1, r3
	str	r1, [r6]
	str	r2, [r6, #8]
	mov	r3, r5
	add	r3, r3, #34
	ldrb	r0, [r3]
	bl	__Func_8011f54
	mov	r1, r5
	str	r0, [r6, #4]
	mov	r0, r6
	bl	OvlFunc_965_200806c
	add	sp, sp, #12
	pop	{r5, r6}
	pop	{r1}
	bx	r1
.L4:
	.align	2, 0
.L3:
	.word	.L2fd4
	.word	-65536
.Lfe1:
	.size	 OvlFunc_965_200a660,.Lfe1-OvlFunc_965_200a660

	.text
	.align	2, 0
