@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_937_2008030
	.thumb_func
	.type	 OvlFunc_937_2008030,function
OvlFunc_937_2008030:
	push	{lr}
	ldr	r3, .L6
	mov	r1, #224
	.code	16
	lsl	r1, r1, #1
	add	r3, r3, r1
	mov	r1, #0
	.code	16
	ldrsh	r2, [r3, r1]
	ldr	r3, .L6+4
	.code	16
	cmp	r2, r3
	bne	.L3
	ldr	r0, .L6+8
	b	.L4
.L3:
	ldr	r3, .L6+12
	.code	16
	cmp	r2, r3
	bne	.L5
	ldr	r0, .L6+16
	b	.L4
.L5:
	ldr	r0, .L6+20
.L4:
	.code	16
	pop	{r1}
	bx	r1
.L7:
	.align	2, 0
.L6:
	.word	gState
	.word	0x64
	.word	.L4d0
	.word	0x65
	.word	.L6c8
	.word	MapEntrance_ARRAY_937__020084a0
.Lfe1:
	.size	 OvlFunc_937_2008030,.Lfe1-OvlFunc_937_2008030

	.text
	.align	2, 0
