@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	Func_8ec4c
	.type	 Func_8ec4c,function
	.thumb_func
Func_8ec4c:
	bx	lr
.Lfe1:
	.size	 Func_8ec4c,.Lfe1-Func_8ec4c

	.text
	.align	2, 0
