@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_7b8cb0_70
	.thumb_func
	.type	 OvlFunc_7b8cb0_70,function
OvlFunc_7b8cb0_70:
	mov	r0, #0
	bx	lr
.Lfe1:
	.size	 OvlFunc_7b8cb0_70,.Lfe1-OvlFunc_7b8cb0_70

	.text
	.align	2, 0
