@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_957_2008b30
	.thumb_func
	.type	 OvlFunc_957_2008b30,function
OvlFunc_957_2008b30:
	push	{r5, lr}
	ldr	r5, .L5
	mov	r3, #224
	ldr	r1, [r5]
	lsl	r3, r3, #1
	add	r2, r1, r3
	sub	r3, r3, #192
	str	r3, [r2]
	add	r3, r3, #200
	add	r2, r1, r3
	mov	r3, #24
	str	r3, [r2]
	mov	r0, #1
	bl	__WaitFrames
	mov	r0, #77
	bl	__Func_808fe38
	ldr	r3, .L5+4
	ldr	r5, [r5, #16]
	add	r2, r5, r3
	mov	r3, #5
	strh	r3, [r2]
	ldr	r0, .L5+8
	bl	__GetFlag
	cmp	r0, #0
	beq	.L3
	ldr	r3, .L5+12
	add	r2, r5, r3
	ldr	r3, .L5+16
	strh	r3, [r2]
	ldr	r3, .L5+20
	add	r2, r5, r3
	mov	r3, #63
	strh	r3, [r2]
	bl	OvlFunc_957_2008a54
	b	.L4
.L3:
	ldr	r3, .L5+12
	add	r2, r5, r3
	ldr	r3, .L5+24
	strh	r3, [r2]
	ldr	r3, .L5+20
	add	r2, r5, r3
	mov	r3, #31
	strh	r3, [r2]
	ldr	r2, .L5+28
	ldr	r3, .L5+32
	strh	r2, [r3]
	ldr	r2, .L5+36
	add	r3, r3, #2
	strh	r2, [r3]
.L4:
	pop	{r5}
	pop	{r0}
	bx	r0
.L6:
	.align	2, 0
.L5:
	.word	iwram_3001ebc
	.word	1322
	.word	513
	.word	1332
	.word	7453
	.word	1334
	.word	16191
	.word	16194
	.word	67108944
	.word	3076
.Lfe1:
	.size	 OvlFunc_957_2008b30,.Lfe1-OvlFunc_957_2008b30

	.text
	.align	2, 0
