@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_950_2008500
	.thumb_func
	.type	 OvlFunc_950_2008500,function
OvlFunc_950_2008500:
	push	{r5, r6, lr}
	mov	r6, r0
	mov	r0, #0
	bl	__MapActor_GetActor
	mov	r2, #128
	ldrh	r3, [r0, #6]
	lsl	r2, r2, #6
	add	r3, r3, r2
	ldr r2, =0xffffc000
	.code	16
	and	r3, r3, r2
	mov	r2, #128
	lsl	r3, r3, #16
	lsl	r2, r2, #24
	cmp	r3, r2
	bne	.L3
	mov	r0, #28
	mov	r1, r6
	bl	__Func_80b0278
	b	.L4
.L3:
	mov	r0, #149
	lsl	r0, r0, #4
	bl	__GetFlag
	cmp r0, #0
	beq 1f
	ldr r0, =0x238d
	b 2f
	.align 2, 0
	.pool
1:
	.code	16
	ldr	r0, .L9
	bl	__GetFlag
	cmp	r0, #0
	beq	.L5
	ldr	r0, .L9+4
	2:
	.code	16
	bl	__MessageID
	mov	r0, r6
	mov	r1, #0
	bl	__ActorMessage
	b	.L4
.L5:
	ldr	r5, .L9+8
	.code	16
	mov	r0, r5
	bl	__MessageID
	mov	r1, #0
	mov	r0, r6
	.code	16
	bl	__Func_8092c40
	mov	r0, #0
	mov	r1, #0
	bl	__Func_8091c7c
	cmp	r0, #0
	bne	.L7
	mov	r0, #10
	bl	__CutsceneWait
	add	r0, r5, #1
	bl	__MessageID
	b	.L8
.L7:
	add	r0, r5, #2
	bl	__MessageID
.L8:
	mov	r0, r6
	mov	r1, #0
	bl	__ActorMessage
.L4:
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L10:
	.align	2, 0
.L9:
	.word	2402
	.word	8731
	.word	8149
.Lfe1:
	.size	 OvlFunc_950_2008500,.Lfe1-OvlFunc_950_2008500

	.text
	.align	2, 0
