@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_932_200a020
	.thumb_func
	.type	 OvlFunc_932_200a020,function
OvlFunc_932_200a020:
	push	{lr}
	ldr	r3, .L20
	mov	r2, #224
	ldr	r1, [r3]
	mov	r3, #129
	lsl	r2, r2, #1
	lsl	r3, r3, #2
	str	r3, [r1, r2]
	ldr	r3, .L20+4
	.code	16
	ldrsh	r2, [r3, r2]
	ldr r3, =0x4d
	.code	16
	cmp	r2, r3
	bne	.L3
	bl	OvlFunc_932_200a0d0
	b	.L4
.L3:
	ldr r3, =0x4f
	.code	16
	cmp	r2, r3
	bne	.L5
	bl	OvlFunc_932_200a310
	b	.L4
.L5:
	ldr r3, =0x50
	.code	16
	cmp	r2, r3
	bne	.L7
	bl	OvlFunc_932_200a428
	b	.L4
.L7:
	ldr r3, =0x51
	.code	16
	cmp	r2, r3
	bne	.L9
	bl	OvlFunc_932_200a490
	b	.L4
.L9:
	ldr r3, =0x52
	.code	16
	cmp	r2, r3
	bne	.L11
	bl	OvlFunc_932_200a5c0
	b	.L4
.L11:
	ldr r3, =0x53
	.code	16
	cmp	r2, r3
	bne	.L13
	bl	OvlFunc_932_200a6c0
	b	.L4
.L13:
	ldr r3, =0x55
	.code	16
	cmp	r2, r3
	bne	.L15
	bl	OvlFunc_932_200a804
	b	.L4
.L15:
	ldr r3, =0x56
	.code	16
	cmp	r2, r3
	bne	.L17
	bl	OvlFunc_932_200a934
	b	.L4
.L17:
	ldr r3, =0x57
	.code	16
	cmp	r2, r3
	bne	.L4
	bl	OvlFunc_932_200a9dc
.L4:
	mov	r0, #0
	pop	{r1}
	bx	r1
.L21:
	.align	2, 0
.L20:
	.word	iwram_3001ebc
	.word	gState
.Lfe1:
	.size	 OvlFunc_932_200a020,.Lfe1-OvlFunc_932_200a020

	.text
	.align	2, 0
