@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_932_200820c
	.thumb_func
	.type	 OvlFunc_932_200820c,function
OvlFunc_932_200820c:
	push	{lr}
	ldr	r3, .L12
	.code	16
	mov	r1, #224
	lsl	r1, r1, #1
	.code	16
	add	r3, r3, r1
	mov	r1, #0
	.code	16
	ldrsh	r2, [r3, r1]
	ldr	r3, .L12+4
	.code	16
	cmp	r2, r3
	bne	.L3
	ldr	r0, .L12+8
	b	.L2
.L3:
	ldr	r3, .L12+12
	.code	16
	cmp	r2, r3
	bne	.L4
	ldr	r0, .L12+16
	b	.L2
.L4:
	ldr	r3, .L12+20
	.code	16
	cmp	r2, r3
	bne	.L5
	ldr	r0, .L12+24
	b	.L2
.L5:
	ldr	r3, .L12+28
	.code	16
	cmp	r2, r3
	bne	.L6
	ldr	r0, .L12+32
	b	.L2
.L6:
	ldr	r3, .L12+36
	.code	16
	cmp	r2, r3
	bne	.L7
	ldr	r0, .L12+40
	b	.L2
.L7:
	ldr	r3, .L12+44
	.code	16
	cmp	r2, r3
	bne	.L8
	ldr	r0, .L12+48
	b	.L2
.L8:
	ldr	r3, .L12+52
	.code	16
	cmp	r2, r3
	bne	.L9
	ldr	r0, .L12+56
	b	.L2
.L9:
	ldr	r3, .L12+60
	.code	16
	cmp	r2, r3
	bne	.L10
	ldr	r0, .L12+64
	b	.L2
.L10:
	ldr	r3, .L12+68
	.code	16
	cmp	r2, r3
	bne	.L11
	ldr	r0, .L12+72
	b	.L2
.L11:
	ldr	r0, .L12+76
.L2:
	pop	{r1}
	bx	r1
.L13:
	.align	2, 0
.L12:
	.word	gState
	.word	0x4d
	.word	.L4940
	.word	0x4f
	.word	.L49a0
	.word	0x51
	.word	gScript_882__0200ca00
	.word	0x52
	.word	.L4a60
	.word	0x53
	.word	.L4aa8
	.word	0x54
	.word	.L4b68
	.word	0x55
	.word	.L4b98
	.word	0x56
	.word	.L4c40
	.word	0x57
	.word	.L4cd0
	.word	.L4928
.Lfe1:
	.size	 OvlFunc_932_200820c,.Lfe1-OvlFunc_932_200820c

	.text
	.align	2, 0
