@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	OvlFunc_38
	.type	 OvlFunc_38,function
	.thumb_func
OvlFunc_38:
	mov	r0, #0x0
	bx	lr
.Lfe1:
	.size	 OvlFunc_38,.Lfe1-OvlFunc_38

	.text
	.align	2, 0
