@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_921_2009704
	.thumb_func
	.type	 OvlFunc_921_2009704,function
OvlFunc_921_2009704:
	push	{r5, lr}
	mov	r5, r0
	mov	r3, r5
	mov	r2, #0
	.code	16
	add	r3, r3, #85
	strb	r2, [r3]
	add	r3, r3, #15
	strh	r2, [r3]
	mov	r1, r5
	add	r1, r1, #35
	ldrb	r2, [r1]
	mov	r3, #254
	.code	16
	and	r3, r3, r2
	strb	r3, [r1]
	ldr	r1, [r5, #80]
	mov	r3, #13
	ldrb	r2, [r1, #9]
	.code	16
	neg	r3, r3
	and	r3, r3, r2
	mov	r2, #4
	.code	16
	orr	r3, r3, r2
	strb	r3, [r1, #9]
	mov	r1, #9
	bl	__Func_80929d8
	mov	r0, r5
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r3, #128
	lsl	r3, r3, #8
	str	r3, [r5, #24]
	str	r3, [r5, #28]
	pop	{r5}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_921_2009704,.Lfe1-OvlFunc_921_2009704
	.align	2, 0
	.global	OvlFunc_921_200974c
	.thumb_func
	.type	 OvlFunc_921_200974c,function
OvlFunc_921_200974c:
	push	{lr}
	mov	r1, r0
	add	r1, r1, #100
	.code	16
	mov	r3, #0
	ldrsh	r2, [r1, r3]
	ldr	r3, [r0, #8]
	lsl	r2, r2, #8
	add	r3, r3, r2
	str	r3, [r0, #8]
	mov	r2, #128
	ldr	r3, [r0, #12]
	lsl	r2, r2, #8
	add	r3, r3, r2
	str	r3, [r0, #12]
	ldr	r2, .L5
	ldr	r3, [r0, #24]
	add	r3, r3, r2
	str	r3, [r0, #24]
	ldr	r3, [r0, #28]
	add	r3, r3, r2
	str	r3, [r0, #28]
	ldrh	r3, [r1]
	add	r3, r3, #2
	strh	r3, [r1]
	ldr	r3, [r0, #104]
	sub	r3, r3, #1
	str	r3, [r0, #104]
	cmp	r3, #0
	bne	.L4
	bl	__DeleteActor
.L4:
	pop	{r0}
	bx	r0
.L6:
	.align	2, 0
.L5:
	.word	1966
.Lfe2:
	.size	 OvlFunc_921_200974c,.Lfe2-OvlFunc_921_200974c

	.text
	.align	2, 0
