@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_916_20088b0
	.thumb_func
	.type	 OvlFunc_916_20088b0,function
OvlFunc_916_20088b0:
	push	{r5, lr}
	sub	sp, sp, #8
	bl	__CutsceneStart
	mov	r1, #8
	mov	r0, #0
	bl	__MapActor_SetAnim
	mov	r0, #6
	bl	__CutsceneWait
	mov	r0, #239
	bl	__PlaySound
	mov r1, #0x80
	ldr r2, =0x3333
	mov r0, #8
	lsl r1, r1, #8
	.code	16
	bl	__MapActor_SetSpeed
	mov	r0, #8
	mov	r1, #2
	bl	__MapActor_SetAnim
	mov	r2, #176
	mov	r1, #104
	mov	r0, #8
	bl	__MapActor_TravelTo
	mov	r0, #6
	bl	__CutsceneWait
	mov	r0, #0
	mov	r1, #2
	bl	__MapActor_SetAnim
	mov r0, #0
	ldr r1, =0x4ccc
	ldr r2, =0x3333
	.code	16
	bl	__MapActor_SetSpeed
	mov	r2, #0
	mov	r1, #8
	mov	r0, #0
	bl	__Func_809228c
	mov	r0, #24
	bl	__CutsceneWait
	mov	r1, #1
	mov	r0, #0
	bl	__MapActor_SetAnim
	mov	r0, #8
	bl	__MapActor_WaitMovement
	mov	r1, #1
	mov	r0, #8
	bl	__MapActor_SetAnim
	mov	r0, #144
	lsl	r0, r0, #1
	bl	__PlaySound
	mov	r0, #213
	bl	__PlaySound
	mov	r5, #9
	mov	r3, #4
	mov	r0, #5
	mov	r1, #9
	mov	r2, #1
	str	r3, [sp]
	str	r5, [sp, #4]
	bl	__Func_8010704
	mov	r3, #6
	str	r3, [sp]
	mov	r0, #0
	mov	r1, #0
	mov	r2, #1
	mov	r3, #4
	str	r5, [sp, #4]
	bl	__Func_8010704
	ldr r3, =.L12c4
	ldr r2, [r3]
	ldr r3, .Lzero_20088b0
	strh r3, [r2]
	.code	16
	bl	__CutsceneEnd
	add	sp, sp, #8
	pop	{r5}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_916_20088b0,.Lfe1-OvlFunc_916_20088b0
	.align 2, 0
.Lzero_20088b0: .word 0

	.text
	.align	2, 0
