@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_957_200b598
	.thumb_func
	.type	 OvlFunc_957_200b598,function
OvlFunc_957_200b598:
	push	{lr}
	ldr	r3, .L9
	mov	r1, #224
	.code	16
	lsl	r1, r1, #1
	add	r3, r3, r1
	mov	r1, #0
	.code	16
	ldrsh	r2, [r3, r1]
	ldr	r3, .L9+4
	.code	16
	cmp	r2, r3
	bne	.L3
	ldr	r0, .L9+8
	b	.L4
.L3:
	ldr	r3, .L9+12
	.code	16
	cmp	r2, r3
	bne	.L5
	ldr	r0, .L9+16
	b	.L4
.L5:
	ldr	r3, .L9+20
	.code	16
	cmp	r2, r3
	bne	.L6
	ldr	r0, .L9+24
	b	.L4
.L6:
	ldr	r3, .L9+28
	.code	16
	cmp	r2, r3
	bne	.L7
	ldr	r0, .L9+32
	b	.L4
.L7:
	ldr	r3, .L9+36
	.code	16
	cmp	r2, r3
	bne	.L8
	ldr	r0, .L9+40
	b	.L4
.L8:
	ldr	r0, .L9+44
.L4:
	.code	16
	pop	{r1}
	bx	r1
.L10:
	.align	2, 0
.L9:
	.word	gState
	.word	0x93
	.word	.L4688
	.word	0x94
	.word	.L4724
	.word	0x95
	.word	.L476c
	.word	0x96
	.word	.L4808
	.word	0x97
	.word	.L4850
	.word	.L45e0
.Lfe1:
	.size	 OvlFunc_957_200b598,.Lfe1-OvlFunc_957_200b598

	.text
	.align	2, 0
