@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_970_20092ac
	.thumb_func
	.type	 OvlFunc_970_20092ac,function
OvlFunc_970_20092ac:
	push	{r5, r6, lr}
	mov	r0, #128
	lsl	r0, r0, #1
	sub	sp, sp, #4
	bl	__Func_8004970
	ldr	r5, .L10+4
	mov	r6, r0
	bl	__AllocSpriteSlot
	ldr	r3, .L10+8
	strh	r0, [r5]
	mov	r0, sp
	str	r3, [r0]
	mov	r1, r6
	ldr	r3, .L10+12
	ldr	r2, .L10+16
	stmia	r3!, {r0, r1, r2}
	sub	r3, #0xc
	mov r1, #0x80
	.code	16
	mov	r3, #0
	ldrsh	r0, [r5, r3]
	mov	r2, r6
	lsl	r1, r1, #1
	bl	__UploadSpriteGFX
	ldr	r2, .L10+20
	ldrh	r3, .L10
	mov	r1, #200
	strh	r3, [r2]
	lsl	r1, r1, #4
	ldr	r0, .L10+24
	bl	__StartTask
	add	sp, sp, #4
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L11:
	.align	2, 0
.L10:
	.word	48
	.word	.L1c1a
	.word	286331153
	.word	67109076
	.word	-2063597504
	.word	.L1c18
	.word	OvlFunc_970_20091c4
.Lfe1:
	.size	 OvlFunc_970_20092ac,.Lfe1-OvlFunc_970_20092ac

	.text
	.align	2, 0
