@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8079e9c
	.thumb_func
	.type	 Func_8079e9c,function
Func_8079e9c:
	push	{r5, lr}
	mov	r5, r1
	ldr	r1, .L17
	mov	r2, r0
	add	r3, r2, r1
	.code	16
	ldrb	r3, [r3]
	cmp	r3, #0
	bne	.L4
	sub	r1, r1, #1
	add	r3, r2, r1
	.code	16
	ldrb	r0, [r3]
	bl	GetEnemyInfo
	mov	r2, #0
	add	r0, r0, #72
.L10:
	ldrb	r3, [r0]
	cmp	r3, r5
	beq	.L9
	add	r2, r2, #1
	add	r0, r0, #1
	cmp	r2, #2
	ble	.L10
	b	.L11
.L4:
	ldr	r1, .L17
	add	r3, r2, r1
	ldrb	r0, [r3]
	bl	GetClassInfo
	mov	r2, #0
	add	r0, r0, #80
.L12:
	ldrb	r3, [r0]
	add	r0, r0, #1
	cmp	r3, r5
	bne	.L14
.L9:
	mov	r0, #1
	b	.L15
.L14:
	add	r2, r2, #1
	cmp	r2, #2
	ble	.L12
.L11:
	mov	r0, #0
.L15:
	pop	{r5}
	pop	{r1}
	bx	r1
.L18:
	.align	2, 0
.L17:
	.word	297
.Lfe1:
	.size	 Func_8079e9c,.Lfe1-Func_8079e9c

	.text
	.align	2, 0
