@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8079b24
	.thumb_func
	.type	 Func_8079b24,function
Func_8079b24:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	ldr	r5, .L10
	mov	r8, r1
	mov	r1, #0
	ldrsh	r2, [r5, r1]
	mov	r6, r0
	mov	r4, #16
	ldrsh	r3, [r5, r4]
	mov	r0, #5
	cmp	r6, r2
	ble	.L3
	mov	r6, r2
	b	.L4
.L3:
	cmp	r6, r3
	bge	.L4
	mov	r6, r3
.L4:
	movs r1, #0
	movs r4, #0
	cmp r1, r0
	bge 3f
	movs r7, #0
	ldrsh r3, [r5, r7]
	cmp r6, r3
	bgt 2f
	mov r12, r5
	movs r2, #0
	1:
	add r1, #1
	add r2, #4
	cmp r1, r0
	bge 4f
	mov r4, r2
	mov r3, r12
	ldrsh r3, [r4, r3]
	mov lr, r3
	cmp r6, lr
	ble 1b
	b 3f
	2:
	movs r4, #0
	b 3f
	4:
	lsl r4, r1, #2
	3:
	
	.code	16
	cmp	r1, r0
	bne	.L6
	sub	r3, r4, #2
	ldrsh	r0, [r5, r3]
	b	.L7
.L6:
	sub	r3, r4, #4
	ldrsh	r1, [r5, r3]
	ldrsh	r0, [r5, r4]
	sub	r3, r4, #2
	ldrsh	r2, [r5, r3]
	add	r3, r4, #2
	ldrsh	r5, [r5, r3]
	sub	r1, r1, r0
	sub	r2, r2, r5
	sub	r0, r6, r0
	mul	r0, r0, r2
	bl	__divsi3
	add	r0, r0, r5
.L7:
	mov	r7, r8
	cmp	r7, #0
	beq	.L8
	cmp	r7, #1
	bne	.L8
	lsr	r3, r0, #31
	add	r3, r0, r3
	asr	r0, r3, #1
.L8:
	mov	r1, #128
	lsl	r1, r1, #1
	add	r0, r0, r1
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L11:
	.align	2, 0
.L10:
	.word	.L89258
.Lfe1:
	.size	 Func_8079b24,.Lfe1-Func_8079b24

	.text
	.align	2, 0
