@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	CheckEquipmentCritBoost
	.thumb_func
	.type	 CheckEquipmentCritBoost,function
CheckEquipmentCritBoost:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	mov r2, #0x80
	lsl r2, #2
	sub sp, #4
	mov r7, r0
	mov r6, #0
	mov r5, #0xd8
	mov r8, r2
	mov r1, #0xe
	.code	16
.L12:
	ldrh	r3, [r5, r7]
	mov	r2, r8
	and	r3, r3, r2
	cmp	r3, #0
	beq	.L6
	ldrh r0, [r5, r7]
	str r1, [sp]
	.code	16
	bl	GetItemInfo
	ldr r1, [sp]
	add r0, #0x18
	.code	16
	mov	r2, #3
.L11:
	ldrb	r3, [r0]
	cmp	r3, #23
	bne	.L10
	mov	r3, #1
	ldrsb	r3, [r0, r3]
	add	r6, r6, r3
.L10:
	sub	r2, r2, #1
	add	r0, r0, #4
	cmp	r2, #0
	bge	.L11
.L6:
	sub	r1, r1, #1
	add	r5, r5, #2
	cmp	r1, #0
	bge	.L12
	cmp	r6, #0
	bge	.L13
	mov	r6, #0
.L13:
	mov r0, r6
	add sp, #4
	.code	16
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 CheckEquipmentCritBoost,.Lfe1-CheckEquipmentCritBoost

	.text
	.align	2, 0
