@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	CheckLure
	.thumb_func
	.type	 CheckLure,function
CheckLure:
	push	{r5, r6, r7, lr}
	mov	r7, fp
	mov	r6, sl
	mov	r5, r9
	push	{r5, r6, r7}
	mov	r7, r8
	push	{r7}
	ldr	r0, .L8
	sub	sp, sp, #8
	bl	ClearFlag
	bl	GetPartySize
	mov	sl, r0
	movs r0, #0
mov r8, r0

	.code	16
	cmp	r8, sl
	bge	.L3
	ldr r3, =gState
mov r2, #0xfc
lsl r2, r2, #1
add r2, r2, r3
mov r3, #0x80
lsl r3, r3, #2
mov r9, r2
mov fp, r3

	.code	16
.L7:
	mov r2, r9
ldrb r0, [r2]
bl GetUnit
mov r2, #0xd8
mov r7, r0
mov r1, #14
1:
ldrh r3, [r2, r7]
mov r0, fp
and r3, r0
cmp r3, #0
beq 2f
ldrh r0, [r2, r7]
str r1, [sp, #4]
str r2, [sp]
bl GetItemInfo
mov r5, r0
ldr r2, [sp]
ldr r1, [sp, #4]
add r5, #0x18
mov r6, #3
3:
ldrb r3, [r5]
add r5, #4
cmp r3, #0x1b
bne 4f
ldr r0, .L8
str r1, [sp, #4]
str r2, [sp]
bl SetFlag
ldr r2, [sp]
ldr r1, [sp, #4]
4:
sub r6, #1
cmp r6, #0
bge 3b
2:
sub r1, #1
add r2, #2
cmp r1, #0
bge 1b

	movs r2, #1
add r8, r8, r2
add r9, r9, r2

	.code	16
	cmp	r8, sl
	blt	.L7
.L3:
	add	sp, sp, #8
	pop	{r3, r5, r6, r7}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	mov	fp, r7
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L9:
	.align	2, 0
.L8:
	.word	359
.Lfe1:
	.size	 CheckLure,.Lfe1-CheckLure

	.text
	.align	2, 0
