@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8078550
	.thumb_func
	.type	 Func_8078550,function
Func_8078550:
	push	{r5, r6, r7, lr}
	sub	sp, sp, #20
	mov	r5, sp
	mov	r0, r5
	bl	Func_80796c4
	mov	r7, #0
	mov	r6, r5
	cmp	r7, r0
	bge	.L3
	mov	r5, r0
.L7:
	mov	r3, #0
	ldrsh	r0, [r6, r3]
	bl	FindEmptyInventorySlot
	sub	r0, r7, r0
	.code	16
	mov	r7, r0
	sub	r5, r5, #1
	.code	16
	add	r6, r6, #2
	add	r7, r7, #15
	cmp	r5, #0
	bne	.L7
.L3:
	mov	r0, r7
	add	sp, sp, #20
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 Func_8078550,.Lfe1-Func_8078550

	.text
	.align	2, 0
