@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_807808c
	.thumb_func
	.type	 Func_807808c,function
Func_807808c:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	mov	r8, r0
	bl	GetPartySize
	mov	r6, #0
	mov	r7, r0
	cmp	r6, r7
	bge	.L14
.L5:
	mov	r1, #252
	ldr	r2, .L15
	lsl	r1, r1, #1
	add	r3, r6, r1
	ldrb	r0, [r2, r3]
	bl	GetUnit
	mov	r5, r0
	ldrh r1, [r5, #0x34]
	ldrh r3, [r5, #0x36]
	strh r1, [r5, #0x38]
	strh r3, [r5, #0x3a]
	.code	16
	lsl	r1, r1, #16
	asr	r1, r1, #16
	lsl	r0, r1, #14
	bl	__divsi3
	mov	r3, #128
	lsl	r3, r3, #7
	cmp	r0, r3
	bgt	.L6
	mov	r3, #0
	cmp	r0, #0
	blt	.L6
	mov	r3, r0
.L6:
	strh	r3, [r5, #20]
	lsl	r3, r3, #16
	cmp	r3, #0
	bne	.L8
	mov	r2, #56
	ldrsh	r3, [r5, r2]
	cmp	r3, #0
	beq	.L8
	mov r3, #1
	strh r3, [r5, #0x14]
	.code	16
.L8:
	mov	r3, #58
	ldrsh	r0, [r5, r3]
	mov	r2, #54
	ldrsh	r1, [r5, r2]
	lsl	r0, r0, #14
	bl	__divsi3
	mov	r3, #128
	lsl	r3, r3, #7
	cmp	r0, r3
	bgt	.L9
	mov	r3, #0
	cmp	r0, #0
	blt	.L9
	mov	r3, r0
.L9:
	strh	r3, [r5, #22]
	lsl	r3, r3, #16
	cmp	r3, #0
	bne	.L11
	mov	r1, #58
	ldrsh	r3, [r5, r1]
	cmp	r3, #0
	beq	.L11
	mov r3, #1
	strh r3, [r5, #0x16]
	.code	16
.L11:
	mov	r2, r8
	cmp	r2, #1
	bne	.L12
	ldr	r1, .L15+4
	mov	r2, #0
	add	r3, r5, r1
	add	r1, r1, #15
	strb	r2, [r3]
	add	r3, r5, r1
	strb	r2, [r3]
.L12:
	add	r6, r6, #1
	cmp	r6, r7
	blt	.L5
.L14:
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L16:
	.align	2, 0
.L15:
	.word	gState
	.word	305
.Lfe1:
	.size	 Func_807808c,.Lfe1-Func_807808c

	.text
	.align	2, 0
