@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8078870
	.thumb_func
	.type	 Func_8078870,function
Func_8078870:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r8
	push	{r6, r7}
	mov	r2, #128
	.code	16
	ldr	r3, .L9
	.code	16
	lsl	r2, r2, #2
	mov	r5, r0
	mov	r7, r1
	mov	r6, #0
	mov	r8, r2
	mov	sl, r3
	.code	16
	add	r5, r5, #216
.L8:
	ldrh	r3, [r5]
	.code	16
	mov	r2, r8
	and	r3, r3, r2
	cmp	r3, #0
	beq	.L6
	ldrh	r0, [r5]
	bl	GetItemInfo
	ldrb	r3, [r0, #2]
	cmp	r3, r7
	bne	.L6
	ldrh	r3, [r5]
	mov	r0, sl
	.code	16
	and	r0, r0, r3
	b	.L2
.L6:
	add	r6, r6, #1
	add	r5, r5, #2
	cmp	r6, #14
	ble	.L8
	mov	r0, #0
.L2:
	pop	{r3, r5}
	mov	r8, r3
	mov	sl, r5
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L10:
	.align	2, 0
.L9:
	.word	511
.Lfe1:
	.size	 Func_8078870,.Lfe1-Func_8078870

	.text
	.align	2, 0
