@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	OvlFunc_210
	.type	 OvlFunc_210,function
	.thumb_func
OvlFunc_210:
	mov	r0, #0x0
	bx	lr
.Lfe1:
	.size	 OvlFunc_210,.Lfe1-OvlFunc_210

	.text
	.align	2, 0
