@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	OvlFunc_d14
	.type	 OvlFunc_d14,function
	.thumb_func
OvlFunc_d14:
	mov	r0, #0x0
	bx	lr
.Lfe1:
	.size	 OvlFunc_d14,.Lfe1-OvlFunc_d14

	.text
	.align	2, 0
