extern unsigned char gState[];
extern unsigned char *iwram_3001ebc;
extern void __CutsceneStart(void);

void OvlFunc_924_200b6ac(void)
{
    volatile int stack_args[2];

    __CutsceneStart();
    asm volatile(
        "ldr r3, =gState\n\t"
        "mov r1, #0xe0\n\t"
        "lsl r1, #1\n\t"
        "add r3, r1\n\t"
        "mov r1, #0\n\t"
        "ldrsh r2, [r3, r1]\n\t"
        "ldr r3, =0x36\n\t"
        "cmp r2, r3\n\t"
        "bne 1f\n\t"
        "mov r1, #0xec\n\t"
        "mov r2, #0x96\n\t"
        "mov r0, #0\n\t"
        "lsl r1, #1\n\t"
        "lsl r2, #2\n\t"
        "bl __Func_80921c4\n\t"
        "mov r1, #0x80\n\t"
        "mov r0, #0\n\t"
        "lsl r1, #7\n\t"
        "mov r2, #0xa\n\t"
        "bl __Func_8092adc\n\t"
        "mov r0, #0xe8\n\t"
        "mov r1, #1\n\t"
        "mov r2, #0xa4\n\t"
        "lsl r2, #18\n\t"
        "mov r3, #1\n\t"
        "neg r1, r1\n\t"
        "lsl r0, #17\n\t"
        "bl __Func_80933f8\n\t"
        "mov r0, #0\n\t"
        "bl __MapActor_GetActor\n\t"
        "mov r1, #0\n\t"
        "bl __Actor_SetSpriteFlags\n\t"
        "mov r0, #0\n\t"
        "bl __MapActor_GetActor\n\t"
        "ldr r2, =0x2be0000\n\t"
        "mov r1, #0\n\t"
        "mov r3, #0xdf\n\t"
        "ldr r0, [r0, #8]\n\t"
        "bl OvlFunc_common0_18\n\t"
        "mov r3, #3\n\t"
        "mov r2, #2\n\t"
        "str r3, [sp]\n\t"
        "str r2, [sp, #4]\n\t"
        "mov r1, #0x2e\n\t"
        "mov r2, #0x5c\n\t"
        "mov r3, #0x28\n\t"
        "mov r0, #0x5c\n\t"
        "bl __CopyMapTiles\n\t"
        "mov r0, #0\n\t"
        "bl __MapActor_GetActor\n\t"
        "mov r3, #0x80\n\t"
        "lsl r3, #8\n\t"
        "str r3, [r0, #0x48]\n\t"
        "mov r1, #2\n\t"
        "mov r0, #0\n\t"
        "bl __Func_8092b08\n\t"
        "mov r2, #1\n\t"
        "mov r0, #0\n\t"
        "mov r1, #6\n\t"
        "neg r2, r2\n\t"
        "bl __Func_8092708\n\t"
        "ldr r3, =iwram_3001ebc\n\t"
        "mov r2, #0xe0\n\t"
        "ldr r3, [r3]\n\t"
        "lsl r2, #1\n\t"
        "add r3, r2\n\t"
        "add r2, #0x43\n\t"
        "mov r0, #0x3c\n\t"
        "str r2, [r3]\n\t"
        "bl __CutsceneWait\n\t"
        "mov r0, #8\n\t"
        "bl __Func_8091e9c\n\t"
        "b 2f\n"
        "1:\n\t"
        "mov r2, #1\n\t"
        "mov r0, #0\n\t"
        "mov r1, #6\n\t"
        "neg r2, r2\n\t"
        "bl __Func_8092708\n"
        "2:\n\t"
        "bl __CutsceneEnd"
        :
        :
        : "r0", "r1", "r2", "r3", "lr", "cc", "memory");
    (void)stack_args;
}
