typedef unsigned char u8;

extern u8 gState[];
extern u8 gBuffer[];
extern int __GetFlag(int flag);
extern void *__GetFieldActor(int id);
extern void *__CreateActor(int type, int x, int y, int z);
extern void __Actor_SetScript(void *actor, const void *script);
extern void __Sprite_SetAnim(void *sprite, int animation);
extern void *__galloc_ewram(int size, int count);
extern const u8 gScript_924__0200de38[];
extern const u8 gScript_924__0200de20[];

void OvlFunc_924_200cfcc(void *arg0, void *arg1)
{
    register void *p1 asm("r8");
    register void *p0 asm("r9");
    register void *actorReg asm("r7");
    register void *tileReg asm("r10");

    asm volatile("mov r8, r1" : "=r"(p1) : "r"(arg1));
    asm volatile("mov r9, r0" : "=r"(p0) : "r"(arg0));
    asm volatile(
        "mov r1, #4\n\t"
        "mov r0, #0x23\n\t"
        "sub sp, #4\n\t"
        "bl __galloc_ewram\n\t"
        "mov r2, r8\n\t"
        "str r2, [r0]\n\t"
        "ldr r0, .Lpool_a_924\n\t"
        "bl __GetFlag\n\t"
        "mov r3, r0\n\t"
        "cmp r3, #0\n\t"
        "bne 1f\n\t"
        "mov r0, sp\n\t"
        "str r3, [r0]\n\t"
        "mov r1, r8\n\t"
        "ldr r3, .Lpool_b_924\n\t"
        "ldr r2, .Lpool_c_924\n\t"
        "stmia r3!, {r0, r1, r2}\n\t"
        "sub r3, #0xc\n\t"
        "mov r3, r9\n\t"
        "mov r0, r8\n\t"
        "str r3, [r0, #4]\n\t"
        "b 8f\n\t"
        "1:\n\t"
        "ldr r3, .Lpool_d_924\n\t"
        "mov r2, #0xfa\n\t"
        "lsl r2, #1\n\t"
        "add r3, r2\n\t"
        "ldr r0, [r3]\n\t"
        "bl __GetFieldActor\n\t"
        "mov r7, r0\n\t"
        "ldr r4, [r7, #0x10]\n\t"
        "mov r3, r4\n\t"
        "cmp r4, #0\n\t"
        "bge 2f\n\t"
        "ldr r0, .Lpool_e_924\n\t"
        "add r3, r4, r0\n\t"
        "2:\n\t"
        "ldr r1, [r7, #8]\n\t"
        "asr r3, #20\n\t"
        "lsl r2, r3, #7\n\t"
        "mov r3, r1\n\t"
        "cmp r1, #0\n\t"
        "bge 3f\n\t"
        "ldr r0, .Lpool_e_924\n\t"
        "add r3, r1, r0\n\t"
        "3:\n\t"
        "asr r3, #20\n\t"
        "add r3, r2, r3\n\t"
        "ldr r2, .Lpool_f_924\n\t"
        "lsl r3, #2\n\t"
        "mov r0, r8\n\t"
        "add r2, r3\n\t"
        "ldr r3, [r0]\n\t"
        "mov r10, r2\n\t"
        "cmp r3, #0\n\t"
        "beq 4f\n\t"
        "ldr r3, [r0, #0x14]\n\t"
        "cmp r3, #0\n\t"
        "beq 4f\n\t"
        "ldr r2, [r7, #0xc]\n\t"
        "mov r3, #0xc0\n\t"
        "lsl r3, #13\n\t"
        "add r2, r3\n\t"
        "mov r0, #0x1a\n\t"
        "mov r3, r4\n\t"
        "bl __CreateActor\n\t"
        "mov r5, r0\n\t"
        "cmp r5, #0\n\t"
        "beq 5f\n\t"
        "ldr r3, [r7, #0x14]\n\t"
        "ldr r1, .Lpool_g_924\n\t"
        "str r3, [r5, #0x14]\n\t"
        "ldr r6, [r5, #0x50]\n\t"
        "bl __Actor_SetScript\n\t"
        "mov r2, r5\n\t"
        "mov r3, #4\n\t"
        "add r2, #0x55\n\t"
        "str r7, [r5, #0x68]\n\t"
        "strb r3, [r2]\n\t"
        "ldr r0, .Lpool_h_924\n\t"
        "ldr r3, [r5, #0xc]\n\t"
        "add r3, r0\n\t"
        "str r3, [r5, #0xc]\n\t"
        "cmp r6, #0\n\t"
        "beq 6f\n\t"
        "mov r2, r8\n\t"
        "ldr r3, [r2]\n\t"
        "mov r1, #6\n\t"
        "sub r1, r3\n\t"
        "mov r0, r6\n\t"
        "bl __Sprite_SetAnim\n\t"
        "mov r2, r6\n\t"
        "add r2, #0x26\n\t"
        "mov r3, #0\n\t"
        "strb r3, [r2]\n\t"
        "ldrb r2, [r6, #9]\n\t"
        "sub r3, #0xd\n\t"
        "and r3, r2\n\t"
        "mov r2, #4\n\t"
        "orr r3, r2\n\t"
        "strb r3, [r6, #9]\n\t"
        "6:\n\t"
        "mov r3, r8\n\t"
        "str r5, [r3, #0x14]\n\t"
        "b 5f\n\t"
        "4:\n\t"
        "mov r3, #0\n\t"
        "mov r0, r8\n\t"
        "str r3, [r0, #0x14]\n\t"
        "5:\n\t"
        "mov r2, r10\n\t"
        "ldrb r3, [r2, #2]\n\t"
        "cmp r3, r9\n\t"
        "bne 7f\n\t"
        "mov r0, r8\n\t"
        "ldr r3, [r0, #0x18]\n\t"
        "cmp r3, #0\n\t"
        "beq 7f\n\t"
        "ldr r1, [r7, #8]\n\t"
        "ldr r2, [r7, #0xc]\n\t"
        "ldr r3, [r7, #0x10]\n\t"
        "mov r0, #0x1a\n\t"
        "bl __CreateActor\n\t"
        "mov r5, r0\n\t"
        "cmp r5, #0\n\t"
        "beq 8f\n\t"
        "ldr r3, [r7, #0x14]\n\t"
        "ldr r1, .Lpool_i_924\n\t"
        "str r3, [r5, #0x14]\n\t"
        "ldr r6, [r5, #0x50]\n\t"
        "bl __Actor_SetScript\n\t"
        "mov r3, r5\n\t"
        "mov r2, #0\n\t"
        "add r3, #0x55\n\t"
        "strb r2, [r3]\n\t"
        "add r3, #0xf\n\t"
        "strh r2, [r3]\n\t"
        "mov r2, r5\n\t"
        "mov r3, #2\n\t"
        "add r2, #0x23\n\t"
        "strb r3, [r2]\n\t"
        "mov r3, #0x80\n\t"
        "lsl r3, #11\n\t"
        "str r3, [r5, #0x30]\n\t"
        "cmp r6, #0\n\t"
        "beq 9f\n\t"
        "mov r0, r6\n\t"
        "mov r1, #6\n\t"
        "bl __Sprite_SetAnim\n\t"
        "mov r2, r6\n\t"
        "ldr r3, .Lpool_j_924\n\t"
        "add r2, #0x26\n\t"
        "strb r3, [r2]\n\t"
        "9:\n\t"
        "mov r2, r8\n\t"
        "str r5, [r2, #0x18]\n\t"
        "b 8f\n\t"
        ".align 2, 0\n\t"
        ".Lpool_j_924: .word 0\n\t"
        ".Lpool_a_924: .word 0x109\n\t"
        ".Lpool_b_924: .word 0x040000d4\n\t"
        ".Lpool_c_924: .word 0x85000007\n\t"
        ".Lpool_d_924: .word gState\n\t"
        ".Lpool_e_924: .word 0xfffff\n\t"
        ".Lpool_f_924: .word gBuffer\n\t"
        ".Lpool_g_924: .word gScript_924__0200de38\n\t"
        ".Lpool_h_924: .word 0xffff8000\n\t"
        ".Lpool_i_924: .word gScript_924__0200de20\n\t"
        "7:\n\t"
        "mov r3, #0\n\t"
        "mov r0, r8\n\t"
        "str r3, [r0, #0x18]\n\t"
        "8:\n\t"
        "add sp, #4\n\t"
        : "=r"(actorReg), "=r"(tileReg)
        : "r"(p1), "r"(p0)
        : "r0", "r1", "r2", "r3", "r4", "r5", "r6", "lr", "memory", "cc"
    );
}
