@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_924_200bb24
	.thumb_func
	.type	 OvlFunc_924_200bb24,function
OvlFunc_924_200bb24:
	push	{r5, r6, r7, lr}
	mov	r7, fp
	mov	r6, sl
	mov	r5, r9
	push	{r5, r6, r7}
	mov	r7, r8
	push	{r7}
	ldr	r3, .L5
	ldr	r3, [r3]
	mov	r8, r3
	mov	fp, r2
	mov	r3, #3
	mov	r2, r8
	and	r2, r2, r3
	sub	sp, sp, #56
	mov	sl, r0
	mov	r9, r1
	mov	r8, r2
	cmp	r2, #0
	bne	.L3
	mov	r3, #7
	add	r7, sp, #16
	str	r3, [r7, #4]
	bl	__Random
	lsl	r0, r0, #1
	lsr	r0, r0, #16
	mov	r3, #1
	and	r0, r0, r3
	cmp	r0, #0
	bne	.L4
	mov	r3, #5
	str	r3, [r7, #4]
.L4:
	ldr	r3, .L5+4
	str	r3, [r7, #8]
	str	r3, [r7, #12]
	bl	__Random
	lsl	r0, r0, #3
	lsr	r0, r0, #16
	lsl	r5, r0, #1
	add	r5, r5, r0
	lsl	r3, r5, #4
	add	r5, r5, r3
	lsl	r3, r5, #8
	add	r5, r5, r3
	bl	__Random
	lsl	r0, r0, #3
	lsr	r0, r0, #16
	lsl	r3, r0, #1
	add	r3, r3, r0
	lsl	r2, r3, #4
	add	r3, r3, r2
	ldr	r6, .L5+8
	lsl	r2, r3, #8
	add	r3, r3, r2
	add	r3, r3, r6
	str	r3, [sp]
	mov	r3, r8
	str	r3, [sp, #4]
	mov	r3, #144
	lsl	r3, r3, #12
	add	r5, r5, r6
	str	r3, [sp, #8]
	mov	r0, sl
	mov	r1, r9
	mov	r2, fp
	mov	r3, r5
	str	r7, [sp, #12]
	bl	OvlFunc_common0_10c
.L3:
	add	sp, sp, #56
	pop	{r3, r5, r6, r7}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	mov	fp, r7
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L6:
	.align	2, 0
.L5:
	.word	iwram_3001e40
	.word	45875
	.word	-52428
.Lfe1:
	.size	 OvlFunc_924_200bb24,.Lfe1-OvlFunc_924_200bb24

	.text
	.align	2, 0
