@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_7fc618_b4
	.thumb_func
	.type	 OvlFunc_7fc618_b4,function
OvlFunc_7fc618_b4:
	mov	r0, #0
	bx	lr
.Lfe1:
	.size	 OvlFunc_7fc618_b4,.Lfe1-OvlFunc_7fc618_b4

	.text
	.align	2, 0
