@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	ColorCycleVFXPalette
	.thumb_func
	.type	 ColorCycleVFXPalette,function
ColorCycleVFXPalette:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r8
	push	{r6, r7}
	mov	r5, r0
	lsl	r5, r5, #10
	add	r1, r5, r1
	mov	r0, r1
	sub	sp, sp, #128
	mov	r6, r2
	mov	r8, r3
	bl	sin
	lsl	r0, r0, #4
	add	r6, r5, r6
	asr	r0, r0, #15
	mov	sl, r0
	mov	r0, r6
	bl	sin
	add	r5, r5, r8
	lsl	r0, r0, #4
	asr	r7, r0, #15
	mov	r0, r5
	bl	sin
	mov	r3, #0
	mov	r2, sp
	lsl	r0, r0, #4
	mov	r6, sp
	strh	r3, [r2]
	asr	r0, r0, #15
	mov	r5, #1
	add	r6, r6, #2
.L12:
	mov	r2, sl
	add	r3, r5, r2
	lsr	r2, r3, #31
	add	r3, r3, r2
	asr	r4, r3, #1
	add	r3, r5, r7
	lsr	r2, r3, #31
	add	r3, r3, r2
	asr	r1, r3, #1
	add	r3, r5, r0
	lsr	r2, r3, #31
	add	r3, r3, r2
	asr	r3, r3, #1
	cmp	r4, #0
	bge	.L6
	mov	r4, #0
.L6:
	cmp	r4, #31
	ble	.L7
	mov	r4, #31
.L7:
	cmp	r1, #0
	bge	.L8
	mov	r1, #0
.L8:
	cmp	r1, #31
	ble	.L9
	mov	r1, #31
.L9:
	cmp	r3, #0
	bge	.L10
	mov	r3, #0
.L10:
	cmp	r3, #31
	ble	.L11
	mov	r3, #31
.L11:
	lsl	r3, r3, #10
	lsl	r2, r1, #5
	orr	r3, r3, r2
	orr	r3, r3, r4
	add	r5, r5, #1
	strh	r3, [r6]
	add	r6, r6, #2
	cmp	r5, #64
	bne	.L12
	mov r1, sp
	.code	16
	ldr	r3, .L13
	mov	r2, #128
	ldr	r0, .L13+4
	bl	_call_via_r3
	add	sp, sp, #128
	pop	{r3, r5}
	mov	r8, r3
	mov	sl, r5
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L14:
	.align	2, 0
.L13:
	.word	Func_8001af8
	.word	83886082
.Lfe1:
	.size	 ColorCycleVFXPalette,.Lfe1-ColorCycleVFXPalette

	.text
	.align	2, 0
