@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80d6888
	.thumb_func
	.type	 Func_80d6888,function
Func_80d6888:
	push	{r5, r6, r7, lr}
	mov	r7, fp
	mov	r6, sl
	mov	r5, r9
	push	{r5, r6, r7}
	mov	r7, r8
	push	{r7}
	sub	sp, sp, #20
	.code	16
	mov	fp, r3
	str	r0, [sp, #16]
	.code	16
	mov	r9, r1
	str	r2, [sp, #12]
	.code	16
	bl	_GetBattleActor
	ldr	r3, .L23
	ldr	r3, [r3]
	.code	16
	mov	r8, r0
	mov	r0, #0
	.code	16
	str	r3, [sp, #8]
	str	r0, [sp, #4]
	.code	16
	b	.L3
.L6:
	mov	r2, #1
	neg	r2, r2
	cmp	fp, r2
	beq	.L7
	add	r1, sp, #52
	.code	16
	ldr	r3, .L23+4
	.code	16
	ldrb	r0, [r1]
	.code	16
	ldr	r1, [sp, #8]
	add	r3, r3, fp
	strb	r0, [r1, r3]
.L7:
	mov	r1, r8
	mov	r0, #42
	ldrsh	r3, [r1, r0]
	cmp	r3, #0
	bne	.L8
	cmp	r9, r2
	beq	.L9
	mov	r3, #39
	add	r3, r3, r7
	mov	sl, r3
	ldrb	r3, [r3]
	mov	r2, #0
	cmp	r3, #0
	beq	.L9
	mov	r6, r7
	add	r6, r6, #40
.L19:
	ldmia	r6!, {r5}
	cmp	r5, #0
	beq	.L14
	mov	r0, r8
	ldr	r3, [r0, #36]
	cmp	r5, r3
	beq	.L14
	ldr	r3, [r0, #32]
	cmp	r5, r3
	beq	.L14
	mov	r1, r9
	cmp	r1, #0
	bne	.L16
	ldr	r0, [sp, #16]
	.code	16
	str	r2, [sp]
	.code	16
	bl	_Func_80b6cd0
	strb	r0, [r5, #5]
	ldr	r2, [sp]
	b	.L17
.L16:
	mov	r3, r9
	strb	r3, [r5, #5]
.L17:
	mov	r3, #255
	strb	r3, [r5, #22]
.L14:
	mov	r0, sl
	ldrb	r3, [r0]
	add	r2, r2, #1
	cmp	r2, r3
	bne	.L19
.L9:
	mov	r2, #1
	ldr	r1, [sp, #12]
	neg	r2, r2
	.code	16
	cmp	r1, r2
	beq	.L8
	mov	r0, r7
	bl	_Sprite_SetAnim
.L8:
	ldr	r3, [sp, #4]
	add	r3, r3, #1
	str	r3, [sp, #4]
.L3:
	mov	r1, r8
	.code	16
	ldr	r0, [r1]
	ldr	r1, [sp, #4]
	bl	_Func_80b7f70
	mov	r7, r0
	cmp	r7, #0
	bne	.L6
	add	sp, sp, #20
	pop	{r3, r5, r6, r7}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	mov	fp, r7
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L24:
	.align	2, 0
.L23:
	.word	iwram_3001eec
	.word	30744
.Lfe1:
	.size	 Func_80d6888,.Lfe1-Func_80d6888

	.text
	.align	2, 0
