@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	OvlFunc_f28
	.type	 OvlFunc_f28,function
	.thumb_func
OvlFunc_f28:
	bx	lr
.Lfe1:
	.size	 OvlFunc_f28,.Lfe1-OvlFunc_f28
	.align	2, 0
	.globl	OvlFunc_f2c
	.type	 OvlFunc_f2c,function
	.thumb_func
OvlFunc_f2c:
	bx	lr
.Lfe2:
	.size	 OvlFunc_f2c,.Lfe2-OvlFunc_f2c

	.text
	.align	2, 0
