@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_791794_f28
	.thumb_func
	.type	 OvlFunc_791794_f28,function
OvlFunc_791794_f28:
	bx	lr
.Lfe1:
	.size	 OvlFunc_791794_f28,.Lfe1-OvlFunc_791794_f28
	.align	2, 0
	.global	OvlFunc_791794_f2c
	.thumb_func
	.type	 OvlFunc_791794_f2c,function
OvlFunc_791794_f2c:
	bx	lr
.Lfe2:
	.size	 OvlFunc_791794_f2c,.Lfe2-OvlFunc_791794_f2c

	.text
	.align	2, 0
