@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_959_2008a80
	.thumb_func
	.type	 OvlFunc_959_2008a80,function
OvlFunc_959_2008a80:
	push	{lr}
	ldr	r3, .L9
	mov	r1, #224
	.code	16
	lsl	r1, r1, #1
	add	r3, r3, r1
	mov	r1, #0
	.code	16
	ldrsh	r2, [r3, r1]
	ldr	r3, .L9+4
	.code	16
	cmp	r2, r3
	bne	.L3
	ldr	r0, .L9+8
	b	.L4
.L3:
	ldr	r3, .L9+12
	.code	16
	cmp	r2, r3
	bne	.L5
	ldr	r0, .L9+16
	b	.L4
.L5:
	ldr	r3, .L9+20
	.code	16
	cmp	r2, r3
	bne	.L6
	ldr	r0, .L9+24
	b	.L4
.L6:
	ldr	r3, .L9+28
	.code	16
	cmp	r2, r3
	bne	.L7
	ldr	r0, .L9+32
	b	.L4
.L7:
	ldr	r3, .L9+36
	.code	16
	cmp	r2, r3
	bne	.L8
	ldr	r0, .L9+40
	b	.L4
.L8:
	ldr	r0, .L9+44
.L4:
	.code	16
	pop	{r1}
	bx	r1
.L10:
	.align	2, 0
.L9:
	.word	gState
	.word	0x6a
	.word	.L69d0
	.word	0xa2
	.word	.L6e08
	.word	0xa1
	.word	.L6c28
	.word	0xa0
	.word	.L6ac0
	.word	0xa3
	.word	.L6e98
	.word	.L69b8
.Lfe1:
	.size	 OvlFunc_959_2008a80,.Lfe1-OvlFunc_959_2008a80
	.align	2, 0
	.global	OvlFunc_959_2008af8
	.thumb_func
	.type	 OvlFunc_959_2008af8,function
OvlFunc_959_2008af8:
	push	{lr}
	ldr	r3, .L15
	.code	16
	mov	r1, #224
	.code	16
	lsl	r1, r1, #1
	add	r3, r3, r1
	.code	16
	mov	r1, #0
	.code	16
	ldrsh	r2, [r3, r1]
	.code	16
	ldr	r3, .L15+4
	cmp	r2, r3
	bne	.L12
	ldr	r0, .L15+8
	b	.L11
.L12:
	ldr	r3, .L15+12
	cmp	r2, r3
	bne	.L13
	ldr	r0, .L15+16
	b	.L11
.L13:
	ldr	r3, .L15+20
	cmp	r2, r3
	bne	.L14
	ldr	r0, .L15+24
	b	.L11
.L14:
	ldr	r0, .L15+28
.L11:
	pop	{r1}
	bx	r1
.L16:
	.align	2, 0
.L15:
	.word	gState
	.word	0xa0
	.word	.L6ff4
	.word	0xa1
	.word	.L7258
	.word	0xa2
	.word	.L7528
	.word	.L763c
.Lfe2:
	.size	 OvlFunc_959_2008af8,.Lfe2-OvlFunc_959_2008af8

	.text
	.align	2, 0
