@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	HeightTile_5
	.thumb_func
	.type	 HeightTile_5,function
HeightTile_5:
	push	{r5, r6, lr}
	mov	r3, #0
	ldrsb	r3, [r0, r3]
	add	r0, r0, #1
	lsl	r6, r3, #19
	mov	r3, #0
	ldrsb	r3, [r0, r3]
	lsl	r5, r3, #19
	mov	r3, #1
	ldrsb	r3, [r0, r3]
	add	r1, r1, r2
	lsl	r3, r3, #19
	mov	r0, r5
	.code	16
	cmp	r1, #15
	beq	.L3
	cmp	r1, #14
	bhi	.L4
	sub	r3, r5, r6
	.code	16
	mov	r0, r1
	.code	16
	mul	r0, r0, r3
	mov	r1, #15
	bl	__divsi3
	add	r0, r6, r0
	b	.L3
.L4:
	sub	r1, r1, #15
	sub	r3, r3, r5
	.code	16
	mov	r0, r1
	.code	16
	mul	r0, r0, r3
	mov	r1, #15
	bl	__divsi3
	add	r0, r5, r0
.L3:
	pop	{r5, r6}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 HeightTile_5,.Lfe1-HeightTile_5

	.text
	.align	2, 0
