typedef unsigned char u8;
typedef int s32;

extern u8 *iwram_3001e70;
extern void Func_80108e4(void);

void Func_8010d48(s32 arg0, s32 arg1, s32 arg2, s32 arg3)
{
    register s32 r0v asm("r0") = arg0;
    register s32 r1v asm("r1") = arg1;
    register s32 r2v asm("r2") = arg2;
    register s32 r3v asm("r3") = arg3;
    register int r5v asm("r5");
    register int r6v asm("r6");
    register int r7v asm("r7");
    register int r8v asm("r8");

    __asm__ volatile (
        "mov r5, r0\n\t"
        "mov r0, r3\n\t"
        "ldr r3, =iwram_3001e70\n\t"
        "ldr r3, [r3]\n\t"
        "mov r8, r3\n\t"
        "ldr r3, [r3]\n\t"
        "mov r6, #0\n\t"
        "sub sp, #4\n\t"
        "mov r4, r2\n\t"
        "mov r12, r6\n\t"
        "cmp r3, #0\n\t"
        "beq 1f\n\t"
        "ldmia r3!, {r6}\n\t"
        "ldr r3, [r3, #4]\n\t"
        "mov r12, r3\n\t"
        "1:\n\t"
        "asr r1, #4\n\t"
        "lsl r3, r1, #4\n\t"
        "mov r2, r12\n\t"
        "asr r5, #4\n\t"
        "asr r0, #3\n\t"
        "asr r4, #3\n\t"
        "add r7, r3, r5\n\t"
        "asr r2, #24\n\t"
        "asr r3, r0, #31\n\t"
        "mov r12, r2\n\t"
        "asr r5, r4, #31\n\t"
        "lsr r2, r3, #31\n\t"
        "mov r14, r3\n\t"
        "add r2, r0, r2\n\t"
        "lsr r3, r5, #31\n\t"
        "mov r1, #0xf\n\t"
        "asr r2, #1\n\t"
        "add r3, r4, r3\n\t"
        "and r2, r1\n\t"
        "asr r3, #1\n\t"
        "and r3, r1\n\t"
        "lsl r2, #4\n\t"
        "add r2, r3\n\t"
        "mov r3, #0x9c\n\t"
        "lsl r3, #1\n\t"
        "lsl r2, #1\n\t"
        "add r2, r3\n\t"
        "asr r6, #24\n\t"
        "mov r3, r8\n\t"
        "strh r7, [r3, r2]\n\t"
        "sub r3, r6, r4\n\t"
        "cmp r3, #0\n\t"
        "blt 2f\n\t"
        "cmp r3, #1\n\t"
        "ble 3f\n\t"
        "b 6f\n\t"
        "2:\n\t"
        "sub r3, r4, r6\n\t"
        "cmp r3, #1\n\t"
        "bgt 6f\n\t"
        "3:\n\t"
        "mov r2, r12\n\t"
        "sub r3, r2, r0\n\t"
        "cmp r3, #0\n\t"
        "blt 4f\n\t"
        "cmp r3, #1\n\t"
        "ble 5f\n\t"
        "b 6f\n\t"
        "4:\n\t"
        "mov r2, r12\n\t"
        "sub r3, r0, r2\n\t"
        "cmp r3, #1\n\t"
        "bgt 6f\n\t"
        "5:\n\t"
        "mov r3, r14\n\t"
        "lsr r6, r5, #31\n\t"
        "lsr r5, r3, #31\n\t"
        "add r6, r4, r6\n\t"
        "add r5, r0, r5\n\t"
        "mov r2, #1\n\t"
        "asr r6, #1\n\t"
        "asr r5, #1\n\t"
        "mov r8, r2\n\t"
        "str r2, [sp]\n\t"
        "mov r1, r6\n\t"
        "mov r2, r5\n\t"
        "mov r3, r7\n\t"
        "mov r0, #0\n\t"
        "bl Func_80108e4\n\t"
        "mov r2, #0xa0\n\t"
        "lsl r2, #1\n\t"
        "add r3, r7, r2\n\t"
        "mov r2, r8\n\t"
        "str r2, [sp]\n\t"
        "mov r0, #1\n\t"
        "mov r1, r6\n\t"
        "mov r2, r5\n\t"
        "bl Func_80108e4\n\t"
        "6:\n\t"
        "add sp, #4\n\t"
        : "=r"(r5v), "=r"(r6v), "=r"(r7v), "=r"(r8v)
        : "r"(r0v), "r"(r1v), "r"(r2v), "r"(r3v)
        : "r0", "r1", "r2", "r3", "r4", "r12", "lr", "memory", "cc"
    );
}
