@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_800ea60
	.thumb_func
	.type	 Func_800ea60,function
Func_800ea60:
	push	{r5, r6, r7, lr}
	ldr r7, =0x3fff
	ldr r3, =iwram_3001ebc
	lsr r6, r0, #14
	and r7, r0
	ldr r0, =0x107
	ldr r5, [r3]
	.code	16
	bl	_GetFlag
	cmp	r0, #0
	beq	.L3
	mov r3, #0xc1
	lsl r3, #1
	add r2, r5, r3
	mov r3, #0xfa
	strh r3, [r2]
	.code	16
	b	.L14
.L3:
	mov	r2, #207
	lsl	r2, r2, #1
	add	r3, r5, r2
	mov	r2, #0
	ldrsh	r3, [r3, r2]
	cmp	r3, #3
	bne	.L5
	ldr r1, =gKeyPress
	mov r2, #0x80
	ldr r3, [r1]
	lsl r2, #1
	and r3, r2
	.code	16
	cmp	r3, #0
	beq	.L6
	mov r3, #0xc1
	lsl r3, #1
	add r2, r5, r3
	ldr r3, =0xfc88
	strh r3, [r2]
	.code	16
	b	.L14
.L6:
	ldr r3, [r1]
	mov r2, #0x80
	lsl r2, #2
	and r3, r2
	.code	16
	cmp	r3, #0
	beq	.L14
	mov r3, #0xc1
	lsl r3, #1
	add r2, r5, r3
	ldr r3, =0xfc87
	strh r3, [r2]
	.code	16
	b	.L14
.L5:
	cmp	r6, #0
	beq	.L11
	cmp	r6, #1
	beq	.L12
	b	.L14
.L11:
	mov	r2, #191
	b	.L10
.L12:
	mov	r2, #192
.L10:
	lsl r2, #1
	add r3, r5, r2
	strh r7, [r3]
	.code	16
.L14:
	mov	r0, r7
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 Func_800ea60,.Lfe1-Func_800ea60

	.text
	.align	2, 0
