@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80f3858
	.thumb_func
	.type	 Func_80f3858,function
Func_80f3858:
	push	{r5, lr}
	ldr	r3, .L4
	ldr	r4, [r3]
	mov	r5, r0
	cmp	r4, #0
	beq	.L3
	ldr	r1, .L4+4
	add	r3, r4, r1
	.code	16
	add	r1, r1, #1
	.code	16
	mov	r2, #0
	.code	16
	strb	r5, [r3]
	add	r3, r4, r1
	.code	16
	strb	r2, [r3]
	mov	r3, #128
	.code	16
	lsl	r3, r3, #5
	.code	16
	mov	r2, #128
	.code	16
	add	r1, r4, r3
	.code	16
	mov	r3, #224
	.code	16
	lsl	r2, r2, #3
	.code	16
	lsl	r3, r3, #5
	.code	16
	add	r0, r4, r2
	.code	16
	add	r2, r4, r3
	.code	16
	mov	r3, r5
	bl	Func_80f2ebc
.L3:
	pop	{r5}
	pop	{r0}
	bx	r0
.L5:
	.align	2, 0
.L4:
	.word	iwram_3001ed0
	.word	12289
.Lfe1:
	.size	 Func_80f3858,.Lfe1-Func_80f3858

	.text
	.align	2, 0
