@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_968_2008e04
	.thumb_func
	.type	 OvlFunc_968_2008e04,function
OvlFunc_968_2008e04:
	push	{lr}
	ldr	r3, .L9
	mov	r1, #224
	.code	16
	lsl	r1, r1, #1
	add	r3, r3, r1
	mov	r1, #0
	.code	16
	ldrsh	r2, [r3, r1]
	ldr	r3, .L9+4
	.code	16
	cmp	r2, r3
	bne	.L3
	ldr	r0, .L9+8
	b	.L4
.L3:
	ldr	r3, .L9+12
	.code	16
	cmp	r2, r3
	bne	.L5
	ldr	r0, .L9+16
	b	.L4
.L5:
	ldr	r3, .L9+20
	.code	16
	cmp	r2, r3
	bne	.L6
	ldr	r0, .L9+24
	b	.L4
.L6:
	ldr	r3, .L9+28
	.code	16
	cmp	r2, r3
	bne	.L7
	ldr	r0, .L9+32
	b	.L4
.L7:
	ldr	r3, .L9+36
	.code	16
	cmp	r2, r3
	bne	.L8
	ldr	r0, .L9+40
	b	.L4
.L8:
	ldr	r0, .L9+44
.L4:
	.code	16
	pop	{r1}
	bx	r1
.L10:
	.align	2, 0
.L9:
	.word	gState
	.word	0xb5
	.word	.L5d68
	.word	0xb7
	.word	.L6020
	.word	0xb8
	.word	.L6230
	.word	0xb9
	.word	.L6350
	.word	0xba
	.word	.L6548
	.word	.L5dc8
.Lfe1:
	.size	 OvlFunc_968_2008e04,.Lfe1-OvlFunc_968_2008e04

	.text
	.align	2, 0
