@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_968_2008e88
	.thumb_func
	.type	 OvlFunc_968_2008e88,function
OvlFunc_968_2008e88:
	push	{r5, lr}
	ldr	r3, .L12
	mov	r1, #224
	.code	16
	lsl	r1, r1, #1
	add	r3, r3, r1
	mov	r1, #0
	.code	16
	ldrsh	r2, [r3, r1]
	ldr	r3, .L12+4
	.code	16
	cmp	r2, r3
	bne	.L3
	ldr	r0, .L12+8
	b	.L4
.L3:
	ldr	r3, .L12+12
	.code	16
	cmp	r2, r3
	bne	.L5
	ldr	r5, .L12+16
	b	.L6
.L5:
	ldr	r3, .L12+20
	.code	16
	cmp	r2, r3
	bne	.L7
	ldr	r5, .L12+24
	b	.L6
.L7:
	ldr	r3, .L12+28
	.code	16
	cmp	r2, r3
	bne	.L8
	ldr	r5, .L12+32
	b	.L6
.L8:
	ldr	r3, .L12+36
	.code	16
	cmp	r2, r3
	bne	.L9
	ldr	r5, .L12+40
	b	.L6
.L9:
	ldr	r3, .L12+44
	.code	16
	cmp	r2, r3
	bne	.L11
	ldr	r5, .L12+48
.L6:
	.code	16
	mov	r0, r5
	bl	__Func_808b868
	mov	r0, r5
	b	.L4
.L11:
	ldr	r0, .L12+52
.L4:
	.code	16
	pop	{r5}
	pop	{r1}
	bx	r1
.L13:
	.align	2, 0
.L12:
	.word	gState
	.word	0xb5
	.word	gScript_945__0200e904
	.word	0xb6
	.word	.L69c4
	.word	0xb7
	.word	.L6b74
	.word	0xb8
	.word	.L6c04
	.word	0xb9
	.word	.L6c64
	.word	0xba
	.word	.L6cf4
	.word	.L68ec
.Lfe1:
	.size	 OvlFunc_968_2008e88,.Lfe1-OvlFunc_968_2008e88

	.text
	.align	2, 0
