@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_968_2009a14
	.thumb_func
	.type	 OvlFunc_968_2009a14,function
OvlFunc_968_2009a14:
	push	{lr}
	mov	r2, #35
	.code	16
	add	r2, r2, r0
	.code	16
	mov	ip, r2
	.code	16
	ldrb	r2, [r2]
	mov	r3, #2
	.code	16
	orr	r3, r3, r2
	mov	r2, ip
	.code	16
	strb	r3, [r2]
	mov	r3, r0
	.code	16
	mov	r1, #0
	.code	16
	add	r3, r3, #85
	strb	r1, [r3]
	ldr	r2, [r0, #8]
	ldr	r3, [r0, #16]
	sub	sp, sp, #8
	asr	r2, r2, #20
	asr	r3, r3, #20
	str	r2, [sp]
	str	r3, [sp, #4]
	mov	r0, #9
	mov	r1, #24
	mov	r2, #1
	mov	r3, #1
	bl	__Func_8010704
	add	sp, sp, #8
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_968_2009a14,.Lfe1-OvlFunc_968_2009a14
	.align	2, 0
	.global	OvlFunc_968_2009a50
	.thumb_func
	.type	 OvlFunc_968_2009a50,function
OvlFunc_968_2009a50:
	push	{r5, r6, r7, lr}
	mov	r7, r0
	.code	16
	ldr	r1, [r7, #80]
	ldrb	r2, [r1, #9]
	mov	r3, #12
	and	r3, r3, r2
	cmp	r3, #12
	bne	.L4
	mov	r3, #13
	neg	r3, r3
	and	r3, r3, r2
	mov	r2, #4
	orr	r3, r3, r2
	strb	r3, [r1, #9]
	.code	16
	mov	r5, #0
	.code	16
	mov	r2, #128
	lsl	r2, r2, #18
	mov	r1, #0
	mov	r3, #223
	.code	16
	str	r5, [r7, #68]
	ldr	r0, [r7, #8]
	bl	OvlFunc_968_2008058
	mov	r6, r0
	.code	16
	mov	r0, r7
	bl	OvlFunc_968_200894c
	str	r5, [r7, #8]
	str	r5, [r7, #16]
	mov	r0, r6
	bl	__DeleteActor
	b	.L5
.L4:
	bl	OvlFunc_968_20099c0
.L5:
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe2:
	.size	 OvlFunc_968_2009a50,.Lfe2-OvlFunc_968_2009a50

	.text
	.align	2, 0
