@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_967_20084b0
	.thumb_func
	.type	 OvlFunc_967_20084b0,function
OvlFunc_967_20084b0:
	push	{lr}
	ldr r3, .LOvlFunc_967_20084b0_literals
	.code	16
	mov	r1, #224
	.code	16
	lsl	r1, r1, #1
	.code	16
	add	r3, r3, r1
	.code	16
	mov	r1, #0
	.code	16
	ldrsh	r2, [r3, r1]
	ldr r3, .LOvlFunc_967_20084b0_literals+4
	.code	16
	cmp	r2, r3
	bne	.L3
	ldr r0, .LOvlFunc_967_20084b0_literals+8
	.code	16
	bl	__GetFlag
	cmp	r0, #0
	beq	.L4
	ldr r0, .LOvlFunc_967_20084b0_literals+12
	.code	16
	b	.L2
.L4:
	ldr r0, .LOvlFunc_967_20084b0_literals+16
	.code	16
	b	.L2
.L3:
	ldr r0, .LOvlFunc_967_20084b0_literals+8
	.code	16
	bl	__GetFlag
	cmp	r0, #0
	beq	.L5
	ldr r0, .LOvlFunc_967_20084b0_literals+20
	.code	16
	b	.L2
.L5:
	ldr r0, .LOvlFunc_967_20084b0_literals+24
	.code	16
.L2:
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 OvlFunc_967_20084b0,.Lfe1-OvlFunc_967_20084b0
	.section .data
.LOvlFunc_967_data_base:
.text
.align 2, 0
.LOvlFunc_967_20084b0_literals:
.word gState
.word 0xb4
.word 0x9a7
.word .LOvlFunc_967_data_base+0xcfc
.word .LOvlFunc_967_data_base+0xba0
.word gScript_887__02009ca4
.word .LOvlFunc_967_data_base+0x780
.size OvlFunc_967_20084b0, .-OvlFunc_967_20084b0


	.text
	.align	2, 0
