@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_936_200964c
	.thumb_func
	.type	 OvlFunc_936_200964c,function
OvlFunc_936_200964c:
	push	{lr}
	ldr	r0, .L12
	bl	__SetFlag
	ldr	r3, .L12+4
	.code	16
	mov	r1, #224
	lsl	r1, r1, #1
	.code	16
	add	r3, r3, r1
	mov	r1, #0
	.code	16
	ldrsh	r2, [r3, r1]
	ldr r3, =0x63
	.code	16
	cmp	r2, r3
	bne	.L3
	bl	OvlFunc_936_20096bc
	b	.L4
.L3:
	ldr r3, =0x66
	.code	16
	cmp	r2, r3
	bne	.L5
	bl	OvlFunc_936_20097e8
	b	.L4
.L5:
	ldr r3, =0x99
	.code	16
	cmp	r2, r3
	bne	.L7
	bl	OvlFunc_936_2009858
	b	.L4
.L7:
	ldr r3, =0x9b
	.code	16
	cmp	r2, r3
	bne	.L9
	bl	OvlFunc_936_20098a4
	b	.L4
.L9:
	ldr r3, =0x9c
	.code	16
	cmp	r2, r3
	bne	.L4
	bl	OvlFunc_936_2009930
.L4:
	mov	r0, #0
	pop	{r1}
	bx	r1
.L13:
	.align	2, 0
.L12:
	.word	2170
	.word	gState
.Lfe1:
	.size	 OvlFunc_936_200964c,.Lfe1-OvlFunc_936_200964c

	.text
	.align	2, 0
