#ifndef _FILE_TABLE_H_
#define _FILE_TABLE_H_

// external symbols from the file_table.ld linker script
extern int _FILE_BUILD_DATE;

// friendly names for C
#define FILE_BUILD_DATE ((int)&_FILE_BUILD_DATE)

// global forward declarations

void *GetFile(int index);


// FP#9 bulk asset-symbols (named by value; pending semantic names)
extern int _FILE_13;
#define FILE_13 ((int)&_FILE_13)
extern int _FILE_14;
#define FILE_14 ((int)&_FILE_14)
extern int _FILE_15;
#define FILE_15 ((int)&_FILE_15)
extern int _FILE_16;
#define FILE_16 ((int)&_FILE_16)
extern int _FILE_17;
#define FILE_17 ((int)&_FILE_17)
extern int _FILE_1c;
#define FILE_1c ((int)&_FILE_1c)
extern int _FILE_3f;
#define FILE_3f ((int)&_FILE_3f)
extern int _FILE_40;
#define FILE_40 ((int)&_FILE_40)
extern int _FILE_41;
#define FILE_41 ((int)&_FILE_41)
extern int _FILE_42;
#define FILE_42 ((int)&_FILE_42)
extern int _FILE_43;
#define FILE_43 ((int)&_FILE_43)
extern int _FILE_44;
#define FILE_44 ((int)&_FILE_44)
extern int _FILE_45;
#define FILE_45 ((int)&_FILE_45)
extern int _FILE_46;
#define FILE_46 ((int)&_FILE_46)
extern int _FILE_49;
#define FILE_49 ((int)&_FILE_49)
extern int _FILE_4a;
#define FILE_4a ((int)&_FILE_4a)
extern int _FILE_4b;
#define FILE_4b ((int)&_FILE_4b)
extern int _FILE_4c;
#define FILE_4c ((int)&_FILE_4c)
extern int _FILE_4d;
#define FILE_4d ((int)&_FILE_4d)
extern int _FILE_4e;
#define FILE_4e ((int)&_FILE_4e)
extern int _FILE_4f;
#define FILE_4f ((int)&_FILE_4f)
extern int _FILE_51;
#define FILE_51 ((int)&_FILE_51)
extern int _FILE_54;
#define FILE_54 ((int)&_FILE_54)
extern int _FILE_55;
#define FILE_55 ((int)&_FILE_55)
extern int _FILE_56;
#define FILE_56 ((int)&_FILE_56)
extern int _FILE_58;
#define FILE_58 ((int)&_FILE_58)
extern int _FILE_59;
#define FILE_59 ((int)&_FILE_59)
extern int _FILE_5c;
#define FILE_5c ((int)&_FILE_5c)
extern int _FILE_5d;
#define FILE_5d ((int)&_FILE_5d)
extern int _FILE_5e;
#define FILE_5e ((int)&_FILE_5e)
extern int _FILE_5f;
#define FILE_5f ((int)&_FILE_5f)
extern int _FILE_60;
#define FILE_60 ((int)&_FILE_60)
extern int _FILE_61;
#define FILE_61 ((int)&_FILE_61)
extern int _FILE_62;
#define FILE_62 ((int)&_FILE_62)
extern int _FILE_63;
#define FILE_63 ((int)&_FILE_63)
extern int _FILE_64;
#define FILE_64 ((int)&_FILE_64)
extern int _FILE_65;
#define FILE_65 ((int)&_FILE_65)
extern int _FILE_66;
#define FILE_66 ((int)&_FILE_66)
extern int _FILE_67;
#define FILE_67 ((int)&_FILE_67)
extern int _FILE_68;
#define FILE_68 ((int)&_FILE_68)
extern int _FILE_69;
#define FILE_69 ((int)&_FILE_69)
extern int _FILE_6a;
#define FILE_6a ((int)&_FILE_6a)
extern int _FILE_6b;
#define FILE_6b ((int)&_FILE_6b)
extern int _FILE_6c;
#define FILE_6c ((int)&_FILE_6c)
extern int _FILE_6d;
#define FILE_6d ((int)&_FILE_6d)
extern int _FILE_6e;
#define FILE_6e ((int)&_FILE_6e)
extern int _FILE_6f;
#define FILE_6f ((int)&_FILE_6f)
extern int _FILE_71;
#define FILE_71 ((int)&_FILE_71)
extern int _FILE_72;
#define FILE_72 ((int)&_FILE_72)
extern int _FILE_73;
#define FILE_73 ((int)&_FILE_73)
extern int _FILE_74;
#define FILE_74 ((int)&_FILE_74)
extern int _FILE_75;
#define FILE_75 ((int)&_FILE_75)
extern int _FILE_76;
#define FILE_76 ((int)&_FILE_76)
extern int _FILE_77;
#define FILE_77 ((int)&_FILE_77)
extern int _FILE_78;
#define FILE_78 ((int)&_FILE_78)
extern int _FILE_79;
#define FILE_79 ((int)&_FILE_79)
extern int _FILE_7a;
#define FILE_7a ((int)&_FILE_7a)
extern int _FILE_7b;
#define FILE_7b ((int)&_FILE_7b)
extern int _FILE_7c;
#define FILE_7c ((int)&_FILE_7c)
extern int _FILE_7d;
#define FILE_7d ((int)&_FILE_7d)
extern int _FILE_7e;
#define FILE_7e ((int)&_FILE_7e)
extern int _FILE_80;
#define FILE_80 ((int)&_FILE_80)
extern int _FILE_81;
#define FILE_81 ((int)&_FILE_81)
extern int _FILE_82;
#define FILE_82 ((int)&_FILE_82)
extern int _FILE_83;
#define FILE_83 ((int)&_FILE_83)
extern int _FILE_84;
#define FILE_84 ((int)&_FILE_84)
extern int _FILE_85;
#define FILE_85 ((int)&_FILE_85)
extern int _FILE_86;
#define FILE_86 ((int)&_FILE_86)
extern int _FILE_87;
#define FILE_87 ((int)&_FILE_87)
extern int _FILE_88;
#define FILE_88 ((int)&_FILE_88)
extern int _FILE_89;
#define FILE_89 ((int)&_FILE_89)
extern int _FILE_8a;
#define FILE_8a ((int)&_FILE_8a)
extern int _FILE_8b;
#define FILE_8b ((int)&_FILE_8b)
extern int _FILE_8c;
#define FILE_8c ((int)&_FILE_8c)
extern int _FILE_8d;
#define FILE_8d ((int)&_FILE_8d)
extern int _FILE_8e;
#define FILE_8e ((int)&_FILE_8e)
extern int _FILE_8f;
#define FILE_8f ((int)&_FILE_8f)
extern int _FILE_90;
#define FILE_90 ((int)&_FILE_90)
extern int _FILE_91;
#define FILE_91 ((int)&_FILE_91)
extern int _FILE_92;
#define FILE_92 ((int)&_FILE_92)
extern int _FILE_94;
#define FILE_94 ((int)&_FILE_94)
extern int _FILE_96;
#define FILE_96 ((int)&_FILE_96)
extern int _FILE_98;
#define FILE_98 ((int)&_FILE_98)
extern int _FILE_99;
#define FILE_99 ((int)&_FILE_99)
extern int _FILE_9b;
#define FILE_9b ((int)&_FILE_9b)
extern int _FILE_9c;
#define FILE_9c ((int)&_FILE_9c)
extern int _FILE_9d;
#define FILE_9d ((int)&_FILE_9d)
extern int _FILE_9e;
#define FILE_9e ((int)&_FILE_9e)
extern int _FILE_a0;
#define FILE_a0 ((int)&_FILE_a0)
extern int _FILE_a3;
#define FILE_a3 ((int)&_FILE_a3)
extern int _FILE_a5;
#define FILE_a5 ((int)&_FILE_a5)
extern int _FILE_a6;
#define FILE_a6 ((int)&_FILE_a6)
extern int _FILE_a8;
#define FILE_a8 ((int)&_FILE_a8)
extern int _FILE_a9;
#define FILE_a9 ((int)&_FILE_a9)
extern int _FILE_aa;
#define FILE_aa ((int)&_FILE_aa)
extern int _FILE_ab;
#define FILE_ab ((int)&_FILE_ab)
extern int _FILE_ac;
#define FILE_ac ((int)&_FILE_ac)
extern int _FILE_ad;
#define FILE_ad ((int)&_FILE_ad)
extern int _FILE_ae;
#define FILE_ae ((int)&_FILE_ae)
extern int _FILE_af;
#define FILE_af ((int)&_FILE_af)
extern int _FILE_b1;
#define FILE_b1 ((int)&_FILE_b1)
extern int _FILE_b2;
#define FILE_b2 ((int)&_FILE_b2)
extern int _FILE_b3;
#define FILE_b3 ((int)&_FILE_b3)
extern int _FILE_b4;
#define FILE_b4 ((int)&_FILE_b4)
extern int _FILE_b5;
#define FILE_b5 ((int)&_FILE_b5)
extern int _FILE_b6;
#define FILE_b6 ((int)&_FILE_b6)
extern int _FILE_b7;
#define FILE_b7 ((int)&_FILE_b7)
extern int _FILE_b8;
#define FILE_b8 ((int)&_FILE_b8)
extern int _FILE_b9;
#define FILE_b9 ((int)&_FILE_b9)
extern int _FILE_ba;
#define FILE_ba ((int)&_FILE_ba)
extern int _FILE_bb;
#define FILE_bb ((int)&_FILE_bb)
extern int _FILE_bd;
#define FILE_bd ((int)&_FILE_bd)
extern int _FILE_be;
#define FILE_be ((int)&_FILE_be)
extern int _FILE_c0;
#define FILE_c0 ((int)&_FILE_c0)
extern int _FILE_c1;
#define FILE_c1 ((int)&_FILE_c1)
extern int _FILE_c2;
#define FILE_c2 ((int)&_FILE_c2)
extern int _FILE_c4;
#define FILE_c4 ((int)&_FILE_c4)
extern int _FILE_c5;
#define FILE_c5 ((int)&_FILE_c5)
extern int _FILE_c6;
#define FILE_c6 ((int)&_FILE_c6)
extern int _FILE_c7;
#define FILE_c7 ((int)&_FILE_c7)
extern int _FILE_cb;
#define FILE_cb ((int)&_FILE_cb)
extern int _FILE_cc;
#define FILE_cc ((int)&_FILE_cc)
extern int _FILE_cd;
#define FILE_cd ((int)&_FILE_cd)
extern int _FILE_ce;
#define FILE_ce ((int)&_FILE_ce)
extern int _FILE_cf;
#define FILE_cf ((int)&_FILE_cf)
extern int _FILE_d1;
#define FILE_d1 ((int)&_FILE_d1)
extern int _FILE_d3;
#define FILE_d3 ((int)&_FILE_d3)
extern int _FILE_d4;
#define FILE_d4 ((int)&_FILE_d4)
extern int _FILE_d5;
#define FILE_d5 ((int)&_FILE_d5)
extern int _FILE_d6;
#define FILE_d6 ((int)&_FILE_d6)
extern int _FILE_d7;
#define FILE_d7 ((int)&_FILE_d7)
extern int _FILE_e7;
#define FILE_e7 ((int)&_FILE_e7)
extern int _FILE_f0;
#define FILE_f0 ((int)&_FILE_f0)
extern int _FILE_f1;
#define FILE_f1 ((int)&_FILE_f1)

#endif // _FILE_TABLE_H_
