@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_881_200808c
	.thumb_func
	.type	 OvlFunc_881_200808c,function
OvlFunc_881_200808c:
	push	{r5, r6, lr}
	ldr	r3, .L4
	ldr	r5, .L4+4
	mov	r2, #142
	.code	16
	lsl	r2, r2, #2
	ldr	r6, [r3]
	add	r5, r5, r2
	sub	r2, r2, #140
	add	r3, r6, r2
	.code	16
	ldr	r3, [r3]
	lsl	r0, r3, #3
	add	r0, r0, r3
	mov	r1, #10
	bl	_divsi3_RAM
	ldr	r3, [r5]
	cmp	r3, r0
	blt	.L3
	ldr	r0, .L4+8
	mov	r1, #42
	bl	__Func_8091f14
	mov	r3, #212
	lsl	r3, r3, #1
	add	r2, r6, r3
	mov	r3, #0
	.code	16
	str	r3, [r2]
.L3:
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L5:
	.align	2, 0
.L4:
	.word	iwram_3001ebc
	.word	gState
	.word	2057
.Lfe1:
	.size	 OvlFunc_881_200808c,.Lfe1-OvlFunc_881_200808c
	.align	2, 0
	.global	OvlFunc_881_20080d4
	.thumb_func
	.type	 OvlFunc_881_20080d4,function
OvlFunc_881_20080d4:
	push	{r5, r6, lr}
	ldr	r3, .L8
	ldr	r5, .L8+4
	mov	r2, #142
	.code	16
	lsl	r2, r2, #2
	ldr	r6, [r3]
	add	r5, r5, r2
	sub	r2, r2, #140
	add	r3, r6, r2
	.code	16
	ldr	r3, [r3]
	lsl	r0, r3, #3
	add	r0, r0, r3
	mov	r1, #10
	bl	_divsi3_RAM
	ldr	r3, [r5]
	cmp	r3, r0
	blt	.L7
	ldr	r0, .L8+8
	mov	r1, #24
	bl	__Func_8091f14
	mov	r3, #212
	lsl	r3, r3, #1
	add	r2, r6, r3
	mov	r3, #0
	.code	16
	str	r3, [r2]
.L7:
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L9:
	.align	2, 0
.L8:
	.word	iwram_3001ebc
	.word	gState
	.word	2058
.Lfe2:
	.size	 OvlFunc_881_20080d4,.Lfe2-OvlFunc_881_20080d4

	.text
	.align	2, 0
