typedef unsigned char u8;
typedef unsigned int u32;

extern u8 gState[];
extern u8 *__MapActor_GetActor(int);
extern void __CutsceneStart(void);
extern void __CutsceneEnd(void);
extern void __Func_80933f8(int, int, int, int);
extern void __PlaySound(int);
extern void __Actor_SetSpriteFlags(u8 *, int);
extern void __WaitFrames(int);
extern void __MapTransitionOut(void);
extern void __WaitMapTransition(void);
extern void __SetFlag(int);
extern void __SetDestMap(int, int);

void OvlFunc_881_200b84c(void)
{
    register u8 *actor asm("r5");
    register u8 *other asm("r8");
    register int velocity asm("r7");
    register int frames asm("r6");
    register u8 *state asm("r3");
    register int offset asm("r2");
    register int a0 asm("r0");
    register int a1 asm("r1");
    register int a2 asm("r2");
    register int a3 asm("r3");
    register u8 *low_other asm("r2");

    state = gState;
    offset = 0xfa;
    offset <<= 1;
    state += offset;
    asm volatile("" : "+r"(state), "+r"(offset));
    actor = __MapActor_GetActor(*(int *)state);
    other = __MapActor_GetActor(0x36);
    __CutsceneStart();
    a0 = 1;
    a1 = 1;
    a2 = 1;
    asm volatile("" : "+r"(a0), "+r"(a1), "+r"(a2));
    a2 = -a2;
    a3 = 0;
    a1 = -a1;
    a0 = -a0;
    asm volatile("" : "+r"(a0), "+r"(a1), "+r"(a2), "+r"(a3));
    __Func_80933f8(a0, a1, a2, a3);
    __PlaySound(0xdb);
    __Actor_SetSpriteFlags(actor, 0);
    low_other = other;
    a3 = 0;
    asm volatile("" : "+r"(low_other), "+r"(a3));
    low_other += 0x55;
    *low_other = a3;
    low_other = actor;
    low_other += 0x55;
    *low_other = a3;
    *(u32 *)(actor + 0x28) = a3;
    low_other += 0x0c;
    asm volatile("" : "+r"(low_other));
    a3 = 1;
    *low_other = a3;
    low_other = other;
    low_other += 0x61;
    *low_other = a3;
    velocity = 0x3333;
    asm volatile("" : "+r"(velocity));
    frames = 0x3b;
    asm volatile("" : "+r"(frames));
    do {
        *(u32 *)(actor + 0x28) += velocity;
        low_other = other;
        asm volatile("" : "+r"(low_other), "+r"(velocity));
        *(u32 *)(low_other + 0x28) += velocity;
        asm volatile("" : "+r"(low_other));
        a0 = 1;
        asm volatile("" : "+r"(a0));
        frames--;
        __WaitFrames(a0);
    } while (frames >= 0);
    __MapTransitionOut();
    __WaitMapTransition();
    __CutsceneEnd();
    __SetFlag(0x122);
    asm volatile("ldr %0, =2" : "=r"(a0));
    __SetDestMap(a0, 0x1b);
}
