@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_881_20097a4
	.thumb_func
	.type	 OvlFunc_881_20097a4,function
OvlFunc_881_20097a4:
	push	{r5, lr}
	mov	r0, #15
	bl	__MapActor_GetActor
	mov	r5, r0
	mov	r0, #14
	bl	__MapActor_GetActor
	ldr	r3, [r0, #8]
	str	r3, [r5, #8]
	ldr	r3, [r0, #16]
	mov	r2, #160
	str	r3, [r5, #16]
	ldr	r3, [r5, #12]
	lsl	r2, r2, #12
	cmp	r3, r2
	bge	.L3
	mov	r3, #160
	lsl	r3, r3, #12
	mov	r0, #128
	str	r3, [r5, #12]
	lsl	r0, r0, #2
	.code	16
	bl	__GetFlag
	cmp	r0, #0
	bne	.L3
	mov	r0, #145
	bl	__PlaySound
	mov	r0, r5
	mov	r1, #3
	bl	__Actor_SetAnim
	mov	r0, #128
	.code	16
	lsl	r0, r0, #2
	.code	16
	bl	__SetFlag
	mov	r2, r5
	add	r2, r2, #100
	mov	r3, #1
	.code	16
	strh	r3, [r2]
.L3:
	pop	{r5}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_881_20097a4,.Lfe1-OvlFunc_881_20097a4

	.text
	.align	2, 0
