@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_881_200b6dc
	.thumb_func
	.type	 OvlFunc_881_200b6dc,function
OvlFunc_881_200b6dc:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r8
	push	{r6, r7}
	ldr	r2, .L5
	mov	r3, #250
	mov	sl, r2
	lsl	r3, r3, #1
	add	r3, r3, sl
	ldr	r6, [r3]
	mov	r7, r0
	mov	r0, r6
	bl	__MapActor_GetActor
	mov	r5, r0
	mov	r0, #188
	lsl	r0, r0, #2
	bl	__GetFlag
	mov	r8, r0
	cmp	r0, #0
	bne	.L3
	bl	__CutsceneStart
	mov	r0, r6
	.code	16
	ldr	r1, .L5+4
	bl	__MapActor_Surprise
	mov	r0, r6
	mov	r1, #9
	bl	__MapActor_SetAnim
	mov	r0, r7
	bl	__MapActor_GetActor
	cmp	r0, #0
	beq	.L4
	mov	r3, #10
	ldrsh	r1, [r0, r3]
	mov	r3, #18
	ldrsh	r2, [r0, r3]
	mov	r0, r6
	bl	__MapActor_TravelTo
.L4:
	mov	r0, r6
	bl	__MapActor_WaitMovement
	mov	r0, #244
	bl	__PlaySound
	mov	r1, #200
	lsl	r1, r1, #4
	ldr	r0, .L5+8
	.code	16
	mov	r7, r5
	bl	__StartTask
	add	r7, r7, #85
	mov	r2, r8
	strb	r2, [r7]
	mov	r3, #128
	ldr	r2, [r5, #12]
	.code	16
	lsl	r3, r3, #14
	ldr	r1, [r5, #8]
	.code	16
	add	r2, r2, r3
	mov	r0, r5
	.code	16
	ldr	r3, [r5, #16]
	bl	__Actor_TravelTo
	mov	r0, r6
	bl	__MapActor_WaitMovement
	mov r2, r8
str r2, [r5, #0x28]
mov r2, #0xf9
mov r3, #4
lsl r2, #1
add r2, r10
strb r3, [r7]
mov r0, #0xbc
mov r3, #2
strb r3, [r2]
lsl r0, #2
bl __SetFlag
	.code	16
	mov	r0, #190
	lsl	r0, r0, #2
	mov	r1, #180
	bl	__SetFlagByte
	bl	__CutsceneEnd
	ldr	r3, .L5+12
	mov	r2, #190
	ldr	r3, [r3]
	lsl	r2, r2, #1
	add	r3, r3, r2
	mov	r2, r8
	strh	r2, [r3]
.L3:
	pop	{r3, r5}
	mov	r8, r3
	mov	sl, r5
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L6:
	.align	2, 0
.L5:
	.word	gState
	.word	257
	.word	OvlFunc_881_200b678
	.word	iwram_3001ebc
.Lfe1:
	.size	 OvlFunc_881_200b6dc,.Lfe1-OvlFunc_881_200b6dc

	.text
	.align	2, 0
