typedef unsigned char u8;
typedef unsigned short u16;
typedef unsigned int u32;

struct SpriteSlot {
    u16 size;
    u16 vramOffset;
};

extern u8 *iwram_3001f30;
extern struct SpriteSlot gSpriteSlots[];
extern u8 *__CreateActor(int type, int x, int y, int z);
extern void __Sprite_SetAnim(u8 *sprite, int animation);
extern void __Func_8003f3c(int id);
extern void OvlFunc_881_200c004(void);
extern void OvlFunc_881_200bfb4(void);

void OvlFunc_881_200c058(u8 *source)
{
    register u8 *r7pin asm("r7");
    register u8 *r0pin asm("r0") = source;

    asm volatile(
        "ldr r3, =iwram_3001f30\n\t"
        "ldr r3, [r3]\n\t"
        "sub sp, #8\n\t"
        "mov r1, #0x3f\n\t"
        "mov r6, r0\n\t"
        "mov r11, r3\n\t"
        "mov r7, #0\n\t"
        "mov r10, sp\n\t"
        "mov r9, r1\n\t"
        ".Lloop_881:\n\t"
        "ldr r2, [r6, #0xc]\n\t"
        "ldr r3, [r6, #0x10]\n\t"
        "ldr r1, [r6, #8]\n\t"
        "mov r0, #0x1a\n\t"
        "bl __CreateActor\n\t"
        "lsl r3, r7, #2\n\t"
        "mov r2, r10\n\t"
        "str r0, [r3, r2]\n\t"
        "cmp r0, #0\n\t"
        "beq .Lend_881\n\t"
        "ldr r3, [r6, #0x14]\n\t"
        "str r3, [r0, #0x14]\n\t"
        "mov r3, r0\n\t"
        "ldr r5, [r0, #0x50]\n\t"
        "add r3, #0x55\n\t"
        "mov r2, #0\n\t"
        "ldr r1, .Lpool1_881\n\t"
        "strb r2, [r3]\n\t"
        "add r3, #0xf\n\t"
        "strh r2, [r3]\n\t"
        "mov r8, r1\n\t"
        "str r6, [r0, #0x68]\n\t"
        "cmp r5, #0\n\t"
        "beq .Lend_881\n\t"
        "b .Lsprite_881\n\t"
        "\n\t"
        ".align 2, 0\n\t"
        ".Lpool1_881:\n\t"
        ".word 0\n\t"
        ".pool\n\t"
        "\n\t"
        ".Lsprite_881:\n\t"
        "mov r1, #0\n\t"
        "mov r0, r5\n\t"
        "bl __Sprite_SetAnim\n\t"
        "mov r3, r5\n\t"
        "add r3, #0x26\n\t"
        "mov r2, r8\n\t"
        "strb r2, [r3]\n\t"
        "ldrb r0, [r5, #0x1c]\n\t"
        "bl __Func_8003f3c\n\t"
        "mov r3, r11\n\t"
        "add r3, #0x46\n\t"
        "ldrh r3, [r3]\n\t"
        "strb r3, [r5, #0x1c]\n\t"
        "ldrb r3, [r5, #0x1d]\n\t"
        "mov r2, #1\n\t"
        "orr r3, r2\n\t"
        "strb r3, [r5, #0x1d]\n\t"
        "ldrb r3, [r5, #0x1c]\n\t"
        "ldr r2, =gSpriteSlots\n\t"
        "lsl r3, #2\n\t"
        "add r3, r2\n\t"
        "ldrh r1, [r3, #2]\n\t"
        "ldr r2, .Lpool2_881\n\t"
        "ldrh r3, [r5, #8]\n\t"
        "lsl r1, #17\n\t"
        "lsr r1, #22\n\t"
        "and r3, r2\n\t"
        "orr r3, r1\n\t"
        "mov r1, #0x21\n\t"
        "neg r1, r1\n\t"
        "strh r3, [r5, #8]\n\t"
        "ldrb r3, [r5, #5]\n\t"
        "mov r2, r1\n\t"
        "and r3, r2\n\t"
        "mov r2, r9\n\t"
        "and r3, r2\n\t"
        "mov r2, #0x40\n\t"
        "orr r3, r2\n\t"
        "ldrb r2, [r5, #7]\n\t"
        "strb r3, [r5, #5]\n\t"
        "mov r3, r9\n\t"
        "and r3, r2\n\t"
        "mov r2, #0x80\n\t"
        "orr r3, r2\n\t"
        "strb r3, [r5, #7]\n\t"
        "ldr r3, [r5, #0x28]\n\t"
        "mov r1, r8\n\t"
        "strb r1, [r3, #0x16]\n\t"
        "b .Lend_881\n\t"
        "\n\t"
        ".align 2, 0\n\t"
        ".Lpool2_881:\n\t"
        ".word 0xfffffc00\n\t"
        ".pool\n\t"
        "\n\t"
        ".Lend_881:\n\t"
        "add r7, #1\n\t"
        "cmp r7, #1\n\t"
        "ble .Lloop_881\n\t"
        "ldr r2, [sp]\n\t"
        "ldr r3, =OvlFunc_881_200c004\n\t"
        "ldr r0, [r2, #0x50]\n\t"
        "str r3, [r2, #0x6c]\n\t"
        "mov r2, #0xd\n\t"
        "ldrb r1, [r0, #9]\n\t"
        "neg r2, r2\n\t"
        "mov r3, r2\n\t"
        "mov r4, #4\n\t"
        "and r3, r1\n\t"
        "orr r3, r4\n\t"
        "strb r3, [r0, #9]\n\t"
        "mov r3, r10\n\t"
        "ldr r1, [r3, #4]\n\t"
        "ldr r0, [r1, #0x50]\n\t"
        "ldrb r3, [r0, #9]\n\t"
        "and r2, r3\n\t"
        "ldr r3, =OvlFunc_881_200bfb4\n\t"
        "orr r2, r4\n\t"
        "str r3, [r1, #0x6c]\n\t"
        "add r1, #0x23\n\t"
        "mov r3, #2\n\t"
        "strb r2, [r0, #9]\n\t"
        "strb r3, [r1]\n\t"
        "add sp, #8\n\t"
        : "=r"(r7pin)
        : "r"(r0pin)
        : "r1", "r2", "r3", "r4", "r5", "r6", "r8", "r9", "r10", "r11", "lr", "memory", "cc"
    );
}
