@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_882_2008328
	.thumb_func
	.type	 OvlFunc_882_2008328,function
OvlFunc_882_2008328:
	push	{lr}
	mov	r0, #158
	bl	__PlaySound
	ldr	r0, .L3
	mov	r1, #49
	mov	r2, #69
	bl	__Func_8010560
	mov	r1, #163
	lsl	r1, r1, #1
	ldr	r2, .L3+4
	mov	r0, #0
	.code	16
	bl	__Func_809218c
	mov	r0, #3
	bl	__CutsceneWait
	mov	r0, #8
	bl	OvlFunc_882_200815c
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	.L57a0
	.word	1126
.Lfe1:
	.size	 OvlFunc_882_2008328,.Lfe1-OvlFunc_882_2008328
	.align	2, 0
	.global	OvlFunc_882_2008360
	.thumb_func
	.type	 OvlFunc_882_2008360,function
OvlFunc_882_2008360:
	push	{lr}
	mov	r0, #158
	bl	__PlaySound
	ldr	r0, .L6
	mov	r1, #52
	mov	r2, #76
	bl	__Func_8010560
	mov	r1, #187
	lsl	r1, r1, #1
	ldr	r2, .L6+4
	mov	r0, #0
	.code	16
	bl	__Func_809218c
	mov	r0, #3
	bl	__CutsceneWait
	mov	r0, #9
	bl	OvlFunc_882_200815c
	pop	{r0}
	bx	r0
.L7:
	.align	2, 0
.L6:
	.word	.L57b6
	.word	1238
.Lfe2:
	.size	 OvlFunc_882_2008360,.Lfe2-OvlFunc_882_2008360
	.align	2, 0
	.global	OvlFunc_882_2008398
	.thumb_func
	.type	 OvlFunc_882_2008398,function
OvlFunc_882_2008398:
	push	{lr}
	mov	r0, #158
	bl	__PlaySound
	ldr	r0, .L9
	mov	r1, #35
	mov	r2, #74
	bl	__Func_8010560
	mov	r1, #102
	ldr	r2, .L9+4
	mov	r0, #0
	.code	16
	bl	__Func_809218c
	mov	r0, #3
	bl	__CutsceneWait
	mov	r0, #10
	bl	OvlFunc_882_200815c
	pop	{r0}
	bx	r0
.L10:
	.align	2, 0
.L9:
	.word	.L578a
	.word	1206
.Lfe3:
	.size	 OvlFunc_882_2008398,.Lfe3-OvlFunc_882_2008398
	.align	2, 0
	.global	OvlFunc_882_20083cc
	.thumb_func
	.type	 OvlFunc_882_20083cc,function
OvlFunc_882_20083cc:
	push	{lr}
	mov	r0, #158
	bl	__PlaySound
	ldr	r0, .L12
	mov	r1, #35
	mov	r2, #73
	bl	__Func_8010560
	mov	r1, #102
	ldr	r2, .L12+4
	mov	r0, #0
	.code	16
	bl	__Func_809218c
	mov	r0, #3
	bl	__CutsceneWait
	mov	r0, #12
	bl	OvlFunc_882_200815c
	pop	{r0}
	bx	r0
.L13:
	.align	2, 0
.L12:
	.word	.L578a
	.word	1206
.Lfe4:
	.size	 OvlFunc_882_20083cc,.Lfe4-OvlFunc_882_20083cc
	.align	2, 0
	.global	OvlFunc_882_2008400
	.thumb_func
	.type	 OvlFunc_882_2008400,function
OvlFunc_882_2008400:
	push	{lr}
	mov	r0, #158
	bl	__PlaySound
	ldr	r0, .L15
	mov	r1, #38
	mov	r2, #72
	bl	__Func_8010560
	mov	r1, #146
	ldr	r2, .L15+4
	mov	r0, #0
	.code	16
	bl	__Func_809218c
	mov	r0, #3
	bl	__CutsceneWait
	mov	r0, #13
	bl	OvlFunc_882_200815c
	pop	{r0}
	bx	r0
.L16:
	.align	2, 0
.L15:
	.word	.L57a0
	.word	1182
.Lfe5:
	.size	 OvlFunc_882_2008400,.Lfe5-OvlFunc_882_2008400

	.text
	.align	2, 0
