@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_93304_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_941dc
	.thumb_func
	.type	 Func_941dc,function
Func_941dc:
	bx	lr
.Lfe1:
	.size	 Func_941dc,.Lfe1-Func_941dc

	.text
	.align	2, 0

	.text
	.align	2, 0
