@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_92950_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_92b90
	.thumb_func
	.type	 Func_92b90,function
Func_92b90:
	bx	lr
.Lfe1:
	.size	 Func_92b90,.Lfe1-Func_92b90

	.text
	.align	2, 0

	.text
	.align	2, 0
