@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8092b08
	.thumb_func
	.type	 Func_8092b08,function
Func_8092b08:
	push	{r5, r6, lr}
	mov	r5, r1
	.code	16
	bl	GetFieldActor
	mov	r6, r0
	cmp	r6, #0
	beq	.L2
	mov	r3, r6
	add	r3, r3, #84
	ldrb	r2, [r3]
	mov	r3, #15
	and	r3, r3, r2
	cmp	r3, #1
	bne	.L2
	ldr	r1, [r6, #80]
	mov	r2, #13
	ldrb	r0, [r1, #9]
	mov	r3, #3
	.code	16
	neg	r2, r2
	and	r5, r5, r3
	mov	r3, r2
	lsl	r4, r5, #2
	and	r3, r3, r0
	orr	r3, r3, r4
	strb	r3, [r1, #9]
	ldrb	r3, [r1, #21]
	and	r2, r2, r3
	orr	r2, r2, r4
	strb	r2, [r1, #21]
	mov	r1, r6
	add	r1, r1, #35
	ldrb	r2, [r1]
	mov	r3, #254
	and	r3, r3, r2
	strb	r3, [r1]
.L4:
.L2:
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Func_8092b08,.Lfe1-Func_8092b08
	.align	2, 0
	.global	Func_8092b54
	.thumb_func
	.type	 Func_8092b54,function
Func_8092b54:
	push	{r5, r6, lr}
	mov	r6, r8
	push	{r6}
	mov	r8, r0
	.code	16
	mov	r0, r1
	bl	MapActor_GetActor
	ldr	r0, [r0, #80]
	ldrb	r6, [r0, #28]
	ldrh	r5, [r0, #8]
	mov	r0, r8
	bl	MapActor_GetActor
	ldr	r0, [r0, #80]
	ldr	r3, .L7
	ldrh	r2, [r0, #8]
	lsl	r5, r5, #22
	lsr	r5, r5, #22
	and	r3, r3, r2
	orr	r3, r3, r5
	strb	r6, [r0, #28]
	strh	r3, [r0, #8]
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L8:
	.align	2, 0
.L7:
	.word	-1024
.Lfe2:
	.size	 Func_8092b54,.Lfe2-Func_8092b54

	.text
	.align	2, 0
