@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8093054
	.thumb_func
	.type	 Func_8093054,function
Func_8093054:
	push	{r5, r6, r7, lr}
	mov	r6, r1
	.code	16
	mov	r5, r0
	.code	16
	bl	Func_8092c40
	ldr	r3, .L5
	.code	16
	mov	r2, #250
	.code	16
	lsl	r2, r2, #1
	.code	16
	add	r3, r3, r2
	.code	16
	ldr	r0, [r3]
	.code	16
	mov	r1, #0
	.code	16
	bl	Func_8091c7c
	mov	r7, r0
	.code	16
	cmp	r7, #0
	bne	.L3
	mov	r0, r5
	.code	16
	mov	r1, r6
	.code	16
	bl	ActorMessage
	ldr	r3, .L5+4
	.code	16
	ldr	r2, [r3]
	.code	16
	mov	r3, #236
	.code	16
	lsl	r3, r3, #1
	.code	16
	add	r2, r2, r3
	.code	16
	ldrh	r3, [r2]
	.code	16
	add	r3, r3, #1
	.code	16
	strh	r3, [r2]
	b	.L4
.L3:
	ldr	r3, .L5+4
	.code	16
	ldr	r2, [r3]
	.code	16
	mov	r3, #236
	.code	16
	lsl	r3, r3, #1
	.code	16
	add	r2, r2, r3
	.code	16
	ldrh	r3, [r2]
	.code	16
	add	r3, r3, #1
	.code	16
	strh	r3, [r2]
	mov	r0, r5
	.code	16
	mov	r1, r6
	.code	16
	bl	ActorMessage
.L4:
	mov	r0, r7
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L6:
	.align	2, 0
.L5:
	.word	gState
	.word	iwram_3001ebc
.Lfe1:
	.size	 Func_8093054,.Lfe1-Func_8093054

	.text
	.align	2, 0
