"""Generate Ninja syntax from the shared graph; run only configured argv arrays."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import shlex
import subprocess
import sys

import build_config
import build_graph
import build_paths as paths
from build_actions import checked
from build_deps import write_changed

ROOT = Path(__file__).resolve().parents[1]
GRAPH = paths.TARGET + "/build.ninja"
ACTIONS = paths.TARGET + "/ninja-actions.json"


def escape(value):
    if any(c in value for c in "\n\r"): raise ValueError("newline in Ninja value")
    return value.replace("$", "$$").replace(" ", "$ ").replace(":", "$:")


def signature(argv):
    return hashlib.sha256(json.dumps(argv).encode()).hexdigest()


def configure(root):
    values = build_config.resolve_values(build_config.load(root)[0])
    flags = shlex.split(os.environ.get("GS_BUILD_ARM_LDFLAGS", ""))
    libs = shlex.split(os.environ.get("GS_BUILD_ARM_LDLIBS", ""))
    edges = build_graph.graph(root, flags, libs)
    for name in (paths.TARGET + "/.ninja_log", paths.TARGET + "/.ninja_deps"):
        checked(root, name)
    for edge in edges:
        for name in edge.outputs + edge.byproducts + ([edge.depfile] if edge.depfile else []):
            if name.startswith((paths.TARGET + "/", paths.HOST + "/")): checked(root, name)
    actions = {}
    lines = ["# Generated by tools/configure_build.py; invoke tools/build.py to refresh settings.",
             "ninja_required_version = 1.10", "builddir = " + paths.TARGET,
             "pool serial", "  depth = 1", ""]
    for i, edge in enumerate(edges):
        name = edge.outputs[0]
        if not edge.command:
            lines.append("build " + " ".join(map(escape, edge.outputs)) + ": phony " + " ".join(map(escape, edge.inputs)))
            continue
        argv = edge.command + (["--ninja-depfile"] if edge.depfile else [])
        actions[name] = argv
        rule = "action_" + str(i)
        cmd = shlex.join(["python3", "-B", "tools/configure_build.py", "run", name, signature(argv)])
        lines += ["rule " + rule, "  command = " + cmd.replace("$", "$$"), "  pool = serial",
                  "  description = " + escape(name)]
        if edge.restat: lines.append("  restat = 1")
        if edge.depfile: lines += ["  depfile = " + escape(edge.depfile), "  deps = gcc"]
        outputs = " ".join(map(escape, edge.outputs))
        if edge.byproducts: outputs += " | " + " ".join(map(escape, edge.byproducts))
        lines.append("build " + outputs + ": " + rule + " " + " ".join(map(escape, edge.inputs)))
    lines += ["default compare", ""]
    write_changed(checked(root, ACTIONS), json.dumps(dict(schema=1, values=values, actions=actions), sort_keys=True, indent=2) + "\n")
    write_changed(checked(root, GRAPH), "\n".join(lines))
    return GRAPH


def run(root, name, expected):
    data = json.loads(checked(root, ACTIONS).read_text())
    argv = data["actions"][name]
    if data.get("schema") != 1 or signature(argv) != expected:
        raise ValueError("stale Ninja configuration; run tools/build.py again")
    env = dict(os.environ)
    for key in list(env):
        if key.startswith("GS_BUILD_"): env.pop(key)
    env.update({"GS_BUILD_" + k: v for k, v in data["values"].items()})
    return subprocess.run(argv, cwd=root, env=env).returncode


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("command", choices=("configure", "run"), nargs="?", default="configure")
    ap.add_argument("action", nargs="?"); ap.add_argument("signature", nargs="?")
    args = ap.parse_args()
    try:
        os.chdir(ROOT)
        if args.command == "run": return run(ROOT, args.action, args.signature)
        print(configure(ROOT)); return 0
    except (OSError, ValueError, KeyError, TypeError, subprocess.SubprocessError) as exc:
        print("configure build: " + str(exc), file=sys.stderr); return 1


if __name__ == "__main__": raise SystemExit(main())
