@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	Func_a1bc8
	.type	 Func_a1bc8,function
	.thumb_func
Func_a1bc8:
	bx	lr
.Lfe1:
	.size	 Func_a1bc8,.Lfe1-Func_a1bc8

	.text
	.align	2, 0
