@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_a8604_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_a939c
	.thumb_func
	.type	 Func_a939c,function
Func_a939c:
	bx	lr
.Lfe1:
	.size	 Func_a939c,.Lfe1-Func_a939c
	.align	2, 0
	.global	Func_a93a0
	.thumb_func
	.type	 Func_a93a0,function
Func_a93a0:
	bx	lr
.Lfe2:
	.size	 Func_a93a0,.Lfe2-Func_a93a0

	.text
	.align	2, 0

	.text
	.align	2, 0
