@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80ab1f4
	.thumb_func
	.type	 Func_80ab1f4,function
Func_80ab1f4:
	push	{r5, r6, lr}
	mov	r4, r0
	ldrh	r0, [r4, #12]
	add r0, r0, r1
ldrh r1, [r4, #14]
sub sp, #4
ldr r5, [sp, #20]
mov r6, r3
add r1, r1, r2
add r0, #1
ldr r3, [sp, #16]
add r1, #1
mov r2, r6
str r5, [sp]
bl _Func_8022768
add sp, #4
	.code	16
	pop	{r5, r6}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 Func_80ab1f4,.Lfe1-Func_80ab1f4

	.text
	.align	2, 0
