@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_947_2009938
	.thumb_func
	.type	 OvlFunc_947_2009938,function
OvlFunc_947_2009938:
	push	{r5, r6, lr}
	mov	r5, r0
	mov	r6, r1
	ldr	r1, [r6, #8]
	ldr	r4, [r5, #8]
	mov	r0, #0
	cmp	r1, r4
	bne	.L4
	ldr	r2, [r6, #12]
	ldr	r3, [r5, #12]
	cmp	r2, r3
	bne	.L4
	ldr	r2, [r6, #16]
	ldr	r3, [r5, #16]
	cmp	r2, r3
	beq	.L7
.L4:
	ldr	r2, .L17
	add	r3, r1, r2
	cmp	r3, r4
	bge	.L7
	mov	r2, #128
	lsl	r2, r2, #13
	add	r3, r1, r2
	cmp	r4, r3
	bge	.L7
	ldr	r3, [r6, #12]
	cmp	r3, #0
	bge	.L11
	ldr	r1, .L17+4
	add	r3, r3, r1
.L11:
	asr	r2, r3, #16
	ldr	r3, [r5, #12]
	cmp	r3, #0
	bge	.L13
	ldr	r1, .L17+4
	add	r3, r3, r1
.L13:
	asr	r3, r3, #16
	cmp	r2, r3
	bne	.L7
	ldr	r3, [r6, #16]
	ldr	r2, [r5, #16]
	cmp	r3, r2
	ble	.L7
	ldr	r1, .L17+8
	add	r3, r3, r1
	cmp	r3, r2
	bge	.L7
	ldr r3, [r5, #0x50]
	ldrb r2, [r3, #9]
	ldr r3, [r6, #0x50]
	ldrb r3, [r3, #9]
	lsl r2, r2, #28
	lsl r1, r3, #28
	lsr r2, r2, #30
	lsr r3, r1, #30
	cmp r2, r3
	bcs 1f
	mov r0, r5
	add r0, r0, #0x23
	ldrb r2, [r0]
	mov r3, #0xfe
	and r3, r2
	strb r3, [r0]
	ldr r4, [r5, #0x50]
	mov r2, #0xd
	ldrb r0, [r4, #9]
	neg r2, r2
	mov r3, r2
	lsr r1, r1, #30
	lsl r1, r1, #2
	and r3, r0
	orr r3, r1
	strb r3, [r4, #9]
	ldr r3, [r6, #0x50]
	ldr r0, [r5, #0x50]
	ldrb r1, [r3, #0x15]
	mov r3, #0xc
	and r3, r1
	ldrb r1, [r0, #0x15]
	and r2, r1
	orr r2, r3
	strb r2, [r0, #0x15]
	1:
	
	.code	16
	mov	r0, #1
.L7:
	pop	{r5, r6}
	pop	{r1}
	bx	r1
.L18:
	.align	2, 0
.L17:
	.word	-1048576
	.word	65535
	.word	-2097152
.Lfe1:
	.size	 OvlFunc_947_2009938,.Lfe1-OvlFunc_947_2009938

	.text
	.align	2, 0
