@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	Func_1a5a0
	.type	 Func_1a5a0,function
	.thumb_func
Func_1a5a0:
	bx	lr
.Lfe1:
	.size	 Func_1a5a0,.Lfe1-Func_1a5a0

	.text
	.align	2, 0
