@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80b153c
	.thumb_func
	.type	 Func_80b153c,function
Func_80b153c:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r8
	push	{r6, r7}
	ldr	r3, 11f
	ldr	r3, [r3]
	mov	r6, r1
	mov	r10, r3
	mov	r5, r0
	bl	_GetUnit
	mov	r7, r0
	mov	r0, r6
	bl	_GetItemInfo
	mov	r8, r0
	mov	r1, r8
	ldrb	r2, [r1, #3]
	mov	r3, #0x10
	and	r3, r2
	mov	r0, #1
	cmp	r3, #0
	beq	1f
	ldr	r0, 12f
	bl	Func_80b04dc
	mov	r0, r5
	mov	r1, r6
	bl	_CheckItem
	mov	r2, #1
	neg	r2, r2
	cmp	r0, r2
	beq	2f
	lsl	r3, r0, #1
	add	r3, #0xd8
	ldrh	r3, [r7, r3]
	lsr	r3, #11
	add	r7, r3, #1
	b	3f
	2:
	mov	r7, #0
	3:
	mov	r2, r8
	mov	r3, #0
	ldrsh	r1, [r2, r3]
	mov	r5, #0x1e
	cmp	r1, #0
	beq	4f
	ldr	r3, 13f
	ldr	r0, [r3, #0x10]
	bl	__udivsi3
	mov	r5, r0
	4:
	ldr	r3, 14f
	add	r3, r10
	ldrb	r3, [r3]
	lsl	r3, #24
	asr	r3, #24
	cmp	r3, #2
	bne	5f
	mov	r0, r6
	mov	r1, #0
	bl	_Func_8078ad0
	cmp	r5, r0
	ble	6f
	mov	r0, r6
	mov	r1, #0
	bl	_Func_8078ad0
	b	7f
	6:
	mov	r0, r5
	7:
	mov	r5, r0
	5:
	add	r5, r7
	cmp	r5, #0x1e
	ble	8f
	mov	r5, #0x1e
	8:
	mov	r3, #0xea
	lsl	r3, #2
	add	r3, r10
	mov	r2, #0xc
	strb	r2, [r3]
	mov	r0, #0
	mov	r1, #0x80
	mov	r2, #0x30
	bl	Func_80b0a6c
	mov	r1, r8
	mov	r3, #0
	ldrsh	r2, [r1, r3]
	mov	r0, r7
	mov	r1, r5
	bl	Func_80b1614
	1:
	
	.code	16
	pop	{r3, r5}
	mov	r8, r3
	mov	sl, r5
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 Func_80b153c,.Lfe1-Func_80b153c
	.align 2, 0
	11:
	.word	iwram_3001f2c
	12:
	.word	0xca0
	13:
	.word	gState
	14:
	.word	0x3aa
	

	.text
	.align	2, 0
