@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80b1470
	.thumb_func
	.type	 Func_80b1470,function
Func_80b1470:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	mov	r5, r1
	mov	sl, r0
	mov	r0, r5
	sub	sp, sp, #4
	mov	r9, r2
	bl	_GetUnit
	mov	r1, sl
	mov	r8, r0
	mov	r6, #8
	mov	r7, #8
	cmp	r1, #0
	beq	.L3
	mov	r0, sl
	bl	_Func_8016478
	mov	r0, r5
	mov	r1, r9
	bl	_CheckItem
	mov	r2, #1
	neg	r2, r2
	cmp	r0, r2
	beq	.L4
	lsl	r3, r0, #1
	add	r3, r3, #216
	mov	r1, r8
	ldrh	r0, [r1, r3]
	lsr	r0, r0, #11
	add	r0, r0, #1
	mov	r1, #5
	bl	_Func_8019908
	ldr r0, =0xc90
	.code	16
	mov	r1, sl
	mov	r2, #0
	mov	r3, #0
	bl	_Func_801e7c0
	b	.L5
.L4:
	ldr r0, =0xc8f
	.code	16
	mov	r1, sl
	mov	r2, #0
	mov	r3, #0
	bl	_Func_801e7c0
.L5:
	mov	r3, #216
	mov	r2, r8
	ldrh	r3, [r2, r3]
	mov	r5, #0
	cmp	r3, #0
	beq	.L3
	mov	r2, #0
.L7:
	mov	r3, r2
	add	r3, r3, #216
	mov	r1, r8
	ldrh	r0, [r1, r3]
	mov	r2, sl
	mov	r3, r6
	mov	r1, #27
	str	r7, [sp]
	bl	_Func_801eb90
	mov	r3, #252
	strb	r3, [r0, #15]
	add	r6, r6, #16
	cmp	r5, #4
	bne	.L8
	mov	r6, #8
	add	r7, r7, #16
.L8:
	cmp	r5, #9
	bne	.L9
	mov	r6, #8
	add	r7, r7, #16
.L9:
	add	r5, r5, #1
	cmp	r5, #14
	bgt	.L3
	lsl	r3, r5, #1
	mov	r2, r3
	mov	r1, r8
	add	r3, r3, #216
	ldrh	r3, [r1, r3]
	cmp	r3, #0
	bne	.L7
.L3:
	add	sp, sp, #4
	pop	{r3, r5, r6}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Func_80b1470,.Lfe1-Func_80b1470

	.text
	.align	2, 0
