typedef unsigned char u8;
extern void OvlFunc_905_20090c8(void);
extern void __StopTask(void (*)(void));
extern void __CutsceneStart(void);
extern void __MapActor_Emote(int, int, int);
extern void __Func_80925cc(int, int);
extern void __Func_8092adc(int, int, int);
extern void __MessageID(int);
extern void __ActorMessage(int, int);
extern void __MapActor_DoAnim(int, int);
extern void __CutsceneWait(int);
extern u8 *__MapActor_GetActor(int);
extern void __MapActor_SetSpeed(int, int, int);
extern void __Func_80921c4(int, int, int);
extern void __MapActor_SetPos(int, int, int);
extern void __SetFlag(int);
extern void __CutsceneEnd(void);
extern void Emote_NoArgs(void) asm("__MapActor_Emote");
extern void SetSpeed_NoArgs(void) asm("__MapActor_SetSpeed");
extern void Move_NoArgs(void) asm("__Func_80921c4");

void OvlFunc_905_200915c(void)
{
    register u8 *actor asm("r0");
    register int r1 asm("r1");
    register int r2 asm("r2");
    register int r3 asm("r3");
    __StopTask(OvlFunc_905_20090c8);
    __CutsceneStart();
    r1 = 0x80; r2 = 0x1e; actor = (u8 *)0xd;
    asm volatile("" : "+r"(actor), "+r"(r1), "+r"(r2));
    r1 <<= 1;
    asm volatile("" : "+r"(actor), "+r"(r1), "+r"(r2));
    Emote_NoArgs();
    __Func_80925cc(0xd, 2);
    __Func_8092adc(0, 0xa000, 0);
    __MessageID(0x132f);
    __ActorMessage(0xd, 0);
    __MapActor_DoAnim(0xd, 3);
    __CutsceneWait(0x1e);
    actor = __MapActor_GetActor(0xa);
    actor += 0x23;
    asm volatile("" : "+r"(actor));
    r2 = *actor;
    asm volatile("" : "+r"(actor), "+r"(r2));
    r3 = 0xfd;
    asm volatile("" : "+r"(actor), "+r"(r2), "+r"(r3));
    r3 &= r2;
    r1 = 0x80; r2 = 0x80;
    asm volatile("" : "+r"(actor), "+r"(r1), "+r"(r2), "+r"(r3));
    *actor = r3;
    r1 <<= 10;
    asm volatile("" : "+r"(r1), "+r"(r2));
    actor = (u8 *)0xd;
    asm volatile("" : "+r"(actor), "+r"(r1), "+r"(r2));
    r2 <<= 9;
    asm volatile("" : "+r"(actor), "+r"(r1), "+r"(r2));
    SetSpeed_NoArgs();
    r1 = 0x96; actor = (u8 *)0xd;
    asm volatile("" : "+r"(actor), "+r"(r1));
    r1 <<= 2; r2 = 0xd8;
    asm volatile("" : "+r"(actor), "+r"(r1), "+r"(r2));
    Move_NoArgs();
    r1 = 0x96; actor = (u8 *)0xd;
    asm volatile("" : "+r"(actor), "+r"(r1));
    r1 <<= 2; r2 = 0xf8;
    asm volatile("" : "+r"(actor), "+r"(r1), "+r"(r2));
    Move_NoArgs();
    r1 = 0x8e; r2 = 0x94; actor = (u8 *)0xd;
    asm volatile("" : "+r"(actor), "+r"(r1), "+r"(r2));
    r1 <<= 2; r2 <<= 1;
    asm volatile("" : "+r"(actor), "+r"(r1), "+r"(r2));
    Move_NoArgs();
    __MapActor_SetPos(0xd, 0, 0);
    actor = __MapActor_GetActor(0xa);
    actor += 0x23;
    asm volatile("" : "+r"(actor));
    r2 = *actor;
    asm volatile("" : "+r"(actor), "+r"(r2));
    r3 = 2;
    asm volatile("" : "+r"(actor), "+r"(r2), "+r"(r3));
    r3 |= r2;
    asm volatile("" : "+r"(actor), "+r"(r3));
    *actor = r3;
    __SetFlag(0x869);
    __CutsceneEnd();
}
