@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_7c5efc_131c
	.thumb_func
	.type	 OvlFunc_7c5efc_131c,function
OvlFunc_7c5efc_131c:
	mov	r0, #1
	bx	lr
.Lfe1:
	.size	 OvlFunc_7c5efc_131c,.Lfe1-OvlFunc_7c5efc_131c

	.text
	.align	2, 0
