@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_2e00_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8002f3c
	.thumb_func
	.type	 Func_8002f3c,function
Func_8002f3c:
	bx	lr
.Lfe1:
	.size	 Func_8002f3c,.Lfe1-Func_8002f3c

	.text
	.align	2, 0
