@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_40e8_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8004270
	.thumb_func
	.type	 Func_8004270,function
Func_8004270:
	bx	lr
.Lfe1:
	.size	 Func_8004270,.Lfe1-Func_8004270
	.align	2, 0
	.global	Func_8004274
	.thumb_func
	.type	 Func_8004274,function
Func_8004274:
	bx	lr
.Lfe2:
	.size	 Func_8004274,.Lfe2-Func_8004274

	.text
	.align	2, 0
