@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_5cf8_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_6798
	.thumb_func
	.type	 Func_6798,function
Func_6798:
	bx	lr
.Lfe1:
	.size	 Func_6798,.Lfe1-Func_6798

	.text
	.align	2, 0

	.text
	.align	2, 0
