@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_6878_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8006abc
	.thumb_func
	.type	 Func_8006abc,function
Func_8006abc:
	ldrb	r0, [r0]
	bx	lr
.Lfe1:
	.size	 Func_8006abc,.Lfe1-Func_8006abc

	.text
	.align	2, 0
