@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80064b8
	.thumb_func
	.type	 Func_80064b8,function
Func_80064b8:
	push	{r5, lr}
	ldr	r3, .L9
	ldr	r3, [r3]
	.code	16
	mov	r5, #0
	.code	16
	b	.L3
.L4:
	mov	r0, #1
	bl	WaitFrames
	ldr	r3, .L9+4
	.code	16
	add	r5, r5, #1
	cmp	r5, r3
	bhi	.L2
	ldr	r3, .L9
	ldr	r3, [r3]
	.code	16
.L3:
	cmp	r3, #0
	bne	.L4
	ldr	r3, .L9+8
	ldr	r3, [r3]
	.code	16
	cmp	r3, #0
	bne	.L4
.L6:
.L2:
	pop	{r5}
	pop	{r0}
	bx	r0
.L10:
	.align	2, 0
.L9:
	.word	ewram_2002080
	.word	0x927bf
	.word	ewram_20023ac
.Lfe1:
	.size	 Func_80064b8,.Lfe1-Func_80064b8

	.text
	.align	2, 0
