@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_883_2008ba8
	.thumb_func
	.type	 OvlFunc_883_2008ba8,function
OvlFunc_883_2008ba8:
	push	{lr}
	bl	__CutsceneStart
	ldr r0, =0x807
	.code	16
	bl	__GetFlag
	cmp	r0, #0
	bne	.L3
	ldr r0, =0x807
	.code	16
	bl	__SetFlag
	ldr r0, =0xf63
	.code	16
	bl	__MessageID
	mov	r0, #18
	ldr r1, =0x103
	.code	16
	mov	r2, #0
	.code	16
	bl	__MapActor_Emote
	mov	r0, #0
	mov	r1, #18
	mov	r2, #20
	bl	__Func_8092848
	mov	r0, #18
	mov	r1, #0
	mov	r2, #6
	bl	__Func_8093040
	mov	r1, #128
	.code	16
	mov	r0, #18
	.code	16
	lsl	r1, r1, #8
	.code	16
	mov	r2, #30
	.code	16
	bl	__Func_8092adc
	mov	r0, #18
	mov	r1, #2
	mov	r2, #20
	bl	__MapActor_Jump
	mov	r0, #18
	mov	r1, #0
	mov	r2, #6
	bl	__Func_8093040
	mov	r0, #18
	mov	r1, #0
	mov	r2, #10
	bl	__Func_8092848
	mov	r0, #18
	ldr r1, =0x103
	.code	16
	mov	r2, #0
	.code	16
	bl	__MapActor_Emote
	mov	r0, #18
	mov	r1, #0
	mov	r2, #10
	bl	__Func_8093040
	mov	r1, #129
	.code	16
	mov	r0, #0
	.code	16
	lsl	r1, r1, #1
	.code	16
	mov	r2, #60
	.code	16
	bl	__MapActor_Emote
	b	.L4
.L3:
	ldr r1, =0x103
	.code	16
	mov	r2, #0
	.code	16
	mov	r0, #18
	.code	16
	bl	__MapActor_Emote
	ldr r0, =0xf66
	.code	16
	bl	__MessageID
	mov	r0, #18
	mov	r1, #0
	mov	r2, #20
	bl	__Func_8093040
.L4:
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_883_2008ba8,.Lfe1-OvlFunc_883_2008ba8

	.text
	.align	2, 0
