@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_883_20091d8
	.thumb_func
	.type	 OvlFunc_883_20091d8,function
OvlFunc_883_20091d8:
	push	{r5, lr}
	ldr	r0, .L4
	bl	__GetFlag
	cmp	r0, #0
	bne	.L2
	bl	__CutsceneStart
	mov	r1, #128
	.code	16
	mov	r2, #128
	.code	16
	lsl	r1, r1, #9
	.code	16
	lsl	r2, r2, #8
	.code	16
	mov	r0, #0
	.code	16
	bl	__MapActor_SetSpeed
	.code	16
	ldr	r5, .L4+4
	mov	r0, r5
	bl	__MessageID
	mov	r0, #15
	mov	r1, #0
	mov	r2, #2
	bl	__Func_8093040
	add	r5, r5, #2
	mov	r2, #2
	.code	16
	mov	r0, #16
	.code	16
	mov	r1, #0
	.code	16
	bl	__Func_8093040
	mov	r1, #1
	mov	r0, r5
	.code	16
	bl	__Func_801776c
	mov	r0, #6
	bl	__CutsceneWait
	mov	r0, #0
	.code	16
	mov	r1, #69
	.code	16
	ldr	r2, .L4+8
	.code	16
	bl	__Func_80921c4
	bl	__CutsceneEnd
.L2:
	pop	{r5}
	pop	{r0}
	bx	r0
.L5:
	.align	2, 0
.L4:
	.word	2056
	.word	3917
	.word	870
.Lfe1:
	.size	 OvlFunc_883_20091d8,.Lfe1-OvlFunc_883_20091d8

	.text
	.align	2, 0
