@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_898_2008cfc
	.thumb_func
	.type	 OvlFunc_898_2008cfc,function
OvlFunc_898_2008cfc:
	push	{lr}
	mov	r0, #14
	bl	__MapActor_GetActor
	add	r0, r0, #100
	ldrh	r2, [r0]
	.code	16
	ldrh	r3, .L6
	.code	16
	orr	r3, r3, r2
	strh	r3, [r0]
	bl	__CutsceneStart
	ldr	r0, .L6+4
	bl	__GetFlag
	cmp	r0, #0
	bne	.L3
	ldr	r0, .L6+8
	bl	__MessageID
	b	.L4
.L7:
	.align	2, 0
.L6:
	.word	2
	.word	2133
	.word	4668
.L3:
	ldr	r0, .L8
	bl	__MessageID
	mov	r0, #2
	bl	__GetFlag
	cmp	r0, #0
	beq	.L4
	ldr	r3, .L8+4
	ldr	r2, [r3]
	mov	r3, #236
	lsl	r3, r3, #1
	add	r2, r2, r3
	ldrh	r3, [r2]
	add	r3, r3, #1
	strh	r3, [r2]
.L4:
	mov	r0, #14
	bl	OvlFunc_898_2008938
	bl	__CutsceneEnd
	mov	r0, #14
	bl	__MapActor_GetActor
	add	r0, r0, #100
	ldrh	r2, [r0]
	mov	r3, #1
	and	r3, r3, r2
	strh	r3, [r0]
	pop	{r0}
	bx	r0
.L9:
	.align	2, 0
.L8:
	.word	4937
	.word	iwram_3001ebc
.Lfe1:
	.size	 OvlFunc_898_2008cfc,.Lfe1-OvlFunc_898_2008cfc

	.text
	.align	2, 0
