@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	Func_c0c4
	.type	 Func_c0c4,function
	.thumb_func
Func_c0c4:
	bx	lr
.Lfe1:
	.size	 Func_c0c4,.Lfe1-Func_c0c4
	.align	2, 0
	.globl	Func_c0c8
	.type	 Func_c0c8,function
	.thumb_func
Func_c0c8:
	bx	lr
.Lfe2:
	.size	 Func_c0c8,.Lfe2-Func_c0c8

	.text
	.align	2, 0
