@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_common1_1608
	.thumb_func
	.type	 OvlFunc_common1_1608,function
OvlFunc_common1_1608:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, sp, #4
	mov	r9, r1
	bl	__MapActor_GetActor
	mov	r6, r0
	cmp	r6, #0
	beq	.L2
	mov	r3, r6
	add	r3, r3, #84
	ldrb	r3, [r3]
	mov	sl, r3
	cmp	r3, #1
	bne	.L2
	mov	r1, #193
	lsl	r1, r1, #3
	mov	r0, #17
	ldr	r7, [r6, #80]
	bl	__galloc_iwram
	mov r3, #0x80
	mov r5, r0
	lsl r3, #3
	mov r2, #0
	add r5, r3
	mov r0, sp
	mov r8, r2
	str r2, [r0, #0]
	ldr r3, =0x040000d4
	mov r1, r5
	ldr r2, =0x85000020
	stmia r3!, {r0, r1, r2}
	sub r3, #12
	mov r0, r9
	bl __LoadItemIcon
	
	.code	16
	mov	r2, r5
	mov	r1, #128
	ldrb	r0, [r7, #28]
	bl	__UploadSpriteGFX
	mov	r5, r0
	mov	r0, #17
	bl	__gfree
	mov r3, r6
	add r3, #0x5c
	mov r2, r10
	strb r2, [r3, #0]
	ldr r0, [r7, #0x28]
	bl __DeleteSpriteLayer
	mov r3, r8
	str r3, [r7, #0x28]
	mov r3, r7
	add r3, #0x27
	mov r2, r8
	strb r2, [r3, #0]
	ldrb r2, [r7, #5]
	mov r3, #0x21
	neg r3, r3
	and r3, r2
	strb r3, [r7, #5]
	
	ldr r3, 9f
	.code	16
	ldrh	r2, [r7, #8]
	and	r5, r5, r3
	ldr r3, =0xfffffc00
	.code	16
	and	r3, r3, r2
	orr	r3, r3, r5
	strh	r3, [r7, #8]
	mov r3, r7
	add r3, #0x25
	mov r2, r8
	strb r2, [r3, #0]
	add r3, #1
	strb r2, [r3, #0]
	
	b 8f
	.align 2, 0
9:
	.word 0x3ff
	.pool
8:
	.code	16
.L2:
	add	sp, sp, #4
	pop	{r3, r5, r6}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_common1_1608,.Lfe1-OvlFunc_common1_1608

	.text
	.align	2, 0
