@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_common1_172c
	.thumb_func
	.type	 OvlFunc_common1_172c,function
OvlFunc_common1_172c:
	push	{r5, r6, lr}
.L3:
.L4:
	mov	r5, r0
	ldr	r3, [r5, #40]
	mov	r2, #255
	add	r3, r3, #255
	lsl	r2, r2, #1
	sub	sp, sp, #12
	cmp	r3, r2
	bhi	.L5
	mov	r2, r5
	add	r2, r2, #85
	mov	r3, #0
	strb	r3, [r2]
.L5:
	bl	__Random
	mov	r3, #100
	mul	r3, r3, r0
	lsr	r3, r3, #16
	cmp	r3, #9
	bhi	.L6
	ldr	r3, [r5, #8]
	mov	r6, sp
	str	r3, [r6]
	ldr	r3, [r5, #12]
	str	r3, [r6, #4]
	ldr	r3, [r5, #16]
	str	r3, [r6, #8]
	bl	__Random
	mov	r5, r0
	bl	__Random
	lsl	r5, r5, #4
	mov	r1, r0
	mov	r2, r6
	mov	r0, r5
	bl	__vec3_translate
	ldr r1, [r6]
	ldr r2, [r6, #4]
	ldr r3, [r6, #8]
	.code	16
	ldr	r0, .L8
	bl	__CreateActor
	mov	r5, r0
	cmp	r5, #0
	beq	.L6
	mov	r2, r5
	add	r2, r2, #85
	mov	r3, #0
	strb	r3, [r2]
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	ldr	r1, .L8+4
	mov	r0, r5
	bl	__Actor_SetScript
	mov	r0, r5
	mov	r1, #1
	bl	__Actor_SetAnim
	mov	r0, r5
	mov	r1, #0
	bl	__Actor_SetAnim
.L6:
	add	sp, sp, #12
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L9:
	.align	2, 0
.L8:
	.word	285
	.word	.L7
.Lfe1:
	.size	 OvlFunc_common1_172c,.Lfe1-OvlFunc_common1_172c

	.text
	.align	2, 0
