@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_common1_fac
	.thumb_func
	.type	 OvlFunc_common1_fac,function
OvlFunc_common1_fac:
	push	{r5, r6, lr}
	mov	r5, r0
	mov	r0, #247
	bl	__PlaySound
	bl	__MapTransitionIn
	bl	__WaitMapTransition
	lsl	r3, r5, #4
	ldr	r2, .L14
	sub	r3, r3, r5
	lsl	r6, r3, #2
	strh	r6, [r2, #26]
	ldr	r1, .L14+4
	mov	r2, r5
	cmp	r5, #0
	bge	.L7
	neg	r2, r5
.L7:
	lsl	r3, r2, #4
	sub	r3, r3, r2
	lsl	r3, r3, #2
	strh	r3, [r1, #26]
	cmp	r5, #0
	bge	.L8
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #86
	bl	__PlaySound
	mov	r0, #8
	bl	OvlFunc_common1_88c
	mov	r1, #1
	mov	r0, #3
	.code	16
	bl	OvlFunc_common1_e10
	lsl	r0, r5, #4
	sub	r0, r5, r0
	lsl	r0, r0, #2
	add	r0, r0, #60
	bl	__CutsceneWait
	mov	r0, #0
	b	.L9
.L8:
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, r5
	add	r0, r0, #90
	bl	__PlaySound
	mov	r0, #4
	bl	OvlFunc_common1_88c
	mov	r1, #0
	mov	r0, #3
	.code	16
	bl	OvlFunc_common1_e10
	mov	r0, r6
	add	r0, r0, #60
	bl	__CutsceneWait
	mov	r0, #8
.L9:
	ldr	r1, .L14+8
	mov	r2, #0
	bl	__MapActor_Emote
	b	.L10
.L12:
	mov	r0, #1
	bl	__WaitFrames
.L10:
	bl	__Func_80f954c
	cmp	r0, #0
	bne	.L12
	mov	r0, #19
	bl	__PlaySound
	mov	r0, #30
	bl	__CutsceneWait
	ldr	r0, .L14+12
	bl	__PlaySound
	bl	__MapTransitionOut
	bl	__WaitMapTransition
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L15:
	.align	2, 0
.L14:
	.word	.L13
	.word	.L3
	.word	261
	.word	289
.Lfe1:
	.size	 OvlFunc_common1_fac,.Lfe1-OvlFunc_common1_fac

	.text
	.align	2, 0
